<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Mail\\Http\\Resources\\v1\\Mailer\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'mail.mailer',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Mail\\Support\\SelectMailTransportField',
        'type'       => 'form-field',
        'name'       => 'selectMailTransport',
        'version'    => 'v1',
        'resolution' => 'web',
    ],
    [
        'type'       => 'form-mailer',
        'name'       => 'array',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'mail::phrase.mailer_array',
    ],
    [
        'driver'     => 'MetaFox\\Mail\\Http\\Resources\\v1\\Admin\\MailerFailoverSettingForm',
        'type'       => 'form-mailer',
        'name'       => 'failover',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'mail::phrase.failover_mailer',
        'url'        => '/admincp/mail/mailer/edit/failover/failover',
    ],
    [
        'driver'     => 'MetaFox\\Mail\\Http\\Resources\\v1\\Admin\\MailerLogSettingForm',
        'type'       => 'form-mailer',
        'name'       => 'log',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'mail::phrase.log_mailer',
        'url'        => '/admincp/mail/mailer/edit/log/log',
    ],
    [
        'driver'     => 'MetaFox\\Mail\\Http\\Resources\\v1\\Admin\\ServiceMailgunSettingForm',
        'type'       => 'form-mailer',
        'name'       => 'mailgun',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'mail::phrase.mailgun_mailer',
        'url'        => '/admincp/mail/mailer/edit/mailgun/mailgun',
    ],
    [
        'driver'     => 'MetaFox\\Mail\\Http\\Resources\\v1\\Admin\\MailerPostmarkSettingForm',
        'type'       => 'form-mailer',
        'name'       => 'postmark',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'mail::phrase.postmark_mailer',
        'url'        => '/admincp/mail/mailer/edit/postmark/postmark',
    ],
    [
        'type'       => 'form-mailer',
        'name'       => 'sendmail',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'mail::phrase.php_sendmail_mailer',
    ],
    [
        'driver'     => 'MetaFox\\Mail\\Http\\Resources\\v1\\Admin\\ServiceSesSettingForm',
        'type'       => 'form-mailer',
        'name'       => 'ses',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'mail::phrase.aws_ses_mailer',
        'url'        => '/admincp/mail/mailer/edit/ses/ses',
    ],
    [
        'driver'     => 'MetaFox\\Mail\\Http\\Resources\\v1\\Admin\\MailerSmtpSettingForm',
        'type'       => 'form-mailer',
        'name'       => 'smtp',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'mail::phrase.smtp_mailer',
        'url'        => '/admincp/mail/mailer/edit/smtp/smtp',
    ],
    [
        'driver'      => 'MetaFox\\Mail\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'        => 'form-settings',
        'name'        => 'mail',
        'version'     => 'v1',
        'resolution'  => 'admin',
        'title'       => 'core::phrase.settings',
        'url'         => '/admincp/mail/setting',
        'description' => 'Mail Settings',
    ],
    [
        'driver'  => 'MetaFox\\Mail\\Http\\Resources\\v1\\PackageSetting',
        'type'    => 'package-setting',
        'name'    => 'mail',
        'version' => 'v1',
    ],
];
