<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Maintain\\Admin\\DriverDataGrid',
        'type'       => 'data-grid',
        'name'       => 'core.maintain.driver',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Maintain\\Admin\\EventDataGrid',
        'type'       => 'data-grid',
        'name'       => 'core.maintain.event',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Maintain\\Admin\\RouteDataGrid',
        'type'       => 'data-grid',
        'name'       => 'core.maintain.route',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Models\\AdminSearch',
        'type'       => 'entity',
        'name'       => 'admin_search',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Models\\Attachment',
        'type'       => 'entity',
        'name'       => 'core_attachment',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Models\\AttachmentFileType',
        'type'       => 'entity',
        'name'       => 'core_attachment_file_type',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Models\\Privacy',
        'type'       => 'entity',
        'name'       => 'core_privacy',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Models\\PrivacyMember',
        'type'       => 'entity',
        'name'       => 'core_privacy_member',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Models\\PrivacyStream',
        'type'       => 'entity',
        'name'       => 'core_privacy_stream',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Models\\Driver',
        'type'       => 'entity',
        'name'       => 'core-driver',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Models\\Link',
        'type'       => 'entity',
        'name'       => 'link',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Models\\StatsContent',
        'type'       => 'entity',
        'name'       => 'stat_content',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Models\\Link',
        'type'       => 'entity-content',
        'name'       => 'link',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Links',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Admin\\DestroyCacheForm',
        'type'       => 'form',
        'name'       => 'core.admin.destroy_cache',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Privacy\\CreateCustomPrivacyOptionForm',
        'type'       => 'form',
        'name'       => 'core.privacy_option.store',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Privacy\\CreateCustomPrivacyOptionMobileForm',
        'type'       => 'form',
        'name'       => 'core.privacy_option.store',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Link\\CreateFeedForm',
        'type'       => 'form',
        'name'       => 'link.feed_form',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Form\\SelectPackageField',
        'type'       => 'form-field',
        'name'       => 'selectPackage',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Form\\SelectPackageAliasField',
        'type'       => 'form-field',
        'name'       => 'selectPackageAlias',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Form\\YesNoChoice',
        'type'       => 'form-field',
        'name'       => 'yesNoChoice',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'       => 'form-settings',
        'name'       => 'core',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.settings',
        'url'        => '/admincp/core/setting',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Admin\\AttachmentSettingForm',
        'type'       => 'form-settings',
        'name'       => 'core.attachment',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.attachment_settings',
        'url'        => '/admincp/core/setting/attachment',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Admin\\LicenseKeySettingForm',
        'type'       => 'form-settings',
        'name'       => 'core.license_key',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.license_settings',
        'url'        => '/admincp/core/setting/license_key',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Admin\\SiteModeSettingForm',
        'type'       => 'form-settings',
        'name'       => 'core.site_mode',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.settings',
        'url'        => '/admincp/core/setting/site-mode',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Admin\\SpamSettingForm',
        'type'       => 'form-settings',
        'name'       => 'core.spam',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.spam_assistance',
        'url'        => '/admincp/core/setting/spam',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Jobs\\DeleteImageJob',
        'type'       => 'job',
        'name'       => 'MetaFox\\Core\\Jobs\\DeleteImageJob',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Jobs\\UpdateAdminSearch',
        'type'       => 'job',
        'name'       => 'MetaFox\\Core\\Jobs\\UpdateAdminSearch',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Attachment\\AttachmentItemCollection',
        'type'       => 'json-collection',
        'name'       => 'core_attachment.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Link\\LinkEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'link.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Link\\LinkItemCollection',
        'type'       => 'json-collection',
        'name'       => 'link.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\SiteSetting\\Admin\\SiteSettingItemCollection',
        'type'       => 'json-collection',
        'name'       => 'site_setting.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Attachment\\AttachmentItem',
        'type'       => 'json-resource',
        'name'       => 'core_attachment.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Error\\Forbidden',
        'type'       => 'json-resource',
        'name'       => 'forbidden.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Link\\LinkDetail',
        'type'       => 'json-resource',
        'name'       => 'link.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Link\\LinkEmbed',
        'type'       => 'json-resource',
        'name'       => 'link.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Link\\LinkItem',
        'type'       => 'json-resource',
        'name'       => 'link.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\SiteSetting\\Admin\\SiteSettingItem',
        'type'       => 'json-resource',
        'name'       => 'site_setting.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'core',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Policies\\LinkPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Core\\Models\\Link',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Policies\\Handlers\\CanApprove',
        'type'       => 'policy-rule',
        'name'       => 'approve',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Policies\\Handlers\\CanFeature',
        'type'       => 'policy-rule',
        'name'       => 'feature',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Policies\\Handlers\\CanPublish',
        'type'       => 'policy-rule',
        'name'       => 'publish',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Policies\\Handlers\\CanPurchaseSponsor',
        'type'       => 'policy-rule',
        'name'       => 'purchaseSponsor',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Policies\\Handlers\\CanSponsor',
        'type'       => 'policy-rule',
        'name'       => 'sponsor',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Policies\\Handlers\\CanSponsorInFeed',
        'type'       => 'policy-rule',
        'name'       => 'sponsorInFeed',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Policies\\Handlers\\CanViewApprove',
        'type'       => 'policy-rule',
        'name'       => 'viewApprove',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Policies\\Handlers\\CanViewApproveListing',
        'type'       => 'policy-rule',
        'name'       => 'viewApproveListing',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Privacy\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'privacy',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Link\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'link',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Privacy\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'privacy',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
];
