<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Report\\Http\\Resources\\v1\\ReportItem\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'report.aggregate.item',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Report Item Detail',
    ],
    [
        'driver'     => 'MetaFox\\Report\\Http\\Resources\\v1\\ReportItemAggregate\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'report.items',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Report Items',
    ],
    [
        'driver'     => 'MetaFox\\Report\\Http\\Resources\\v1\\ReportReason\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'report.reason',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Report Reasons',
    ],
    [
        'driver'     => 'MetaFox\\Report\\Models\\ReportOwner',
        'type'       => 'entity',
        'name'       => 'report_owner',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Report\\Models\\ReportOwnerUser',
        'type'       => 'entity',
        'name'       => 'report_owner_user',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Report\\Http\\Resources\\v1\\ReportItem\\Admin\\SearchReportItemForm',
        'type'       => 'form',
        'name'       => 'report.report_item.search',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Report\\Http\\Resources\\v1\\ReportItem\\StoreReportItemMobileForm',
        'type'       => 'form',
        'name'       => 'report.report_item.store',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Report\\Http\\Resources\\v1\\ReportItem\\StoreReportItemForm',
        'type'       => 'form',
        'name'       => 'report.report_item.store',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Report\\Http\\Resources\\v1\\ReportOwner\\StoreReportOwnerMobileForm',
        'type'       => 'form',
        'name'       => 'report.report_owner.store',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Report\\Http\\Resources\\v1\\ReportOwner\\StoreReportItemReportOwnerForm',
        'type'       => 'form',
        'name'       => 'report.report_owner.store_report_item',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Report\\Http\\Resources\\v1\\ReportReason\\Admin\\SearchReportReasonForm',
        'type'       => 'form',
        'name'       => 'report.report_reason.search',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Report\\Http\\Resources\\v1\\ReportReason\\Admin\\CreateReportReasonForm',
        'type'       => 'form',
        'name'       => 'report.report_reason.store',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Report\\Http\\Resources\\v1\\ReportReason\\Admin\\EditReportReasonForm',
        'type'       => 'form',
        'name'       => 'report.report_reason.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Report\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'       => 'form-settings',
        'name'       => 'report',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.settings',
        'url'        => '/admincp/report/setting',
    ],
    [
        'driver'     => 'MetaFox\\Report\\Http\\Resources\\v1\\ReportItem\\Admin\\ReportItemItemCollection',
        'type'       => 'json-collection',
        'name'       => 'report_item.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Report\\Http\\Resources\\v1\\ReportOwner\\ReportOwnerItemCollection',
        'type'       => 'json-collection',
        'name'       => 'report_owner.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Report\\Http\\Resources\\v1\\ReportReason\\ReportReasonItemCollection',
        'type'       => 'json-collection',
        'name'       => 'report_reason.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Report\\Http\\Resources\\v1\\ReportItem\\ReportItemDetail',
        'type'       => 'json-resource',
        'name'       => 'report_item.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Report\\Http\\Resources\\v1\\ReportItem\\ReportItemItem',
        'type'       => 'json-resource',
        'name'       => 'report_item.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Report\\Http\\Resources\\v1\\ReportOwner\\ReportOwnerItem',
        'type'       => 'json-resource',
        'name'       => 'report_owner.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Report\\Http\\Resources\\v1\\ReportReason\\Admin\\ReportReasonDetail',
        'type'       => 'json-resource',
        'name'       => 'report_reason.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Report\\Http\\Resources\\v1\\ReportReason\\ReportReasonItem',
        'type'       => 'json-resource',
        'name'       => 'report_reason.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Report\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'report',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Report\\Policies\\ReportItemPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Report\\Models\\ReportItem',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Report\\Policies\\ReportReasonPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Report\\Models\\ReportReason',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Report\\Policies\\Handlers\\CanReportItem',
        'type'       => 'policy-rule',
        'name'       => 'reportItem',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Report\\Policies\\Handlers\\CanReportToOwner',
        'type'       => 'policy-rule',
        'name'       => 'reportToOwner',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Report\\Http\\Resources\\v1\\ReportItem\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'report_item',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Report\\Http\\Resources\\v1\\ReportOwner\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'report_owner',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Report\\Http\\Resources\\v1\\ReportItem\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'report_item',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Report\\Http\\Resources\\v1\\ReportOwner\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'report_owner',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Report\\Http\\Resources\\v1\\ReportReason\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'report_reason',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
];
