<?php

/* this is auto generated file */
return [
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'forum.forum.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'forum::phrase.edit_forum',
        'ordering' => 10,
        'value'    => 'editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'style'     => 'danger',
        'menu'      => 'forum.forum.itemActionMenu',
        'name'      => 'delete',
        'label'     => 'core::phrase.delete',
        'ordering'  => 11,
        'value'     => 'deleteItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'forum.forum_post.detailActionMenu',
        'name'     => 'edit',
        'label'    => 'forum::phrase.edit_post',
        'ordering' => 1,
        'value'    => 'forum_post/editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_approve'],
            ['falsy', 'item.is_approved'],
        ],
        'menu'     => 'forum.forum_post.detailActionMenu',
        'name'     => 'approve',
        'label'    => 'core::phrase.approve',
        'ordering' => 2,
        'value'    => 'approveItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_quote'],
        ],
        'menu'     => 'forum.forum_post.detailActionMenu',
        'name'     => 'quote',
        'label'    => 'forum::phrase.forum_phrase_item_action_quote',
        'ordering' => 3,
        'value'    => 'forum/quoteItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'style'     => 'danger',
        'menu'      => 'forum.forum_post.detailActionMenu',
        'name'      => 'delete',
        'label'     => 'core::phrase.delete',
        'ordering'  => 7,
        'value'     => 'deleteItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'forum.forum_post.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'forum::phrase.edit_post',
        'ordering' => 1,
        'value'    => 'forum_post/editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_approve'],
            ['falsy', 'item.is_approved'],
        ],
        'menu'     => 'forum.forum_post.itemActionMenu',
        'name'     => 'approve',
        'label'    => 'core::phrase.approve',
        'ordering' => 2,
        'value'    => 'approveItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_quote'],
        ],
        'menu'     => 'forum.forum_post.itemActionMenu',
        'name'     => 'quote',
        'label'    => 'forum::phrase.forum_phrase_item_action_quote',
        'ordering' => 3,
        'value'    => 'forum/quoteItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'style'     => 'danger',
        'menu'      => 'forum.forum_post.itemActionMenu',
        'name'      => 'delete',
        'label'     => 'core::phrase.delete',
        'ordering'  => 7,
        'value'     => 'deleteItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'edit',
        'label'    => 'forum::phrase.edit_thread',
        'ordering' => 1,
        'value'    => 'editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_approve'],
            ['falsy', 'item.is_approved'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'approve',
        'label'    => 'forum::phrase.approve_thread',
        'ordering' => 3,
        'value'    => 'approveItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_move'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'move',
        'label'    => 'forum::phrase.move_thread',
        'ordering' => 4,
        'value'    => 'forum/moveItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_copy'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'copy',
        'label'    => 'forum::phrase.copy_thread',
        'ordering' => 5,
        'value'    => 'forum/copyItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_merge'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'merge',
        'label'    => 'forum::phrase.merge_thread',
        'ordering' => 6,
        'value'    => 'forum/mergeItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_stick'],
            ['falsy', 'item.is_sticked'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'stick',
        'label'    => 'forum::phrase.stick_thread',
        'ordering' => 7,
        'value'    => 'forum/stickItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_stick'],
            ['truthy', 'item.is_sticked'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'unstick',
        'label'    => 'forum::phrase.unstick_thread',
        'ordering' => 8,
        'value'    => 'forum/stickItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_close'],
            ['falsy', 'item.is_closed'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'close',
        'label'    => 'forum::phrase.close_thread',
        'ordering' => 9,
        'value'    => 'forum/closeItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_close'],
            ['truthy', 'item.is_closed'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'reopen',
        'label'    => 'forum::phrase.reopen_thread',
        'ordering' => 10,
        'value'    => 'forum/reopenItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_subscribe'],
            ['falsy', 'item.is_subscribed'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'subscribe',
        'label'    => 'forum::phrase.forum_phrase_item_action_subscribe',
        'ordering' => 12,
        'value'    => 'forum/subscribeItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_subscribe'],
            ['truthy', 'item.is_subscribed'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'unsubscribe',
        'label'    => 'forum::phrase.forum_phrase_item_action_unsubscribe',
        'ordering' => 13,
        'value'    => 'forum/subscribeItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['falsy', 'item.is_sponsored_feed'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'core::phrase.sponsor_in_feed',
        'ordering' => 14,
        'value'    => 'sponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['truthy', 'item.is_sponsored_feed'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'unsponsor_in_feed',
        'label'    => 'core::phrase.remove_sponsor_in_feed',
        'ordering' => 15,
        'value'    => 'unsponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['falsy', 'item.is_sponsor'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'sponsor',
        'label'    => 'forum::phrase.sponsor_this_item',
        'ordering' => 16,
        'value'    => 'sponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['truthy', 'item.is_sponsor'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'unsponsor',
        'label'    => 'forum::phrase.forum_phrase_item_action_un_sponsor',
        'ordering' => 17,
        'value'    => 'unsponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'style'    => 'danger',
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'delete',
        'label'    => 'forum::phrase.delete_thread',
        'ordering' => 22,
        'value'    => 'deleteItem',
    ],
    [
        'menu'     => 'forum.forum_thread.filter_menu',
        'name'     => 'all',
        'label'    => 'core::phrase.when.all',
        'ordering' => 1,
        'value'    => 'all',
    ],
    [
        'menu'     => 'forum.forum_thread.filter_menu',
        'name'     => 'this_month',
        'label'    => 'core::phrase.when.this_month',
        'ordering' => 2,
        'value'    => 'this_month',
    ],
    [
        'menu'     => 'forum.forum_thread.filter_menu',
        'name'     => 'this_week',
        'label'    => 'core::phrase.when.this_week',
        'ordering' => 3,
        'value'    => 'this_week',
    ],
    [
        'menu'     => 'forum.forum_thread.filter_menu',
        'name'     => 'today',
        'label'    => 'core::phrase.when.today',
        'ordering' => 4,
        'value'    => 'today',
    ],
    [
        'menu'     => 'forum.forum.filter_menu',
        'name'     => 'all',
        'label'    => 'core::phrase.when.all',
        'ordering' => 1,
        'value'    => 'all',
    ],
    [
        'menu'     => 'forum.forum.filter_menu',
        'name'     => 'this_month',
        'label'    => 'core::phrase.when.this_month',
        'ordering' => 2,
        'value'    => 'this_month',
    ],
    [
        'menu'     => 'forum.forum.filter_menu',
        'name'     => 'this_week',
        'label'    => 'core::phrase.when.this_week',
        'ordering' => 3,
        'value'    => 'this_week',
    ],
    [
        'menu'     => 'forum.forum.filter_menu',
        'name'     => 'today',
        'label'    => 'core::phrase.when.today',
        'ordering' => 4,
        'value'    => 'today',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'forum::phrase.edit_thread',
        'ordering' => 1,
        'value'    => 'editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_approve'],
            ['falsy', 'item.is_approved'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'approve',
        'label'    => 'forum::phrase.approve_thread',
        'ordering' => 3,
        'value'    => 'approveItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_move'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'move',
        'label'    => 'forum::phrase.move_thread',
        'ordering' => 4,
        'value'    => 'forum/moveItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_copy'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'copy',
        'label'    => 'forum::phrase.copy_thread',
        'ordering' => 5,
        'value'    => 'forum/copyItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_merge'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'merge',
        'label'    => 'forum::phrase.merge_thread',
        'ordering' => 6,
        'value'    => 'forum/mergeItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_stick'],
            ['falsy', 'item.is_sticked'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'stick',
        'label'    => 'forum::phrase.stick_thread',
        'ordering' => 7,
        'value'    => 'forum/stickItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_stick'],
            ['truthy', 'item.is_sticked'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'unstick',
        'label'    => 'forum::phrase.unstick_thread',
        'ordering' => 8,
        'value'    => 'forum/stickItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_close'],
            ['falsy', 'item.is_closed'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'close',
        'label'    => 'forum::phrase.close_thread',
        'ordering' => 9,
        'value'    => 'forum/closeItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_close'],
            ['truthy', 'item.is_closed'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'reopen',
        'label'    => 'forum::phrase.reopen_thread',
        'ordering' => 10,
        'value'    => 'forum/reopenItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_subscribe'],
            ['falsy', 'item.is_subscribed'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'subscribe',
        'label'    => 'forum::phrase.forum_phrase_item_action_subscribe',
        'ordering' => 12,
        'value'    => 'forum/subscribeItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_subscribe'],
            ['truthy', 'item.is_subscribed'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'unsubscribe',
        'label'    => 'forum::phrase.forum_phrase_item_action_unsubscribe',
        'ordering' => 13,
        'value'    => 'forum/subscribeItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['falsy', 'item.is_sponsored_feed'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'core::phrase.sponsor_in_feed',
        'ordering' => 14,
        'value'    => 'sponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['truthy', 'item.is_sponsored_feed'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'unsponsor_in_feed',
        'label'    => 'core::phrase.remove_sponsor_in_feed',
        'ordering' => 15,
        'value'    => 'unsponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['falsy', 'item.is_sponsor'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'sponsor',
        'label'    => 'forum::phrase.sponsor_this_item',
        'ordering' => 16,
        'value'    => 'sponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['truthy', 'item.is_sponsor'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'unsponsor',
        'label'    => 'forum::phrase.forum_phrase_item_action_un_sponsor',
        'ordering' => 17,
        'value'    => 'unsponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'style'    => 'danger',
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'delete',
        'label'    => 'forum::phrase.delete_thread',
        'ordering' => 22,
        'value'    => 'deleteItem',
    ],
    [
        'menu'     => 'forum.forum_thread.sort_menu',
        'name'     => 'recent',
        'label'    => 'core::phrase.sort.recent',
        'ordering' => 1,
        'value'    => 'recent',
    ],
    [
        'menu'     => 'forum.forum_thread.sort_menu',
        'name'     => 'most_liked',
        'label'    => 'core::phrase.sort.most_liked',
        'ordering' => 2,
        'value'    => 'most_liked',
    ],
    [
        'menu'     => 'forum.forum_thread.sort_menu',
        'name'     => 'most_discussed',
        'label'    => 'core::phrase.sort.most_discussed',
        'ordering' => 3,
        'value'    => 'most_discussed',
    ],
    [
        'menu'     => 'forum.forum.sort_menu',
        'name'     => 'recent',
        'label'    => 'core::phrase.sort.recent',
        'ordering' => 1,
        'value'    => 'recent',
    ],
    [
        'menu'     => 'forum.forum.sort_menu',
        'name'     => 'most_liked',
        'label'    => 'core::phrase.sort.most_liked',
        'ordering' => 2,
        'value'    => 'most_liked',
    ],
    [
        'menu'     => 'forum.forum.sort_menu',
        'name'     => 'most_discussed',
        'label'    => 'core::phrase.sort.most_discussed',
        'ordering' => 3,
        'value'    => 'most_discussed',
    ],
    [
        'tab'      => 'all',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'forum',
            'resource_name' => 'forum_thread',
        ],
        'menu'     => 'forum.sidebarMenu',
        'name'     => 'all',
        'label'    => 'forum::phrase.all_threads',
        'ordering' => 1,
        'value'    => 'viewAll',
        'to'       => '/forum/all',
    ],
    [
        'tab'      => 'my_thread',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'forum',
            'resource_name' => 'forum_thread',
        ],
        'menu'     => 'forum.sidebarMenu',
        'name'     => 'my_thread',
        'label'    => 'forum::phrase.forum_phrase_menu_my_threads',
        'ordering' => 2,
        'value'    => 'viewMyThread',
        'to'       => '/forum/my-thread',
    ],
    [
        'tab'      => 'my_pending_thread',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'forum',
            'resource_name' => 'forum_thread',
        ],
        'menu'     => 'forum.sidebarMenu',
        'name'     => 'my_pending_thread',
        'label'    => 'forum::phrase.forum_phrase_menu_my_pending_threads',
        'ordering' => 3,
        'value'    => 'viewMyPendingThread',
        'to'       => '/forum/my-pending-thread',
    ],
    [
        'tab'      => 'subscribed_thread',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'forum',
            'resource_name' => 'forum_thread',
        ],
        'menu'     => 'forum.sidebarMenu',
        'name'     => 'subscribed_thread',
        'label'    => 'forum::phrase.forum_phrase_menu_subscribed_threads',
        'ordering' => 4,
        'value'    => 'viewSubscribedThread',
        'to'       => '/forum/subscribed-thread',
    ],
    [
        'tab'      => 'history_thread',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'forum',
            'resource_name' => 'forum_thread',
        ],
        'menu'     => 'forum.sidebarMenu',
        'name'     => 'history_thread',
        'label'    => 'forum::phrase.forum_phrase_menu_history',
        'ordering' => 5,
        'value'    => 'viewHistoryThread',
        'to'       => '/forum/history-thread',
    ],
    [
        'tab'      => 'pending_thread',
        'showWhen' => [
            'and',
            ['truthy', 'acl.forum.forum_thread.approve'],
        ],
        'params' => [
            'module_name'   => 'forum',
            'resource_name' => 'forum_thread',
        ],
        'menu'     => 'forum.sidebarMenu',
        'name'     => 'pending_thread',
        'label'    => 'forum::phrase.forum_phrase_menu_pending_threads',
        'ordering' => 6,
        'value'    => 'viewPendingThread',
        'to'       => '/forum/pending-thread',
    ],
    [
        'tab'    => 'wiki_thread',
        'params' => [
            'module_name'   => 'forum',
            'resource_name' => 'forum_thread',
        ],
        'menu'     => 'forum.sidebarMenu',
        'name'     => 'wiki_thread',
        'label'    => 'forum::phrase.forum_phrase_menu_wiki',
        'ordering' => 7,
        'value'    => 'viewWikiThread',
        'to'       => '/forum/wiki-thread',
    ],
    [
        'tab'      => 'my_pending_post',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'forum',
            'resource_name' => 'forum_post',
        ],
        'menu'     => 'forum.sidebarMenu',
        'name'     => 'my_pending_post',
        'label'    => 'forum::phrase.forum_phrase_menu_my_pending_posts',
        'ordering' => 8,
        'value'    => 'viewMyPendingPost',
        'to'       => '/forum/my-pending-post',
    ],
    [
        'tab'      => 'pending_post',
        'showWhen' => [
            'and',
            ['truthy', 'acl.forum.forum_post.approve'],
        ],
        'params' => [
            'module_name'   => 'forum',
            'resource_name' => 'forum_post',
        ],
        'menu'     => 'forum.sidebarMenu',
        'name'     => 'pending_post',
        'label'    => 'forum::phrase.forum_phrase_menu_pending_posts',
        'ordering' => 9,
        'value'    => 'viewPendingPost',
        'to'       => '/forum/pending-post',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.forum.forum.view'],
        ],
        'module_name'   => 'forum',
        'resource_name' => 'forum_thread',
        'menu'          => 'search.mobileCategoryMenu',
        'name'          => 'forum_thread',
        'label'         => 'forum::phrase.forum_thread_global_search_label',
        'ordering'      => 5,
        'value'         => 'searchGlobalThread',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.forum.forum.view'],
        ],
        'menu'     => 'search.mobileHashtagCategoryMenu',
        'name'     => 'forum_thread',
        'label'    => 'forum::phrase.forum_thread_global_search_label',
        'ordering' => 4,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.forum.forum.view'],
        ],
        'menu'          => 'group.mobileCategoryMenu',
        'name'          => 'forum_thread',
        'module_name'   => 'forum',
        'resource_name' => 'forum_thread',
        'label'         => 'forum::phrase.forum_thread_global_search_label',
        'ordering'      => 5,
        'value'         => 'searchGlobalThread',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.forum.forum.view'],
        ],
        'menu'          => 'page.mobileCategoryMenu',
        'name'          => 'forum_thread',
        'module_name'   => 'forum',
        'resource_name' => 'forum_thread',
        'label'         => 'forum::phrase.forum_thread_global_search_label',
        'ordering'      => 5,
        'value'         => 'searchGlobalThread',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.forum.forum_thread.create'],
            ['truthy', 'item.is_owner'],
        ],
        'menu'     => 'forum.forum.headerItemActionOnUserProfileMenu',
        'name'     => 'forum_thread',
        'label'    => 'forum::phrase.forum_phrase_menu_create_new_thread',
        'ordering' => 1,
        'to'       => '/forum/thread/add',
    ],
    [
        'tab'      => 'forum',
        'showWhen' => [
            'and',
            ['truthy', 'acl.forum.forum_thread.create'],
            ['falsy', 'item.is_muted'],
            ['truthy', 'item.extra.can_manage_setting'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'forum.forum.headerItemActionOnGroupProfileMenu',
        'name'     => 'forum_thread',
        'label'    => 'forum::phrase.forum_phrase_menu_create_new_thread',
        'ordering' => 1,
        'to'       => '/forum/thread/add?owner_id=:id',
    ],
    [
        'tab'      => 'forum',
        'showWhen' => [
            'and',
            ['truthy', 'acl.forum.forum_thread.create'],
            ['truthy', 'item.profile_settings.forum_share_forum_thread'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'forum.forum.headerItemActionOnPageProfileMenu',
        'name'     => 'forum_thread',
        'label'    => 'forum::phrase.forum_phrase_menu_create_new_thread',
        'ordering' => 1,
        'to'       => '/forum/thread/add?owner_id=:id',
    ],
    [
        'showWhen'  => [],
        'menu'      => 'core.bodyMenu',
        'name'      => 'forums',
        'label'     => 'forum::phrase.forums',
        'ordering'  => 8,
        'value'     => '',
        'to'        => '/forum',
        'as'        => 'item',
        'icon'      => 'comment-square',
        'iconColor' => '#ffba27',
    ],
];
