<?php

/* this is auto generated file */
return [
    [
        'subInfo'  => 'forum::phrase.browse_threads_you_like_to_read',
        'menu'     => 'core.dropdownMenu',
        'name'     => 'forum',
        'label'    => 'forum::phrase.forums',
        'ordering' => 12,
        'icon'     => 'ico-comments-square',
        'to'       => '/forum',
    ],
    [
        'subInfo'  => 'forum::phrase.browse_threads_you_like_to_read',
        'menu'     => 'core.primaryMenu',
        'name'     => 'forum',
        'label'    => 'forum::phrase.forums',
        'ordering' => 12,
        'icon'     => 'ico-comments-square',
        'to'       => '/forum',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.forum.forum_thread.create'],
            ['truthy', 'item.is_owner'],
        ],
        'menu'     => 'forum.forum.headerItemActionOnUserProfileMenu',
        'name'     => 'forum_thread',
        'label'    => 'forum::phrase.forum_phrase_menu_create_new_thread',
        'ordering' => 1,
        'to'       => '/forum/thread/add',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'forum.forum.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'forum::phrase.edit_forum',
        'ordering' => 1,
        'value'    => 'editItem',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'menu'      => 'forum.forum.itemActionMenu',
        'name'      => 'delete',
        'label'     => 'core::phrase.delete',
        'ordering'  => 2,
        'value'     => 'deleteItem',
        'icon'      => 'ico-trash',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'forum.forum_post.detailActionMenu',
        'name'     => 'edit',
        'label'    => 'forum::phrase.edit_post',
        'ordering' => 1,
        'value'    => 'forum_post/editItem',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_approve'],
            ['falsy', 'item.is_approved'],
        ],
        'menu'     => 'forum.forum_post.detailActionMenu',
        'name'     => 'approve',
        'label'    => 'core::phrase.approve',
        'ordering' => 2,
        'value'    => 'approveItem',
        'icon'     => 'ico-check-circle-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_quote'],
        ],
        'menu'     => 'forum.forum_post.detailActionMenu',
        'name'     => 'quote',
        'label'    => 'forum::phrase.forum_phrase_item_action_quote',
        'ordering' => 3,
        'value'    => 'forum/quoteItem',
        'icon'     => 'ico-comment-square-quote-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'menu'      => 'forum.forum_post.detailActionMenu',
        'name'      => 'delete',
        'label'     => 'core::phrase.delete',
        'ordering'  => 7,
        'value'     => 'deleteItem',
        'icon'      => 'ico-trash',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'forum.forum_post.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'forum::phrase.edit_post',
        'ordering' => 1,
        'value'    => 'forum_post/editItem',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_approve'],
            ['falsy', 'item.is_approved'],
        ],
        'menu'     => 'forum.forum_post.itemActionMenu',
        'name'     => 'approve',
        'label'    => 'core::phrase.approve',
        'ordering' => 2,
        'value'    => 'approveItem',
        'icon'     => 'ico-check-circle-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_quote'],
        ],
        'menu'     => 'forum.forum_post.itemActionMenu',
        'name'     => 'quote',
        'label'    => 'forum::phrase.forum_phrase_item_action_quote',
        'ordering' => 3,
        'value'    => 'forum/quoteItem',
        'icon'     => 'ico-comment-square-quote-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'menu'      => 'forum.forum_post.itemActionMenu',
        'name'      => 'delete',
        'label'     => 'core::phrase.delete',
        'ordering'  => 7,
        'value'     => 'deleteItem',
        'icon'      => 'ico-trash',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'edit',
        'label'    => 'forum::phrase.edit_thread',
        'ordering' => 1,
        'value'    => 'editItem',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'first_divider',
        'ordering' => 2,
        'as'       => 'divider',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_approve'],
            ['falsy', 'item.is_approved'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'approve',
        'label'    => 'forum::phrase.approve_thread',
        'ordering' => 3,
        'value'    => 'approveItem',
        'icon'     => 'ico-check-circle-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_move'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'move',
        'label'    => 'forum::phrase.move_thread',
        'ordering' => 4,
        'value'    => 'forum/moveItem',
        'icon'     => 'ico-move-up',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_copy'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'copy',
        'label'    => 'forum::phrase.copy_thread',
        'ordering' => 5,
        'value'    => 'forum/copyItem',
        'icon'     => 'ico-copy-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_merge'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'merge',
        'label'    => 'forum::phrase.merge_thread',
        'ordering' => 6,
        'value'    => 'forum/mergeItem',
        'icon'     => 'ico-merge-file-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_stick'],
            ['falsy', 'item.is_sticked'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'stick',
        'label'    => 'forum::phrase.stick_thread',
        'ordering' => 7,
        'value'    => 'forum/stickItem',
        'icon'     => 'ico-thumb-tack-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_stick'],
            ['truthy', 'item.is_sticked'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'unstick',
        'label'    => 'forum::phrase.unstick_thread',
        'ordering' => 8,
        'value'    => 'forum/stickItem',
        'icon'     => 'ico-list-down',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_close'],
            ['falsy', 'item.is_closed'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'close',
        'label'    => 'forum::phrase.close_thread',
        'ordering' => 9,
        'value'    => 'forum/closeItem',
        'icon'     => 'ico-text-file-lock',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_close'],
            ['truthy', 'item.is_closed'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'reopen',
        'label'    => 'forum::phrase.reopen_thread',
        'ordering' => 10,
        'value'    => 'forum/reopenItem',
        'icon'     => 'ico-rotate-right-alt',
    ],
    [
        'showWhen' => [
            'or',
            ['truthy', 'item.extra.can_close'],
            ['truthy', 'item.extra.can_stick'],
            ['truthy', 'item.extra.can_merge'],
            ['truthy', 'item.extra.can_copy'],
            ['truthy', 'item.extra.can_move'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'second_divider',
        'ordering' => 11,
        'as'       => 'divider',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_subscribe'],
            ['falsy', 'item.is_subscribed'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'subscribe',
        'label'    => 'forum::phrase.forum_phrase_item_action_subscribe',
        'ordering' => 12,
        'value'    => 'forum/subscribeItem',
        'icon'     => 'ico-bell2-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_subscribe'],
            ['truthy', 'item.is_subscribed'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'unsubscribe',
        'label'    => 'forum::phrase.forum_phrase_item_action_unsubscribe',
        'ordering' => 13,
        'value'    => 'forum/subscribeItem',
        'icon'     => 'ico-bell2-off-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['falsy', 'item.is_sponsored_feed'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'core::phrase.sponsor_in_feed',
        'ordering' => 14,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['truthy', 'item.is_sponsored_feed'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'unsponsor_in_feed',
        'label'    => 'core::phrase.remove_sponsor_in_feed',
        'ordering' => 15,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['falsy', 'item.is_sponsor'],
        ],
        'menu'       => 'forum.forum_thread.detailActionMenu',
        'name'       => 'sponsor',
        'label'      => 'forum::phrase.sponsor_this_item',
        'ordering'   => 16,
        'value'      => 'sponsorItem',
        'icon'       => 'ico-sponsor',
        'is_active'  => 0,
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['truthy', 'item.is_sponsor'],
        ],
        'menu'       => 'forum.forum_thread.detailActionMenu',
        'name'       => 'unsponsor',
        'label'      => 'forum::phrase.forum_phrase_item_action_un_sponsor',
        'ordering'   => 17,
        'value'      => 'unsponsorItem',
        'icon'       => 'ico-sponsor',
        'is_active'  => 0,
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'or',
            ['truthy', 'item.extra.can_sponsor'],
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['truthy', 'item.extra.can_subscribe'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'third_divider',
        'ordering' => 18,
        'as'       => 'divider',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'delete',
        'label'    => 'forum::phrase.delete_thread',
        'ordering' => 22,
        'value'    => 'deleteItem',
        'icon'     => 'ico-trash',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'forum::phrase.edit_thread',
        'ordering' => 1,
        'value'    => 'editItem',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'first_divider',
        'ordering' => 2,
        'as'       => 'divider',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_approve'],
            ['falsy', 'item.is_approved'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'approve',
        'label'    => 'forum::phrase.approve_thread',
        'ordering' => 3,
        'value'    => 'approveItem',
        'icon'     => 'ico-check-circle-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_move'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'move',
        'label'    => 'forum::phrase.move_thread',
        'ordering' => 4,
        'value'    => 'forum/moveItem',
        'icon'     => 'ico-move-up',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_copy'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'copy',
        'label'    => 'forum::phrase.copy_thread',
        'ordering' => 5,
        'value'    => 'forum/copyItem',
        'icon'     => 'ico-copy-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_merge'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'merge',
        'label'    => 'forum::phrase.merge_thread',
        'ordering' => 6,
        'value'    => 'forum/mergeItem',
        'icon'     => 'ico-merge-file-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_stick'],
            ['falsy', 'item.is_sticked'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'stick',
        'label'    => 'forum::phrase.stick_thread',
        'ordering' => 7,
        'value'    => 'forum/stickItem',
        'icon'     => 'ico-thumb-tack-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_stick'],
            ['truthy', 'item.is_sticked'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'unstick',
        'label'    => 'forum::phrase.unstick_thread',
        'ordering' => 8,
        'value'    => 'forum/stickItem',
        'icon'     => 'ico-list-down',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_close'],
            ['falsy', 'item.is_closed'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'close',
        'label'    => 'forum::phrase.close_thread',
        'ordering' => 9,
        'value'    => 'forum/closeItem',
        'icon'     => 'ico-text-file-lock',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_close'],
            ['truthy', 'item.is_closed'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'reopen',
        'label'    => 'forum::phrase.reopen_thread',
        'ordering' => 10,
        'value'    => 'forum/reopenItem',
        'icon'     => 'ico-rotate-right-alt',
    ],
    [
        'showWhen' => [
            'or',
            ['truthy', 'item.extra.can_close'],
            ['truthy', 'item.extra.can_stick'],
            ['truthy', 'item.extra.can_merge'],
            ['truthy', 'item.extra.can_copy'],
            ['truthy', 'item.extra.can_move'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'second_divider',
        'ordering' => 11,
        'as'       => 'divider',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_subscribe'],
            ['falsy', 'item.is_subscribed'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'subscribe',
        'label'    => 'forum::phrase.forum_phrase_item_action_subscribe',
        'ordering' => 12,
        'value'    => 'forum/subscribeItem',
        'icon'     => 'ico-bell2-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_subscribe'],
            ['truthy', 'item.is_subscribed'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'unsubscribe',
        'label'    => 'forum::phrase.forum_phrase_item_action_unsubscribe',
        'ordering' => 13,
        'value'    => 'forum/subscribeItem',
        'icon'     => 'ico-bell2-off-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['falsy', 'item.is_sponsored_feed'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'core::phrase.sponsor_in_feed',
        'ordering' => 14,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['truthy', 'item.is_sponsored_feed'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'unsponsor_in_feed',
        'label'    => 'core::phrase.remove_sponsor_in_feed',
        'ordering' => 15,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['falsy', 'item.is_sponsor'],
        ],
        'menu'       => 'forum.forum_thread.itemActionMenu',
        'name'       => 'sponsor',
        'label'      => 'forum::phrase.sponsor_this_item',
        'ordering'   => 16,
        'value'      => 'sponsorItem',
        'icon'       => 'ico-sponsor',
        'is_active'  => 0,
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['truthy', 'item.is_sponsor'],
        ],
        'menu'       => 'forum.forum_thread.itemActionMenu',
        'name'       => 'unsponsor',
        'label'      => 'forum::phrase.forum_phrase_item_action_un_sponsor',
        'ordering'   => 17,
        'value'      => 'unsponsorItem',
        'icon'       => 'ico-sponsor',
        'is_active'  => 0,
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'or',
            ['truthy', 'item.extra.can_sponsor'],
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['truthy', 'item.extra.can_subscribe'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'third_divider',
        'ordering' => 18,
        'as'       => 'divider',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'delete',
        'label'    => 'forum::phrase.delete_thread',
        'ordering' => 22,
        'value'    => 'deleteItem',
        'icon'     => 'ico-trash',
    ],
    [
        'tab'      => 'landing',
        'menu'     => 'forum.sidebarMenu',
        'name'     => 'landing',
        'label'    => 'forum::phrase.forum_phrase_menu_home',
        'ordering' => 1,
        'icon'     => 'ico-newspaper-alt-o',
        'to'       => '/forum',
    ],
    [
        'tab'      => 'my_thread',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'forum.sidebarMenu',
        'name'     => 'my_thread',
        'label'    => 'forum::phrase.forum_phrase_menu_my_threads',
        'ordering' => 2,
        'icon'     => 'ico-user-man-o',
        'to'       => '/forum/my-thread',
    ],
    [
        'tab'      => 'my_pending_thread',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'forum.sidebarMenu',
        'name'     => 'my_pending_thread',
        'label'    => 'forum::phrase.forum_phrase_menu_my_pending_threads',
        'ordering' => 3,
        'icon'     => 'ico-user1-clock-o',
        'to'       => '/forum/my-pending-thread',
    ],
    [
        'tab'      => 'subscribed_thread',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'forum.sidebarMenu',
        'name'     => 'subscribed_thread',
        'label'    => 'forum::phrase.forum_phrase_menu_subscribed_threads',
        'ordering' => 4,
        'icon'     => 'ico-bell2-o',
        'to'       => '/forum/subscribed-thread',
    ],
    [
        'tab'      => 'history_thread',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'forum.sidebarMenu',
        'name'     => 'history_thread',
        'label'    => 'forum::phrase.forum_phrase_menu_history',
        'ordering' => 5,
        'icon'     => 'ico-clock-o',
        'to'       => '/forum/history-thread',
    ],
    [
        'tab'      => 'pending_thread',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.forum.forum_thread.approve'],
        ],
        'menu'     => 'forum.sidebarMenu',
        'name'     => 'pending_thread',
        'label'    => 'forum::phrase.forum_phrase_menu_pending_threads',
        'ordering' => 6,
        'icon'     => 'ico-sandclock-start-o',
        'to'       => '/forum/pending-thread',
    ],
    [
        'tab'      => 'wiki_thread',
        'menu'     => 'forum.sidebarMenu',
        'name'     => 'wiki_thread',
        'label'    => 'forum::phrase.forum_phrase_menu_wiki',
        'ordering' => 7,
        'icon'     => 'ico-file-word-o',
        'to'       => '/forum/wiki-thread',
    ],
    [
        'tab'      => 'my_pending_post',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'forum.sidebarMenu',
        'name'     => 'my_pending_post',
        'label'    => 'forum::phrase.forum_phrase_menu_my_pending_posts',
        'ordering' => 8,
        'icon'     => 'ico-user1-clock-o',
        'to'       => '/forum/my-pending-post',
    ],
    [
        'tab'      => 'pending_post',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.forum.forum_post.approve'],
        ],
        'menu'     => 'forum.sidebarMenu',
        'name'     => 'pending_post',
        'label'    => 'forum::phrase.forum_phrase_menu_pending_posts',
        'ordering' => 9,
        'icon'     => 'ico-sandclock-start-o',
        'to'       => '/forum/pending-post',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.forum.forum_thread.create'],
        ],
        'buttonProps' => [
            'fullWidth' => true,
            'color'     => 'primary',
            'variant'   => 'contained',
        ],
        'menu'     => 'forum.sidebarMenu',
        'name'     => 'add',
        'label'    => 'forum::phrase.forum_phrase_menu_create_new_thread',
        'ordering' => 10,
        'as'       => 'sidebarButton',
        'icon'     => 'ico-plus',
        'to'       => '/forum/thread/add',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.forum.forum.view'],
        ],
        'menu'     => 'search.webCategoryMenu',
        'name'     => 'forum_thread',
        'label'    => 'forum::phrase.forum_thread_global_search_label',
        'ordering' => 5,
        'to'       => '/search/forum_thread',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.forum.forum.view'],
        ],
        'menu'     => 'search.webCategoryOrderingMenu',
        'name'     => 'forum_thread',
        'label'    => 'forum::phrase.forum_thread_global_search_label',
        'ordering' => 11,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.forum.forum.view'],
        ],
        'menu'     => 'search.webHashtagCategoryMenu',
        'name'     => 'forum_thread',
        'label'    => 'forum::phrase.forum_thread_global_search_label',
        'ordering' => 4,
    ],
    [
        'tab'      => 'forum',
        'showWhen' => [
            'and',
            ['truthy', 'acl.forum.forum.view'],
            ['truthy', 'item.profile_menu_settings.forum_profile_menu'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'forum',
        'label'    => 'forum::phrase.forums',
        'ordering' => 13,
        'to'       => '/forum',
    ],
    [
        'tab'      => 'forum',
        'showWhen' => [
            'and',
            ['truthy', 'acl.forum.forum_thread.create'],
            ['falsy', 'item.is_muted'],
            ['truthy', 'item.extra.can_manage_setting'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'forum.forum.headerItemActionOnGroupProfileMenu',
        'name'     => 'forum_thread',
        'label'    => 'forum::phrase.forum_phrase_menu_create_new_thread',
        'ordering' => 1,
        'to'       => '/forum/thread/add?owner_id=:id',
    ],
    [
        'tab'      => 'forum',
        'showWhen' => [
            'and',
            ['truthy', 'acl.forum.forum_thread.create'],
            ['truthy', 'item.profile_settings.forum_share_forum_thread'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'forum.forum.headerItemActionOnPageProfileMenu',
        'name'     => 'forum_thread',
        'label'    => 'forum::phrase.forum_phrase_menu_create_new_thread',
        'ordering' => 1,
        'to'       => '/forum/thread/add?owner_id=:id',
    ],
    [
        'tab'      => 'forum',
        'showWhen' => [
            'or',
            ['eq', 'item.reg_method', '0'],
            [
                'or',
                ['truthy', 'acl.group.group.moderate'],
                ['truthy', 'item.is_member'],
            ],
        ],
        'menu'     => 'group.group.profileMenu',
        'name'     => 'forum',
        'label'    => 'forum::phrase.forums',
        'ordering' => 13,
        'to'       => '/forum',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.forum.forum.view'],
        ],
        'menu'     => 'group.searchWebCategoryMenu',
        'name'     => 'forum_thread',
        'label'    => 'forum::phrase.forum_thread_global_search_label',
        'ordering' => 2,
    ],
    [
        'tab'      => 'forum',
        'showWhen' => [
            'and',
            ['truthy', 'acl.forum.forum.view'],
        ],
        'menu'     => 'page.page.profileMenu',
        'name'     => 'forum',
        'label'    => 'forum::phrase.forums',
        'ordering' => 13,
        'to'       => '/forum',
    ],
];
