<?php

/* this is auto generated file */
return [
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'blog.blog.detailActionMenu',
        'name'     => 'edit',
        'label'    => 'blog::phrase.edit_blog',
        'ordering' => 1,
        'value'    => 'editItem',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_publish'],
            ['truthy', 'item.is_draft'],
        ],
        'menu'     => 'blog.blog.detailActionMenu',
        'name'     => 'publish',
        'label'    => 'blog::phrase.publish',
        'ordering' => 3,
        'value'    => 'publishBlog',
        'icon'     => 'ico-check',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'blog.blog.detailActionMenu',
        'name'     => 'approve',
        'label'    => 'blog::phrase.approve',
        'ordering' => 4,
        'value'    => 'approveItem',
        'icon'     => 'ico-check-circle-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['falsy', 'item.is_sponsored_feed'],
            ['falsy', 'item.is_draft'],
        ],
        'menu'     => 'blog.blog.detailActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'blog::phrase.sponsor_in_feed',
        'ordering' => 5,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['truthy', 'item.is_sponsored_feed'],
            ['falsy', 'item.is_draft'],
        ],
        'menu'     => 'blog.blog.detailActionMenu',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'blog::phrase.un_sponsor_in_feed',
        'ordering' => 6,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['falsy', 'item.is_sponsor'],
            ['falsy', 'item.is_draft'],
        ],
        'menu'     => 'blog.blog.detailActionMenu',
        'name'     => 'sponsor',
        'label'    => 'blog::phrase.sponsor_this_item',
        'ordering' => 7,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['truthy', 'item.is_sponsor'],
            ['falsy', 'item.is_draft'],
        ],
        'menu'     => 'blog.blog.detailActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'blog::phrase.unsponsor_this_item',
        'ordering' => 8,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_draft'],
        ],
        'menu'     => 'blog.blog.detailActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 9,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_draft'],
        ],
        'menu'     => 'blog.blog.detailActionMenu',
        'name'     => 'remove_feature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 10,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'menu'      => 'blog.blog.detailActionMenu',
        'name'      => 'delete',
        'label'     => 'blog::phrase.delete',
        'ordering'  => 13,
        'value'     => 'deleteItem',
        'icon'      => 'ico-trash',
    ],
    [
        'tab'      => 'blog',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.blog.blog.create'],
            ['truthy', 'item.profile_settings.blog_share_blogs'],
            ['falsy', 'item.is_muted'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'blog.blog.headerItemActionOnGroupProfileMenu',
        'name'     => 'blog',
        'label'    => 'blog::phrase.add_new_blog',
        'ordering' => 1,
        'to'       => '/blog/add?owner_id=:id',
    ],
    [
        'tab'      => 'blog',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.blog.blog.create'],
            ['truthy', 'item.profile_settings.blog_share_blogs'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'blog.blog.headerItemActionOnPageProfileMenu',
        'name'     => 'blog',
        'label'    => 'blog::phrase.add_new_blog',
        'ordering' => 1,
        'to'       => '/blog/add?owner_id=:id',
    ],
    [
        'tab'      => 'blog',
        'showWhen' => [
            'and',
            ['truthy', 'acl.blog.blog.create'],
            ['truthy', 'item.is_owner'],
        ],
        'menu'     => 'blog.blog.headerItemActionOnUserProfileMenu',
        'name'     => 'blog',
        'label'    => 'blog::phrase.add_new_blog',
        'ordering' => 1,
        'to'       => '/blog/add?owner_id=:id',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'blog.blog.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'blog::phrase.edit_blog',
        'ordering' => 1,
        'value'    => 'editItem',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_publish'],
            ['truthy', 'item.is_draft'],
        ],
        'menu'     => 'blog.blog.itemActionMenu',
        'name'     => 'publish',
        'label'    => 'blog::phrase.publish',
        'ordering' => 3,
        'value'    => 'publishBlog',
        'icon'     => 'ico-check',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'blog.blog.itemActionMenu',
        'name'     => 'approve',
        'label'    => 'blog::phrase.approve',
        'ordering' => 4,
        'value'    => 'approveItem',
        'icon'     => 'ico-check-circle-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['falsy', 'item.is_sponsored_feed'],
            ['falsy', 'item.is_draft'],
        ],
        'menu'     => 'blog.blog.itemActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'blog::phrase.sponsor_in_feed',
        'ordering' => 5,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['truthy', 'item.is_sponsored_feed'],
            ['falsy', 'item.is_draft'],
        ],
        'menu'     => 'blog.blog.itemActionMenu',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'blog::phrase.un_sponsor_in_feed',
        'ordering' => 6,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['falsy', 'item.is_sponsor'],
            ['falsy', 'item.is_draft'],
        ],
        'menu'     => 'blog.blog.itemActionMenu',
        'name'     => 'sponsor',
        'label'    => 'blog::phrase.sponsor_this_item',
        'ordering' => 7,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['truthy', 'item.is_sponsor'],
            ['falsy', 'item.is_draft'],
        ],
        'menu'     => 'blog.blog.itemActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'blog::phrase.unsponsor_this_item',
        'ordering' => 8,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_draft'],
        ],
        'menu'     => 'blog.blog.itemActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 9,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_draft'],
        ],
        'menu'     => 'blog.blog.itemActionMenu',
        'name'     => 'remove_feature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 10,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'menu'      => 'blog.blog.itemActionMenu',
        'name'      => 'delete',
        'label'     => 'blog::phrase.delete',
        'ordering'  => 13,
        'value'     => 'deleteItem',
        'icon'      => 'ico-trash',
    ],
    [
        'tab'      => 'landing',
        'menu'     => 'blog.sidebarMenu',
        'name'     => 'landing',
        'label'    => 'blog::phrase.home',
        'ordering' => 1,
        'icon'     => 'ico-newspaper-alt-o',
        'to'       => '/blog',
    ],
    [
        'tab'      => 'all',
        'menu'     => 'blog.sidebarMenu',
        'name'     => 'all',
        'label'    => 'blog::phrase.all_blogs',
        'ordering' => 2,
        'icon'     => 'ico-hashtag',
        'to'       => '/blog/all',
    ],
    [
        'tab'      => 'my',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'blog.sidebarMenu',
        'name'     => 'my',
        'label'    => 'blog::phrase.my_blogs',
        'ordering' => 3,
        'icon'     => 'ico-user-man-o',
        'to'       => '/blog/my',
    ],
    [
        'tab'      => 'my_pending',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['neq', 'session.user.role.id', 1],
        ],
        'menu'     => 'blog.sidebarMenu',
        'name'     => 'my_pending',
        'label'    => 'blog::phrase.my_pending_blogs',
        'ordering' => 4,
        'icon'     => 'ico-user1-clock-o',
        'to'       => '/blog/my-pending',
    ],
    [
        'tab'      => 'friend',
        'showWhen' => [
            'and',
            ['falsy', 'setting.core.general.friends_only_community'],
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'blog.sidebarMenu',
        'name'     => 'friends',
        'label'    => 'blog::phrase.friends_blogs',
        'ordering' => 5,
        'icon'     => 'ico-user1-two-o',
        'to'       => '/blog/friend',
    ],
    [
        'tab'      => 'draft',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'blog.sidebarMenu',
        'name'     => 'draft',
        'label'    => 'blog::phrase.my_draft_blogs',
        'ordering' => 6,
        'icon'     => 'ico-pencilline-o',
        'to'       => '/blog/draft',
    ],
    [
        'tab'      => 'pending',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.blog.blog.approve'],
        ],
        'menu'     => 'blog.sidebarMenu',
        'name'     => 'pending',
        'label'    => 'blog::phrase.pending_blogs',
        'ordering' => 7,
        'icon'     => 'ico-clock-o',
        'to'       => '/blog/pending',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.blog.blog.create'],
        ],
        'buttonProps' => [
            'fullWidth' => true,
            'color'     => 'primary',
            'variant'   => 'contained',
        ],
        'menu'     => 'blog.sidebarMenu',
        'name'     => 'add',
        'label'    => 'blog::phrase.create_new_blog',
        'ordering' => 8,
        'as'       => 'sidebarButton',
        'icon'     => 'ico-plus',
        'to'       => '/blog/add',
    ],
    [
        'subInfo'  => 'blog::phrase.browse_blogs_you_like_to_read',
        'menu'     => 'core.dropdownMenu',
        'name'     => 'blogs',
        'label'    => 'blog::phrase.blogs',
        'ordering' => 10,
        'icon'     => 'ico-newspaper-alt',
        'to'       => '/blog',
    ],
    [
        'subInfo'  => 'blog::phrase.browse_blogs_you_like_to_read',
        'menu'     => 'core.primaryMenu',
        'name'     => 'blogs',
        'label'    => 'blog::phrase.blogs',
        'ordering' => 10,
        'icon'     => 'ico-newspaper-alt',
        'to'       => '/blog',
    ],
    [
        'tab'      => 'blog',
        'showWhen' => [
            'or',
            ['eq', 'item.reg_method', '0'],
            [
                'or',
                ['truthy', 'acl.group.group.moderate'],
                ['truthy', 'item.is_member'],
            ],
        ],
        'menu'     => 'group.group.profileMenu',
        'name'     => 'blog',
        'label'    => 'blog::phrase.blogs',
        'ordering' => 9,
        'to'       => '/blog',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.blog.blog.view'],
        ],
        'menu'     => 'group.searchWebCategoryMenu',
        'name'     => 'blog',
        'label'    => 'blog::phrase.blog_global_search_label',
        'ordering' => 2,
    ],
    [
        'tab'      => 'blog',
        'showWhen' => [
            'and',
            ['truthy', 'acl.blog.blog.view'],
            ['truthy', 'item.profile_settings.blog_view_browse_blogs'],
        ],
        'menu'     => 'page.page.profileMenu',
        'name'     => 'blog',
        'label'    => 'blog::phrase.blogs',
        'ordering' => 9,
        'to'       => '/blog',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.blog.blog.view'],
        ],
        'menu'     => 'search.webCategoryMenu',
        'name'     => 'blog',
        'label'    => 'blog::phrase.blog_global_search_label',
        'ordering' => 3,
        'to'       => '/search/blog',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.blog.blog.view'],
        ],
        'menu'     => 'search.webCategoryOrderingMenu',
        'name'     => 'blog',
        'label'    => 'blog::phrase.blog_global_search_label',
        'ordering' => 2,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.blog.blog.view'],
        ],
        'menu'     => 'search.webHashtagCategoryMenu',
        'name'     => 'blog',
        'label'    => 'blog::phrase.blog_global_search_label',
        'ordering' => 2,
    ],
    [
        'tab'      => 'blog',
        'showWhen' => [
            'and',
            ['truthy', 'item.profile_menu_settings.blog_profile_menu'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'blog',
        'label'    => 'blog::phrase.blogs',
        'ordering' => 9,
        'to'       => '/blog',
    ],
];
