<?php

/* this is auto generated file */
return [
    [
        'name'         => 'admin.group.browse_category',
        'phrase_title' => 'core::phrase.categories',
        'url'          => 'admincp/group/category/browse',
    ],
    [
        'name'                 => 'admin.group.browse_child_category',
        'phrase_title'         => 'core::phrase.categories',
        'url'                  => 'admincp/group/category/{id}/category/browse',
        'custom_sharing_route' => 1,
    ],
    [
        'name'         => 'admin.group.browse_example_rule',
        'phrase_title' => 'group::seo.browse_example_rule',
        'url'          => 'admincp/group/example-rule/browse',
    ],
    [
        'name'         => 'admin.group.create_example_rule',
        'phrase_title' => 'group::seo.browse_create_example_rule',
        'url'          => 'admincp/group/example-rule/create',
    ],
    [
        'name'         => 'admin.group.create_category',
        'phrase_title' => 'core::phrase.add_category',
        'url'          => 'admincp/group/category/create',
    ],
    [
        'name'         => 'admin.group.edit_category',
        'phrase_title' => 'core::phrase.edit_category',
        'url'          => 'admincp/group/category/edit/{id}',
    ],
    [
        'name'         => 'admin.group.group_setting',
        'phrase_title' => 'core::phrase.settings',
        'url'          => 'admincp/group/setting',
    ],
    [
        'name'         => 'admin.group.permissions',
        'phrase_title' => 'core::phrase.permissions',
        'url'          => 'admincp/group/permission',
    ],
    [
        'name'               => 'group.browse_all_group',
        'phrase_title'       => 'group::seo.browse_all_group_title',
        'phrase_description' => 'group::seo.browse_all_group_description',
        'phrase_keywords'    => 'group::seo.browse_all_group_keywords',
        'phrase_heading'     => 'group::seo.browse_all_group_heading',
        'url'                => 'group/all',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'group.browse_friend_group',
        'phrase_title'       => 'group::seo.browse_friend_group_title',
        'phrase_description' => 'group::seo.browse_friend_group_description',
        'phrase_keywords'    => 'group::seo.browse_friend_group_keywords',
        'phrase_heading'     => 'group::seo.browse_friend_group_heading',
        'url'                => 'group/friend',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'group.browse_invited_group',
        'phrase_title'       => 'group::seo.browse_invited_group_title',
        'phrase_description' => 'group::seo.browse_invited_group_description',
        'phrase_keywords'    => 'group::seo.browse_invited_group_keywords',
        'phrase_heading'     => 'group::seo.browse_invited_group_heading',
        'url'                => 'group/invited',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'group.browse_joined_group',
        'phrase_title'       => 'group::seo.browse_joined_group_title',
        'phrase_description' => 'group::seo.browse_joined_group_desription',
        'phrase_keywords'    => 'group::seo.browse_joined_group_keywords',
        'phrase_heading'     => 'group::seo.browse_joined_group_heading',
        'url'                => 'group/joined',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'group.browse_my_pending_group',
        'phrase_title'       => 'group::seo.browse_my_pending_group_title',
        'phrase_description' => 'group::seo.browse_my_pending_group_description',
        'phrase_keywords'    => 'group::seo.browse_my_pending_group_keywords',
        'phrase_heading'     => 'group::seo.browse_my_pending_group_heading',
        'url'                => 'group/my-pending',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'group.browse_pending_group',
        'phrase_title'       => 'group::seo.browse_pending_group_title',
        'phrase_description' => 'group::seo.browse_pending_group_description',
        'phrase_keywords'    => 'group::seo.browse_pending_group_keywords',
        'phrase_heading'     => 'group::seo.browse_pending_group_heading',
        'url'                => 'group/pending',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'group.group',
        'phrase_title'       => 'core::seo.core_search_title',
        'phrase_description' => 'core::seo.core_search_description',
        'phrase_keywords'    => 'core::seo.core_search_keywords',
        'phrase_heading'     => 'core::seo.core_search_heading',
        'url'                => 'group/search',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'group.group.about',
        'phrase_title'       => 'group::seo.group_about_title',
        'phrase_description' => 'group::seo.group_about_description',
        'phrase_keywords'    => 'group::seo.group_about_keywords',
        'phrase_heading'     => 'group::seo.group_about_heading',
        'url'                => 'group/settings/{id}/about',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'group.group.browse_joined',
        'phrase_title'       => 'group::seo.group_browse_joined_title',
        'phrase_description' => 'group::seo.group_browse_joined_description',
        'phrase_keywords'    => 'group::seo.group_browse_joined_keywords',
        'phrase_heading'     => 'group::seo.group_browse_joined_heading',
        'url'                => 'group/joined',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'group.group.create',
        'phrase_title'       => 'group::seo.group_create_title',
        'phrase_description' => 'group::seo.group_create_description',
        'phrase_keywords'    => 'group::seo.group_create_keywords',
        'phrase_heading'     => 'group::seo.group_create_heading',
        'url'                => 'group/add',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'group.group.group_rules',
        'phrase_title'       => 'group::seo.group_group_rules_title',
        'phrase_description' => 'group::seo.group_group_rules_description',
        'phrase_keywords'    => 'group::seo.group_group_rules_keywords',
        'phrase_heading'     => 'group::seo.group_group_rules_heading',
        'url'                => 'group/manage/{id}/group_rules',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'group.group.info',
        'phrase_title'       => 'group::seo.group_info_title',
        'phrase_description' => 'group::seo.group_info_description',
        'phrase_keywords'    => 'group::seo.group_info_keywords',
        'phrase_heading'     => 'group::seo.group_info_heading',
        'url'                => 'group/settings/{id}',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'group.group.landing',
        'phrase_title'       => 'group::seo.group_landing_title',
        'phrase_description' => 'group::seo.group_landing_description',
        'phrase_keywords'    => 'group::seo.group_landing_keywords',
        'phrase_heading'     => 'group::seo.group_landing_heading',
        'url'                => 'group',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'group.group.membership_questions',
        'phrase_title'       => 'group::seo.group_membership_questions_title',
        'phrase_description' => 'group::seo.group_membership_questions_description',
        'phrase_keywords'    => 'group::seo.group_membership_questions_keywords',
        'phrase_heading'     => 'group::seo.group_membership_questions_heading',
        'url'                => 'group/manage/{id}/membership_questions',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'group.group.menu',
        'phrase_title'       => 'group::seo.group',
        'phrase_description' => 'group::seo.group_desription',
        'phrase_keywords'    => 'group::seo.group_keywords',
        'phrase_heading'     => 'group::seo.group_heading',
        'url'                => 'group/settings/{id}/menu',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'group.group.moderation_rights',
        'phrase_title'       => 'group::seo.group_moderation_rights_title',
        'phrase_description' => 'group::seo.group_moderation_rights_description',
        'phrase_keywords'    => 'group::seo.group_moderation_rights_keywords',
        'phrase_heading'     => 'group::seo.group_moderation_rights_heading',
        'url'                => 'group/manage/{id}/moderation_rights',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'group.group.my',
        'phrase_title'       => 'group::seo.browse_my_group_title',
        'phrase_description' => 'group::seo.browse_my_group_description',
        'phrase_keywords'    => 'group::seo.browse_my_group_keywords',
        'phrase_heading'     => 'group::seo.browse_my_group_heading',
        'url'                => 'group/my',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'group.group.pending_posts',
        'phrase_title'       => 'group::seo.group_pending_posts_title',
        'phrase_description' => 'group::seo.group_pending_posts_description',
        'phrase_keywords'    => 'group::seo.group_pending_posts_keywords',
        'phrase_heading'     => 'group::seo.group_pending_posts_heading',
        'url'                => 'group/manage/{id}/pending_posts',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'group.group.permissions',
        'phrase_title'       => 'group::seo.group_permissions_title',
        'phrase_description' => 'group::seo.group_permissions_description',
        'phrase_keywords'    => 'group::seo.group_permissions_keywords',
        'phrase_heading'     => 'group::seo.group_permissions_heading',
        'url'                => 'group/settings/{id}/permissions',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'group.group.published',
        'phrase_title'       => 'group::seo.group_your_content_title',
        'phrase_description' => 'group::seo.group_your_content_description',
        'phrase_keywords'    => 'group::seo.group_your_content_keywords',
        'phrase_heading'     => 'group::seo.group_your_content_heading',
        'url'                => 'group/{id}/review_my_content/published',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'group.group.removed',
        'phrase_title'       => 'group::seo.group_your_content_title',
        'phrase_description' => 'group::seo.group_your_content_description',
        'phrase_keywords'    => 'group::seo.group_your_content_keywords',
        'phrase_heading'     => 'group::seo.group_your_content_heading',
        'url'                => 'group/{id}/review_my_content/removed',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'group.group.report',
        'phrase_title'       => 'group::seo.group_report_title',
        'phrase_description' => 'group::seo.group_report_description',
        'phrase_keywords'    => 'group::seo.group_report_keywords',
        'phrase_heading'     => 'group::seo.group_report_heading',
        'url'                => 'group/manage/{id}/report',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'group.profile.about',
        'phrase_title'       => 'group::seo.group_profile_about_title',
        'phrase_description' => 'group::seo.group_profile_about_description',
        'phrase_keywords'    => 'group::seo.group_profile_about_keywords',
        'phrase_heading'     => 'group::seo.group_profile_about_heading',
        'url'                => 'group/{id}/about',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'group.profile.home',
        'phrase_title'       => 'group::seo.group_profile_home_title',
        'phrase_description' => 'group::seo.group_profile_home_description',
        'phrase_keywords'    => 'group::seo.group_profile_home_keywords',
        'phrase_heading'     => 'group::seo.group_profile_home_heading',
        'url'                => 'group/{id}/{tab?}',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'group.profile.media',
        'phrase_title'       => 'group::seo.group_profile_home_title',
        'phrase_description' => 'group::seo.group_profile_home_description',
        'phrase_keywords'    => 'group::seo.group_profile_home_keywords',
        'phrase_heading'     => 'group::seo.group_profile_home_heading',
        'url'                => 'group/{id}/media',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'group.profile.member',
        'phrase_title'       => 'group::seo.group_profile_member_title',
        'phrase_description' => 'group::seo.group_profile_member_description',
        'phrase_keywords'    => 'group::seo.group_profile_member_keywords',
        'phrase_heading'     => 'group::seo.group_profile_member_heading',
        'url'                => 'group/{id}/member',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'group.profile.search',
        'phrase_title'       => 'group::seo.group_search_in_profile',
        'phrase_description' => 'group::seo.group_search_in_profile_description',
        'phrase_keywords'    => 'group::seo.group_search_in_profile_keywords',
        'phrase_heading'     => 'group::seo.group_search_in_profile_heading',
        'url'                => 'group/search/{id}',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'user.profile.group',
        'phrase_title'       => 'group::seo.user_profile_group_title',
        'phrase_description' => 'group::seo.user_profile_group_desription',
        'phrase_keywords'    => 'group::seo.user_profile_group_keywords',
        'phrase_heading'     => 'group::seo.user_profile_group_heading',
        'url'                => 'user/{id}/group',
        'item_type'          => 'user',
    ],
];
