<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Menu\\Http\\Resources\\v1\\Menu\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'menu',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Menu\\Http\\Resources\\v1\\MenuItem\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'menu.menu_item',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Menu\\Http\\Resources\\v1\\MenuItem\\Admin\\AdminSidebarMenuDataGrid',
        'type'       => 'data-grid',
        'name'       => 'menu.admin_sidebar_item',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver' => 'MetaFox\\Menu\\Models\\Menu',
        'type'   => 'entity',
        'name'   => 'menu',
    ],
    [
        'driver' => 'MetaFox\\Menu\\Models\\MenuItem',
        'type'   => 'entity',
        'name'   => 'menuitem',
    ],
    [
        'driver'     => 'MetaFox\\Menu\\Http\\Resources\\v1\\Menu\\Admin\\SearchMenuForm',
        'type'       => 'form',
        'name'       => 'core.menu.search',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Menu\\Http\\Resources\\v1\\Menu\\Admin\\StoreMenuForm',
        'type'       => 'form',
        'name'       => 'core.menu.store',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Menu\\Http\\Resources\\v1\\Menu\\Admin\\UpdateMenuForm',
        'type'       => 'form',
        'name'       => 'core.menu.update',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Menu\\Http\\Resources\\v1\\MenuItem\\Admin\\StoreMenuItemForm',
        'type'       => 'form',
        'name'       => 'core.menuitem.store',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Menu\\Http\\Resources\\v1\\MenuItem\\Admin\\UpdateMenuItemForm',
        'type'       => 'form',
        'name'       => 'core.menuitem.update',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'      => 'MetaFox\\Menu\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'        => 'form-settings',
        'name'        => 'menu',
        'version'     => 'v1',
        'resolution'  => 'admin',
        'title'       => 'menu::phrase.menu_settings',
        'url'         => '/admincp/menu/settings',
        'description' => 'Menu Settings',
    ],
    [
        'driver'  => 'MetaFox\\Menu\\Http\\Resources\\v1\\Menu\\Admin\\MenuItemCollection',
        'type'    => 'json-collection',
        'name'    => 'menu.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Menu\\Http\\Resources\\v1\\MenuItem\\Admin\\MenuItemItemCollection',
        'type'    => 'json-collection',
        'name'    => 'menuitem.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Menu\\Http\\Resources\\v1\\Menu\\Admin\\MenuDetail',
        'type'    => 'json-resource',
        'name'    => 'menu.detail',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Menu\\Http\\Resources\\v1\\Menu\\Admin\\MenuItem',
        'type'    => 'json-resource',
        'name'    => 'menu.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Menu\\Http\\Resources\\v1\\MenuItem\\Admin\\MenuItemDetail',
        'type'    => 'json-resource',
        'name'    => 'menuitem.detail',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Menu\\Http\\Resources\\v1\\MenuItem\\Admin\\MenuItemItem',
        'type'    => 'json-resource',
        'name'    => 'menuitem.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Menu\\Http\\Resources\\v1\\PackageSetting',
        'type'    => 'package-setting',
        'name'    => 'menu',
        'version' => 'v1',
    ],
    [
        'driver'     => 'MetaFox\\Menu\\Http\\Resources\\v1\\Menu\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'menu',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Menu\\Http\\Resources\\v1\\MenuItem\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'menuitem',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
];
