<?php

/**
 * stub: packages/config/config.stub.
 */

return [
    'shareAssets' => [
        'images/403.png'                  => 'image_error_403',
        'images/404.png'                  => 'image_error_404',
        'images/logo.png'                 => 'image_logo',
        'images/logo-dark.png'            => 'image_logo_dark',
        'images/no-results.png'           => 'image_no_results',
        'images/preview.png'              => 'image_preview',
        'images/sign-in-multi-access.png' => 'image_sign_in_multi_access',
        'images/welcome-image.png'        => 'image_welcome',
        'images/transparency_menu.png'    => 'theme-transparent',
        'images/flat.png'                 => 'theme-a0',
        'images/favicon.ico'              => 'site_favicon',
        'images/safari-pinned-tab.svg'    => 'site_mask_icon',
        'images/apple-touch-icon.png'     => 'site_apple_touch_icon',
    ],
    'themes' => [
        [
            'theme_id'      => 'a0',
            'title'         => 'Theme Default',
            'resolution'    => 'web',
            'package_id'    => 'metafox/core',
            'total_variant' => 6,
            'is_system'     => 1,
            'is_active'     => 1,
            'created_at'    => now(),
        ],
        [
            'theme_id'      => 'admincp',
            'title'         => 'Theme AdminCP',
            'resolution'    => 'admin',
            'total_variant' => 1,
            'package_id'    => 'metafox/core',
            'is_system'     => 1,
            'is_active'     => 1,
            'created_at'    => now(),
        ],
    ],
    'styles' => [
        [
            'theme_id'   => 'a0',
            'variant_id' => 'a0',
            'title'      => 'A0',
            'package_id' => 'metafox/core',
            'is_system'  => 1,
            'is_active'  => 1,
            'created_at' => now(),
        ],
        [
            'theme_id'   => 'a0',
            'variant_id' => 'a1',
            'title'      => 'A1',
            'package_id' => 'metafox/core',
            'is_system'  => 1,
            'is_active'  => 1,
            'created_at' => now(),
        ],
        [
            'theme_id'   => 'a0',
            'variant_id' => 'a2',
            'title'      => 'A2',
            'package_id' => 'metafox/core',
            'is_system'  => 1,
            'is_active'  => 1,
            'created_at' => now(),
        ],
        [
            'theme_id'   => 'a0',
            'variant_id' => 'a3',
            'title'      => 'A3',
            'package_id' => 'metafox/core',
            'is_system'  => 1,
            'is_active'  => 1,
            'created_at' => now(),
        ],
        [
            'theme_id'   => 'a0',
            'variant_id' => 'a4',
            'title'      => 'A4',
            'package_id' => 'metafox/core',
            'is_system'  => 1,
            'is_active'  => 1,
            'created_at' => now(),
        ],
        [
            'theme_id'   => 'a0',
            'variant_id' => 'a5',
            'title'      => 'A5',
            'package_id' => 'metafox/core',
            'is_system'  => 1,
            'is_active'  => 1,
            'created_at' => now(),
        ],
        [
            'theme_id'   => 'admincp',
            'variant_id' => 'admincp',
            'title'      => 'Theme AdminCP',
            'package_id' => 'metafox/core',
            'is_system'  => 1,
            'is_active'  => 1,
            'created_at' => now(),
        ],
    ],
];
