<?php

/* this is auto generated file */
return [
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_saved'],
            ['falsy', 'item.is_draft'],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'blog.blog.detailActionMenu',
        'name'     => 'save',
        'label'    => 'blog::phrase.save',
        'ordering' => 11,
        'value'    => 'saveItemDetail',
        'icon'     => 'ico-bookmark-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_saved'],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'blog.blog.detailActionMenu',
        'name'     => 'un-save',
        'label'    => 'blog::phrase.remove_from_saved_list',
        'ordering' => 12,
        'value'    => 'undoSaveItemDetail',
        'icon'     => 'ico-list-del',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_saved'],
            ['falsy', 'item.is_draft'],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'blog.blog.itemActionMenu',
        'name'     => 'save',
        'label'    => 'blog::phrase.save',
        'ordering' => 11,
        'value'    => 'saveItem',
        'icon'     => 'ico-bookmark-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_saved'],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'blog.blog.itemActionMenu',
        'name'     => 'un-save',
        'label'    => 'blog::phrase.remove_from_saved_list',
        'ordering' => 12,
        'value'    => 'undoSaveItem',
        'icon'     => 'ico-list-del',
    ],
    [
        'subInfo'  => 'saved::phrase.see_posts_and_items_you_ve_saved',
        'menu'     => 'core.dropdownMenu',
        'name'     => 'saved',
        'label'    => 'saved::phrase.saved_items',
        'ordering' => 16,
        'icon'     => 'ico-bookmark-o',
        'to'       => '/saved',
    ],
    [
        'subInfo'  => 'saved::phrase.see_posts_and_items_you_ve_saved',
        'menu'     => 'core.primaryMenu',
        'name'     => 'saved',
        'label'    => 'saved::phrase.saved_items',
        'ordering' => 16,
        'icon'     => 'ico-bookmark-o',
        'to'       => '/saved',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_saved'],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'save',
        'label'    => 'event::phrase.save',
        'ordering' => 11,
        'value'    => 'saveItem',
        'icon'     => 'ico-bookmark-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_saved'],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'un-save',
        'label'    => 'event::phrase.remove_from_saved_list',
        'ordering' => 12,
        'value'    => 'undoSaveItem',
        'icon'     => 'ico-list-del',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_save_item'],
            ['falsy', 'item.is_saved'],
            ['eq', 'item.is_pending', 0],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'save',
        'label'    => 'activity::phrase.save_post',
        'ordering' => 17,
        'value'    => 'saveItem',
        'icon'     => 'ico-bookmark-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_saved'],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'un-save',
        'label'    => 'activity::phrase.remove_from_saved_list',
        'ordering' => 18,
        'value'    => 'undoSaveItem',
        'icon'     => 'ico-list-del',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_save_item'],
            ['falsy', 'item.is_saved'],
        ],
        'menu'     => 'feed.feed.itemActionMenuForProfile',
        'name'     => 'save',
        'label'    => 'activity::phrase.save_post',
        'ordering' => 5,
        'value'    => 'saveItem',
        'icon'     => 'ico-bookmark-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_saved'],
        ],
        'menu'     => 'feed.feed.itemActionMenuForProfile',
        'name'     => 'un-save',
        'label'    => 'activity::phrase.remove_from_saved_list',
        'ordering' => 6,
        'value'    => 'undoSaveItem',
        'icon'     => 'ico-list-del',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_save_item'],
            ['falsy', 'item.is_saved'],
        ],
        'menu'     => 'forum.forum_post.detailActionMenu',
        'name'     => 'save',
        'label'    => 'core::phrase.save',
        'ordering' => 4,
        'value'    => 'saveItemDetail',
        'icon'     => 'ico-bookmark-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_save_item'],
            ['truthy', 'item.is_saved'],
        ],
        'menu'     => 'forum.forum_post.detailActionMenu',
        'name'     => 'unsave',
        'label'    => 'forum::phrase.forum_phrase_item_action_remove_from_saved_list',
        'ordering' => 5,
        'value'    => 'undoSaveItemDetail',
        'icon'     => 'ico-list-del',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_save_item'],
            ['falsy', 'item.is_saved'],
        ],
        'menu'     => 'forum.forum_post.itemActionMenu',
        'name'     => 'save',
        'label'    => 'core::phrase.save',
        'ordering' => 4,
        'value'    => 'saveItemDetail',
        'icon'     => 'ico-bookmark-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_save_item'],
            ['truthy', 'item.is_saved'],
        ],
        'menu'     => 'forum.forum_post.itemActionMenu',
        'name'     => 'unsave',
        'label'    => 'forum::phrase.forum_phrase_item_action_remove_from_saved_list',
        'ordering' => 5,
        'value'    => 'undoSaveItemDetail',
        'icon'     => 'ico-list-del',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_save_item'],
            ['falsy', 'item.is_saved'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'save',
        'label'    => 'core::phrase.save',
        'ordering' => 19,
        'value'    => 'saveItemDetail',
        'icon'     => 'ico-bookmark-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_save_item'],
            ['truthy', 'item.is_saved'],
        ],
        'menu'     => 'forum.forum_thread.detailActionMenu',
        'name'     => 'unsave',
        'label'    => 'forum::phrase.forum_phrase_item_action_remove_from_saved_list',
        'ordering' => 20,
        'value'    => 'undoSaveItemDetail',
        'icon'     => 'ico-list-del',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_save_item'],
            ['falsy', 'item.is_saved'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'save',
        'label'    => 'core::phrase.save',
        'ordering' => 19,
        'value'    => 'saveItem',
        'icon'     => 'ico-bookmark-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_save_item'],
            ['truthy', 'item.is_saved'],
        ],
        'menu'     => 'forum.forum_thread.itemActionMenu',
        'name'     => 'unsave',
        'label'    => 'forum::phrase.forum_phrase_item_action_remove_from_saved_list',
        'ordering' => 20,
        'value'    => 'undoSaveItem',
        'icon'     => 'ico-list-del',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_save_item'],
            ['falsy', 'item.is_saved'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'save',
        'label'    => 'page::phrase.save',
        'ordering' => 12,
        'value'    => 'saveItem',
        'icon'     => 'ico-bookmark-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_save_item'],
            ['truthy', 'item.is_saved'],
        ],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'un-save',
        'label'    => 'page::phrase.remove_from_saved_list',
        'ordering' => 13,
        'value'    => 'undoSaveItem',
        'icon'     => 'ico-list-del',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_saved'],
            ['falsy', 'item.is_pending'],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'marketplace.marketplace.detailActionMenu',
        'name'     => 'save',
        'label'    => 'marketplace::phrase.save',
        'ordering' => 13,
        'value'    => 'saveItemDetail',
        'icon'     => 'ico-bookmark-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_saved'],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'marketplace.marketplace.detailActionMenu',
        'name'     => 'un-save',
        'label'    => 'marketplace::phrase.remove_from_saved_list',
        'ordering' => 14,
        'value'    => 'undoSaveItemDetail',
        'icon'     => 'ico-list-del',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_saved'],
            ['falsy', 'item.is_pending'],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'marketplace.marketplace.itemActionMenu',
        'name'     => 'save',
        'label'    => 'marketplace::phrase.save',
        'ordering' => 13,
        'value'    => 'saveItem',
        'icon'     => 'ico-bookmark-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_saved'],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'marketplace.marketplace.itemActionMenu',
        'name'     => 'un-save',
        'label'    => 'marketplace::phrase.remove_from_saved_list',
        'ordering' => 14,
        'value'    => 'undoSaveItem',
        'icon'     => 'ico-list-del',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_saved', 0],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'music.music_album.itemActionMenu',
        'name'     => 'save',
        'label'    => 'music::phrase.save_music_album',
        'ordering' => 14,
        'value'    => 'saveItem',
        'icon'     => 'ico-bookmark-o',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_saved', 0],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'music.music_album.detailActionMenu',
        'name'     => 'save',
        'label'    => 'music::phrase.save_music_album',
        'ordering' => 14,
        'value'    => 'saveItem',
        'icon'     => 'ico-bookmark-o',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_saved', 1],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'music.music_album.itemActionMenu',
        'name'     => 'un-save',
        'label'    => 'music::phrase.remove_from_saved_list',
        'ordering' => 15,
        'value'    => 'undoSaveItem',
        'icon'     => 'ico-list-del',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_saved', 1],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'music.music_album.detailActionMenu',
        'name'     => 'un-save',
        'label'    => 'music::phrase.remove_from_saved_list',
        'ordering' => 15,
        'value'    => 'undoSaveItem',
        'icon'     => 'ico-list-del',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_saved', 0],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'music.music_playlist.itemActionMenu',
        'name'     => 'save',
        'label'    => 'music::phrase.save_music_playlist',
        'ordering' => 14,
        'value'    => 'saveItem',
        'icon'     => 'ico-bookmark-o',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_saved', 0],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'music.music_playlist.detailActionMenu',
        'name'     => 'save',
        'label'    => 'music::phrase.save_music_playlist',
        'ordering' => 14,
        'value'    => 'saveItem',
        'icon'     => 'ico-bookmark-o',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_saved', 1],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'music.music_playlist.itemActionMenu',
        'name'     => 'un-save',
        'label'    => 'music::phrase.remove_from_saved_list',
        'ordering' => 15,
        'value'    => 'undoSaveItem',
        'icon'     => 'ico-list-del',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_saved', 1],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'music.music_playlist.detailActionMenu',
        'name'     => 'un-save',
        'label'    => 'music::phrase.remove_from_saved_list',
        'ordering' => 15,
        'value'    => 'undoSaveItem',
        'icon'     => 'ico-list-del',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_saved', 0],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'save',
        'label'    => 'music::phrase.save_music_song',
        'ordering' => 14,
        'value'    => 'saveItem',
        'icon'     => 'ico-bookmark-o',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_saved', 0],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'save',
        'label'    => 'music::phrase.save_music_song',
        'ordering' => 14,
        'value'    => 'saveItem',
        'icon'     => 'ico-bookmark-o',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_saved', 1],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'un-save',
        'label'    => 'music::phrase.remove_from_saved_list',
        'ordering' => 15,
        'value'    => 'undoSaveItem',
        'icon'     => 'ico-list-del',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_saved', 1],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'un-save',
        'label'    => 'music::phrase.remove_from_saved_list',
        'ordering' => 15,
        'value'    => 'undoSaveItem',
        'icon'     => 'ico-list-del',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_save_item'],
            ['falsy', 'item.is_saved'],
        ],
        'menu'     => 'photo.photo.itemActionMenu',
        'name'     => 'save',
        'label'    => 'photo::phrase.save',
        'ordering' => 5,
        'value'    => 'saveItem',
        'icon'     => 'ico-bookmark-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_saved'],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'photo.photo.itemActionMenu',
        'name'     => 'un-save',
        'label'    => 'photo::phrase.remove_from_saved_list',
        'ordering' => 6,
        'value'    => 'undoSaveItem',
        'icon'     => 'ico-list-del',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_saved', 0],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'photo.photo_album.itemActionMenu',
        'name'     => 'save',
        'label'    => 'photo::phrase.save',
        'ordering' => 9,
        'value'    => 'saveItem',
        'icon'     => 'ico-bookmark-o',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_saved', 1],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'photo.photo_album.itemActionMenu',
        'name'     => 'un-save',
        'label'    => 'photo::phrase.remove_from_saved_list',
        'ordering' => 10,
        'value'    => 'undoSaveItem',
        'icon'     => 'ico-list-del',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_saved', 0],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'poll.poll.itemActionMenu',
        'name'     => 'save',
        'label'    => 'poll::phrase.save',
        'ordering' => 9,
        'value'    => 'saveItemDetail',
        'icon'     => 'ico-bookmark-o',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_saved', 1],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'poll.poll.itemActionMenu',
        'name'     => 'un-save',
        'label'    => 'poll::phrase.remove_from_saved_list',
        'ordering' => 10,
        'value'    => 'undoSaveItemDetail',
        'icon'     => 'ico-list-del',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_saved', 0],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'save',
        'label'    => 'quiz::phrase.save',
        'ordering' => 9,
        'value'    => 'saveItemDetail',
        'icon'     => 'ico-bookmark-o',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_saved', 1],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'un-save',
        'label'    => 'quiz::phrase.remove_from_saved_list',
        'ordering' => 10,
        'value'    => 'undoSaveItemDetail',
        'icon'     => 'ico-list-del',
    ],
    [
        'menu'     => 'saved.saved.addToCollection',
        'name'     => 'add_to_collection',
        'label'    => 'saved::phrase.add_to_collection',
        'ordering' => 1,
        'as'       => 'addToCollection',
        'icon'     => 'ico-add',
    ],
    [
        'showWhen' => [],
        'menu'     => 'saved.saved.itemActionMenu',
        'name'     => 'unsave',
        'label'    => 'saved::phrase.remove_from_saved_list',
        'ordering' => 2,
        'value'    => 'saved/deleteItem',
        'icon'     => 'ico-list-del',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_opened'],
        ],
        'menu'     => 'saved.saved.itemActionMenu',
        'name'     => 'mark_as_opened',
        'label'    => 'saved::phrase.mark_as_opened',
        'ordering' => 3,
        'value'    => 'saved/markAsOpened',
        'icon'     => 'ico-folder-check-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_opened'],
        ],
        'menu'     => 'saved.saved.itemActionMenu',
        'name'     => 'mark_as_un_opened',
        'label'    => 'saved::phrase.mark_as_unopened',
        'ordering' => 4,
        'value'    => 'saved/markAsUnOpened',
        'icon'     => 'ico-folder-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.saved.saved_list.update'],
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'saved.saved_list.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'saved::phrase.edit',
        'ordering' => 2,
        'value'    => 'saved_list/editList',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_add_friend'],
        ],
        'menu'     => 'saved.saved_list.itemActionMenu',
        'name'     => 'add_friend',
        'label'    => 'saved::phrase.add_friends',
        'ordering' => 3,
        'value'    => 'saved_list/addFriend',
        'icon'     => 'ico-plus',
    ],
    [
        'menu'     => 'saved.saved_list.itemActionMenu',
        'name'     => 'view_friend',
        'label'    => 'saved::phrase.view_members_list',
        'ordering' => 4,
        'value'    => 'saved_list/viewFriend',
        'icon'     => 'ico-user2-next-o',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.extra.is_owner'],
        ],
        'menu'     => 'saved.saved_list.itemActionMenu',
        'name'     => 'leave_collection',
        'label'    => 'saved::phrase.leave_collection',
        'ordering' => 5,
        'value'    => 'saved_list/leaveCollection',
        'icon'     => 'ico-signout',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.saved.saved_list.delete'],
            ['truthy', 'item.extra.can_delete'],
        ],
        'menu'     => 'saved.saved_list.itemActionMenu',
        'name'     => 'delete',
        'label'    => 'saved::phrase.delete',
        'ordering' => 6,
        'value'    => 'saved_list/deleteItem',
        'icon'     => 'ico-trash',
    ],
    [
        'tab'       => 'landing',
        'menu'      => 'saved.sidebarMenu',
        'name'      => 'landing',
        'label'     => 'saved::phrase.all_items',
        'ordering'  => 1,
        'icon'      => 'ico-compose-alt',
        'to'        => '/saved',
        'is_active' => 0,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.saved.saved_list.create'],
        ],
        'buttonProps' => [
            'fullWidth' => true,
            'color'     => 'primary',
            'variant'   => 'contained',
        ],
        'asModal'  => true,
        'menu'     => 'saved.sidebarMenu',
        'name'     => 'add',
        'label'    => 'saved::phrase.new_collection',
        'ordering' => 2,
        'as'       => 'sidebarButton',
        'value'    => 'saved/addNewCollection',
        'icon'     => 'ico-plus',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_saved', 0],
            ['falsy', 'item.is_processing'],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'video.video.itemActionMenu',
        'name'     => 'save',
        'label'    => 'video::phrase.save',
        'ordering' => 9,
        'value'    => 'saveItemDetail',
        'icon'     => 'ico-bookmark-o',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_saved', 1],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'video.video.itemActionMenu',
        'name'     => 'un-save',
        'label'    => 'video::phrase.remove_from_saved_list',
        'ordering' => 10,
        'value'    => 'undoSaveItemDetail',
        'icon'     => 'ico-list-del',
    ],
    [
        'showWhen' => [],
        'menu'     => 'saved.saved_list_member.itemActionMenu',
        'name'     => 'remove_member',
        'label'    => 'saved::phrase.remove_member',
        'ordering' => 1,
        'value'    => 'saved_list_member/removeMember',
        'icon'     => 'ico-list-del',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.is_collection_owner'],
            ['truthy', 'item.extra.can_delete'],
        ],
        'menu'     => 'saved.saved.itemActionWithinListMenu',
        'name'     => 'unsave',
        'label'    => 'saved::phrase.remove_from_saved_list',
        'ordering' => 2,
        'value'    => 'saved/deleteItem',
        'icon'     => 'ico-list-del',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_remove'],
        ],
        'menu'     => 'saved.saved.itemActionWithinListMenu',
        'name'     => 'remove_from_collection',
        'label'    => 'saved::phrase.remove_from_collection',
        'ordering' => 3,
        'value'    => 'saved/removeCollectionItem',
        'icon'     => 'ico-list-del',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_opened'],
        ],
        'menu'     => 'saved.saved.itemActionWithinListMenu',
        'name'     => 'mark_as_opened',
        'label'    => 'saved::phrase.mark_as_opened',
        'ordering' => 4,
        'value'    => 'saved/markAsOpened',
        'icon'     => 'ico-folder-check-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_opened'],
        ],
        'menu'     => 'saved.saved.itemActionWithinListMenu',
        'name'     => 'mark_as_un_opened',
        'label'    => 'saved::phrase.mark_as_unopened',
        'ordering' => 5,
        'value'    => 'saved/markAsUnOpened',
        'icon'     => 'ico-folder-o',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_saved'],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'livestreaming.live_video.detailActionMenu',
        'name'     => 'save',
        'label'    => 'livestreaming::phrase.save',
        'ordering' => 14,
        'value'    => 'saveItemDetail',
        'icon'     => 'ico-bookmark-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_saved'],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'livestreaming.live_video.detailActionMenu',
        'name'     => 'un-save',
        'label'    => 'livestreaming::phrase.remove_from_saved_list',
        'ordering' => 15,
        'value'    => 'undoSaveItemDetail',
        'icon'     => 'ico-list-del',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_saved'],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'livestreaming.live_video.itemActionMenu',
        'name'     => 'save',
        'label'    => 'livestreaming::phrase.save',
        'ordering' => 14,
        'value'    => 'saveItem',
        'icon'     => 'ico-bookmark-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_saved'],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'livestreaming.live_video.itemActionMenu',
        'name'     => 'un-save',
        'label'    => 'livestreaming::phrase.remove_from_saved_list',
        'ordering' => 15,
        'value'    => 'undoSaveItem',
        'icon'     => 'ico-list-del',
    ],
];
