<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Comment\\Models\\Comment',
        'type'       => 'entity',
        'name'       => 'comment',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Comment\\Models\\CommentAttachment',
        'type'       => 'entity',
        'name'       => 'comment_attachment',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Comment\\Models\\CommentHide',
        'type'       => 'entity',
        'name'       => 'comment_hide',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Comment\\Models\\CommentHistory',
        'type'       => 'entity',
        'name'       => 'comment_history',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Comment\\Models\\Comment',
        'type'       => 'entity-content',
        'name'       => 'comment',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Comments',
    ],
    [
        'driver'     => 'MetaFox\\Comment\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'       => 'form-settings',
        'name'       => 'comment',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.settings',
        'url'        => '/admincp/comment/setting',
    ],
    [
        'driver'     => 'MetaFox\\Comment\\Jobs\\DeleteCommentByItemJob',
        'type'       => 'job',
        'name'       => 'MetaFox\\Comment\\Jobs\\DeleteCommentByItemJob',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Comment\\Http\\Resources\\v1\\CommentAttachment\\CommentAttachmentEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'comment_attachments.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Comment\\Http\\Resources\\v1\\CommentAttachment\\CommentAttachmentItemCollection',
        'type'       => 'json-collection',
        'name'       => 'comment_attachments.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Comment\\Http\\Resources\\v1\\Comment\\CommentEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'comment.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Comment\\Http\\Resources\\v1\\Comment\\CommentItemCollection',
        'type'       => 'json-collection',
        'name'       => 'comment.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Comment\\Http\\Resources\\v1\\Comment\\CommentItemRelatedCollection',
        'type'       => 'json-collection',
        'name'       => 'comment.item_related',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Comment\\Http\\Resources\\v1\\CommentAttachment\\CommentAttachmentDetail',
        'type'       => 'json-resource',
        'name'       => 'comment_attachments.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Comment\\Http\\Resources\\v1\\CommentAttachment\\CommentAttachmentEmbed',
        'type'       => 'json-resource',
        'name'       => 'comment_attachments.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Comment\\Http\\Resources\\v1\\CommentAttachment\\CommentAttachmentItem',
        'type'       => 'json-resource',
        'name'       => 'comment_attachments.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Comment\\Http\\Resources\\v1\\Comment\\CommentDetail',
        'type'       => 'json-resource',
        'name'       => 'comment.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Comment\\Http\\Resources\\v1\\Comment\\CommentEmbed',
        'type'       => 'json-resource',
        'name'       => 'comment.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Comment\\Http\\Resources\\v1\\Comment\\CommentItem',
        'type'       => 'json-resource',
        'name'       => 'comment.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Comment\\Http\\Resources\\v1\\Comment\\CommentItemRelated',
        'type'       => 'json-resource',
        'name'       => 'comment.item_related',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Comment\\Notifications\\CommentNotification',
        'type'       => 'notification',
        'name'       => 'new_comment',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Comment\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'comment',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Comment\\Policies\\CommentPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Comment\\Models\\Comment',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Comment\\Policies\\Handlers\\CanComment',
        'type'       => 'policy-rule',
        'name'       => 'comment',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Comment\\Http\\Resources\\v1\\Comment\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'comment',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Comment\\Http\\Resources\\v1\\Comment\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'comment',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
];
