<?php

/* this is auto generated file */
return [
    [
        'menu'     => 'core.accountMenu',
        'name'     => 'manage_friends',
        'label'    => 'friend::phrase.manage_friends',
        'ordering' => 3,
        'icon'     => 'ico-user-couple',
        'to'       => '/friend',
    ],
    [
        'subInfo'  => 'friend::phrase.see_your_friends',
        'menu'     => 'core.dropdownMenu',
        'name'     => 'friends',
        'label'    => 'friend::phrase.friends',
        'ordering' => 2,
        'icon'     => 'ico-user1-two',
        'to'       => '/friend',
    ],
    [
        'placement' => 'bottom',
        'content'   => [
            'component' => 'friend_request.ui.friendRequestsPopper',
        ],
        'menu'     => 'core.headerSubMenu',
        'name'     => 'new_friend_request',
        'label'    => 'friend::phrase.friend_requests',
        'ordering' => 2,
        'as'       => 'popover',
        'icon'     => 'ico-user-man-plus-o',
        'to'       => '/friend_request',
    ],
    [
        'menu'     => 'core.primaryMenu',
        'name'     => 'friends',
        'label'    => 'friend::phrase.friends',
        'ordering' => 2,
        'icon'     => 'ico-user1-two',
        'to'       => '/friend',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.friend.friend_list.view'],
        ],
        'menu'     => 'friend.friend_list.itemActionMenu',
        'name'     => 'add',
        'label'    => 'friend::phrase.add_friends',
        'ordering' => 1,
        'value'    => 'friend_list/addFriend',
        'icon'     => 'ico-plus',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.friend.friend_list.update'],
        ],
        'menu'     => 'friend.friend_list.itemActionMenu',
        'name'     => 'edit_list',
        'label'    => 'friend::phrase.edit_friend_list',
        'ordering' => 2,
        'value'    => 'friend_list/editList',
        'icon'     => 'ico-pencil',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.friend.friend_list.delete'],
        ],
        'menu'     => 'friend.friend_list.itemActionMenu',
        'name'     => 'delete',
        'label'    => 'friend::phrase.delete',
        'ordering' => 3,
        'value'    => 'deleteItem',
        'icon'     => 'ico-trash',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.user.user.isLoggedIn'],
        ],
        'tab'      => 'landing',
        'menu'     => 'friend.sidebarMenu',
        'name'     => 'landing',
        'label'    => 'friend::phrase.all_friends',
        'ordering' => 1,
        'icon'     => 'ico-user1-two',
        'to'       => '/friend',
    ],
    [
        'tab'      => 'incoming',
        'showWhen' => [
            'and',
            ['truthy', 'acl.user.user.isLoggedIn'],
        ],
        'menu'     => 'friend.sidebarMenu',
        'name'     => 'incoming_request',
        'label'    => 'friend::phrase.friend_requests',
        'ordering' => 2,
        'icon'     => 'ico-user2-down-o',
        'to'       => '/friend/requests',
    ],
    [
        'tab'      => 'send_request',
        'showWhen' => [
            'and',
            ['truthy', 'acl.user.user.isLoggedIn'],
        ],
        'menu'     => 'friend.sidebarMenu',
        'name'     => 'send_request',
        'label'    => 'friend::phrase.sent_requests',
        'ordering' => 3,
        'icon'     => 'ico-user3-clock-o',
        'to'       => '/friend/send-requests',
    ],
    [
        'buttonProps' => [
            'fullWidth' => true,
            'color'     => 'primary',
            'variant'   => 'contained',
        ],
        'showWhen' => [
            'and',
            ['truthy', 'acl.user.user.isLoggedIn'],
            ['truthy', 'acl.friend.friend_list.create'],
        ],
        'menu'     => 'friend.sidebarMenu',
        'name'     => 'add_new_list',
        'label'    => 'friend::phrase.add_new_list',
        'ordering' => 5,
        'as'       => 'sidebarButton',
        'value'    => 'friend/addNewList',
        'icon'     => 'ico-plus',
    ],
    [
        'tab'      => 'friend',
        'showWhen' => [
            'and',
            ['truthy', 'item.profile_menu_settings.friend_profile_menu'],
            ['truthy', 'item.profile_settings.friend_view_friend'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'friend',
        'label'    => 'friend::phrase.friends',
        'ordering' => 3,
        'to'       => '/friend',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_share'],
        ],
        'menu'     => 'feed.itemShareActionsMenu',
        'name'     => 'share_on_friends',
        'label'    => 'activity::phrase.share_on_friends',
        'ordering' => 3,
        'value'    => 'friend/shareOnFriendProfile',
        'icon'     => 'ico-user1-two',
    ],
];
