<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'user',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\CancelFeedback\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'user.cancelled.feedback',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserRelation\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'user.relation',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserGender\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'user.user_gender',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\UserGender',
        'type'       => 'entity',
        'name'       => 'Gender',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\UserShortcut',
        'type'       => 'entity',
        'name'       => 'shortcut',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\User',
        'type'       => 'entity',
        'name'       => 'user',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Users',
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\UserActivity',
        'type'       => 'entity',
        'name'       => 'user_activity',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\UserBlocked',
        'type'       => 'entity',
        'name'       => 'user_blocked',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\CancelFeedback',
        'type'       => 'entity',
        'name'       => 'user_cancel_feedback',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\CancelReason',
        'type'       => 'entity',
        'name'       => 'user_cancel_reason',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\UserGender',
        'type'       => 'entity',
        'name'       => 'user_gender',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\UserProfile',
        'type'       => 'entity',
        'name'       => 'user_profile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\UserPromotion',
        'type'       => 'entity',
        'name'       => 'user_promotion',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\UserRelation',
        'type'       => 'entity',
        'name'       => 'user_relation',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\UserRelationData',
        'type'       => 'entity',
        'name'       => 'user_relation_data',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\UserValue',
        'type'       => 'entity',
        'name'       => 'user_value',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\UserVerify',
        'type'       => 'entity',
        'name'       => 'user_verify',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\UserVerifyError',
        'type'       => 'entity',
        'name'       => 'user_verify_error',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\User',
        'type'       => 'entity-content',
        'name'       => 'user',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Users',
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\User',
        'type'       => 'entity-user',
        'name'       => 'user',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\AccountCancelForm',
        'type'       => 'form',
        'name'       => 'user.account.cancel',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\AccountCancelMobileForm',
        'type'       => 'form',
        'name'       => 'user.account.cancel',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditCurrencyForm',
        'type'       => 'form',
        'name'       => 'user.account.edit_currency',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditEmailAddressForm',
        'type'       => 'form',
        'name'       => 'user.account.edit_email_address',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditLanguageForm',
        'type'       => 'form',
        'name'       => 'user.account.edit_language',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditNameForm',
        'type'       => 'form',
        'name'       => 'user.account.edit_name',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditPasswordForm',
        'type'       => 'form',
        'name'       => 'user.account.edit_password',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditPaymentForm',
        'type'       => 'form',
        'name'       => 'user.account.edit_payment',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditPhoneNumberForm',
        'type'       => 'form',
        'name'       => 'user.account.edit_phone_number',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditTimezoneForm',
        'type'       => 'form',
        'name'       => 'user.account.edit_timezone',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditUserNameForm',
        'type'       => 'form',
        'name'       => 'user.account.edit_user_name',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\AccountSettingMobileForm',
        'type'       => 'form',
        'name'       => 'user.account.info',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditLanguageMobileForm',
        'type'       => 'form',
        'name'       => 'user.account.language',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditPasswordMobileForm',
        'type'       => 'form',
        'name'       => 'user.account.password',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditReviewTagPostMobileForm',
        'type'       => 'form',
        'name'       => 'user.account.review_tag',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\Forms\\AccountSettingForm',
        'type'       => 'form',
        'name'       => 'user.account_setting',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\AccountPopupForm',
        'type'       => 'form',
        'name'       => 'user.add_account_popup',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\Admin\\BanUserForm',
        'type'       => 'form',
        'name'       => 'user.ban',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\Admin\\BatchMoveRoleForm',
        'type'       => 'form',
        'name'       => 'user.batch_move_role',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\Admin\\DenyUserForm',
        'type'       => 'form',
        'name'       => 'user.deny_user',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserPassword\\PasswordRequestMobileForm',
        'type'       => 'form',
        'name'       => 'user.forgot_password',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserPassword\\PasswordRequestForm',
        'type'       => 'form',
        'name'       => 'user.forgot_password',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserLoginForm',
        'type'       => 'form',
        'name'       => 'user.login',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\Admin\\UserLoginForm',
        'type'       => 'form',
        'name'       => 'user.login',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserLoginMobileForm',
        'type'       => 'form',
        'name'       => 'user.login',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\LoginPopupUserForm',
        'type'       => 'form',
        'name'       => 'user.login_popup',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserPassword\\UpdatePasswordForm',
        'type'       => 'form',
        'name'       => 'user.password.edit',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserPassword\\UpdatePasswordMobileForm',
        'type'       => 'form',
        'name'       => 'user.password.edit',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserPassword\\RequestMethodMobileForm',
        'type'       => 'form',
        'name'       => 'user.password.request_method',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserPassword\\RequestMethodForm',
        'type'       => 'form',
        'name'       => 'user.password.request_method',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserPassword\\VerifyRequestMobileForm',
        'type'       => 'form',
        'name'       => 'user.password.verify_request',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserPassword\\VerifyRequestForm',
        'type'       => 'form',
        'name'       => 'user.password.verify_request',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserProfileForm',
        'type'       => 'form',
        'name'       => 'user.profile',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserProfileMobileForm',
        'type'       => 'form',
        'name'       => 'user.profile',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserRegisterMobileForm',
        'type'       => 'form',
        'name'       => 'user.register',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserRegisterForm',
        'type'       => 'form',
        'name'       => 'user.register',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\SearchUserMobileForm',
        'type'       => 'form',
        'name'       => 'user.search',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\SearchUserForm',
        'type'       => 'form',
        'name'       => 'user.search',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\SmallUserLoginForm',
        'type'       => 'form',
        'name'       => 'user.small_login',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\Admin\\AccountSettingForm',
        'type'       => 'form',
        'name'       => 'user.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\CancelReason\\Admin\\CreateForm',
        'type'       => 'form',
        'name'       => 'user.user_cancel_reason.store',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\CancelReason\\Admin\\EditForm',
        'type'       => 'form',
        'name'       => 'user.user_cancel_reason.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserGender\\Admin\\SearchUserGenderForm',
        'type'       => 'form',
        'name'       => 'user.user_gender.search',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserGender\\Admin\\StoreUserGenderForm',
        'type'       => 'form',
        'name'       => 'user.user_gender.store',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserGender\\Admin\\UpdateUserGenderForm',
        'type'       => 'form',
        'name'       => 'user.user_gender.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserPromotion\\Admin\\CreateForm',
        'type'       => 'form',
        'name'       => 'user.user_promotion.store',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserPromotion\\Admin\\EditForm',
        'type'       => 'form',
        'name'       => 'user.user_promotion.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserRelation\\Admin\\CreateForm',
        'type'       => 'form',
        'name'       => 'user.user_relation.store',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserRelation\\Admin\\EditForm',
        'type'       => 'form',
        'name'       => 'user.user_relation.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserVerify\\ResendForm',
        'type'       => 'form',
        'name'       => 'user_verify.resend',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\User\\Form\\Mobile\\AvatarUploadField',
        'type'       => 'form-field',
        'name'       => 'avatarUpload',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Form\\Html\\AvatarUploadField',
        'type'       => 'form-field',
        'name'       => 'avatarUpload',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Admin\\UserSettingForm',
        'type'       => 'form-settings',
        'name'       => 'user',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'user::phrase.user_settings',
        'url'        => '/admincp/user/setting',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Admin\\UserRegistrationSettingForm',
        'type'       => 'form-settings',
        'name'       => 'user.registration',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'user::phrase.registration_settings',
        'url'        => '/admincp/user/setting/registration',
    ],
    [
        'driver'     => 'MetaFox\\User\\Jobs\\ExpiredUserBanJob',
        'type'       => 'job',
        'name'       => 'MetaFox\\User\\Jobs\\ExpiredUserBanJob',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserShortcut\\UserShortcutItemCollection',
        'type'       => 'json-collection',
        'name'       => 'shortcut.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserBlocked\\UserBlockedEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'user_blocked.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserBlocked\\UserBlockedItemCollection',
        'type'       => 'json-collection',
        'name'       => 'user_blocked.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\CancelFeedback\\Admin\\CancelFeedbackItemCollection',
        'type'       => 'json-collection',
        'name'       => 'user_cancel_feedback.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\CancelReason\\Admin\\CancelReasonItemCollection',
        'type'       => 'json-collection',
        'name'       => 'user_cancel_reason.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'user.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserEntity\\UserEntityCollection',
        'type'       => 'json-collection',
        'name'       => 'user_entity.',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserEntity\\UserEntityItemCollection',
        'type'       => 'json-collection',
        'name'       => 'user_entity.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserGender\\Admin\\UserGenderItemCollection',
        'type'       => 'json-collection',
        'name'       => 'user_gender.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\Admin\\UserItemCollection',
        'type'       => 'json-collection',
        'name'       => 'user.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserPreviewCollection',
        'type'       => 'json-collection',
        'name'       => 'user.preview',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserPromotion\\Admin\\UserPromotionItemCollection',
        'type'       => 'json-collection',
        'name'       => 'user_promotion.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserRelation\\Admin\\UserRelationItemCollection',
        'type'       => 'json-collection',
        'name'       => 'user_relation.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\AccountSetting',
        'type'       => 'json-resource',
        'name'       => 'account.setting',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserShortcut\\UserShortcutDetail',
        'type'       => 'json-resource',
        'name'       => 'shortcut.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserShortcut\\UserShortcutItem',
        'type'       => 'json-resource',
        'name'       => 'shortcut.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserAccount',
        'type'       => 'json-resource',
        'name'       => 'user.account',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserActivity',
        'type'       => 'json-resource',
        'name'       => 'user.activity',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserActivityItem',
        'type'       => 'json-resource',
        'name'       => 'user.activity_item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserBlocked\\UserBlockedDetail',
        'type'       => 'json-resource',
        'name'       => 'user_blocked.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserBlocked\\UserBlockedEmbed',
        'type'       => 'json-resource',
        'name'       => 'user_blocked.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserBlocked\\UserBlockedItem',
        'type'       => 'json-resource',
        'name'       => 'user_blocked.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\CancelFeedback\\Admin\\CancelFeedbackDetail',
        'type'       => 'json-resource',
        'name'       => 'user_cancel_feedback.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\CancelFeedback\\Admin\\CancelFeedbackItem',
        'type'       => 'json-resource',
        'name'       => 'user_cancel_feedback.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\CancelReason\\Admin\\CancelReasonDetail',
        'type'       => 'json-resource',
        'name'       => 'user_cancel_reason.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\CancelReason\\Admin\\CancelReasonItem',
        'type'       => 'json-resource',
        'name'       => 'user_cancel_reason.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserDetail',
        'type'       => 'json-resource',
        'name'       => 'user.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserEmbed',
        'type'       => 'json-resource',
        'name'       => 'user.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserEntity\\UserEntityDetail',
        'type'       => 'json-resource',
        'name'       => 'user_entity.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserEntity\\UserEntityItem',
        'type'       => 'json-resource',
        'name'       => 'user_entity.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserEntity\\UserEntityPreview',
        'type'       => 'json-resource',
        'name'       => 'user_entity.preview',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserGender\\Admin\\UserGenderItem',
        'type'       => 'json-resource',
        'name'       => 'user_gender.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserInfo',
        'type'       => 'json-resource',
        'name'       => 'user.info',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserItem',
        'type'       => 'json-resource',
        'name'       => 'user.item',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserMe',
        'type'       => 'json-resource',
        'name'       => 'user.me',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserPreview',
        'type'       => 'json-resource',
        'name'       => 'user.preview',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserProfile\\UserProfileEmbed',
        'type'       => 'json-resource',
        'name'       => 'user_profile.embed',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserPromotion\\Admin\\UserPromotionDetail',
        'type'       => 'json-resource',
        'name'       => 'user_promotion.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserPromotion\\Admin\\UserPromotionItem',
        'type'       => 'json-resource',
        'name'       => 'user_promotion.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserRelation\\Admin\\UserRelationDetail',
        'type'       => 'json-resource',
        'name'       => 'user_relation.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserRelation\\Admin\\UserRelationItem',
        'type'       => 'json-resource',
        'name'       => 'user_relation.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserSimple',
        'type'       => 'json-resource',
        'name'       => 'user.simple',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Notifications\\ResetPasswordTokenNotification',
        'type'       => 'notification',
        'name'       => 'new_password_requested',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Notifications\\DirectUpdatedPassword',
        'type'       => 'notification',
        'name'       => 'new_password_updated',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Notifications\\NewPostTimeline',
        'type'       => 'notification',
        'name'       => 'new_post_timeline',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Notifications\\ProfileUpdatedByAdmin',
        'type'       => 'notification',
        'name'       => 'profile_updated_by_admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'user',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Policies\\UserPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\User\\Models\\User',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Policies\\UserProfilePolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\User\\Models\\UserProfile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Policies\\UserShortcutPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\User\\Models\\UserShortcut',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'user',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Mobile Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserShortcut\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'shortcut',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'user',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserBlocked\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'user_blocked',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserVerify\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'user_verify',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
];
