<?php

/* this is auto generated file */
return [
    [
        'name'         => 'admin.user.browse_cancellation',
        'phrase_title' => 'user::phrase.browse_cancellation_title',
    ],
    [
        'name'         => 'admin.user.browse_inactive_reminder',
        'phrase_title' => 'user::phrase.browse_inactive-reminder_title',
    ],
    [
        'name'         => 'admin.user.browse_relationship',
        'phrase_title' => 'user::phrase.browse_relationship_title',
    ],
    [
        'name'         => 'admin.user.browse_search_ip',
        'phrase_title' => 'user::phrase.browse_search-ip_title',
    ],
    [
        'name'         => 'admin.user.browse_user',
        'phrase_title' => 'user::admin.manage_members',
        'url'          => 'admincp/user/user/browse',
    ],
    [
        'name'         => 'admin.user.browse_user_gender',
        'phrase_title' => 'user::phrase.manage_genders',
        'url'          => 'admincp/user/user-gender/browse',
    ],
    [
        'name'         => 'admin.user.create_user_gender',
        'phrase_title' => 'user::phrase.add_new_gender',
        'url'          => 'admincp/user/user-gender/create',
    ],
    [
        'name'                 => 'admin.user.edit_user',
        'phrase_title'         => 'user::seo.edit_user_title',
        'url'                  => 'admincp/user/user/edit/{id}',
        'item_type'            => 'user',
        'custom_sharing_route' => 1,
    ],
    [
        'name'         => 'admin.user.permissions',
        'phrase_title' => 'core::phrase.permissions',
        'url'          => 'admincp/user/permission',
    ],
    [
        'name'         => 'admin.user.registration_setting',
        'phrase_title' => 'user::phrase.registration_settings',
        'url'          => 'admincp/user/setting/registration',
    ],
    [
        'name'         => 'admin.user.user_setting',
        'phrase_title' => 'user::phrase.user_settings',
        'url'          => 'admincp/user/setting',
    ],
    [
        'name'         => 'admin.user.browse_relation',
        'phrase_title' => 'user::phrase.user_relations',
        'url'          => 'admincp/user/relation/browse',
    ],
    [
        'name'         => 'admin.user.create_relation',
        'phrase_title' => 'user::phrase.add_new_relation',
        'url'          => 'admincp/user/relation/create',
    ],
    [
        'name'         => 'admin.user.edit_relation',
        'phrase_title' => 'user::phrase.edit_relation',
        'url'          => 'admincp/user/relation/edit/{id}',
    ],
    [
        'name'               => 'user.browse_all_user',
        'phrase_title'       => 'user::seo.browse_all_user_title',
        'phrase_description' => 'user::seo.browse_all_user_description',
        'phrase_keywords'    => 'user::seo.browse_all_user_keywords',
        'phrase_heading'     => 'user::seo.browse_all_user_heading',
        'url'                => 'user/all',
        'item_type'          => 'user',
    ],
    [
        'name'               => 'user.browse_featured_user',
        'phrase_title'       => 'user::seo.browse_featured_title',
        'phrase_description' => 'user::seo.browse_featured_description',
        'phrase_keywords'    => 'user::seo.browse_featured_keywords',
        'phrase_heading'     => 'user::seo.browse_featured_heading',
        'url'                => 'user/featured',
        'item_type'          => 'user',
    ],
    [
        'name'               => 'user.browse_recent_user',
        'phrase_title'       => 'user::seo.browse_recent_title',
        'phrase_description' => 'user::seo.browse_recent_description',
        'phrase_keywords'    => 'user::seo.browse_recent_keywords',
        'phrase_heading'     => 'user::seo.browse_recent_heading',
        'url'                => 'user/recent',
        'item_type'          => 'user',
    ],
    [
        'name'               => 'user.browse_recommend_user',
        'phrase_title'       => 'user::seo.browse_recommend_title',
        'phrase_description' => 'user::seo.browse_recommend_description',
        'phrase_keywords'    => 'user::seo.browse_recommend_keywords',
        'phrase_heading'     => 'user::seo.browse_recommend_heading',
        'url'                => 'user/recommend',
        'item_type'          => 'user',
    ],
    [
        'name'               => 'user.profile.about',
        'phrase_title'       => 'user::seo.user_profile_about_title',
        'phrase_description' => 'user::seo.user_profile_blog_description',
        'phrase_keywords'    => 'user::seo.user_profile_about_keywords',
        'phrase_heading'     => 'user::seo.user_profile_about_heading',
        'url'                => 'user/{id}/about',
        'item_type'          => 'user',
    ],
    [
        'name'               => 'user.profile.friend',
        'phrase_title'       => 'user::seo.user_profile_friend_title',
        'phrase_description' => 'user::seo.user_profile_friend_desription',
        'phrase_keywords'    => 'user::seo.user_profile_friend_keywords',
        'phrase_heading'     => 'user::seo.user_profile_friend_heading',
        'url'                => 'user/{id}/friend',
        'item_type'          => 'user',
    ],
    [
        'name'               => 'user.profile.home',
        'phrase_title'       => 'user::seo.user_profile_home_title',
        'phrase_description' => 'user::seo.user_profile_home_description',
        'phrase_keywords'    => 'user::seo.user_profile_home_keywords',
        'phrase_heading'     => 'user::seo.user_profile_home_heading',
        'url'                => 'user/{id}',
        'item_type'          => 'user',
    ],
    [
        'name'               => 'user.settings.blocked',
        'phrase_title'       => 'user::seo.browse_user_blocked_title',
        'phrase_description' => 'user::seo.browse_user_blocked_description',
        'phrase_keywords'    => 'user::seo.browse_user_blocked_keywords',
        'phrase_heading'     => 'user::seo.browse_user_blocked_heading',
        'url'                => 'settings/blocked',
    ],
    [
        'name'               => 'user.settings.email_notifications',
        'phrase_title'       => 'user::seo.browse_user_email_notifications_title',
        'phrase_description' => 'user::seo.browse_user_email_notifications_description',
        'phrase_keywords'    => 'user::seo.browse_user_email_notifications_keywords',
        'phrase_heading'     => 'user::seo.browse_user_email_notifications_heading',
        'url'                => 'settings/email-notifications',
    ],
    [
        'name'               => 'user.settings.general',
        'phrase_title'       => 'user::seo.browse_user_account_settings_title',
        'phrase_description' => 'user::seo.browse_user_account_settings_description',
        'phrase_keywords'    => 'user::seo.browse_user_account_settings_keywords',
        'phrase_heading'     => 'user::seo.browse_user_account_settings_heading',
        'url'                => 'settings',
    ],
    [
        'name'               => 'user.settings.invisible',
        'phrase_title'       => 'user::seo.browse_user_invisible_mode_title',
        'phrase_description' => 'user::seo.browse_user_invisible_mode_description',
        'phrase_keywords'    => 'user::seo.browse_user_invisible_mode_keywords',
        'phrase_heading'     => 'user::seo.browse_user_invisible_mode_heading',
        'url'                => 'settings/invisible',
    ],
    [
        'name'               => 'user.settings.items',
        'phrase_title'       => 'user::seo.browse_user_items_title',
        'phrase_description' => 'user::seo.browse_user_items_description',
        'phrase_keywords'    => 'user::seo.browse_user_items_keywords',
        'phrase_heading'     => 'user::seo.browse_user_items_heading',
        'url'                => 'settings/items',
    ],
    [
        'name'               => 'user.settings.notifications',
        'phrase_title'       => 'user::seo.browse_user_notifications_title',
        'phrase_description' => 'user::seo.browse_user_notifications_description',
        'phrase_keywords'    => 'user::seo.browse_user_notifications_keywords',
        'phrase_heading'     => 'user::seo.browse_user_notifications_heading',
        'url'                => 'user/settings/notifications',
    ],
    [
        'name'               => 'user.settings.payment',
        'phrase_title'       => 'user::seo.settings',
        'phrase_description' => 'user::seo.settings_desription',
        'phrase_keywords'    => 'user::seo.settings_keywords',
        'phrase_heading'     => 'user::seo.settings_heading',
        'url'                => 'settings/payment',
    ],
    [
        'name'               => 'user.settings.profile',
        'phrase_title'       => 'user::seo.browse_user_your_profile_title',
        'phrase_description' => 'user::seo.browse_user_your_profile_description',
        'phrase_keywords'    => 'user::seo.browse_user_your_profile_keywords',
        'phrase_heading'     => 'user::seo.browse_user_your_profile_heading',
        'url'                => 'settings/profile',
    ],
    [
        'name'               => 'user.settings.profile_menu',
        'phrase_title'       => 'user::seo.browse_user_profile_menu_settings_title',
        'phrase_description' => 'user::seo.browse_user_profile_menu_settings_description',
        'phrase_keywords'    => 'user::seo.browse_user_profile_menu_settings_keywords',
        'phrase_heading'     => 'user::seo.browse_user_profile_menu_settings_heading',
        'url'                => 'settings/profile-menu',
    ],
    [
        'name'               => 'user.settings.review',
        'phrase_title'       => 'user::seo.browse_user_review_post_title',
        'phrase_description' => 'user::seo.browse_user_review_post_description',
        'phrase_keywords'    => 'user::seo.browse_user_review_post_keywords',
        'phrase_heading'     => 'user::seo.browse_user_review_post_heading',
        'url'                => 'settings/review',
    ],
    [
        'name'               => 'user.user',
        'phrase_title'       => 'core::seo.core_search_title',
        'phrase_description' => 'core::seo.core_search_description',
        'phrase_keywords'    => 'core::seo.core_search_keywords',
        'phrase_heading'     => 'core::seo.core_search_heading',
        'url'                => 'user/search',
    ],
    [
        'name'         => 'user.user.cancel_account',
        'phrase_title' => 'user::seo.user_cancel_account_title',
    ],
    [
        'name'               => 'user.user.edit',
        'phrase_title'       => 'user::seo.user_edit_title',
        'phrase_description' => 'user::seo.user_edit_description',
        'phrase_keywords'    => 'user::seo.user_edit_keywords',
        'phrase_heading'     => 'user::seo.user_edit_heading',
        'url'                => 'user/{id}/profile',
        'item_type'          => 'user',
    ],
    [
        'name'               => 'user.user.forgot_password',
        'phrase_title'       => 'user::seo.user_forgot_password_title',
        'phrase_description' => 'user::seo.user_forgot_password_description',
        'phrase_keywords'    => 'user::seo.user_forgot_password_keywords',
        'phrase_heading'     => 'user::seo.user_forgot_password_heading',
        'url'                => 'user/forgot-password',
    ],
    [
        'name'               => 'user.user.forgot_password.request',
        'phrase_title'       => 'user::seo.user_forgot_password_title',
        'phrase_description' => 'user::seo.user_forgot_password_description',
        'phrase_keywords'    => 'user::seo.user_forgot_password_keywords',
        'phrase_heading'     => 'user::seo.user_forgot_password_heading',
        'url'                => 'user/password/request',
    ],
    [
        'name'               => 'user.user.landing',
        'phrase_title'       => 'user::seo.user_landing_title',
        'phrase_description' => 'user::seo.user_landing_description',
        'phrase_keywords'    => 'user::seo.user_landing_keywords',
        'phrase_heading'     => 'user::seo.user_landing_heading',
        'url'                => 'user',
    ],
    [
        'name'               => 'user.user.login',
        'phrase_title'       => 'user::seo.user_login_title',
        'phrase_description' => 'user::seo.user_login_description',
        'phrase_keywords'    => 'user::seo.user_login_keywords',
        'phrase_heading'     => 'user::seo.user_login_heading',
        'url'                => 'login',
    ],
    [
        'name'               => 'user.user.register',
        'phrase_title'       => 'user::seo.user_register_title',
        'phrase_description' => 'user::seo.user_register_description',
        'phrase_keywords'    => 'user::seo.user_register_keywords',
        'phrase_heading'     => 'user::seo.user_register_heading',
        'url'                => 'register',
    ],
    [
        'name'               => 'user.user.verify_email',
        'phrase_title'       => 'user::seo.user_verify_email_title',
        'phrase_description' => 'user::seo.user_verify_email_description',
        'phrase_keywords'    => 'user::seo.user_verify_email_keywords',
        'phrase_heading'     => 'user::seo.user_verify_email_heading',
        'url'                => 'user/verify-email/{hash}',
    ],
    [
        'name'         => 'admin.user.browse_cancelled_members',
        'phrase_title' => 'user::phrase.cancelled_members',
        'url'          => 'admincp/user/cancelled/browse/feedback',
    ],
];
