<?php

namespace MetaFox\Form\Mobile;

// stub: /phpstorm/mobile_fields.meta.stub

use Illuminate\Support\Facades\Facade;

/**
 * Class Builder.
 *
 * @method static \MetaFox\Photo\Form\Mobile\AlbumField                      album(?string $name=null)
 * @method static \MetaFox\Form\Mobile\Attachment                            attachment(?string $name=null)
 * @method static \MetaFox\Form\Mobile\Autocomplete                          autocomplete(?string $name=null)
 * @method static \MetaFox\User\Form\Mobile\AvatarUploadField                avatarUpload(?string $name=null)
 * @method static \MetaFox\Form\Mobile\BirthdayField                         birthday(?string $name=null)
 * @method static \MetaFox\Form\Mobile\Button                                button(?string $name=null)
 * @method static \MetaFox\Form\Mobile\CategoryField                         category(?string $name=null)
 * @method static \MetaFox\Form\Mobile\CheckboxField                         checkbox(?string $name=null)
 * @method static \MetaFox\Form\Mobile\CheckboxGroupField                    checkboxGroup(?string $name=null)
 * @method static \MetaFox\Form\Mobile\ChipField                             chip(?string $name=null)
 * @method static \MetaFox\Form\Mobile\ChoiceField                           choice(?string $name=null)
 * @method static \MetaFox\Form\Mobile\ClearSearch                           clearSearch(?string $name=null)
 * @method static \MetaFox\Form\Mobile\Clickable                             clickable(?string $name=null)
 * @method static \MetaFox\Localize\Form\Mobile\CountryCityCode              countryCity(?string $name=null)
 * @method static \MetaFox\Form\Mobile\CountryState                          countryState(?string $name=null)
 * @method static \MetaFox\Localize\Form\Mobile\CountryStatePicker           countryStatePicker(?string $name=null)
 * @method static \MetaFox\Form\Mobile\CustomGendersField                    customGenders(?string $name=null)
 * @method static \MetaFox\Form\Mobile\DateField                             date(?string $name=null)
 * @method static \MetaFox\Form\Mobile\DateTimeField                         dateTime(?string $name=null)
 * @method static \MetaFox\Form\Mobile\EmailField                            email(?string $name=null)
 * @method static \MetaFox\Form\Mobile\FieldPickerField                      fieldPicker(?string $name=null)
 * @method static \MetaFox\Form\Mobile\FileField                             file(?string $name=null)
 * @method static \MetaFox\Form\Mobile\FriendPickerField                     friendPicker(?string $name=null)
 * @method static \MetaFox\Form\Mobile\HiddenField                           hidden(?string $name=null)
 * @method static \MetaFox\Captcha\Form\Mobile\ImageCaptchaField             imageCaptcha(?string $name=null)
 * @method static \MetaFox\Form\Mobile\InformationField                      information(?string $name=null)
 * @method static \MetaFox\Form\Mobile\InputField                            input(?string $name=null)
 * @method static \MetaFox\Form\Mobile\IntegerField                          integer(?string $name=null)
 * @method static \MetaFox\Form\Mobile\LinkButtonField                       linkButton(?string $name=null)
 * @method static \MetaFox\Form\Mobile\LocationField                         location(?string $name=null)
 * @method static \MetaFox\Form\Mobile\AppleLoginButtonField                 appleLoginButton(?string $name=null)
 * @method static \MetaFox\Form\Mobile\FacebookLoginButtonField              facebookLoginButton(?string $name=null)
 * @method static \MetaFox\Form\Mobile\GoogleLoginButtonField                googleLoginButton(?string $name=null)
 * @method static \MetaFox\Form\Mobile\MembershipField                       membership(?string $name=null)
 * @method static \MetaFox\Group\Support\Form\Mobile\MembershipQuestionField membershipQuestion(?string $name=null)
 * @method static \MetaFox\Form\Mobile\MentionInputField                     mentionInput(?string $name=null)
 * @method static \MetaFox\Form\Mobile\MultiFileField                        multiFile(?string $name=null)
 * @method static \MetaFox\Form\Mobile\NumberField                           number(?string $name=null)
 * @method static \MetaFox\Form\Mobile\NumberCode                            numberCode(?string $name=null)
 * @method static \MetaFox\Form\Mobile\PasswordField                         password(?string $name=null)
 * @method static \MetaFox\Form\Mobile\PhoneNumberField                      phoneNumber(?string $name=null)
 * @method static \MetaFox\Form\Mobile\PointPackageField                     pointPackage(?string $name=null)
 * @method static \MetaFox\Poll\Form\Mobile\PollAnswerField                  pollAnswer(?string $name=null)
 * @method static \MetaFox\Poll\Form\Mobile\PollCloseTimeField               pollCloseTime(?string $name=null)
 * @method static \MetaFox\Form\Mobile\PriceField                            price(?string $name=null)
 * @method static \MetaFox\Form\Mobile\PrivacyField                          privacy(?string $name=null)
 * @method static \MetaFox\Form\Mobile\QuizQuestionField                     quizQuestion(?string $name=null)
 * @method static \MetaFox\Form\Mobile\RadioField                            radio(?string $name=null)
 * @method static \MetaFox\Form\Mobile\RadioGroupField                       radioGroup(?string $name=null)
 * @method static \MetaFox\Form\Mobile\RadioLabelGroupField                  radioLabelGroup(?string $name=null)
 * @method static \MetaFox\Form\Mobile\RangeSliderField                      rangeSlider(?string $name=null)
 * @method static \MetaFox\Captcha\Form\Mobile\RecaptchaV3Field              recaptchaV3(?string $name=null)
 * @method static \MetaFox\Form\Mobile\RegisterButtonField                   registerButton(?string $name=null)
 * @method static \MetaFox\Form\Mobile\RelationshipPickerField               relationshipPicker(?string $name=null)
 * @method static \MetaFox\Form\Mobile\RichTextEditor                        richTextEditor(?string $name=null)
 * @method static \MetaFox\Form\Mobile\Row                                   row(?string $name=null)
 * @method static \MetaFox\Form\Section                                      section(?string $name=null)
 * @method static \MetaFox\Form\Mobile\SimpleFriendPickerField               simpleFriendPicker(?string $name=null)
 * @method static \MetaFox\Form\Mobile\SinglePhotoField                      singlePhoto(?string $name=null)
 * @method static \MetaFox\Video\Form\Mobile\SingleVideoField                singleVideo(?string $name=null)
 * @method static \MetaFox\Form\Mobile\SingleAudioField                      singleAudio(?string $name=null)
 * @method static \MetaFox\Form\Mobile\SliderField                           slider(?string $name=null)
 * @method static \MetaFox\Form\Mobile\SpamQuestionField                     spamQuestion(?string $name=null)
 * @method static \MetaFox\Form\Mobile\SubFormField                          subForm(?string $name=null)
 * @method static \MetaFox\Form\Mobile\SubmitButton                          submit(?string $name=null)
 * @method static \MetaFox\Form\Mobile\SubmitButton                          submitButton(?string $name=null)
 * @method static \MetaFox\Form\Mobile\SwitchField                           switch(?string $name=null)
 * @method static \MetaFox\Form\Mobile\TabListField                          tabList(?string $name=null)
 * @method static \MetaFox\Form\Mobile\TagsField                             tags(?string $name=null)
 * @method static \MetaFox\Form\Mobile\TextField                             text(?string $name=null)
 * @method static \MetaFox\Form\Mobile\TextAreaField                         textArea(?string $name=null)
 * @method static \MetaFox\Form\Mobile\ComposerInput                         composerInput(?string $name=null)
 * @method static \MetaFox\Form\Mobile\TimePickerField                       timePicker(?string $name=null)
 * @method static \MetaFox\Form\Mobile\TypeCategoryField                     typeCategory(?string $name=null)
 * @method static \MetaFox\Form\Mobile\Typography                            typography(?string $name=null)
 * @method static \MetaFox\Form\Mobile\UrlField                              url(?string $name=null)
 * @method static \MetaFox\Form\Mobile\VideoUploadField                      videoUpload(?string $name=null)
 * @method static \MetaFox\Form\Mobile\AuthenticatorQrCode                   authenticatorQrCode(?string $name=null)
 * @method static array                                                      getFields()
 * @method static string                                                     getCreator(string $name)
 */
class Builder extends Facade
{
    protected static function getFacadeAccessor()
    {
        return 'MobileFormBuilder';
    }
}
