<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\Forum\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'forum',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Models\\Forum',
        'type'       => 'entity',
        'name'       => 'forum',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Forums',
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Models\\ForumPost',
        'type'       => 'entity',
        'name'       => 'forum_post',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Forum Posts',
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Models\\ForumPostText',
        'type'       => 'entity',
        'name'       => 'forum_post_text',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Models\\ForumThread',
        'type'       => 'entity',
        'name'       => 'forum_thread',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Forum Threads',
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Models\\ForumThreadLastRead',
        'type'       => 'entity',
        'name'       => 'forum_thread_last_read',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Models\\ForumPost',
        'type'       => 'entity-content',
        'name'       => 'forum_post',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Forum Posts',
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Models\\ForumThread',
        'type'       => 'entity-content',
        'name'       => 'forum_thread',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Forum Threads',
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\Forum\\Admin\\DeleteForumForm',
        'type'       => 'form',
        'name'       => 'forum.delete',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumPost\\QuoteMobileForm',
        'type'       => 'form',
        'name'       => 'forum.forum_post.quote',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumPost\\CreateForm',
        'type'       => 'form',
        'name'       => 'forum.forum_post.store',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumPost\\CreateMobileForm',
        'type'       => 'form',
        'name'       => 'forum.forum_post.store',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumPost\\EditMobileForm',
        'type'       => 'form',
        'name'       => 'forum.forum_post.update',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumPost\\EditForm',
        'type'       => 'form',
        'name'       => 'forum.forum_post.update',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumThread\\CopyMobileForm',
        'type'       => 'form',
        'name'       => 'forum.forum_thread.copy',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumThread\\MergeMobileForm',
        'type'       => 'form',
        'name'       => 'forum.forum_thread.merge',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumThread\\MoveMobileForm',
        'type'       => 'form',
        'name'       => 'forum.forum_thread.move',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumThread\\MoveForm',
        'type'       => 'form',
        'name'       => 'forum.forum_thread.move',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumThread\\CreateForm',
        'type'       => 'form',
        'name'       => 'forum.forum_thread.store',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumThread\\CreateMobileForm',
        'type'       => 'form',
        'name'       => 'forum.forum_thread.store',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumThread\\EditForm',
        'type'       => 'form',
        'name'       => 'forum.forum_thread.update',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumThread\\EditMobileForm',
        'type'       => 'form',
        'name'       => 'forum.forum_thread.update',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\Forum\\SearchForumForm',
        'type'       => 'form',
        'name'       => 'forum.search',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\Forum\\Admin\\CreateForumForm',
        'type'       => 'form',
        'name'       => 'forum.store',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumThread\\SearchForumThreadForm',
        'type'       => 'form',
        'name'       => 'forum_thread.search',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumThread\\SearchHomepageThreadForm',
        'type'       => 'form',
        'name'       => 'forum_thread.homepage_search',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumThread\\SearchForumThreadMobileForm',
        'type'       => 'form',
        'name'       => 'forum_thread.search',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\Forum\\Admin\\EditForumForm',
        'type'       => 'form',
        'name'       => 'forum.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumThread\\EditMobileForm',
        'type'       => 'form-mobile',
        'name'       => 'forum.forum_thread.update',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'       => 'form-settings',
        'name'       => 'forum',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.settings',
        'url'        => '/admincp/forum/setting',
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Jobs\\CopyThread',
        'type'       => 'job',
        'name'       => 'MetaFox\\Forum\\Jobs\\CopyThread',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Job',
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Jobs\\CreatePost',
        'type'       => 'job',
        'name'       => 'MetaFox\\Forum\\Jobs\\CreatePost',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Job',
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Jobs\\SubscribedThread',
        'type'       => 'job',
        'name'       => 'MetaFox\\Forum\\Jobs\\SubscribedThread',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Job',
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\Forum\\ForumItemCollection',
        'type'       => 'json-collection',
        'name'       => 'forum.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumPost\\ForumPostItemCollection',
        'type'       => 'json-collection',
        'name'       => 'forum_post.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\Forum\\ForumQuickNavigationCollection',
        'type'       => 'json-collection',
        'name'       => 'forum.quick_navigation',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\Forum\\ForumSideBlockItemCollection',
        'type'       => 'json-collection',
        'name'       => 'forum.side_block_item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumThread\\ForumThreadCollection',
        'type'       => 'json-collection',
        'name'       => 'forum_thread.',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\Forum\\ForumDetail',
        'type'       => 'json-resource',
        'name'       => 'forum.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\Forum\\ForumEmbed',
        'type'       => 'json-resource',
        'name'       => 'forum.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\Forum\\ForumItem',
        'type'       => 'json-resource',
        'name'       => 'forum.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumPost\\ForumPostDetail',
        'type'       => 'json-resource',
        'name'       => 'forum_post.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumPost\\ForumPostEmbed',
        'type'       => 'json-resource',
        'name'       => 'forum_post.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumPost\\ForumPostItem',
        'type'       => 'json-resource',
        'name'       => 'forum_post.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\Forum\\ForumQuickNavigationItem',
        'type'       => 'json-resource',
        'name'       => 'forum.quick_navigation_item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\Forum\\ForumSideBlockItem',
        'type'       => 'json-resource',
        'name'       => 'forum.side_block_item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumThread\\ForumThreadDetail',
        'type'       => 'json-resource',
        'name'       => 'forum_thread.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumThread\\ForumThreadEmbed',
        'type'       => 'json-resource',
        'name'       => 'forum_thread.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumThread\\ForumThreadItem',
        'type'       => 'json-resource',
        'name'       => 'forum_thread.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Notifications\\ApprovedPost',
        'type'       => 'notification',
        'name'       => 'approved_post',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Notifications\\ApprovedThread',
        'type'       => 'notification',
        'name'       => 'approved_thread',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'forum',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Policies\\ForumPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Forum\\Models\\Forum',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Policies\\ForumPostPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Forum\\Models\\ForumPost',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Policies\\ForumThreadPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Forum\\Models\\ForumThread',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\Forum\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'forum',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumPost\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'forum_post',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumThread\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'forum_thread',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\Forum\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'forum',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumPost\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'forum_post',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Forum\\Http\\Resources\\v1\\ForumThread\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'forum_thread',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
];
