<?php

/* this is auto generated file */
return [
    [
        'name'         => 'admin.forum.browse_forum',
        'phrase_title' => 'forum::phrase.browse_forum',
        'url'          => 'admincp/forum/forum/browse',
    ],
    [
        'name'         => 'admin.forum.create_forum',
        'phrase_title' => 'forum::phrase.create_new_forum',
        'url'          => 'admincp/forum/forum/create',
    ],
    [
        'name'         => 'admin.forum.forum_setting',
        'phrase_title' => 'core::phrase.settings',
        'url'          => 'admincp/forum/setting',
    ],
    [
        'name'         => 'admin.forum.permissions',
        'phrase_title' => 'core::phrase.permissions',
        'url'          => 'admincp/forum/permission',
    ],
    [
        'name'               => 'forum.browse_history_forum_thread',
        'phrase_title'       => 'forum::seo.forum_thread.browse_history_title',
        'phrase_description' => 'forum::seo.forum_thread.browse_history_description',
        'phrase_keywords'    => 'forum::seo.forum_thread.browse_history_keywords',
        'phrase_heading'     => 'forum::seo.forum_thread.browse_history_heading',
        'url'                => 'forum/history-thread',
        'item_type'          => 'forum',
    ],
    [
        'name'               => 'forum.browse_my_forum_thread',
        'phrase_title'       => 'forum::seo.forum_thread.browse_my_title',
        'phrase_description' => 'forum::seo.forum_thread.browse_my_description',
        'phrase_keywords'    => 'forum::seo.forum_thread.browse_my_keywords',
        'phrase_heading'     => 'forum::seo.forum_thread.browse_my_heading',
        'url'                => 'forum/my-thread',
        'item_type'          => 'forum',
    ],
    [
        'name'               => 'forum.browse_my_pending_forum_post',
        'phrase_title'       => 'forum::seo.forum_post.browse_my_pending_title',
        'phrase_description' => 'forum::seo.forum_post.browse_my_pending_description',
        'phrase_keywords'    => 'forum::seo.forum_post.browse_my_pending_keywords',
        'phrase_heading'     => 'forum::seo.forum_post.browse_my_pending_heading',
        'url'                => 'forum/my-pending-post',
        'item_type'          => 'forum',
    ],
    [
        'name'               => 'forum.browse_my_pending_forum_thread',
        'phrase_title'       => 'forum::seo.forum_thread.browse_my_pending_forum_thread_title',
        'phrase_description' => 'forum::seo.forum_thread.browse_my_pending_forum_thread_desription',
        'phrase_keywords'    => 'forum::seo.forum_thread.browse_my_pending_forum_thread_keywords',
        'phrase_heading'     => 'forum::seo.forum_thread.browse_my_pending_forum_thread_heading',
        'url'                => 'forum/my-pending-thread',
        'item_type'          => 'forum',
    ],
    [
        'name'               => 'forum.browse_pending_forum_post',
        'phrase_title'       => 'forum::seo.forum_post.browse_pending_title',
        'phrase_description' => 'forum::seo.forum_post.browse_pending_description',
        'phrase_keywords'    => 'forum::seo.forum_post.browse_pending_keywords',
        'phrase_heading'     => 'forum::seo.forum_post.browse_pending_heading',
        'url'                => 'forum/pending-post',
        'item_type'          => 'forum',
    ],
    [
        'name'               => 'forum.browse_pending_forum_thread',
        'phrase_title'       => 'forum::seo.forum_thread.browse_pending_title',
        'phrase_description' => 'forum::seo.forum_thread.browse_pending_description',
        'phrase_keywords'    => 'forum::seo.forum_thread.browse_pending_keywords',
        'phrase_heading'     => 'forum::seo.forum_thread.browse_pending_heading',
        'url'                => 'forum/pending-thread',
        'item_type'          => 'forum',
    ],
    [
        'name'               => 'forum.browse_subscribed_forum_thread',
        'phrase_title'       => 'forum::seo.forum_thread.browse_subscribed_title',
        'phrase_description' => 'forum::seo.forum_thread.browse_subscribed_description',
        'phrase_keywords'    => 'forum::seo.forum_thread.browse_subscribed_keywords',
        'phrase_heading'     => 'forum::seo.forum_thread.browse_subscribed_heading',
        'url'                => 'forum/subscribed-thread',
        'item_type'          => 'forum',
    ],
    [
        'name'               => 'forum.browse_wiki_forum_thread',
        'phrase_title'       => 'forum::seo.forum_thread.browse_wiki_title',
        'phrase_description' => 'forum::seo.forum_thread.browse_wiki_description',
        'phrase_keywords'    => 'forum::seo.forum_thread.browse_wiki_keywords',
        'phrase_heading'     => 'forum::seo.forum_thread.browse_wiki_heading',
        'url'                => 'forum/wiki-thread',
        'item_type'          => 'forum',
    ],
    [
        'name'               => 'forum.forum',
        'phrase_title'       => 'core::seo.core_search_title',
        'phrase_description' => 'core::seo.core_search_description',
        'phrase_keywords'    => 'core::seo.core_search_keywords',
        'phrase_heading'     => 'core::seo.core_search_heading',
        'url'                => 'forum/search',
        'item_type'          => 'forum',
    ],
    [
        'name'               => 'forum.forum.landing',
        'phrase_title'       => 'forum::seo.forum.forum_landing_title',
        'phrase_description' => 'forum::seo.forum.forum_landing_description',
        'phrase_keywords'    => 'forum::seo.forum.forum_landing_keywords',
        'phrase_heading'     => 'forum::seo.forum.forum_landing_heading',
        'url'                => 'forum',
        'item_type'          => 'forum',
    ],
    [
        'name'               => 'forum.forum_thread.create',
        'phrase_title'       => 'forum::seo.forum_thread.create_title',
        'phrase_description' => 'forum::seo.forum_thread.create_description',
        'phrase_keywords'    => 'forum::seo.forum_thread.create_keywords',
        'phrase_heading'     => 'forum::seo.forum_thread.create_heading',
        'url'                => 'forum/thread/add',
        'item_type'          => 'forum_thread',
    ],
    [
        'name'               => 'forum.forum_thread.edit',
        'phrase_title'       => 'forum::seo.forum_thread.edit_title',
        'phrase_description' => 'forum::seo.forum_thread.edit_description',
        'phrase_keywords'    => 'forum::seo.forum_thread.edit_keywords',
        'phrase_heading'     => 'forum::seo.forum_thread.edit_heading',
        'url'                => 'forum/thread/edit/{id}',
        'item_type'          => 'forum_thread',
    ],
    [
        'name'               => 'forum.forum_thread.view_detail',
        'phrase_title'       => 'forum::seo.forum_thread.view_detail_title',
        'phrase_description' => 'forum::seo.forum_thread.view_detail_description',
        'phrase_keywords'    => 'forum::seo.forum_thread.view_detail_keywords',
        'phrase_heading'     => 'forum::seo.forum_thread.view_detail_heading',
        'url'                => 'forum/thread/{id}/{slug?}',
        'item_type'          => 'forum_thread',
    ],
    [
        'name'               => 'group.profile.forum',
        'phrase_title'       => 'forum::seo.group_profile_forum_title',
        'phrase_description' => 'forum::seo.group_profile_forum_desription',
        'phrase_keywords'    => 'forum::seo.group_profile_forum_keywords',
        'phrase_heading'     => 'forum::seo.group_profile_forum_heading',
        'url'                => 'group/{id}/forum',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'page.profile.forum',
        'phrase_title'       => 'forum::seo.page_profile_forum_title',
        'phrase_description' => 'forum::seo.page_profile_forum_desription',
        'phrase_keywords'    => 'forum::seo.page_profile_forum_keywords',
        'phrase_heading'     => 'forum::seo.page_profile_forum_heading',
        'url'                => 'page/{id}/forum',
        'item_type'          => 'page',
    ],
    [
        'name'               => 'user.profile.forum',
        'phrase_title'       => 'forum::seo.user_profile_forum_title',
        'phrase_description' => 'forum::seo.user_profile_forum_desription',
        'phrase_keywords'    => 'forum::seo.user_profile_forum_keywords',
        'phrase_heading'     => 'forum::seo.user_profile_forum_heading',
        'url'                => 'user/{id}/forum',
        'item_type'          => 'user',
    ],
    [
        'name'               => 'forum.forum.detail',
        'phrase_title'       => 'forum::seo.forum.detail_title',
        'phrase_description' => 'forum::seo.forum.detail_description',
        'phrase_keywords'    => 'forum::seo.forum.detail_keywords',
        'phrase_heading'     => 'forum::seo.forum.detail_heading',
        'url'                => 'forum/{id}/{slug?}',
        'item_type'          => 'forum',
    ],
];
