<?php

/* this is auto generated file */
return [
    [
        'post_type'  => 'poll',
        'icon_color' => '#f05d28',
        'showWhen'   => [
            'or',
            [
                'and',
                ['eq', 'attachmentType', 'poll'],
                ['falsy', 'isEdit'],
            ],
            [
                'and',
                ['falsy', 'hasShareValue'],
                ['falsy', 'pstatusbg_enable'],
                ['falsy', 'hasMediaFile'],
                ['neq', 'attachmentType', 'link'],
                ['neq', 'module_name', 'event'],
            ],
        ],
        'menu'     => 'feed.feed.feedComposerMenu',
        'name'     => 'compose_poll',
        'label'    => 'activity::phrase.poll',
        'ordering' => 7,
        'as'       => 'post.poll',
        'value'    => 'poll',
        'icon'     => 'barchart',
    ],
    [
        'tab'      => 'poll',
        'showWhen' => [
            'or',
            ['eq', 'item.reg_method', '0'],
            ['truthy', 'item.is_member'],
        ],
        'menu'     => 'group.group.profileMenu',
        'name'     => 'poll',
        'label'    => 'poll::phrase.polls',
        'ordering' => 6,
        'to'       => '/poll',
    ],
    [
        'tab'      => 'poll',
        'menu'     => 'page.page.profileMenu',
        'name'     => 'poll',
        'label'    => 'poll::phrase.polls',
        'ordering' => 6,
        'to'       => '/poll',
    ],
    [
        'menu'     => 'poll.poll.filter_menu',
        'name'     => 'all',
        'label'    => 'core::phrase.when.all',
        'ordering' => 1,
        'value'    => 'all',
    ],
    [
        'menu'     => 'poll.poll.filter_menu',
        'name'     => 'this_month',
        'label'    => 'core::phrase.when.this_month',
        'ordering' => 2,
        'value'    => 'this_month',
    ],
    [
        'menu'     => 'poll.poll.filter_menu',
        'name'     => 'this_week',
        'label'    => 'core::phrase.when.this_week',
        'ordering' => 3,
        'value'    => 'this_week',
    ],
    [
        'menu'     => 'poll.poll.filter_menu',
        'name'     => 'today',
        'label'    => 'core::phrase.when.today',
        'ordering' => 4,
        'value'    => 'today',
    ],
    [
        'tab'      => 'poll',
        'showWhen' => [
            'and',
            ['truthy', 'acl.poll.poll.create'],
            ['truthy', 'item.profile_settings.poll_share_polls'],
            ['falsy', 'item.is_muted'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'poll.poll.headerItemActionOnGroupProfileMenu',
        'name'     => 'poll',
        'label'    => 'poll::phrase.add_new_poll',
        'ordering' => 1,
        'to'       => '/poll/add?owner_id=:id',
    ],
    [
        'tab'      => 'poll',
        'showWhen' => [
            'and',
            ['truthy', 'acl.poll.poll.create'],
            ['truthy', 'item.profile_settings.poll_share_polls'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'poll.poll.headerItemActionOnPageProfileMenu',
        'name'     => 'poll',
        'label'    => 'poll::phrase.add_new_poll',
        'ordering' => 1,
        'to'       => '/poll/add?owner_id=:id',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'poll.poll.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'poll::phrase.edit_poll_title',
        'ordering' => 1,
        'value'    => 'editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['falsy', 'item.is_sponsored_feed'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'poll.poll.itemActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'poll::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'sponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['truthy', 'item.is_sponsored_feed'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'poll.poll.itemActionMenu',
        'name'     => 'unsponsor_in_feed',
        'label'    => 'poll::phrase.unsponsor_in_feed',
        'ordering' => 4,
        'value'    => 'unsponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['falsy', 'item.is_sponsor'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'poll.poll.itemActionMenu',
        'name'     => 'sponsor',
        'label'    => 'poll::phrase.sponsor_this_item',
        'ordering' => 5,
        'value'    => 'sponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['truthy', 'item.is_sponsor'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'poll.poll.itemActionMenu',
        'name'     => 'unsponsor',
        'label'    => 'poll::phrase.unsponsor_this_item',
        'ordering' => 6,
        'value'    => 'unsponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'poll.poll.itemActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'poll.poll.itemActionMenu',
        'name'     => 'unfeature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'poll.poll.itemActionMenu',
        'name'     => 'approve',
        'label'    => 'poll::phrase.approve',
        'ordering' => 11,
        'value'    => 'approveItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'style'     => 'danger',
        'menu'      => 'poll.poll.itemActionMenu',
        'name'      => 'delete',
        'label'     => 'poll::phrase.delete',
        'ordering'  => 12,
        'value'     => 'deleteItem',
    ],
    [
        'menu'     => 'poll.poll.sort_menu',
        'name'     => 'latest',
        'label'    => 'core::phrase.sort.recent',
        'ordering' => 1,
        'value'    => 'latest',
    ],
    [
        'menu'     => 'poll.poll.sort_menu',
        'name'     => 'most_viewed',
        'label'    => 'core::phrase.sort.most_viewed',
        'ordering' => 2,
        'value'    => 'most_viewed',
    ],
    [
        'menu'     => 'poll.poll.sort_menu',
        'name'     => 'most_liked',
        'label'    => 'core::phrase.sort.most_liked',
        'ordering' => 3,
        'value'    => 'most_liked',
    ],
    [
        'menu'     => 'poll.poll.sort_menu',
        'name'     => 'most_discussed',
        'label'    => 'core::phrase.sort.most_discussed',
        'ordering' => 4,
        'value'    => 'most_discussed',
    ],
    [
        'tab'    => 'all',
        'params' => [
            'module_name'   => 'poll',
            'resource_name' => 'poll',
        ],
        'menu'     => 'poll.sidebarMenu',
        'name'     => 'all',
        'label'    => 'poll::phrase.all_polls',
        'ordering' => 1,
        'value'    => 'viewAll',
        'to'       => '/poll/all',
    ],
    [
        'tab'    => 'my',
        'params' => [
            'module_name'   => 'poll',
            'resource_name' => 'poll',
        ],
        'menu'     => 'poll.sidebarMenu',
        'name'     => 'my',
        'label'    => 'poll::phrase.my_polls',
        'ordering' => 2,
        'value'    => 'viewMyPolls',
        'to'       => '/poll/my',
    ],
    [
        'tab'    => 'my_pending',
        'params' => [
            'module_name'   => 'poll',
            'resource_name' => 'poll',
        ],
        'showWhen' => [
            'and',
            ['neq', 'session.user.role.id', 1],
        ],
        'menu'     => 'poll.sidebarMenu',
        'name'     => 'my_pending',
        'label'    => 'poll::phrase.my_pending_polls',
        'ordering' => 3,
        'value'    => 'viewMyPendingPolls',
    ],
    [
        'tab'    => 'friend',
        'params' => [
            'module_name'   => 'poll',
            'resource_name' => 'poll',
        ],
        'menu'     => 'poll.sidebarMenu',
        'name'     => 'friend',
        'label'    => 'poll::phrase.friends_polls',
        'ordering' => 4,
        'value'    => 'viewFriendPolls',
        'to'       => '/poll/friend',
    ],
    [
        'tab'      => 'pending',
        'showWhen' => [
            'or',
            ['truthy', 'acl.poll.poll.approve'],
        ],
        'params' => [
            'module_name'   => 'poll',
            'resource_name' => 'poll',
        ],
        'menu'     => 'poll.sidebarMenu',
        'name'     => 'pending',
        'label'    => 'poll::phrase.pending_polls',
        'ordering' => 5,
        'value'    => 'viewPendingPolls',
        'to'       => '/poll/pending',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.poll.poll.view'],
            ['falsy', 'is_hashtag'],
        ],
        'module_name'   => 'poll',
        'resource_name' => 'poll',
        'menu'          => 'search.mobileCategoryMenu',
        'name'          => 'poll',
        'label'         => 'poll::phrase.poll_global_search_label',
        'ordering'      => 11,
        'value'         => 'searchGlobalPoll',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.poll.poll.view'],
        ],
        'module_name'   => 'poll',
        'resource_name' => 'poll',
        'menu'          => 'group.mobileCategoryMenu',
        'name'          => 'poll',
        'label'         => 'poll::phrase.poll_global_search_label',
        'ordering'      => 11,
        'value'         => 'searchGlobalPoll',
    ],
    [
        'tab'      => 'poll',
        'showWhen' => [
            'and',
            ['truthy', 'item.profile_menu_settings.poll_profile_menu'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'poll',
        'label'    => 'poll::phrase.polls',
        'ordering' => 11,
        'to'       => '/poll',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.poll.poll.view'],
        ],
        'module_name'   => 'poll',
        'resource_name' => 'poll',
        'menu'          => 'page.mobileCategoryMenu',
        'name'          => 'poll',
        'label'         => 'poll::phrase.poll_global_search_label',
        'ordering'      => 11,
        'value'         => 'searchGlobalPoll',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'poll.poll.detailActionMenu',
        'name'     => 'edit',
        'label'    => 'poll::phrase.edit_poll_title',
        'ordering' => 1,
        'value'    => 'editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['falsy', 'item.is_sponsored_feed'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'poll.poll.detailActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'poll::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'sponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['truthy', 'item.is_sponsored_feed'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'poll.poll.detailActionMenu',
        'name'     => 'unsponsor_in_feed',
        'label'    => 'poll::phrase.unsponsor_in_feed',
        'ordering' => 4,
        'value'    => 'unsponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['falsy', 'item.is_sponsor'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'poll.poll.detailActionMenu',
        'name'     => 'sponsor',
        'label'    => 'poll::phrase.sponsor_this_item',
        'ordering' => 5,
        'value'    => 'sponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['truthy', 'item.is_sponsor'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'poll.poll.detailActionMenu',
        'name'     => 'unsponsor',
        'label'    => 'poll::phrase.unsponsor_this_item',
        'ordering' => 6,
        'value'    => 'unsponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'poll.poll.detailActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'poll.poll.detailActionMenu',
        'name'     => 'unfeature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'poll.poll.detailActionMenu',
        'name'     => 'approve',
        'label'    => 'poll::phrase.approve',
        'ordering' => 11,
        'value'    => 'approveItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'style'     => 'danger',
        'menu'      => 'poll.poll.detailActionMenu',
        'name'      => 'delete',
        'label'     => 'poll::phrase.delete',
        'ordering'  => 12,
        'value'     => 'deleteItem',
    ],
    [
        'showWhen'  => [],
        'menu'      => 'core.bodyMenu',
        'name'      => 'poll',
        'label'     => 'poll::phrase.polls',
        'ordering'  => 14,
        'value'     => '',
        'to'        => '/poll',
        'as'        => 'item',
        'icon'      => 'barchart',
        'iconColor' => '#00d475',
    ],
];
