<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Mobile\\Http\\Resources\\v1\\AdMobConfig\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'mobile.admob',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
    ],
    [
        'driver'      => 'MetaFox\\Mobile\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'        => 'form-settings',
        'name'        => 'mobile',
        'version'     => 'v1',
        'resolution'  => 'admin',
        'is_active'   => true,
        'is_preload'  => false,
        'title'       => 'core::phrase.settings',
        'url'         => '/admincp/mobile/setting',
        'description' => 'mobile::phrase.edit_mobile_setting_desc',
    ],
    [
        'driver'      => 'MetaFox\\MobileIntegration\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'        => 'form-settings',
        'name'        => 'mobile-integration',
        'version'     => 'v1',
        'resolution'  => 'admin',
        'is_active'   => true,
        'is_preload'  => false,
        'title'       => 'core::phrase.settings',
        'url'         => '/admincp/mobile-integration/setting',
        'description' => 'mobile-integration::phrase.edit_mobile-integration_setting_desc',
    ],
    [
        'driver'     => 'MetaFox\\Mobile\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'mobile',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\MobileIntegration\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'mobile-integration',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
];
