<?php

/* this is auto generated file */
return [
    [
        'name'       => 'group.groupManagerMenu',
        'resolution' => 'web',
        'type'       => 'context',
        'title'      => 'Manage Group',
    ],
    [
        'name'       => 'group.groupManagerSettings',
        'resolution' => 'web',
        'type'       => 'context',
        'title'      => 'Manage Group Settings',
    ],
    [
        'name'       => 'group.sidebarSearchInGroupMenu',
        'resolution' => 'web',
        'type'       => 'context',
    ],
    [
        'name'       => 'group.tabMenuProfilePhoto',
        'resolution' => 'web',
        'type'       => 'context',
    ],
    [
        'name'       => 'group.actionMenuProfilePhoto',
        'resolution' => 'web',
        'type'       => 'context',
    ],
    [
        'name'       => 'group.actionMenuProfileMedia',
        'resolution' => 'web',
        'type'       => 'context',
    ],
    [
        'name'       => 'group.creatorContentMenu',
        'resolution' => 'web',
        'type'       => 'context',
    ],
    [
        'name'       => 'group.sidebarMenu',
        'resolution' => 'mobile',
        'type'       => 'sidebar',
        'title'      => 'Groups',
    ],
    [
        'name'          => 'group.group.itemActionMenu',
        'resource_name' => 'group',
        'resolution'    => 'web',
        'type'          => 'context',
    ],
    [
        'name'          => 'group.group.detailActionMenu',
        'resource_name' => 'group',
        'resolution'    => 'web',
        'type'          => 'context',
    ],
    [
        'name'          => 'group.group.profilePopoverMenu',
        'resource_name' => 'group',
        'resolution'    => 'web',
        'type'          => 'context',
    ],
    [
        'name'          => 'group.group.profileMenu',
        'resource_name' => 'group',
        'resolution'    => 'web',
        'type'          => 'profile',
        'title'         => 'Group Profile Menu',
    ],
    [
        'name'          => 'group.group.profileActionMenu',
        'resource_name' => 'group',
        'resolution'    => 'web',
        'type'          => 'context',
    ],
    [
        'name'          => 'group.group.itemActionInviteMenu',
        'resource_name' => 'group',
        'resolution'    => 'web',
        'type'          => 'context',
    ],
    [
        'name'          => 'group.group_member.profileActionMenu',
        'resource_name' => 'group',
        'resolution'    => 'web',
        'type'          => 'context',
    ],
    [
        'name'          => 'group.group_member.itemActionMenu',
        'resource_name' => 'group',
        'resolution'    => 'web',
        'type'          => 'context',
    ],
    [
        'name'          => 'group.group.profilePopoverMenu',
        'resource_name' => 'group',
        'resolution'    => 'mobile',
        'type'          => 'context',
    ],
    [
        'name'          => 'group.group_rule.itemActionMenu',
        'resource_name' => 'group',
        'resolution'    => 'web',
        'type'          => 'context',
    ],
    [
        'name'          => 'group.group_member.profileMenu',
        'resource_name' => 'group',
        'resolution'    => 'web',
        'type'          => 'context',
    ],
    [
        'name'          => 'group.group_member.itemActionMenu',
        'resource_name' => 'group',
        'resolution'    => 'mobile',
        'type'          => 'context',
    ],
    [
        'name'          => 'group.group.profileMenu',
        'resource_name' => 'group',
        'resolution'    => 'mobile',
        'type'          => 'context',
    ],
    [
        'name'          => 'group.group.profileActionMenu',
        'resource_name' => 'group',
        'resolution'    => 'mobile',
        'type'          => 'context',
    ],
    [
        'name'          => 'group.group.itemActionMenu',
        'resource_name' => 'group',
        'resolution'    => 'mobile',
        'type'          => 'context',
    ],
    [
        'name'          => 'group.group_rule.itemActionMenu',
        'resource_name' => 'group',
        'resolution'    => 'mobile',
        'type'          => 'context',
    ],
    [
        'name'          => 'group.group_member.profileMenu',
        'resource_name' => 'group',
        'resolution'    => 'mobile',
        'type'          => 'context',
    ],
    [
        'name'          => 'group.group_member.profileActionMenu',
        'resource_name' => 'group',
        'resolution'    => 'mobile',
        'type'          => 'context',
    ],
    [
        'name'          => 'group.group.fab_buttons',
        'resource_name' => 'group',
        'resolution'    => 'mobile',
        'type'          => 'filter',
    ],
    [
        'name'          => 'group.group.filter_menu',
        'resource_name' => 'group',
        'resolution'    => 'mobile',
        'type'          => 'filter',
    ],
    [
        'name'          => 'group.group.sort_menu',
        'resource_name' => 'group',
        'resolution'    => 'mobile',
        'type'          => 'context',
    ],
    [
        'name'       => 'group.sidebarMenu',
        'resolution' => 'web',
        'type'       => 'sidebar',
        'title'      => 'Groups',
    ],
    [
        'name'       => 'group.mobileCategoryMenu',
        'resolution' => 'mobile',
        'type'       => 'context',
    ],
    [
        'name'          => 'group.group.headerItemActionOnUserProfileMenu',
        'resource_name' => 'group',
        'resolution'    => 'web',
        'type'          => 'context',
    ],
    [
        'name'          => 'group.group.detailActionMenu',
        'resource_name' => 'group',
        'resolution'    => 'mobile',
        'type'          => 'context',
    ],
];
