<?php

/* this is auto generated file */
return [
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 1],
            ['truthy', 'item.extra.can_change_to_moderator'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'change_to_moderator',
        'label'    => 'group::phrase.change_to_moderator',
        'ordering' => 2,
        'value'    => 'changeToModerator',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 1],
            ['truthy', 'item.extra.can_remove_as_admin'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'remove_as_admin',
        'label'    => 'group::phrase.remove_as_admin',
        'ordering' => 3,
        'value'    => 'removeAsAdmin',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 1],
            ['truthy', 'item.extra.can_reassign_owner'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'reassign_owner',
        'label'    => 'group::phrase.reassign_owner',
        'ordering' => 5,
        'value'    => 'reassignOwner',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 2],
            ['truthy', 'item.extra.can_add_as_admin'],
            ['falsy', 'item.extra.can_cancel_admin_invite'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'add_as_admin',
        'label'    => 'group::phrase.add_as_admin',
        'ordering' => 6,
        'value'    => 'addAsAdmin',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 2],
            ['truthy', 'item.extra.can_add_as_admin'],
            ['truthy', 'item.extra.can_cancel_admin_invite'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'cancel_admin_invite_from_moderator',
        'label'    => 'group::phrase.remove_admin_invite',
        'ordering' => 6,
        'value'    => 'cancelAdminInvite',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 2],
            ['truthy', 'item.extra.can_remove_as_moderator'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'remove_as_moderator',
        'label'    => 'group::phrase.remove_as_moderator',
        'ordering' => 7,
        'value'    => 'removeAsModerator',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 0],
            ['truthy', 'item.extra.can_set_as_admin'],
            ['falsy', 'item.extra.can_cancel_admin_invite'],
            ['falsy', 'item.extra.can_cancel_moderator_invite'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'set_as_admin',
        'label'    => 'group::phrase.set_as_admin',
        'ordering' => 9,
        'value'    => 'setAsAdmin',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 0],
            ['truthy', 'item.extra.can_set_as_admin'],
            ['truthy', 'item.extra.can_cancel_admin_invite'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'cancel_admin_invite',
        'label'    => 'group::phrase.remove_admin_invite',
        'ordering' => 10,
        'value'    => 'cancelAdminInvite',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 0],
            ['truthy', 'item.extra.can_set_as_moderator'],
            ['falsy', 'item.extra.can_cancel_moderator_invite'],
            ['falsy', 'item.extra.can_cancel_admin_invite'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'set_as_moderator',
        'label'    => 'group::phrase.set_as_moderator',
        'ordering' => 11,
        'value'    => 'setAsModerator',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 0],
            ['truthy', 'item.extra.can_set_as_moderator'],
            ['truthy', 'item.extra.can_cancel_moderator_invite'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'cancel_moderator_invite',
        'label'    => 'group::phrase.cancel_moderator_invite',
        'ordering' => 12,
        'value'    => 'cancelModeratorInvite',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_block'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'block_from_group',
        'label'    => 'group::phrase.block_from_group',
        'ordering' => 13,
        'value'    => 'blockFromGroup',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_mute_in_group'],
            ['falsy', 'item.is_muted'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'mute_in_group',
        'label'    => 'group::phrase.mute_in_group',
        'ordering' => 14,
        'value'    => 'muteInGroupForm',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_mute_in_group'],
            ['truthy', 'item.is_muted'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'unmute_in_group',
        'label'    => 'group::phrase.unmute_in_group',
        'ordering' => 15,
        'value'    => 'unmuteInGroup',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_leave'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'style'    => 'danger',
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'leave_group',
        'label'    => 'group::phrase.leave_group',
        'ordering' => 16,
        'value'    => 'unjoin',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 0],
            ['truthy', 'item.extra.can_remove_member'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'style'    => 'danger',
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'remove_member',
        'label'    => 'group::phrase.remove_member',
        'ordering' => 17,
        'value'    => 'removeMember',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.friendship', 0],
            ['truthy', 'item.extra.can_add_friend'],
        ],
        'params' => [
            'module_name'   => 'user',
            'resource_name' => 'user',
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'add_friend',
        'label'    => 'group::phrase.add_friend',
        'ordering' => 2,
        'value'    => 'addFriend',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.friendship', 3],
        ],
        'params' => [
            'module_name'   => 'user',
            'resource_name' => 'user',
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'cancel_request',
        'label'    => 'group::phrase.cancel_request',
        'ordering' => 3,
        'value'    => 'cancelRequest',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_add_friend'],
            ['eq', 'item.friendship', 2],
        ],
        'params' => [
            'module_name'   => 'user',
            'resource_name' => 'user',
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'confirm_request',
        'label'    => 'group::phrase.confirm',
        'ordering' => 4,
        'value'    => 'acceptFriendRequest',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_add_friend'],
            ['eq', 'item.friendship', 2],
        ],
        'params' => [
            'module_name'   => 'user',
            'resource_name' => 'user',
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'delete_request',
        'label'    => 'group::phrase.delete',
        'ordering' => 5,
        'value'    => 'denyFriendRequest',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'params' => [
            'module_name'   => 'user',
            'resource_name' => 'user',
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'edit_profile',
        'label'    => 'group::phrase.edit_profile',
        'ordering' => 6,
        'value'    => 'editProfile',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['neq', 'item.friendship', 5],
        ],
        'params' => [
            'module_name'   => 'chatplus',
            'resource_name' => 'room',
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'message',
        'label'    => 'group::phrase.message',
        'ordering' => 7,
        'value'    => 'openChatRoom',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_poke'],
            ['neq', 'item.friendship', 5],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'      => 'group.group_member.profileActionMenu',
        'name'      => 'poke',
        'label'     => 'group::phrase.poke',
        'ordering'  => 8,
        'value'     => 'pokeItem',
        'is_active' => 0,
        'is_delete' => 1,
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_featured'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'feature',
        'label'    => 'group::phrase.featured_this_user',
        'ordering' => 9,
        'value'    => 'featureItem',
    ],
    [
        'style'    => 'danger',
        'showWhen' => [
            'and',
            ['eq', 'item.friendship', 1],
        ],
        'params' => [
            'module_name'   => 'user',
            'resource_name' => 'user',
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'un_friend',
        'label'    => 'group::phrase.un_friend',
        'ordering' => 10,
        'value'    => 'user/unFriend',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_feature'],
            ['truthy', 'item.is_featured'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'unfeature',
        'label'    => 'group::phrase.un_featured_this_user',
        'ordering' => 10,
        'value'    => 'unfeatureItem',
    ],
    [
        'style'    => 'danger',
        'showWhen' => [
            'and',
            ['falsy', 'item.is_blocked'],
            ['neq', 'item.friendship', 5],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'block',
        'label'    => 'group::phrase.block_this_user',
        'ordering' => 11,
        'value'    => 'blockItem',
    ],
    [
        'style'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.is_blocked'],
            ['neq', 'item.friendship', 5],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'unblock',
        'label'    => 'group::phrase.un_block_this_user',
        'ordering' => 12,
        'value'    => 'unblockItem',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['neq', 'item.friendship', 5],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'gift_points',
        'label'    => 'group::phrase.gift_points',
        'ordering' => 14,
        'value'    => 'comingSoon',
    ],
    [
        'active'   => true,
        'tab'      => 'home',
        'menu'     => 'group.group_member.profileMenu',
        'name'     => 'home',
        'label'    => 'group::phrase.overview',
        'ordering' => 1,
        'to'       => '/',
    ],
    [
        'tab'      => 'about',
        'menu'     => 'group.group_member.profileMenu',
        'name'     => 'about',
        'label'    => 'group::phrase.about',
        'ordering' => 2,
        'to'       => '/about',
    ],
    [
        'tab'      => 'friend',
        'menu'     => 'group.group_member.profileMenu',
        'name'     => 'friend',
        'label'    => 'group::phrase.friends',
        'ordering' => 3,
        'to'       => '/friend',
    ],
    [
        'tab'      => 'photo',
        'menu'     => 'group.group_member.profileMenu',
        'name'     => 'photo',
        'label'    => 'group::phrase.photos',
        'ordering' => 4,
        'to'       => '/photo',
    ],
    [
        'tab'      => 'video',
        'menu'     => 'group.group_member.profileMenu',
        'name'     => 'video',
        'label'    => 'group::phrase.videos',
        'ordering' => 5,
        'to'       => '/video',
    ],
    [
        'tab'      => 'groups',
        'menu'     => 'group.group_member.profileMenu',
        'name'     => 'groups',
        'label'    => 'group::phrase.groups',
        'ordering' => 6,
        'to'       => '/group',
    ],
    [
        'tab'      => 'marketplace',
        'menu'     => 'group.group_member.profileMenu',
        'name'     => 'marketplace',
        'label'    => 'group::phrase.listing',
        'ordering' => 7,
        'to'       => '/listing',
    ],
    [
        'tab'      => 'group',
        'menu'     => 'group.group_member.profileMenu',
        'name'     => 'group',
        'label'    => 'group::phrase.groups',
        'ordering' => 8,
        'to'       => '/group',
    ],
    [
        'tab'      => 'event',
        'menu'     => 'group.group_member.profileMenu',
        'name'     => 'event',
        'label'    => 'group::phrase.events',
        'ordering' => 9,
        'to'       => '/event',
    ],
    [
        'menu'     => 'group.group_rule.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'group::phrase.edit_rule',
        'ordering' => 1,
        'value'    => 'updateGroupRule',
    ],
    [
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group_rule',
        ],
        'style'    => 'danger',
        'menu'     => 'group.group_rule.itemActionMenu',
        'name'     => 'delete',
        'label'    => 'group::phrase.delete_rule',
        'ordering' => 2,
        'value'    => 'deleteItem',
    ],
    [
        'menu'     => 'group.group.filter_menu',
        'name'     => 'all',
        'label'    => 'core::phrase.when.all',
        'ordering' => 1,
        'value'    => 'all',
    ],
    [
        'menu'     => 'group.group.filter_menu',
        'name'     => 'this_month',
        'label'    => 'core::phrase.when.this_month',
        'ordering' => 2,
        'value'    => 'this_month',
    ],
    [
        'menu'     => 'group.group.filter_menu',
        'name'     => 'this_week',
        'label'    => 'core::phrase.when.this_week',
        'ordering' => 3,
        'value'    => 'this_week',
    ],
    [
        'menu'     => 'group.group.filter_menu',
        'name'     => 'today',
        'label'    => 'core::phrase.when.today',
        'ordering' => 4,
        'value'    => 'today',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_generate_invite_link'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.itemActionInviteMenu',
        'name'     => 'generate',
        'label'    => 'group::phrase.generate_invite_link',
        'ordering' => 1,
        'value'    => 'group/generateLinkInvite',
    ],
    [
        'showWhen' => [
            'and',
            [
                'or',
                ['truthy', 'item.is_member'],
                ['truthy', 'item.extra.can_edit'],
            ],
            ['falsy', 'item.is_pending'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.itemActionInviteMenu',
        'name'     => 'invite',
        'label'    => 'group::phrase.invite_friends',
        'ordering' => 2,
        'value'    => 'group_invite/inviteFriends',
    ],
    [
        'showWhen' => ['eq', 'item.membership', 2],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'cancel_request',
        'label'    => 'group::phrase.cancel_request',
        'ordering' => 3,
        'value'    => 'cancelRequest',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'approve',
        'label'    => 'group::phrase.approve',
        'ordering' => 4,
        'value'    => 'approveItem',
    ],
    [
        'variant'  => 'contained',
        'showWhen' => [
            'and',
            ['eq', 'item.membership', 3],
            ['falsy', 'item.is_member'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'accept',
        'label'    => 'group::phrase.accept',
        'ordering' => 4,
        'value'    => 'acceptInvite',
    ],
    [
        'variant'  => 'outlined-square',
        'showWhen' => [
            'and',
            ['eq', 'item.membership', 3],
            ['falsy', 'item.is_member'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'decline',
        'label'    => 'group::phrase.decline_invite',
        'ordering' => 5,
        'value'    => 'declineInvite',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['falsy', 'item.is_sponsor'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'sponsor',
        'label'    => 'group::phrase.sponsor',
        'ordering' => 9,
        'value'    => 'sponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            [
                'or',
                ['truthy', 'item.is_member'],
                ['truthy', 'item.extra.can_edit'],
            ],
            ['falsy', 'item.is_pending'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'invite',
        'label'    => 'group::phrase.invite_friends',
        'ordering' => 10,
        'value'    => 'inviteFriends',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['truthy', 'item.is_sponsor'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'unsponsor',
        'label'    => 'group::phrase.unsponsor',
        'ordering' => 11,
        'value'    => 'unsponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 12,
        'value'    => 'featureItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'unfeature',
        'label'    => 'group::phrase.un_feature',
        'ordering' => 13,
        'value'    => 'unfeatureItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'style'    => 'danger',
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'delete',
        'label'    => 'group::phrase.delete',
        'ordering' => 16,
        'value'    => 'deleteItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit_cover'],
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'update_cover',
        'label'    => 'group::phrase.update_cover',
        'ordering' => 1,
        'value'    => '@app/EDIT_ITEM_COVER',
        'icon'     => '',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit_cover'],
            ['truthy', 'item.cover_photo_id'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'remove_cover',
        'label'    => 'group::phrase.remove_cover',
        'ordering' => 2,
        'value'    => 'remove_cover',
        'icon'     => '',
    ],
    [
        'variant'  => 'contained',
        'disabled' => false,
        'showWhen' => [
            'and',
            ['eq', 'item.membership', 0],
            ['falsy', 'item.is_pending'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'join',
        'label'    => 'group::phrase.join_group',
        'ordering' => 3,
        'value'    => 'join',
    ],
    [
        'showWhen' => [
            'and',
            [
                'or',
                ['truthy', 'item.is_member'],
                ['truthy', 'item.extra.can_edit'],
            ],
            ['falsy', 'item.is_pending'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group_invite',
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'invite',
        'label'    => 'group::phrase.invite_friends',
        'ordering' => 5,
        'value'    => 'group/inviteFriends',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_generate_invite_link'],
            ['eq', 'item.reg_method', 2],
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'generate',
        'label'    => 'group::phrase.generate_invite_link',
        'ordering' => 5,
        'value'    => 'group/generateInviteLink',
    ],
    [
        'showWhen' => ['eq', 'item.membership', 2],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'cancel_request',
        'label'    => 'group::phrase.cancel_request',
        'ordering' => 6,
        'value'    => 'cancelRequest',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
            [
                'or',
                ['truthy', 'item.extra.can_manage_member_report_content'],
                ['truthy', 'item.extra.can_manage_pending_posts'],
            ],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'manage',
        'label'    => 'group::phrase.manage',
        'ordering' => 7,
        'value'    => 'manage',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_manage_pending_request_tab'],
            [
                'or',
                ['truthy', 'item.extra.can_manage_setting'],
                ['truthy', 'item.is_moderator'],
            ],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'manage_pending_requests',
        'label'    => 'group::phrase.pending_request',
        'ordering' => 8,
        'value'    => 'pendingRequests',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_member'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'your_content',
        'label'    => 'group::phrase.your_content',
        'ordering' => 9,
        'as'       => '',
        'value'    => 'yourContent',
        'to'       => '/group/:id/review_my_content',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 10,
        'value'    => 'featureItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'unfeature',
        'label'    => 'group::phrase.un_feature',
        'ordering' => 11,
        'value'    => 'unfeatureItem',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['falsy', 'item.is_sponsor'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'sponsor',
        'label'    => 'group::phrase.sponsor',
        'ordering' => 12,
        'value'    => 'sponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['truthy', 'item.is_sponsor'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'unsponsor',
        'label'    => 'group::phrase.unsponsor',
        'ordering' => 13,
        'value'    => 'unsponsorItem',
    ],
    [
        'color'    => 'primary',
        'showWhen' => ['truthy', 'item.is_owner'],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'reassign_owner',
        'label'    => 'group::phrase.reassign_owner',
        'ordering' => 14,
        'value'    => 'reassignOwnerDialog',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_pending'],
            ['truthy', 'item.is_member'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'leave_group',
        'label'    => 'group::phrase.leave_group',
        'ordering' => 15,
        'value'    => 'unjoin',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'params'    => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'style'    => 'danger',
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'delete',
        'label'    => 'group::phrase.delete',
        'ordering' => 16,
        'value'    => 'deleteItem',
    ],
    [
        'active'   => true,
        'tab'      => 'home',
        'showWhen' => [
            'or',
            ['eq', 'item.reg_method', '0'],
            ['truthy', 'item.is_member'],
        ],
        'menu'     => 'group.group.profileMenu',
        'name'     => 'home',
        'label'    => 'group::phrase.discussions',
        'ordering' => 1,
        'to'       => '/',
    ],
    [
        'tab'      => 'about',
        'menu'     => 'group.group.profileMenu',
        'name'     => 'about',
        'label'    => 'group::phrase.about',
        'ordering' => 2,
        'to'       => '/about',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_member'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.profilePopoverMenu',
        'name'     => 'edit',
        'label'    => 'group::phrase.leave_group',
        'ordering' => 2,
        'value'    => 'unjoin',
    ],
    [
        'showWhen' => [
            'and',
            [
                'or',
                ['truthy', 'item.is_member'],
                ['truthy', 'item.extra.can_edit'],
            ],
            ['falsy', 'item.is_pending'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.profilePopoverMenu',
        'name'     => 'invite',
        'label'    => 'group::phrase.invite_friends',
        'ordering' => 3,
        'value'    => 'group_invite/inviteFriends',
    ],
    [
        'menu'     => 'group.group.sort_menu',
        'name'     => 'latest',
        'label'    => 'core::phrase.sort.latest',
        'ordering' => 1,
        'value'    => 'latest',
    ],
    [
        'menu'     => 'group.group.sort_menu',
        'name'     => 'most_member',
        'label'    => 'core::phrase.sort.most_joined',
        'ordering' => 2,
        'value'    => 'most_member',
    ],
    [
        'tab'    => 'all',
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.sidebarMenu',
        'name'     => 'all',
        'label'    => 'group::phrase.all_groups',
        'ordering' => 1,
        'value'    => 'viewAll',
        'to'       => '/group/all',
    ],
    [
        'tab'      => 'my',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.sidebarMenu',
        'name'     => 'my',
        'label'    => 'group::phrase.my_groups',
        'ordering' => 2,
        'value'    => 'viewMyGroups',
        'to'       => '/group/my',
    ],
    [
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'showWhen' => [
            'and',
            ['neq', 'session.user.role.id', 1],
        ],
        'menu'     => 'group.sidebarMenu',
        'name'     => 'my_pending',
        'label'    => 'group::phrase.my_pending_groups',
        'ordering' => 3,
        'value'    => 'viewMyPendingGroups',
    ],
    [
        'tab'      => 'friend',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.sidebarMenu',
        'name'     => 'friend',
        'label'    => 'group::phrase.friends_groups',
        'ordering' => 4,
        'value'    => 'viewFriendGroups',
        'to'       => '/group/friend',
    ],
    [
        'tab'      => 'joined',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.sidebarMenu',
        'name'     => 'joined',
        'label'    => 'group::phrase.joined_groups',
        'ordering' => 5,
        'value'    => 'viewJoinedGroups',
        'to'       => '/group/joined',
    ],
    [
        'tab'      => 'invited',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.sidebarMenu',
        'name'     => 'invited',
        'label'    => 'group::phrase.group_invites',
        'ordering' => 6,
        'value'    => 'viewInvitedGroups',
        'to'       => '/group/invited',
    ],
    [
        'tab'      => 'pending',
        'showWhen' => [
            'or',
            ['truthy', 'acl.group.group.approve'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.sidebarMenu',
        'name'     => 'pending',
        'label'    => 'group::phrase.pending_groups',
        'ordering' => 7,
        'value'    => 'viewPendingGroups',
        'to'       => '/group/pending',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.group.group.view'],
            ['falsy', 'is_hashtag'],
        ],
        'menu'          => 'search.mobileCategoryMenu',
        'name'          => 'group',
        'label'         => 'group::phrase.group_global_search_label',
        'ordering'      => 6,
        'value'         => 'searchGlobalGroup',
        'module_name'   => 'group',
        'resource_name' => 'group',
    ],
    [
        'tab'      => 'group',
        'showWhen' => [
            'and',
            ['truthy', 'item.profile_menu_settings.group_profile_menu'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'group',
        'label'    => 'group::phrase.groups',
        'ordering' => 6,
        'to'       => '/group',
    ],
    [
        'module_name'   => 'group',
        'resource_name' => 'group',
        'menu'          => 'group.mobileCategoryMenu',
        'name'          => 'all',
        'label'         => 'core::phrase.all',
        'ordering'      => 0,
        'value'         => 'searchGlobalInGroup',
    ],
    [
        'showWhen' => ['eq', 'item.membership', 2],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.detailActionMenu',
        'name'     => 'cancel_request',
        'label'    => 'group::phrase.cancel_request',
        'ordering' => 3,
        'value'    => 'cancelRequest',
    ],
    [
        'variant'  => 'contained',
        'showWhen' => ['eq', 'item.membership', 3],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.detailActionMenu',
        'name'     => 'accept',
        'label'    => 'group::phrase.accept',
        'ordering' => 4,
        'value'    => 'acceptInvite',
    ],
    [
        'variant'  => 'outlined-square',
        'showWhen' => ['eq', 'item.membership', 3],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.detailActionMenu',
        'name'     => 'decline',
        'label'    => 'group::phrase.decline_invite',
        'ordering' => 5,
        'value'    => 'declineInvite',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['falsy', 'item.is_sponsor'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.detailActionMenu',
        'name'     => 'sponsor',
        'label'    => 'group::phrase.sponsor',
        'ordering' => 9,
        'value'    => 'sponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            [
                'or',
                ['truthy', 'item.is_member'],
                ['truthy', 'item.extra.can_edit'],
            ],
            ['falsy', 'item.is_pending'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.detailActionMenu',
        'name'     => 'invite',
        'label'    => 'group::phrase.invite_friends',
        'ordering' => 10,
        'value'    => 'inviteFriends',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['truthy', 'item.is_sponsor'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.detailActionMenu',
        'name'     => 'unsponsor',
        'label'    => 'group::phrase.unsponsor',
        'ordering' => 11,
        'value'    => 'unsponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.detailActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 12,
        'value'    => 'featureItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.detailActionMenu',
        'name'     => 'unfeature',
        'label'    => 'group::phrase.un_feature',
        'ordering' => 13,
        'value'    => 'unfeatureItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'style'    => 'danger',
        'menu'     => 'group.group.detailActionMenu',
        'name'     => 'delete',
        'label'    => 'group::phrase.delete',
        'ordering' => 16,
        'value'    => 'deleteItem',
    ],
    [
        'showWhen'  => [],
        'menu'      => 'core.bodyMenu',
        'name'      => 'group',
        'label'     => 'group::phrase.groups',
        'ordering'  => 13,
        'value'     => '',
        'to'        => '/group',
        'as'        => 'item',
        'icon'      => 'user3-three',
        'iconColor' => '#b132fb',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_share'],
        ],
        'params' => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'feed.itemShareActionsMenu',
        'name'     => 'share_on_group',
        'label'    => 'activity::phrase.share_on_group',
        'ordering' => 5,
        'value'    => 'shareOnGroupProfile',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_pending', 0],
            ['truthy', 'item.extra.can_pin_item'],
            ['falsy', 'item.extra.can_review_feed'],
            ['truthy', 'profile_id'],
            ['or', ['eqeqeq', 'params._identity', '$.item.user'], ['eqeqeq', 'params._identity', '$.item.parent_user']],
            ['eq', 'profile_type', 'group'],
            ['noneOf', 'item.pins', '$.profile_id'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'pinItemOnGroup',
        'label'    => 'group::phrase.pin_post_on_group',
        'ordering' => 2,
        'value'    => 'pinItem',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_pending', 0],
            ['truthy', 'item.extra.can_pin_item'],
            ['truthy', 'profile_id'],
            ['or', ['eqeqeq', 'params._identity', '$.item.user'], ['eqeqeq', 'params._identity', '$.item.parent_user']],
            ['eq', 'profile_type', 'group'],
            ['oneOf', 'item.pins', '$.profile_id'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'unpinItemOnGroup',
        'label'    => 'activity::phrase.unpin_post',
        'ordering' => 3, 'value' => 'unpinItem',
    ],
];
