<?php

/* this is auto generated file */
return [
    [
        'subInfo'  => 'group::phrase.browse_groups_you_like_to_join',
        'menu'     => 'core.dropdownMenu',
        'name'     => 'groups',
        'label'    => 'group::phrase.groups',
        'ordering' => 6,
        'icon'     => 'ico-user3-three',
        'to'       => '/group',
    ],
    [
        'subInfo'  => 'group::phrase.browse_groups_you_like_to_join',
        'menu'     => 'core.primaryMenu',
        'name'     => 'groups',
        'label'    => 'group::phrase.groups',
        'ordering' => 6,
        'icon'     => 'ico-user3-three',
        'to'       => '/group',
    ],
    [
        'menu'     => 'group.actionMenuProfileMedia',
        'name'     => 'add_photos',
        'ordering' => 1,
        'as'       => 'feed.ui.addPhotoButton',
    ],
    [
        'menu'     => 'group.actionMenuProfilePhoto',
        'name'     => 'add_photos',
        'ordering' => 1,
        'as'       => 'feed.ui.addPhotoButton',
    ],
    [
        'tab'      => 'pending',
        'showWhen' => [
            'and',
            ['truthy', 'item.is_member'],
            ['falsy', 'item.is_admin'],
            ['falsy', 'item.is_moderator'],
            ['falsy', 'item.is_owner'],
        ],
        'menu'     => 'group.creatorContentMenu',
        'name'     => 'pending',
        'label'    => 'group::phrase.pending',
        'ordering' => 1,
        'as'       => '',
        'icon'     => 'ico-clock-o',
        'to'       => '/group/:id/review_my_content/pending',
    ],
    [
        'tab'      => 'published',
        'showWhen' => [
            'and',
            ['truthy', 'item.is_member'],
        ],
        'menu'     => 'group.creatorContentMenu',
        'name'     => 'published',
        'label'    => 'group::phrase.published',
        'ordering' => 1,
        'as'       => '',
        'icon'     => 'ico-newspaper-o',
        'to'       => '/group/:id/review_my_content/published',
    ],
    [
        'tab'      => 'declined',
        'showWhen' => [
            'and',
            ['truthy', 'item.is_member'],
            ['falsy', 'item.is_admin'],
            ['falsy', 'item.is_moderator'],
            ['falsy', 'item.is_owner'],
        ],
        'menu'     => 'group.creatorContentMenu',
        'name'     => 'declined',
        'label'    => 'group::phrase.declined',
        'ordering' => 1,
        'as'       => '',
        'icon'     => 'ico-flag-triangle-o',
        'to'       => '/group/:id/review_my_content/declined',
    ],
    [
        'tab'      => 'removed',
        'showWhen' => [
            'and',
            ['truthy', 'item.is_member'],
        ],
        'menu'     => 'group.creatorContentMenu',
        'name'     => 'removed',
        'label'    => 'group::phrase.removed',
        'ordering' => 1,
        'as'       => '',
        'icon'     => 'ico-trash-o',
        'to'       => '/group/:id/review_my_content/removed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_generate_invite_link'],
            ['eq', 'item.reg_method', 2],
        ],
        'menu'     => 'group.group.itemActionInviteMenu',
        'name'     => 'generate',
        'label'    => 'group::phrase.generate_invite_link',
        'ordering' => 1,
        'value'    => 'group/generateInviteLink',
        'icon'     => 'ico-link',
    ],
    [
        'showWhen' => [
            'and',
            [
                'or',
                ['truthy', 'item.is_member'],
                ['truthy', 'item.extra.can_edit'],
            ],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'group.group.itemActionInviteMenu',
        'name'     => 'invite',
        'label'    => 'group::phrase.invite_friends',
        'ordering' => 2,
        'value'    => 'group/inviteFriends',
        'icon'     => 'ico-envelope-o',
    ],
    [
        'variant'  => 'outlined-square',
        'showWhen' => [
            'and',
            ['eq', 'item.membership', 0],
            ['falsy', 'item.is_pending'],
        ],
        'enabledWhen' => ['truthy', 'item.extra.can_join'],
        'menu'        => 'group.group.itemActionMenu',
        'name'        => 'join_group',
        'label'       => 'group::phrase.join_group',
        'ordering'    => 1,
        'value'       => 'group/join',
        'icon'        => 'ico-plus',
    ],
    [
        'disabled' => true,
        'variant'  => 'outlined-square',
        'showWhen' => ['eq', 'item.membership', 2],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'pending_request',
        'label'    => 'group::phrase.pending_request',
        'ordering' => 2,
        'icon'     => 'ico-clock-o',
    ],
    [
        'showWhen' => ['eq', 'item.membership', 2],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'cancel_request',
        'label'    => 'group::phrase.cancel_request',
        'ordering' => 3,
        'value'    => 'group/cancelRequest',
        'icon'     => 'ico-close',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'approve',
        'label'    => 'group::phrase.approve',
        'ordering' => 4,
        'value'    => 'approveItem',
        'icon'     => 'ico-check-circle-o',
    ],
    [
        'variant'  => 'contained',
        'showWhen' => [
            'and',
            ['eq', 'item.membership', 3],
            ['falsy', 'item.is_member'],
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'accept',
        'label'    => 'group::phrase.accept',
        'ordering' => 4,
        'value'    => 'group/acceptInvite',
        'icon'     => 'ico-check',
    ],
    [
        'variant'  => 'outlined-square',
        'showWhen' => [
            'and',
            ['eq', 'item.membership', 3],
            ['falsy', 'item.is_member'],
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'decline',
        'label'    => 'group::phrase.decline_invite',
        'ordering' => 5,
        'value'    => 'group/declineInvite',
        'icon'     => 'ico-close',
    ],
    [
        'enabledWhen' => ['falsy', 'isAuth'],
        'variant'     => 'contained-square',
        'showWhen'    => [
            'and',
            ['truthy', 'item.is_member'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'joined',
        'label'    => 'group::phrase.joined',
        'ordering' => 6,
        'value'    => 'group/unjoin',
        'icon'     => 'ico-check',
    ],
    [
        'showWhen' => [
            'or',
            ['truthy', 'item.extra.can_edit'],
            ['truthy', 'item.extra.can_manage_member_report_content'],
            ['truthy', 'item.extra.can_manage_pending_posts'],
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'group::phrase.manage',
        'ordering' => 7,
        'value'    => 'group/manage',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['falsy', 'item.is_sponsor'],
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'sponsor',
        'label'    => 'group::phrase.sponsor',
        'ordering' => 9,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            [
                'or',
                ['truthy', 'item.is_member'],
                ['truthy', 'item.extra.can_edit'],
            ],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'invite',
        'label'    => 'group::phrase.invite_friends',
        'ordering' => 10,
        'value'    => 'group/inviteFriends',
        'icon'     => 'ico-envelope-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['truthy', 'item.is_sponsor'],
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'unsponsor',
        'label'    => 'group::phrase.unsponsor',
        'ordering' => 11,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 12,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'unfeature',
        'label'    => 'group::phrase.un_feature',
        'ordering' => 13,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'delete',
        'label'    => 'group::phrase.delete',
        'ordering' => 16,
        'value'    => 'deleteItem',
        'icon'     => 'ico-trash',
    ],
    [
        'variant'  => 'outlined',
        'disabled' => true,
        'showWhen' => ['eq', 'item.membership', 1],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'joined',
        'label'    => 'group::phrase.joined',
        'ordering' => 1,
        'icon'     => 'ico-check',
    ],
    [
        'variant'  => 'contained',
        'disabled' => false,
        'showWhen' => [
            'and',
            ['eq', 'item.membership', 0],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'join',
        'label'    => 'group::phrase.join_group',
        'ordering' => 2,
        'value'    => 'group/join',
        'icon'     => 'ico-plus',
    ],
    [
        'variant'  => 'outlined',
        'disabled' => true,
        'showWhen' => ['eq', 'item.membership', 2],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'pending',
        'label'    => 'group::phrase.pending_request',
        'ordering' => 4,
        'icon'     => 'ico-clock-o',
    ],
    [
        'showWhen' => ['eq', 'item.membership', 2],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'cancel_request',
        'label'    => 'group::phrase.cancel_request',
        'ordering' => 5,
        'value'    => 'group/cancelRequest',
        'icon'     => 'ico-close',
    ],
    [
        'showWhen' => [
            'or',
            ['truthy', 'item.extra.can_edit'],
            ['truthy', 'item.extra.can_manage_member_report_content'],
            ['truthy', 'item.extra.can_manage_pending_posts'],
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'manage',
        'label'    => 'group::phrase.manage',
        'ordering' => 6,
        'value'    => 'group/manage',
        'icon'     => 'ico-gear-o',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_pending'],
            ['truthy', 'item.is_member'],
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'your_content',
        'label'    => 'group::phrase.your_content',
        'ordering' => 7,
        'as'       => '',
        'value'    => 'group/yourContent',
        'icon'     => 'ico-user-man-o',
        'to'       => '/group/:id/review_my_content',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 8,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'unfeature',
        'label'    => 'group::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['falsy', 'item.is_sponsor'],
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'sponsor',
        'label'    => 'group::phrase.sponsor',
        'ordering' => 9,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['truthy', 'item.is_sponsor'],
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'unsponsor',
        'label'    => 'group::phrase.unsponsor',
        'ordering' => 10,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.is_owner'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'reassign_owner',
        'label'    => 'group::phrase.reassign_owner',
        'ordering' => 11,
        'value'    => 'group/reassignOwnerDialog',
        'icon'     => 'ico-user2-next-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_member'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'leave_group',
        'label'    => 'group::phrase.leave_group',
        'ordering' => 13,
        'value'    => 'group/unjoin',
        'icon'     => 'ico-user3-next-o',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_pending'],
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'menu'      => 'group.group.profileActionMenu',
        'name'      => 'delete',
        'label'     => 'group::phrase.delete',
        'ordering'  => 14,
        'value'     => 'deleteItem',
        'icon'      => 'ico-trash',
    ],
    [
        'active'   => true,
        'tab'      => 'home',
        'showWhen' => [
            'or',
            ['eq', 'item.reg_method', '0'],
            [
                'or',
                ['truthy', 'acl.group.group.moderate'],
                ['truthy', 'item.is_member'],
            ],
        ],
        'menu'     => 'group.group.profileMenu',
        'name'     => 'home',
        'label'    => 'group::phrase.discussions',
        'ordering' => 1,
        'to'       => '/',
    ],
    [
        'tab'      => 'about',
        'menu'     => 'group.group.profileMenu',
        'name'     => 'about',
        'label'    => 'group::phrase.about',
        'ordering' => 2,
        'to'       => '/about',
    ],
    [
        'variant'  => 'outlined-square',
        'showWhen' => [
            'and',
            ['eq', 'item.membership', 0],
            ['falsy', 'item.is_pending'],
        ],
        'enabledWhen' => ['truthy', 'item.extra.can_join'],
        'menu'        => 'group.group.profilePopoverMenu',
        'name'        => 'join_group',
        'label'       => 'group::phrase.join_group',
        'ordering'    => 1,
        'value'       => 'group/join',
        'icon'        => 'ico-plus',
    ],
    [
        'disabled' => true,
        'variant'  => 'outlined-square',
        'showWhen' => ['eq', 'item.membership', 2],
        'menu'     => 'group.group.profilePopoverMenu',
        'name'     => 'pending_request',
        'label'    => 'group::phrase.pending_request',
        'ordering' => 2,
        'icon'     => 'ico-clock-o',
    ],
    [
        'showWhen' => ['eq', 'item.membership', 2],
        'menu'     => 'group.group.profilePopoverMenu',
        'name'     => 'cancel_request',
        'label'    => 'group::phrase.cancel_request',
        'ordering' => 3,
        'value'    => 'group/cancelRequest',
        'icon'     => 'ico-close',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'group.group.profilePopoverMenu',
        'name'     => 'approve',
        'label'    => 'group::phrase.approve',
        'ordering' => 4,
        'value'    => 'approveItem',
        'icon'     => 'ico-check-circle-o',
    ],
    [
        'variant'  => 'contained',
        'showWhen' => [
            'and',
            ['eq', 'item.membership', 3],
            ['falsy', 'item.is_member'],
        ],
        'menu'     => 'group.group.profilePopoverMenu',
        'name'     => 'accept',
        'label'    => 'group::phrase.accept',
        'ordering' => 4,
        'value'    => 'group/acceptInvite',
        'icon'     => 'ico-check',
    ],
    [
        'variant'  => 'outlined-square',
        'showWhen' => [
            'and',
            ['eq', 'item.membership', 3],
            ['falsy', 'item.is_member'],
        ],
        'menu'     => 'group.group.profilePopoverMenu',
        'name'     => 'decline',
        'label'    => 'group::phrase.decline_invite',
        'ordering' => 5,
        'value'    => 'group/declineInvite',
        'icon'     => 'ico-close',
    ],
    [
        'enabledWhen' => ['falsy', 'isAuth'],
        'variant'     => 'contained-square',
        'showWhen'    => [
            'and',
            ['truthy', 'item.is_member'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'group.group.profilePopoverMenu',
        'name'     => 'joined',
        'label'    => 'group::phrase.joined',
        'ordering' => 6,
        'value'    => 'group/unjoin',
        'icon'     => 'ico-check',
    ],
    [
        'showWhen' => [
            'or',
            ['truthy', 'item.extra.can_edit'],
            ['truthy', 'item.extra.can_manage_member_report_content'],
            ['truthy', 'item.extra.can_manage_pending_posts'],
        ],
        'menu'     => 'group.group.profilePopoverMenu',
        'name'     => 'edit',
        'label'    => 'group::phrase.manage',
        'ordering' => 7,
        'value'    => 'group/manage',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            [
                'or',
                ['truthy', 'item.is_member'],
                ['truthy', 'item.extra.can_edit'],
            ],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'group.group.profilePopoverMenu',
        'name'     => 'invite',
        'label'    => 'group::phrase.invite_friends',
        'ordering' => 10,
        'value'    => 'group/inviteFriends',
        'icon'     => 'ico-envelope-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_member'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'group.group.profilePopoverMenu',
        'name'     => 'leave_group',
        'label'    => 'group::phrase.leave_group',
        'ordering' => 13,
        'value'    => 'group/unjoin',
        'icon'     => 'ico-user3-next-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'menu'     => 'group.group.profilePopoverMenu',
        'name'     => 'delete',
        'label'    => 'group::phrase.delete',
        'ordering' => 16,
        'value'    => 'deleteItem',
        'icon'     => 'ico-trash',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'group.groupManagerMenu',
        'name'     => 'manager_group',
        'label'    => 'group::phrase.manage_group',
        'ordering' => 1,
        'as'       => 'sidebarHeading',
    ],
    [
        'tab'      => 'pending_posts',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_manage_pending_posts'],
        ],
        'menu'     => 'group.groupManagerMenu',
        'name'     => 'pending_posts',
        'label'    => 'group::phrase.pending_posts',
        'ordering' => 2,
        'icon'     => 'ico-clock-o',
        'to'       => '/group/manage/:id/pending_posts',
    ],
    [
        'tab'      => 'membership_questions',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_manage_membership_question'],
        ],
        'menu'     => 'group.groupManagerMenu',
        'name'     => 'membership_questions',
        'label'    => 'group::phrase.membership_questions',
        'ordering' => 3,
        'icon'     => 'ico-user2-question-o',
        'to'       => '/group/manage/:id/membership_questions',
    ],
    [
        'tab'      => 'group_rules',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_update_rule_confirmation'],
        ],
        'menu'     => 'group.groupManagerMenu',
        'name'     => 'group_rules',
        'label'    => 'group::phrase.group_rules',
        'ordering' => 4,
        'icon'     => 'ico-list-bullet-o',
        'to'       => '/group/manage/:id/group_rules',
    ],
    [
        'tab'      => 'moderation_rights',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_manage_setting'],
        ],
        'menu'     => 'group.groupManagerMenu',
        'name'     => 'moderation_rights',
        'label'    => 'group::phrase.moderation_rights',
        'ordering' => 6,
        'icon'     => 'ico-shield-o',
        'to'       => '/group/manage/:id/moderation_rights',
    ],
    [
        'tab'      => 'landing',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
            ['truthy', 'item.extra.can_manage_setting'],
        ],
        'menu'     => 'group.groupManagerMenu',
        'name'     => 'settings',
        'label'    => 'group::phrase.settings',
        'ordering' => 7,
        'icon'     => 'ico-gear-o',
        'to'       => '/group/settings/:id',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'group.groupManagerSettings',
        'name'     => 'manager_group',
        'label'    => 'group::phrase.group_settings',
        'ordering' => 1,
        'as'       => 'sidebarHeading',
    ],
    [
        'tab'      => 'info',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'group.groupManagerSettings',
        'name'     => 'group_info',
        'label'    => 'group::phrase.group_info',
        'ordering' => 2,
        'to'       => '/group/settings/:id/info',
    ],
    [
        'tab'      => 'about',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'group.groupManagerSettings',
        'name'     => 'about_group',
        'label'    => 'group::phrase.about_group',
        'ordering' => 3,
        'to'       => '/group/settings/:id/about',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'group.groupManagerSettings',
        'name'     => 'privacy_settings',
        'label'    => 'group::phrase.privacy_settings',
        'ordering' => 5,
        'as'       => 'sidebarHeading',
    ],
    [
        'tab'      => 'permissions',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'group.groupManagerSettings',
        'name'     => 'permissions',
        'label'    => 'core::phrase.permissions',
        'ordering' => 6,
        'to'       => '/group/settings/:id/permissions',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'group.groupManagerSettings',
        'name'     => 'divider',
        'ordering' => 7,
        'as'       => 'sidebarDivider',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'group.groupManagerSettings',
        'name'     => 'group_menu_settings',
        'label'    => 'group::phrase.group_menu_settings',
        'ordering' => 8,
        'as'       => 'sidebarHeading',
    ],
    [
        'tab'      => 'menu',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'group.groupManagerSettings',
        'name'     => 'menu',
        'label'    => 'group::phrase.menu',
        'ordering' => 9,
        'to'       => '/group/settings/:id/menu',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 1],
            ['truthy', 'item.extra.can_change_to_moderator'],
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'change_to_moderator',
        'label'    => 'group::phrase.change_to_moderator',
        'ordering' => 2,
        'value'    => 'group/changeToModerator',
        'icon'     => 'ico-shield-o',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 1],
            ['truthy', 'item.extra.can_remove_as_admin'],
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'remove_as_admin',
        'label'    => 'group::phrase.remove_as_admin',
        'ordering' => 3,
        'value'    => 'group/removeAsAdmin',
        'icon'     => 'ico-user2-down-o',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 1],
            ['truthy', 'item.extra.can_remove_admin'],
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'remove_admin',
        'label'    => 'group::phrase.remove_member',
        'ordering' => 4,
        'value'    => 'group/removeAdmin',
        'icon'     => 'ico-user1-del-o',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 1],
            ['truthy', 'item.extra.can_reassign_owner'],
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'reassign_owner',
        'label'    => 'group::phrase.reassign_owner',
        'ordering' => 5,
        'value'    => 'group/reassignOwner',
        'icon'     => 'ico-businessman',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 2],
            ['truthy', 'item.extra.can_add_as_admin'],
            ['falsy', 'item.extra.can_cancel_admin_invite'],
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'add_as_admin',
        'label'    => 'group::phrase.add_as_admin',
        'ordering' => 6,
        'value'    => 'group/addAsAdmin',
        'icon'     => 'ico-businessman',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 2],
            ['truthy', 'item.extra.can_add_as_admin'],
            ['truthy', 'item.extra.can_cancel_admin_invite'],
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'cancel_admin_invite_from_moderator',
        'label'    => 'group::phrase.remove_admin_invite',
        'ordering' => 6,
        'value'    => 'closeMenu, group/cancelAdminInvite',
        'icon'     => 'ico-close-circle-o',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 2],
            ['truthy', 'item.extra.can_remove_as_moderator'],
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'remove_as_moderator',
        'label'    => 'group::phrase.remove_as_moderator',
        'ordering' => 7,
        'value'    => 'group/removeAsModerator',
        'icon'     => 'ico-user2-minus-o',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 2],
            ['truthy', 'item.extra.can_remove_moderator'],
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'remove_moderator',
        'label'    => 'group::phrase.remove_member',
        'ordering' => 8,
        'value'    => 'group/removeModerator',
        'icon'     => 'ico-user1-del-o',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 0],
            ['truthy', 'item.extra.can_set_as_admin'],
            ['falsy', 'item.extra.can_cancel_admin_invite'],
            ['falsy', 'item.extra.can_cancel_moderator_invite'],
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'set_as_admin',
        'label'    => 'group::phrase.set_as_admin',
        'ordering' => 9,
        'value'    => 'group/setAsAdmin',
        'icon'     => 'ico-businessman',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 0],
            ['truthy', 'item.extra.can_set_as_admin'],
            ['truthy', 'item.extra.can_cancel_admin_invite'],
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'cancel_admin_invite',
        'label'    => 'group::phrase.remove_admin_invite',
        'ordering' => 10,
        'value'    => 'closeMenu, group/cancelAdminInvite',
        'icon'     => 'ico-close-circle-o',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 0],
            ['truthy', 'item.extra.can_set_as_moderator'],
            ['falsy', 'item.extra.can_cancel_moderator_invite'],
            ['falsy', 'item.extra.can_cancel_admin_invite'],
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'set_as_moderator',
        'label'    => 'group::phrase.set_as_moderator',
        'ordering' => 11,
        'value'    => 'group/setAsModerator',
        'icon'     => 'ico-shield-o',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 0],
            ['truthy', 'item.extra.can_set_as_moderator'],
            ['truthy', 'item.extra.can_cancel_moderator_invite'],
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'cancel_moderator_invite',
        'label'    => 'group::phrase.cancel_moderator_invite',
        'ordering' => 12,
        'value'    => 'closeMenu, group/cancelModeratorInvite',
        'icon'     => 'ico-close-circle-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_block'],
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'block_from_group',
        'label'    => 'group::phrase.block_from_group',
        'ordering' => 13,
        'value'    => 'group/blockFromGroup',
        'icon'     => 'ico-ban',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_mute_in_group'],
            ['falsy', 'item.is_muted'],
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'mute_in_group',
        'label'    => 'group::phrase.mute_in_group',
        'ordering' => 14,
        'value'    => 'group/muteInGroupForm',
        'icon'     => 'ico-eye-alt-blocked',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_mute_in_group'],
            ['truthy', 'item.is_muted'],
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'unmute_in_group',
        'label'    => 'group::phrase.unmute_in_group',
        'ordering' => 15,
        'value'    => 'group/unmuteInGroup',
        'icon'     => 'ico-user3-plus',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 0],
            ['truthy', 'item.extra.can_remove_member'],
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'remove_member',
        'label'    => 'group::phrase.remove_member',
        'ordering' => 16,
        'value'    => 'group/removeMember',
        'icon'     => 'ico-user1-del-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_leave'],
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'leave_group',
        'label'    => 'group::phrase.leave_group',
        'ordering' => 17,
        'value'    => 'group/unjoin',
        'icon'     => 'ico-user3-next-o',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['eq', 'item.friendship', 1],
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'un_friend',
        'label'    => 'group::phrase.un_friend',
        'ordering' => 1,
        'value'    => 'user/unFriend',
        'icon'     => 'ico-user3-minus-o',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.friendship', 0],
            ['truthy', 'item.extra.can_add_friend'],
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'add_friend',
        'label'    => 'group::phrase.add_friend',
        'ordering' => 2,
        'value'    => 'user/addFriend',
        'icon'     => 'ico-user3-plus',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.friendship', 3],
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'cancel_request',
        'label'    => 'group::phrase.cancel_request',
        'ordering' => 3,
        'value'    => 'user/cancelRequest',
        'icon'     => 'ico-user2-del-o',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_add_friend'],
            ['eq', 'item.friendship', 2],
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'confirm_request',
        'label'    => 'group::phrase.confirm',
        'ordering' => 4,
        'value'    => 'user/acceptFriendRequest',
        'icon'     => 'ico-check',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_add_friend'],
            ['eq', 'item.friendship', 2],
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'delete_request',
        'label'    => 'group::phrase.delete',
        'ordering' => 5,
        'value'    => 'user/denyFriendRequest',
        'icon'     => 'ico-close',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'edit_profile',
        'label'    => 'group::phrase.edit_profile',
        'ordering' => 6,
        'value'    => 'user/editProfile',
        'icon'     => 'ico-pencil',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['neq', 'item.friendship', 5],
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'message',
        'label'    => 'group::phrase.message',
        'ordering' => 7,
        'value'    => 'chat/room/openChatRoom',
        'icon'     => 'ico-comment-o',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_poke'],
            ['neq', 'item.friendship', 5],
        ],
        'menu'      => 'group.group_member.profileActionMenu',
        'name'      => 'poke',
        'label'     => 'group::phrase.poke',
        'ordering'  => 8,
        'value'     => 'pokeItem',
        'icon'      => 'ico-smile-o',
        'is_active' => 0,
        'is_delete' => 1,
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_featured'],
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'feature',
        'label'    => 'group::phrase.featured_this_user',
        'ordering' => 9,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond-o',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_feature'],
            ['truthy', 'item.is_featured'],
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'unfeature',
        'label'    => 'group::phrase.un_featured_this_user',
        'ordering' => 10,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond-o',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['falsy', 'item.is_blocked'],
            ['neq', 'item.friendship', 5],
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'block',
        'label'    => 'group::phrase.block_this_user',
        'ordering' => 11,
        'value'    => 'blockItem',
        'icon'     => 'ico-ban',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.is_blocked'],
            ['neq', 'item.friendship', 5],
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'unblock',
        'label'    => 'group::phrase.un_block_this_user',
        'ordering' => 12,
        'value'    => 'unblockItem',
        'icon'     => 'ico-ban',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['neq', 'item.friendship', 5],
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'gift_points',
        'label'    => 'group::phrase.gift_points',
        'ordering' => 14,
        'value'    => 'comingSoon',
        'icon'     => 'ico-gift-o',
    ],
    [
        'active'   => true,
        'tab'      => 'home',
        'menu'     => 'group.group_member.profileMenu',
        'name'     => 'home',
        'label'    => 'group::phrase.overview',
        'ordering' => 1,
        'to'       => '/',
    ],
    [
        'tab'      => 'about',
        'menu'     => 'group.group_member.profileMenu',
        'name'     => 'about',
        'label'    => 'group::phrase.about',
        'ordering' => 2,
        'to'       => '/about',
    ],
    [
        'tab'      => 'friend',
        'menu'     => 'group.group_member.profileMenu',
        'name'     => 'friend',
        'label'    => 'group::phrase.friends',
        'ordering' => 3,
        'to'       => '/friend',
    ],
    [
        'tab'      => 'photo',
        'menu'     => 'group.group_member.profileMenu',
        'name'     => 'photo',
        'label'    => 'group::phrase.photos',
        'ordering' => 4,
        'to'       => '/photo',
    ],
    [
        'tab'      => 'video',
        'menu'     => 'group.group_member.profileMenu',
        'name'     => 'video',
        'label'    => 'group::phrase.videos',
        'ordering' => 5,
        'to'       => '/video',
    ],
    [
        'tab'      => 'groups',
        'menu'     => 'group.group_member.profileMenu',
        'name'     => 'groups',
        'label'    => 'group::phrase.groups',
        'ordering' => 6,
        'to'       => '/group',
    ],
    [
        'tab'      => 'marketplace',
        'menu'     => 'group.group_member.profileMenu',
        'name'     => 'marketplace',
        'label'    => 'group::phrase.listing',
        'ordering' => 7,
        'to'       => '/listing',
    ],
    [
        'tab'      => 'blog',
        'menu'     => 'group.group_member.profileMenu',
        'name'     => 'blog',
        'label'    => 'group::phrase.blogs',
        'ordering' => 8,
        'to'       => '/blog',
    ],
    [
        'tab'      => 'event',
        'menu'     => 'group.group_member.profileMenu',
        'name'     => 'event',
        'label'    => 'group::phrase.events',
        'ordering' => 9,
        'to'       => '/event',
    ],
    [
        'menu'     => 'group.group_rule.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'group::phrase.edit_rule',
        'ordering' => 1,
        'value'    => 'updateGroupRule',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'menu'     => 'group.group_rule.itemActionMenu',
        'name'     => 'delete',
        'label'    => 'group::phrase.delete_rule',
        'ordering' => 2,
        'value'    => 'deleteItem',
        'icon'     => 'ico-trash',
    ],
    [
        'tab'      => 'landing',
        'menu'     => 'group.sidebarMenu',
        'name'     => 'landing',
        'label'    => 'group::phrase.home',
        'ordering' => 1,
        'icon'     => 'ico-user1-three-o',
        'to'       => '/group',
    ],
    [
        'tab'      => 'all',
        'menu'     => 'group.sidebarMenu',
        'name'     => 'all',
        'label'    => 'group::phrase.all_groups',
        'ordering' => 2,
        'icon'     => 'ico-hashtag',
        'to'       => '/group/all',
    ],
    [
        'tab'      => 'my',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'group.sidebarMenu',
        'name'     => 'my',
        'label'    => 'group::phrase.my_groups',
        'ordering' => 3,
        'icon'     => 'ico-user-man-o',
        'to'       => '/group/my',
    ],
    [
        'tab'      => 'my_pending',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['neq', 'session.user.role.id', 1],
        ],
        'menu'     => 'group.sidebarMenu',
        'name'     => 'my_pending',
        'label'    => 'group::phrase.my_pending_groups',
        'ordering' => 4,
        'icon'     => 'ico-user1-clock-o',
        'to'       => '/group/my-pending',
    ],
    [
        'tab'      => 'friend',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'group.sidebarMenu',
        'name'     => 'friend',
        'label'    => 'group::phrase.friends_groups',
        'ordering' => 5,
        'icon'     => 'ico-user1-two-o',
        'to'       => '/group/friend',
    ],
    [
        'tab'      => 'joined',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'group.sidebarMenu',
        'name'     => 'joined',
        'label'    => 'group::phrase.joined_groups',
        'ordering' => 6,
        'icon'     => 'ico-check-circle-o',
        'to'       => '/group/joined',
    ],
    [
        'tab'      => 'invited',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'group.sidebarMenu',
        'name'     => 'invited',
        'label'    => 'group::phrase.group_invites',
        'ordering' => 7,
        'icon'     => 'ico-envelope-o',
        'to'       => '/group/invited',
    ],
    [
        'tab'      => 'pending',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.group.group.approve'],
        ],
        'menu'     => 'group.sidebarMenu',
        'name'     => 'pending',
        'label'    => 'group::phrase.pending_groups',
        'ordering' => 8,
        'icon'     => 'ico-clock-o',
        'to'       => '/group/pending',
    ],
    [
        'tab'      => 'add',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.group.group.create'],
        ],
        'buttonProps' => [
            'fullWidth' => true,
            'color'     => 'primary',
            'variant'   => 'contained',
        ],
        'menu'     => 'group.sidebarMenu',
        'name'     => 'add',
        'label'    => 'group::phrase.create_group',
        'ordering' => 9,
        'as'       => 'sidebarButton',
        'icon'     => 'ico-plus',
        'to'       => '/group/add',
    ],
    [
        'tab'      => 'post',
        'menu'     => 'group.sidebarSearchInGroupMenu',
        'name'     => 'post',
        'label'    => 'group::phrase.posts',
        'ordering' => 0,
    ],
    [
        'tab'      => 'photo',
        'menu'     => 'group.sidebarSearchInGroupMenu',
        'name'     => 'photo',
        'label'    => 'group::phrase.photos',
        'ordering' => 1,
    ],
    [
        'tab'      => 'video',
        'menu'     => 'group.sidebarSearchInGroupMenu',
        'name'     => 'video',
        'label'    => 'group::phrase.videos',
        'ordering' => 2,
    ],
    [
        'tab'      => 'blog',
        'menu'     => 'group.sidebarSearchInGroupMenu',
        'name'     => 'blog',
        'label'    => 'group::phrase.blogs',
        'ordering' => 3,
    ],
    [
        'tab'      => 'topic',
        'menu'     => 'group.sidebarSearchInGroupMenu',
        'name'     => 'topic',
        'label'    => 'group::phrase.threads',
        'ordering' => 4,
    ],
    [
        'tab'      => 'poll',
        'menu'     => 'group.sidebarSearchInGroupMenu',
        'name'     => 'poll',
        'label'    => 'group::phrase.polls',
        'ordering' => 5,
    ],
    [
        'tab'      => 'quiz',
        'menu'     => 'group.sidebarSearchInGroupMenu',
        'name'     => 'quiz',
        'label'    => 'group::phrase.quizzes',
        'ordering' => 6,
    ],
    [
        'tab'      => 'event',
        'menu'     => 'group.sidebarSearchInGroupMenu',
        'name'     => 'event',
        'label'    => 'group::phrase.events',
        'ordering' => 7,
    ],
    [
        'tab'      => 'song',
        'menu'     => 'group.sidebarSearchInGroupMenu',
        'name'     => 'song',
        'label'    => 'group::phrase.songs',
        'ordering' => 8,
    ],
    [
        'tab'      => 'marketplace',
        'menu'     => 'group.sidebarSearchInGroupMenu',
        'name'     => 'marketplace',
        'label'    => 'group::phrase.listings',
        'ordering' => 9,
    ],
    [
        'tab'      => 'photo',
        'menu'     => 'group.tabMenuProfilePhoto',
        'name'     => 'photo',
        'label'    => 'group::phrase.photos',
        'ordering' => 1,
        'to'       => 'photo',
    ],
    [
        'tab'      => 'album',
        'menu'     => 'group.tabMenuProfilePhoto',
        'name'     => 'album',
        'label'    => 'group::phrase.albums',
        'ordering' => 2,
        'to'       => 'album',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.group.group.view'],
        ],
        'menu'     => 'search.webCategoryMenu',
        'name'     => 'group',
        'label'    => 'group::phrase.group_global_search_label',
        'ordering' => 6,
        'to'       => '/search/group',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.group.group.view'],
        ],
        'menu'     => 'search.webCategoryOrderingMenu',
        'name'     => 'group',
        'label'    => 'group::phrase.group_global_search_label',
        'ordering' => 8,
    ],
    [
        'tab'      => 'group',
        'showWhen' => [
            'and',
            ['truthy', 'item.profile_menu_settings.group_profile_menu'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'group',
        'label'    => 'group::phrase.groups',
        'ordering' => 6,
        'to'       => '/group',
    ],
    [
        'tab'      => 'group',
        'showWhen' => [
            'and',
            ['truthy', 'acl.group.group.create'],
            ['truthy', 'item.is_owner'],
        ],
        'menu'     => 'group.group.headerItemActionOnUserProfileMenu',
        'name'     => 'group',
        'label'    => 'group::phrase.create_group',
        'ordering' => 1,
        'to'       => '/group/add',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_mark_announcement'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'mark_as_announcement',
        'label'    => 'group::phrase.mark_as_announcement',
        'ordering' => 22,
        'value'    => 'announcementItem',
        'icon'     => 'ico-warning-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_remove_announcement'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'remove_announcement',
        'label'    => 'group::phrase.remove_announcement',
        'ordering' => 22,
        'value'    => 'removeAnnouncementItem',
        'icon'     => 'ico-trash-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_share'],
        ],
        'menu'     => 'feed.itemShareActionsMenu',
        'name'     => 'share_on_group',
        'label'    => 'activity::phrase.share_on_group',
        'ordering' => 5,
        'value'    => 'group/shareOnGroupProfile',
        'icon'     => 'ico-user3-three',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_pending', 0],
            ['truthy', 'item.extra.can_pin_item'],
            ['falsy', 'item.extra.can_review_feed'],
            ['truthy', 'profile_id'],
            ['eq', 'profile_type', 'group'],
            ['noneOf', 'item.pins', '$.profile_id'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'pinItemOnGroup',
        'label'    => 'group::phrase.pin_post_on_group',
        'ordering' => 2,
        'value'    => 'pinItem',
        'icon'     => 'ico-thumb-tack',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_pending', 0],
            ['truthy', 'item.extra.can_pin_item'],
            ['truthy', 'profile_id'],
            ['eq', 'profile_type', 'group'],
            ['oneOf', 'item.pins', '$.profile_id'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'unpinItemOnGroup',
        'label'    => 'activity::phrase.unpin_post',
        'ordering' => 3,
        'value'    => 'unpinItem',
        'icon'     => 'ico-thumb-tack-o',
    ],
];
