<?php

/* this is auto generated file */
return [
    [
        'placement' => 'bottom',
        'content'   => [
            'component' => 'notification.ui.notificationPopper',
        ],
        'menu'     => 'core.headerSubMenu',
        'name'     => 'new_notification',
        'label'    => 'notification::phrase.notifications',
        'ordering' => 4,
        'as'       => 'popover',
        'icon'     => 'ico-bell2-o',
        'to'       => '/notification',
    ],
    [
        'menu'     => 'notification.notification.detailActionMenu',
        'name'     => 'mark_read',
        'label'    => 'notification::phrase.mark_as_read',
        'ordering' => 1,
        'value'    => 'notification/markAsRead',
        'icon'     => 'ico-check',
    ],
    [
        'className' => 'itemDelete',
        'menu'      => 'notification.notification.detailActionMenu',
        'name'      => 'delete',
        'label'     => 'notification::phrase.delete',
        'ordering'  => 2,
        'value'     => 'notification/deleteItem',
        'icon'      => 'ico-trash',
    ],
    [
        'menu'     => 'notification.notification.itemActionMenu',
        'name'     => 'mark_read',
        'label'    => 'notification::phrase.mark_as_read',
        'ordering' => 1,
        'value'    => 'notification/markAsRead',
        'icon'     => 'ico-check',
    ],
    [
        'className' => 'itemDelete',
        'menu'      => 'notification.notification.itemActionMenu',
        'name'      => 'delete',
        'label'     => 'notification::phrase.remove_this_notification',
        'ordering'  => 2,
        'value'     => 'notification/deleteItem',
        'icon'      => 'ico-trash',
    ],
    [
        'menu'     => 'notification.notificationSettingsMenu',
        'name'     => 'mark_all_as_read',
        'label'    => 'notification::phrase.mark_all_as_read',
        'ordering' => 1,
        'value'    => 'notification/markAllAsRead',
        'icon'     => 'ico-check',
    ],
    [
        'menu'     => 'notification.notificationSettingsMenu',
        'name'     => 'edit_notification_setting',
        'label'    => 'notification::phrase.notification_settings',
        'ordering' => 2,
        'value'    => 'notification/editNotificationSetting',
        'icon'     => 'ico-gear-o',
    ],
    [
        'menu'     => 'notification.notificationSettingsMenu',
        'name'     => 'browse_notifications',
        'label'    => 'notification::phrase.open_notifications',
        'ordering' => 3,
        'value'    => 'notification/browseNotifications',
        'icon'     => 'ico-wallet-o',
    ],
    [
        'tab'      => 'email-notifications',
        'menu'     => 'user.settingMenu',
        'name'     => 'email_notifications',
        'label'    => 'notification::phrase.email_notifications',
        'ordering' => 9,
        'to'       => '/settings/email-notifications',
    ],
    [
        'tab'      => 'notifications',
        'menu'     => 'user.settingMenu',
        'name'     => 'notifications',
        'label'    => 'notification::phrase.in_app_notifications',
        'ordering' => 10,
        'to'       => '/settings/notifications',
    ],
    [
        'tab'      => 'sms-notifications',
        'menu'     => 'user.settingMenu',
        'name'     => 'sms_notifications',
        'label'    => 'notification::phrase.sms_notifications',
        'ordering' => 11,
        'to'       => '/settings/sms-notifications',
    ],
];
