<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Captcha\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'       => 'form-settings',
        'name'       => 'captcha',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'core::phrase.settings',
        'url'        => '/admincp/captcha/setting',
    ],
    [
        'driver'     => 'MetaFox\\Captcha\\Http\\Resources\\v1\\Admin\\RuleSettingForm',
        'type'       => 'form-settings',
        'name'       => 'captcha.rule',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'captcha::phrase.rules',
        'url'        => '/admincp/captcha/setting/rule',
    ],
    [
        'driver'  => 'MetaFox\\Captcha\\Http\\Resources\\v1\\PackageSetting',
        'type'    => 'package-setting',
        'name'    => 'captcha',
        'version' => 'v1',
    ],
    [
        'driver'     => 'MetaFox\\Captcha\\Form\\Html\\RecaptchaV3Field',
        'type'       => 'form-field',
        'name'       => 'recaptchaV3',
        'resolution' => 'web',
    ],
    [
        'driver'     => 'MetaFox\\Captcha\\Form\\Html\\ImageCaptchaField',
        'type'       => 'form-field',
        'name'       => 'imageCaptcha',
        'resolution' => 'web',
    ],
    [
        'driver'     => 'MetaFox\\Captcha\\Form\\Html\\HiddenImageCaptchaField',
        'type'       => 'form-field',
        'name'       => 'hiddenImageCaptcha',
        'resolution' => 'web',
    ],
    [
        'driver'     => 'MetaFox\\Captcha\\Form\\Mobile\\RecaptchaV3Field',
        'type'       => 'form-field',
        'name'       => 'recaptchaV3',
        'resolution' => 'mobile',
    ],
    [
        'driver'     => 'MetaFox\\Captcha\\Form\\Mobile\\ImageCaptchaField',
        'type'       => 'form-field',
        'name'       => 'imageCaptcha',
        'resolution' => 'mobile',
    ],
    [
        'driver'     => 'MetaFox\\Captcha\\Http\\Resources\\v1\\ImageCaptcha\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'image_captcha',
        'version'    => 'v1',
        'resolution' => 'web',
    ],
    [
        'driver'     => 'MetaFox\\Captcha\\Http\\Resources\\v1\\Captcha\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'captcha',
        'version'    => 'v1',
        'resolution' => 'web',
    ],
    [
        'driver'     => 'MetaFox\\Captcha\\Http\\Resources\\v1\\Captcha\\CaptchaForm',
        'type'       => 'form',
        'name'       => 'captcha.verify',
        'version'    => 'v1',
        'resolution' => 'web',
    ],
    [
        'driver'     => 'MetaFox\\Captcha\\Http\\Resources\\v1\\Captcha\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'captcha.type',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Captcha\\Http\\Resources\\v1\\Admin\\RecaptchaV3SettingForm',
        'type'       => 'form-captcha',
        'name'       => 'recaptcha_v3',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'captcha::admin.recaptcha_v3',
    ],
];
