<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\Country\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'localize.country',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\CountryChild\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'localize.country.state',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\CountryCity\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'localize.country.state.city',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\Currency\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'localize.currency',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\Language\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'localize.language',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\Phrase\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'localize.phrase',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\Phrase\\Admin\\MissingDataGrid',
        'type'       => 'data-grid',
        'name'       => 'localize.phrase.missing',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver' => 'MetaFox\\Localize\\Models\\Country',
        'type'   => 'entity',
        'name'   => 'country',
    ],
    [
        'driver' => 'MetaFox\\Localize\\Models\\CountryCity',
        'type'   => 'entity',
        'name'   => 'country_city',
    ],
    [
        'driver' => 'MetaFox\\Localize\\Models\\CountryChild',
        'type'   => 'entity',
        'name'   => 'country_state',
    ],
    [
        'driver' => 'MetaFox\\Localize\\Models\\Currency',
        'type'   => 'entity',
        'name'   => 'currency',
    ],
    [
        'driver' => 'MetaFox\\Localize\\Models\\Language',
        'type'   => 'entity',
        'name'   => 'language',
    ],
    [
        'driver' => 'MetaFox\\Localize\\Models\\Phrase',
        'type'   => 'entity',
        'name'   => 'phrase',
    ],
    [
        'driver' => 'MetaFox\\Localize\\Models\\Timezone',
        'type'   => 'entity',
        'name'   => 'timezone',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\Currency\\Admin\\StoreCurrencyForm',
        'type'       => 'form',
        'name'       => 'core.currency.store',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\Currency\\Admin\\UpdateCurrencyForm',
        'type'       => 'form',
        'name'       => 'core.currency.update',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\CountryChild\\Admin\\SearchCountryChildForm',
        'type'       => 'form',
        'name'       => 'localize.country_state.search',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\CountryChild\\Admin\\StoreCountryChildForm',
        'type'       => 'form',
        'name'       => 'localize.country_state.store',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\CountryChild\\Admin\\UpdateCountryChildForm',
        'type'       => 'form',
        'name'       => 'localize.country_state.update',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\Country\\Admin\\SearchCountryForm',
        'type'       => 'form',
        'name'       => 'localize.country.search',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\Country\\Admin\\StoreCountryForm',
        'type'       => 'form',
        'name'       => 'localize.country.store',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\Country\\Admin\\TranslateCountryForm',
        'type'       => 'form',
        'name'       => 'localize.country.translate',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\Country\\Admin\\UpdateCountryForm',
        'type'       => 'form',
        'name'       => 'localize.country.update',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\Currency\\Admin\\StoreCurrencyForm',
        'type'       => 'form',
        'name'       => 'localize.currency.store',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\Currency\\Admin\\UpdateCurrencyForm',
        'type'       => 'form',
        'name'       => 'localize.currency.update',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\Language\\Admin\\ExportLanguageForm',
        'type'       => 'form',
        'name'       => 'localize.language.export',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\Language\\Admin\\ImportLanguageForm',
        'type'       => 'form',
        'name'       => 'localize.language.import',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\Language\\Admin\\UpdateLanguageForm',
        'type'       => 'form',
        'name'       => 'localize.language.update',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\Phrase\\Admin\\SearchPhraseForm',
        'type'       => 'form',
        'name'       => 'localize.phrase.search',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\Phrase\\Admin\\StorePhraseForm',
        'type'       => 'form',
        'name'       => 'localize.phrase.store',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\Phrase\\Admin\\TranslatePhraseForm',
        'type'       => 'form',
        'name'       => 'localize.phrase.translate',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\Phrase\\Admin\\UpdatePhraseForm',
        'type'       => 'form',
        'name'       => 'localize.phrase.update',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Form\\Html\\CountryCityCode',
        'type'       => 'form-field',
        'name'       => 'countryCity',
        'resolution' => 'web',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Form\\Mobile\\CountryCityCode',
        'type'       => 'form-field',
        'name'       => 'countryCity',
        'resolution' => 'mobile',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Form\\Html\\SearchCountryCityCode',
        'type'       => 'form-field',
        'name'       => 'searchCountryCity',
        'resolution' => 'web',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Form\\Mobile\\SearchCountryCityCode',
        'type'       => 'form-field',
        'name'       => 'searchCountryCity',
        'resolution' => 'mobile',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Form\\Mobile\\CountryStatePicker',
        'type'       => 'form-field',
        'name'       => 'countryStatePicker',
        'resolution' => 'mobile',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Form\\Html\\CurrencyPricingGroupField',
        'type'       => 'form-field',
        'name'       => 'currencyPricingGroup',
        'resolution' => 'web',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Form\\Html\\SelectLocale',
        'type'       => 'form-field',
        'name'       => 'selectLocale',
        'resolution' => 'web',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'       => 'form-settings',
        'name'       => 'localize',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'  => 'MetaFox\\Localize\\Http\\Resources\\v1\\CountryCity\\Admin\\CountryCityItemCollection',
        'type'    => 'json-collection',
        'name'    => 'country_city.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Localize\\Http\\Resources\\v1\\CountryChild\\Admin\\CountryChildItemCollection',
        'type'    => 'json-collection',
        'name'    => 'country_state.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Localize\\Http\\Resources\\v1\\Country\\Admin\\CountryItemCollection',
        'type'    => 'json-collection',
        'name'    => 'country.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Localize\\Http\\Resources\\v1\\Currency\\Admin\\CurrencyItemCollection',
        'type'    => 'json-collection',
        'name'    => 'currency.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Localize\\Http\\Resources\\v1\\Language\\Admin\\LanguageItemCollection',
        'type'    => 'json-collection',
        'name'    => 'language.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Localize\\Http\\Resources\\v1\\Phrase\\Admin\\PhraseItemCollection',
        'type'    => 'json-collection',
        'name'    => 'phrase.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Localize\\Http\\Resources\\v1\\Timezone\\TimezoneItemCollection',
        'type'    => 'json-collection',
        'name'    => 'timezone.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Localize\\Http\\Resources\\v1\\CountryCity\\Admin\\CountryCityDetail',
        'type'    => 'json-resource',
        'name'    => 'country_city.detail',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Localize\\Http\\Resources\\v1\\CountryCity\\Admin\\CountryCityItem',
        'type'    => 'json-resource',
        'name'    => 'country_city.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Localize\\Http\\Resources\\v1\\CountryChild\\Admin\\CountryChildDetail',
        'type'    => 'json-resource',
        'name'    => 'country_state.detail',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Localize\\Http\\Resources\\v1\\CountryChild\\Admin\\CountryChildItem',
        'type'    => 'json-resource',
        'name'    => 'country_state.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Localize\\Http\\Resources\\v1\\Country\\Admin\\CountryDetail',
        'type'    => 'json-resource',
        'name'    => 'country.detail',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Localize\\Http\\Resources\\v1\\Country\\Admin\\CountryItem',
        'type'    => 'json-resource',
        'name'    => 'country.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Localize\\Http\\Resources\\v1\\Currency\\Admin\\CurrencyDetail',
        'type'    => 'json-resource',
        'name'    => 'currency.detail',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Localize\\Http\\Resources\\v1\\Currency\\Admin\\CurrencyItem',
        'type'    => 'json-resource',
        'name'    => 'currency.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Localize\\Http\\Resources\\v1\\Language\\Admin\\LanguageDetail',
        'type'    => 'json-resource',
        'name'    => 'language.detail',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Localize\\Http\\Resources\\v1\\Language\\Admin\\LanguageItem',
        'type'    => 'json-resource',
        'name'    => 'language.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Localize\\Http\\Resources\\v1\\Phrase\\Admin\\PhraseDetail',
        'type'    => 'json-resource',
        'name'    => 'phrase.detail',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Localize\\Http\\Resources\\v1\\Phrase\\Admin\\PhraseItem',
        'type'    => 'json-resource',
        'name'    => 'phrase.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Localize\\Http\\Resources\\v1\\Timezone\\TimezoneItem',
        'type'    => 'json-resource',
        'name'    => 'timezone.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Localize\\Http\\Resources\\v1\\PackageSetting',
        'type'    => 'package-setting',
        'name'    => 'localize',
        'version' => 'v1',
    ],
    [
        'driver' => 'MetaFox\\Localize\\Policies\\CountryPolicy',
        'type'   => 'policy-resource',
        'name'   => 'MetaFox\\Localize\\Models\\Country',
    ],
    [
        'driver' => 'MetaFox\\Localize\\Policies\\CountryChildPolicy',
        'type'   => 'policy-resource',
        'name'   => 'MetaFox\\Localize\\Models\\CountryChild',
    ],
    [
        'driver' => 'MetaFox\\Localize\\Policies\\CurrencyPolicy',
        'type'   => 'policy-resource',
        'name'   => 'MetaFox\\Localize\\Models\\Currency',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\CountryCity\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'country_city',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\CountryChild\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'country_state',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\Language\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'language',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Localize\\Http\\Resources\\v1\\Phrase\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'phrase',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
];
