<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Queue\\Http\\Resources\\v1\\Connection\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'queue.connection',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Queue\\Http\\Resources\\v1\\FailedJob\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'queue.failed_job',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver' => 'MetaFox\\Queue\\Models\\FailedJob',
        'type'   => 'entity',
        'name'   => 'failed_job',
    ],
    [
        'driver'     => 'MetaFox\\Queue\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'       => 'form',
        'name'       => 'queue.admin.site_setting',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Queue\\Http\\Resources\\v1\\Connection\\Admin\\UpdateBeanstalkdQueue',
        'type'       => 'form',
        'name'       => 'queue.connection.update_beanstalkd_queue',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Queue\\Http\\Resources\\v1\\Connection\\Admin\\UpdateRabbitMQQueue',
        'type'       => 'form',
        'name'       => 'queue.connection.update_rabbit_m_q_queue',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Queue\\Http\\Resources\\v1\\Connection\\Admin\\UpdateRedisQueue',
        'type'       => 'form',
        'name'       => 'queue.connection.update_redis_queue',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Queue\\Http\\Resources\\v1\\Connection\\Admin\\UpdateSqsQueue',
        'type'       => 'form',
        'name'       => 'queue.connection.update_sqs_queue',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'      => 'MetaFox\\Queue\\Http\\Resources\\v1\\Connection\\Admin\\UpdateBeanstalkdQueue',
        'type'        => 'form-queue',
        'name'        => 'beanstalkd',
        'version'     => 'v1',
        'resolution'  => 'admin',
        'is_preload'  => 1,
        'title'       => 'queue::beanstalkd.form_title',
        'url'         => '/admincp/queue/connection/edit/beanstalkd/beanstalkd',
        'description' => 'queue::beanstalkd.form_desc',
    ],
    [
        'driver'      => 'MetaFox\\Queue\\Http\\Resources\\v1\\Connection\\Admin\\UpdateRabbitMQQueue',
        'type'        => 'form-queue',
        'name'        => 'rabbitmq',
        'version'     => 'v1',
        'resolution'  => 'admin',
        'is_preload'  => 1,
        'title'       => 'queue::rabbitmq.form_title',
        'url'         => '/admincp/queue/connection/edit/rabbitmq/redis',
        'description' => 'queue::rabbitmq.form_desc',
    ],
    [
        'driver'      => 'MetaFox\\Queue\\Http\\Resources\\v1\\Connection\\Admin\\UpdateRedisQueue',
        'type'        => 'form-queue',
        'name'        => 'redis',
        'version'     => 'v1',
        'resolution'  => 'admin',
        'is_preload'  => 1,
        'title'       => 'queue::redis.form_title',
        'url'         => '/admincp/queue/connection/edit/redis/redis',
        'description' => 'queue::redis.form_desc',
    ],
    [
        'driver'      => 'MetaFox\\Queue\\Http\\Resources\\v1\\Connection\\Admin\\UpdateSqsQueue',
        'type'        => 'form-queue',
        'name'        => 'sqs',
        'version'     => 'v1',
        'resolution'  => 'admin',
        'is_preload'  => 1,
        'title'       => 'queue::sqs.form_title',
        'url'         => '/admincp/queue/connection/edit/sqs/sqs',
        'description' => 'queue::sqs.form_desc',
    ],
    [
        'driver'      => 'MetaFox\\Queue\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'        => 'form-settings',
        'name'        => 'queue',
        'version'     => 'v1',
        'resolution'  => 'admin',
        'is_preload'  => 1,
        'title'       => 'core::phrase.settings',
        'url'         => '/admincp/queue/setting',
        'description' => 'Queue Settings',
    ],
    [
        'driver'  => 'MetaFox\\Queue\\Http\\Resources\\v1\\FailedJob\\Admin\\FailedJobItemCollection',
        'type'    => 'json-collection',
        'name'    => 'failed_job.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Queue\\Http\\Resources\\v1\\FailedJob\\Admin\\FailedJobDetail',
        'type'    => 'json-resource',
        'name'    => 'failed_job.detail',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Queue\\Http\\Resources\\v1\\FailedJob\\Admin\\FailedJobItem',
        'type'    => 'json-resource',
        'name'    => 'failed_job.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Queue\\Http\\Resources\\v1\\PackageSetting',
        'type'    => 'package-setting',
        'name'    => 'queue',
        'version' => 'v1',
    ],
    [
        'driver'     => 'MetaFox\\Queue\\Http\\Resources\\v1\\Connection\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'connection',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
];
