<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Category\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'blog.category',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Models\\Blog',
        'type'       => 'entity',
        'name'       => 'blog',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Blogs',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Models\\Category',
        'type'       => 'entity',
        'name'       => 'blog_category',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Blog Categories',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Models\\CategoryData',
        'type'       => 'entity',
        'name'       => 'blog_category_data',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Blog Category Data',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Models\\Blog',
        'type'       => 'entity-content',
        'name'       => 'blog',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Blogs',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Category\\Admin\\DestroyCategoryForm',
        'type'       => 'form',
        'name'       => 'blog.blog_category.destroy',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Category\\Admin\\StoreCategoryForm',
        'type'       => 'form',
        'name'       => 'blog.blog_category.store',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Category\\Admin\\UpdateCategoryForm',
        'type'       => 'form',
        'name'       => 'blog.blog_category.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\StoreBlogMobileForm',
        'type'       => 'form',
        'name'       => 'blog.blog.store',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\UpdateBlogMobileForm',
        'type'       => 'form',
        'name'       => 'blog.blog.update',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\SearchBlogForm',
        'type'       => 'form',
        'name'       => 'blog.search',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\SearchBlogMobileForm',
        'type'       => 'form',
        'name'       => 'blog.search',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\StoreBlogForm',
        'type'       => 'form',
        'name'       => 'blog.store',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\StoreBlogMobileForm',
        'type'       => 'form',
        'name'       => 'blog.store_blog_mobile',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\UpdateBlogForm',
        'type'       => 'form',
        'name'       => 'blog.update',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'       => 'form-settings',
        'name'       => 'blog',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.settings',
        'url'        => '/admincp/blog/setting',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Jobs\\DeleteCategoryJob',
        'type'       => 'job',
        'name'       => 'MetaFox\\Blog\\Jobs\\DeleteCategoryJob',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Category\\CategoryItemCollection',
        'type'       => 'json-collection',
        'name'       => 'blog_category.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\BlogEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'blog.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\BlogItemCollection',
        'type'       => 'json-collection',
        'name'       => 'blog.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Category\\CategoryDetail',
        'type'       => 'json-resource',
        'name'       => 'blog_category.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Category\\CategoryItem',
        'type'       => 'json-resource',
        'name'       => 'blog_category.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\BlogDetail',
        'type'       => 'json-resource',
        'name'       => 'blog.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\BlogEmbed',
        'type'       => 'json-resource',
        'name'       => 'blog.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\BlogItem',
        'type'       => 'json-resource',
        'name'       => 'blog.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'blog',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Policies\\BlogPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Blog\\Models\\Blog',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Policies\\CategoryPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Blog\\Models\\Category',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'blog',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'blog',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Category\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'blog_category',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
];
