<?php

/* this is auto generated file */
return [
    [
        'name'         => 'admin.blog.blog_setting',
        'phrase_title' => 'core::phrase.settings',
        'url'          => 'admincp/blog/setting',
    ],
    [
        'name'         => 'admin.blog.browse_category',
        'phrase_title' => 'core::phrase.categories',
        'url'          => 'admincp/blog/category/browse',
    ],
    [
        'name'                 => 'admin.blog.browse_child_category',
        'phrase_title'         => 'core::phrase.categories',
        'url'                  => 'admincp/blog/category/{id}/category/browse',
        'custom_sharing_route' => 1,
    ],
    [
        'name'         => 'admin.blog.create_category',
        'phrase_title' => 'core::phrase.add_category',
        'url'          => 'admincp/blog/category/create',
    ],
    [
        'name'         => 'admin.blog.edit_category',
        'phrase_title' => 'core::phrase.edit_category',
        'url'          => 'admincp/blog/category/edit/{id}',
    ],
    [
        'name'         => 'admin.blog.permissions',
        'phrase_title' => 'core::phrase.permissions',
        'url'          => 'admincp/blog/permission',
    ],
    [
        'name'               => 'blog.blog',
        'phrase_title'       => 'core::seo.core_search_title',
        'phrase_description' => 'core::seo.core_search_description',
        'phrase_keywords'    => 'core::seo.core_search_keywords',
        'phrase_heading'     => 'core::seo.core_search_heading',
        'url'                => 'blog/search',
        'item_type'          => 'blog',
    ],
    [
        'name'               => 'blog.blog.create',
        'phrase_title'       => 'blog::seo.blog_create_title',
        'phrase_description' => 'blog::seo.blog_create_description',
        'phrase_keywords'    => 'blog::seo.blog_create_keywords',
        'phrase_heading'     => 'blog::seo.blog_create_heading',
        'url'                => 'blog/add',
        'item_type'          => 'blog',
    ],
    [
        'name'               => 'blog.blog.edit',
        'phrase_title'       => 'blog::seo.blog_edit_title',
        'phrase_description' => 'blog::seo.blog_edit_description',
        'phrase_keywords'    => 'blog::seo.blog_edit_keywords',
        'phrase_heading'     => 'blog::seo.blog_edit_heading',
        'url'                => 'blog/edit/{id}',
        'item_type'          => 'blog',
    ],
    [
        'name'               => 'blog.blog.landing',
        'phrase_title'       => 'blog::seo.blog_landing_title',
        'phrase_description' => 'blog::seo.blog_landing_description',
        'phrase_keywords'    => 'blog::seo.blog_landing_keywords',
        'phrase_heading'     => 'blog::seo.blog_landing_heading',
        'url'                => 'blog',
        'item_type'          => 'blog',
    ],
    [
        'name'               => 'blog.blog.my',
        'phrase_title'       => 'blog::seo.blog_my_title',
        'phrase_description' => 'blog::seo.blog_my_description',
        'phrase_keywords'    => 'blog::seo.blog_my_keywords',
        'phrase_heading'     => 'blog::seo.blog_my_heading',
        'url'                => 'blog/my',
        'item_type'          => 'blog',
    ],
    [
        'name'               => 'blog.blog.view_detail',
        'phrase_title'       => 'blog::seo.blog_view_detail_title',
        'phrase_description' => 'blog::seo.blog_view_detail_description',
        'phrase_keywords'    => 'blog::seo.blog_view_detail_keywords',
        'phrase_heading'     => 'blog::seo.blog_view_detail_heading',
        'url'                => 'blog/{id}',
        'item_type'          => 'blog',
    ],
    [
        'name'               => 'blog.browse_all_blog',
        'phrase_title'       => 'blog::seo.blog_browse_all_title',
        'phrase_description' => 'blog::seo.blog_browse_all_description',
        'phrase_keywords'    => 'blog::seo.blog_browse_all_keywords',
        'phrase_heading'     => 'blog::seo.blog_browse_all_heading',
        'url'                => 'blog/all',
        'item_type'          => 'blog',
    ],
    [
        'name'               => 'blog.browse_draft_blog',
        'phrase_title'       => 'blog::seo.blog_browse_draft_title',
        'phrase_description' => 'blog::seo.blog_browse_draft_description',
        'phrase_keywords'    => 'blog::seo.blog_browse_draft_keywords',
        'phrase_heading'     => 'blog::seo.blog_browse_draft_heading',
        'url'                => 'blog/draft',
        'item_type'          => 'blog',
    ],
    [
        'name'               => 'blog.browse_friend_blog',
        'phrase_title'       => 'blog::seo.blog_browse_friend_title',
        'phrase_description' => 'blog::seo.blog_browse_friend_description',
        'phrase_keywords'    => 'blog::seo.blog_browse_friend_keywords',
        'phrase_heading'     => 'blog::seo.blog_browse_friend_heading',
        'url'                => 'blog/friend',
        'item_type'          => 'blog',
    ],
    [
        'name'               => 'blog.browse_my_pending_blog',
        'phrase_title'       => 'blog::seo.blog_browse_my_pending_title',
        'phrase_description' => 'blog::seo.blog_browse_my_pending_description',
        'phrase_keywords'    => 'blog::seo.blog_browse_my_pending_keywords',
        'phrase_heading'     => 'blog::seo.blog_browse_my_pending_heading',
        'url'                => 'blog/my-pending',
        'item_type'          => 'blog',
    ],
    [
        'name'               => 'blog.browse_pending_blog',
        'phrase_title'       => 'blog::seo.blog_browse_pending_title',
        'phrase_description' => 'blog::seo.blog_browse_pending_description',
        'phrase_keywords'    => 'blog::seo.blog_browse_pending_keywords',
        'phrase_heading'     => 'blog::seo.blog_browse_pending_heading',
        'url'                => 'blog/pending',
        'item_type'          => 'blog',
    ],
    [
        'name'               => 'group.profile.blog',
        'phrase_title'       => 'blog::seo.group_profile_blog_title',
        'phrase_description' => 'blog::seo.group_profile_blog_description',
        'phrase_keywords'    => 'blog::seo.group_profile_blog_keywords',
        'phrase_heading'     => 'blog::seo.group_profile_blog_heading',
        'url'                => 'group/{id}/blog',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'page.profile.blog',
        'phrase_title'       => 'blog::seo.page_profile_blog_title',
        'phrase_description' => 'blog::seo.page_profile_blog_description',
        'phrase_keywords'    => 'blog::seo.page_profile_blog_keywords',
        'phrase_heading'     => 'blog::seo.page_profile_blog_heading',
        'url'                => 'page/{id}/blog',
        'item_type'          => 'page',
    ],
    [
        'name'               => 'user.profile.blog',
        'phrase_title'       => 'blog::seo.user_profile_blog_title',
        'phrase_description' => 'blog::seo.user_profile_blog_desription',
        'phrase_keywords'    => 'blog::seo.user_profile_blog_keywords',
        'phrase_heading'     => 'blog::seo.user_profile_blog_heading',
        'url'                => 'user/{id}/blog',
        'item_type'          => 'user',
    ],
];
