<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Advertise\\Http\\Resources\\v1\\Advertise\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'advertise',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Http\\Resources\\v1\\Invoice\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'advertise.invoice',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Http\\Resources\\v1\\Placement\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'advertise.placement',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Http\\Resources\\v1\\Sponsor\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'advertise.sponsor',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Models\\Advertise',
        'type'       => 'entity',
        'name'       => 'advertise',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Models\\Invoice',
        'type'       => 'entity',
        'name'       => 'advertise_invoice',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Models\\Sponsor',
        'type'       => 'entity',
        'name'       => 'advertise_sponsor',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Http\\Resources\\v1\\Advertise\\Admin\\SearchAdvertiseForm',
        'type'       => 'form',
        'name'       => 'advertise.advertise.search_form',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Http\\Resources\\v1\\Advertise\\EditAdvertiseForm',
        'type'       => 'form',
        'name'       => 'advertise.edit',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Edit Form',
        'url'        => '/advertise/edit/:id',
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Http\\Resources\\v1\\Advertise\\PaymentAdvertiseForm',
        'type'       => 'form',
        'name'       => 'advertise.payment',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Payment Advertise Form',
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Http\\Resources\\v1\\Placement\\Admin\\DeletePlacementForm',
        'type'       => 'form',
        'name'       => 'advertise.placement.delete',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Http\\Resources\\v1\\Advertise\\SearchChartForm',
        'type'       => 'form',
        'name'       => 'advertise.search_chart_form',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Search Advertise Chart Form',
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Http\\Resources\\v1\\Advertise\\SearchAdvertiseForm',
        'type'       => 'form',
        'name'       => 'advertise.search_form',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'title'      => 'Search Advertise Form',
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Http\\Resources\\v1\\Advertise\\CreateAdvertiseForm',
        'type'       => 'form',
        'name'       => 'advertise.store',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Create Form',
        'url'        => '/advertise/add',
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Http\\Resources\\v1\\Invoice\\PaymentInvoiceForm',
        'type'       => 'form',
        'name'       => 'advertise_invoice.payment',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Payment Invoice Form',
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Http\\Resources\\v1\\Invoice\\SearchInvoiceForm',
        'type'       => 'form',
        'name'       => 'advertise_invoice.search_form',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'title'      => 'Search Invoice Form',
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Http\\Resources\\v1\\Invoice\\Admin\\SearchInvoiceForm',
        'type'       => 'form',
        'name'       => 'advertise.invoice.search_form',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => true,
        'title'      => 'Search Invoice Form',
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'       => 'form-settings',
        'name'       => 'advertise',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.settings',
        'url'        => '/admincp/advertise/setting',
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Http\\Resources\\v1\\Advertise\\AdvertiseEmbed',
        'type'       => 'json-resource',
        'name'       => 'advertise.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Http\\Resources\\v1\\Placement\\PlacementEmbed',
        'type'       => 'json-resource',
        'name'       => 'advertise_placement.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'advertise_placement',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Policies\\AdvertisePolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Advertise\\Models\\Advertise',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Policies\\InvoicePolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Advertise\\Models\\Invoice',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Policies\\PlacementPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Advertise\\Models\\Placement',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Policies\\SponsorPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Advertise\\Models\\Sponsor',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Http\\Resources\\v1\\Advertise\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'advertise',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Http\\Resources\\v1\\Advertise\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'advertise',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Http\\Resources\\v1\\Invoice\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'advertise_invoice',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Advertise\\Http\\Resources\\v1\\Invoice\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'invoice',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
];
