<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Category\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'photo.category',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.settings',
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Models\\Photo',
        'type'       => 'entity',
        'name'       => 'photo',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Photos',
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Models\\Album',
        'type'       => 'entity',
        'name'       => 'photo_album',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Photo Albums',
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Models\\AlbumItem',
        'type'       => 'entity',
        'name'       => 'photo_album_item',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Models\\Category',
        'type'       => 'entity',
        'name'       => 'photo_category',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Photo Categories',
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Models\\CategoryData',
        'type'       => 'entity',
        'name'       => 'photo_category_data',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Models\\CollectionStatistic',
        'type'       => 'entity',
        'name'       => 'photo_collection_statistic',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Models\\PhotoInfo',
        'type'       => 'entity',
        'name'       => 'photo_info',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Models\\PhotoGroup',
        'type'       => 'entity',
        'name'       => 'photo_set',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Models\\PhotoGroupItem',
        'type'       => 'entity',
        'name'       => 'photo_set_item',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Models\\Photo',
        'type'       => 'entity-content',
        'name'       => 'photo',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Photos',
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Models\\Album',
        'type'       => 'entity-content',
        'name'       => 'photo_album',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Photo Albums',
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Models\\PhotoGroup',
        'type'       => 'entity-content',
        'name'       => 'photo_set',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Media Sets',
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Album\\AddItemsAlbumMobileForm',
        'type'       => 'form',
        'name'       => 'photo.album.add_items',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Album\\AddPhotosForm',
        'type'       => 'form',
        'name'       => 'photo_album.add_photos',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Album\\SearchAlbumForm',
        'type'       => 'form',
        'name'       => 'photo_album.search',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Album\\SearchAlbumMobileForm',
        'type'       => 'form',
        'name'       => 'photo_album.search',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Album\\StoreAlbumMobileForm',
        'type'       => 'form',
        'name'       => 'photo.album.store',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Album\\CreateAlbumForm',
        'type'       => 'form',
        'name'       => 'photo_album.store',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Album\\UpdateAlbumMobileForm',
        'type'       => 'form',
        'name'       => 'photo.album.update',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Album\\EditAlbumForm',
        'type'       => 'form',
        'name'       => 'photo_album.update',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Category\\Admin\\DestroyCategoryForm',
        'type'       => 'form',
        'name'       => 'photo.photo_category.destroy',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Category\\Admin\\StoreCategoryForm',
        'type'       => 'form',
        'name'       => 'photo.photo_category.store',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Category\\Admin\\UpdateCategoryForm',
        'type'       => 'form',
        'name'       => 'photo.photo_category.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Photo\\UpdatePhotoMobileForm',
        'type'       => 'form',
        'name'       => 'photo.photo.update',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Photo\\UploadPhotoMobileForm',
        'type'       => 'form',
        'name'       => 'photo.photo.upload',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Photo\\SearchPhotoMobileForm',
        'type'       => 'form',
        'name'       => 'photo.search',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Photo\\SearchPhotoForm',
        'type'       => 'form',
        'name'       => 'photo.search',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\PhotoGroup\\CreateFeedForm',
        'type'       => 'form',
        'name'       => 'photo_set.feed_form',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Photo\\EditPhotoForm',
        'type'       => 'form',
        'name'       => 'photo.update',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Photo\\UploadPhotoForm',
        'type'       => 'form',
        'name'       => 'photo.upload',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Support\\Form\\Field\\AlbumField',
        'type'       => 'form-field',
        'name'       => 'album',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Form\\Mobile\\AlbumField',
        'type'       => 'form-field',
        'name'       => 'album',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Support\\Form\\Field\\SimpleUploadPhotosField',
        'type'       => 'form-field',
        'name'       => 'simpleUploadPhotos',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Support\\Form\\Field\\UploadMultiAlbumItemField',
        'type'       => 'form-field',
        'name'       => 'uploadMultiAlbumItem',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Photo\\Admin\\SiteSettingForm',
        'type'       => 'form-settings',
        'name'       => 'photo',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.settings',
        'url'        => '/admincp/photo/setting',
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Jobs\\DeleteAlbumJob',
        'type'       => 'job',
        'name'       => 'MetaFox\\Photo\\Jobs\\DeleteAlbumJob',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Jobs\\DeleteCategoryJob',
        'type'       => 'job',
        'name'       => 'MetaFox\\Photo\\Jobs\\DeleteCategoryJob',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Album\\AlbumEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'photo_album.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Album\\AlbumItemCollection',
        'type'       => 'json-collection',
        'name'       => 'photo_album.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\AlbumItem\\AlbumItemItemCollection',
        'type'       => 'json-collection',
        'name'       => 'photo_album_item.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Category\\CategoryEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'photo_category.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Category\\CategoryItemCollection',
        'type'       => 'json-collection',
        'name'       => 'photo_category.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Photo\\PhotoEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'photo.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Photo\\PhotoItemCollection',
        'type'       => 'json-collection',
        'name'       => 'photo.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\PhotoGroup\\PhotoGroupEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'photo_set.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\PhotoGroupItem\\PhotoGroupItemItemCollection',
        'type'       => 'json-collection',
        'name'       => 'photo_set_item.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Photo\\PhotoTaggedFriendCollection',
        'type'       => 'json-collection',
        'name'       => 'photo.tagged_friend',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Album\\AlbumDetail',
        'type'       => 'json-resource',
        'name'       => 'photo_album.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Album\\AlbumEmbed',
        'type'       => 'json-resource',
        'name'       => 'photo_album.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Album\\AlbumItem',
        'type'       => 'json-resource',
        'name'       => 'photo_album.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\AlbumItem\\AlbumItemItem',
        'type'       => 'json-resource',
        'name'       => 'photo_album_item.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Category\\CategoryDetail',
        'type'       => 'json-resource',
        'name'       => 'photo_category.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Category\\CategoryEmbed',
        'type'       => 'json-resource',
        'name'       => 'photo_category.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Category\\CategoryItem',
        'type'       => 'json-resource',
        'name'       => 'photo_category.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Photo\\PhotoDetail',
        'type'       => 'json-resource',
        'name'       => 'photo.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Photo\\PhotoEmbed',
        'type'       => 'json-resource',
        'name'       => 'photo.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Photo\\PhotoItem',
        'type'       => 'json-resource',
        'name'       => 'photo.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\PhotoGroup\\PhotoGroupDetail',
        'type'       => 'json-resource',
        'name'       => 'photo_set.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\PhotoGroup\\PhotoGroupEmbed',
        'type'       => 'json-resource',
        'name'       => 'photo_set.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\PhotoGroupItem\\PhotoGroupItemItem',
        'type'       => 'json-resource',
        'name'       => 'photo_set_item.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Photo\\PhotoTaggedFriend',
        'type'       => 'json-resource',
        'name'       => 'photo.tagged_friend',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Notifications\\DoneProcessingGroupItemsNotification',
        'type'       => 'notification',
        'name'       => 'done_processing_group_items',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'photo',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Policies\\AlbumPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Photo\\Models\\Album',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Policies\\CategoryPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Photo\\Models\\Category',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Policies\\PhotoPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Photo\\Models\\Photo',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Policies\\PhotoGroupPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Photo\\Models\\PhotoGroup',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Photo\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'photo',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Album\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'photo_album',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\PhotoGroup\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'photo_set',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Photo\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'photo',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\Photo\\Http\\Resources\\v1\\Album\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'photo_album',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
];
