<?php

/* this is auto generated file */
return [
    [
        'name'         => 'admin.photo.browse_category',
        'phrase_title' => 'core::phrase.categories',
        'url'          => 'admincp/photo/category/browse',
    ],
    [
        'name'                 => 'admin.photo.browse_child_category',
        'phrase_title'         => 'core::phrase.categories',
        'url'                  => 'admincp/photo/category/{id}/category/browse',
        'custom_sharing_route' => 1,
    ],
    [
        'name'         => 'admin.photo.create_category',
        'phrase_title' => 'core::phrase.add_category',
        'url'          => 'admincp/photo/category/create',
    ],
    [
        'name'         => 'admin.photo.edit_category',
        'phrase_title' => 'core::phrase.edit_category',
        'url'          => 'admincp/photo/category/edit/{id}',
    ],
    [
        'name'         => 'admin.photo.permissions',
        'phrase_title' => 'core::phrase.permissions',
        'url'          => 'admincp/photo/permission',
    ],
    [
        'name'         => 'admin.photo.photo_setting',
        'phrase_title' => 'core::phrase.settings',
        'url'          => 'admincp/photo/setting',
    ],
    [
        'name'               => 'group.profile.photo',
        'phrase_title'       => 'photo::seo.group_profile_photo_title',
        'phrase_description' => 'photo::seo.group_profile_photo_description',
        'phrase_keywords'    => 'photo::seo.group_profile_photo_keywords',
        'phrase_heading'     => 'photo::seo.group_profile_photo_heading',
        'url'                => 'group/{id}/photo',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'page.profile.photo',
        'phrase_title'       => 'photo::seo.page_profile_photo_title',
        'phrase_description' => 'photo::seo.page_profile_photo_description',
        'phrase_keywords'    => 'photo::seo.page_profile_photo_keywords',
        'phrase_heading'     => 'photo::seo.page_profile_photo_heading',
        'url'                => 'page/{id}/photo',
        'item_type'          => 'page',
    ],
    [
        'name'               => 'photo.browse_all_photo',
        'phrase_title'       => 'photo::seo.photo_browse_all_title',
        'phrase_description' => 'photo::seo.photo_browse_all_description',
        'phrase_keywords'    => 'photo::seo.photo_browse_all_keywords',
        'phrase_heading'     => 'photo::seo.photo_browse_all_heading',
        'url'                => 'photo/all',
        'item_type'          => 'photo',
    ],
    [
        'name'               => 'photo.browse_all_photo_album',
        'phrase_title'       => 'photo::seo.photo_album_browse_all_title',
        'phrase_description' => 'photo::seo.photo_album_browse_all_description',
        'phrase_keywords'    => 'photo::seo.photo_album_browse_all_keywords',
        'phrase_heading'     => 'photo::seo.photo_album_browse_all_heading',
        'url'                => 'photo/albums',
        'item_type'          => 'photo_album',
    ],
    [
        'name'               => 'photo.browse_friend_photo',
        'phrase_title'       => 'photo::seo.photo_browse_friend_title',
        'phrase_description' => 'photo::seo.photo_browse_friend_description',
        'phrase_keywords'    => 'photo::seo.photo_browse_friend_keywords',
        'phrase_heading'     => 'photo::seo.photo_browse_friend_heading',
        'url'                => 'photo/friend',
        'item_type'          => 'photo',
    ],
    [
        'name'               => 'photo.browse_my_pending_photo',
        'phrase_title'       => 'photo::seo.photo_browse_my_pending_title',
        'phrase_description' => 'photo::seo.photo_browse_my_pending_description',
        'phrase_keywords'    => 'photo::seo.photo_browse_my_pending_keywords',
        'phrase_heading'     => 'photo::seo.photo_browse_my_pending_heading',
        'url'                => 'photo/my-pending',
        'item_type'          => 'photo',
    ],
    [
        'name'               => 'photo.browse_my_photo_album',
        'phrase_title'       => 'photo::seo.photo_album_browse_my_title',
        'phrase_description' => 'photo::seo.photo_album_browse_my_description',
        'phrase_keywords'    => 'photo::seo.photo_album_browse_my_keywords',
        'phrase_heading'     => 'photo::seo.photo_album_browse_my_heading',
        'url'                => 'photo/my-albums',
        'item_type'          => 'photo_album',
    ],
    [
        'name'               => 'photo.browse_pending_photo',
        'phrase_title'       => 'photo::seo.photo_browse_pending_title',
        'phrase_description' => 'photo::seo.photo_browse_pending_description',
        'phrase_keywords'    => 'photo::seo.photo_browse_pending_keywords',
        'phrase_heading'     => 'photo::seo.photo_browse_pending_heading',
        'url'                => 'photo/pending',
        'item_type'          => 'photo',
    ],
    [
        'name'               => 'photo.photo',
        'phrase_title'       => 'core::seo.core_search_title',
        'phrase_description' => 'core::seo.core_search_description',
        'phrase_keywords'    => 'core::seo.core_search_keywords',
        'phrase_heading'     => 'core::seo.core_search_heading',
        'url'                => 'photo/search',
        'item_type'          => 'photo',
    ],
    [
        'name'               => 'photo.photo.create',
        'phrase_title'       => 'photo::seo.photo_create_title',
        'phrase_description' => 'photo::seo.photo_create_description',
        'phrase_keywords'    => 'photo::seo.photo_create_keywords',
        'phrase_heading'     => 'photo::seo.photo_create_heading',
        'url'                => 'photo/add',
        'item_type'          => 'photo',
    ],
    [
        'name'               => 'photo.photo.edit',
        'phrase_title'       => 'photo::seo.photo_edit_title',
        'phrase_description' => 'photo::seo.photo_edit_description',
        'phrase_keywords'    => 'photo::seo.photo_edit_keywords',
        'phrase_heading'     => 'photo::seo.photo_edit_heading',
        'url'                => 'photo/edit/{id}',
        'item_type'          => 'photo',
    ],
    [
        'name'               => 'photo.photo.landing',
        'phrase_title'       => 'photo::seo.photo_landing_title',
        'phrase_description' => 'photo::seo.photo_landing_description',
        'phrase_keywords'    => 'photo::seo.photo_landing_keywords',
        'phrase_heading'     => 'photo::seo.photo_landing_heading',
        'url'                => 'photo',
        'item_type'          => 'photo',
    ],
    [
        'name'               => 'photo.photo.my',
        'phrase_title'       => 'photo::seo.photo_browse_my_title',
        'phrase_description' => 'photo::seo.photo_browse_my_description',
        'phrase_keywords'    => 'photo::seo.photo_browse_my_keywords',
        'phrase_heading'     => 'photo::seo.photo_browse_my_heading',
        'url'                => 'photo/my',
        'item_type'          => 'photo',
    ],
    [
        'name'               => 'photo.photo.view_detail',
        'phrase_title'       => 'photo::seo.photo_view_detail_title',
        'phrase_description' => 'photo::seo.photo_view_detail_description',
        'phrase_keywords'    => 'photo::seo.photo_view_detail_keywords',
        'phrase_heading'     => 'photo::seo.photo_view_detail_heading',
        'url'                => 'photo/{id}',
        'item_type'          => 'photo',
    ],
    [
        'name'               => 'photo.photo_album.create',
        'phrase_title'       => 'photo::seo.photo_album_create_title',
        'phrase_description' => 'photo::seo.photo_album_create_description',
        'phrase_keywords'    => 'photo::seo.photo_album_create_keywords',
        'phrase_heading'     => 'photo::seo.photo_album_create_heading',
        'url'                => 'photo/album/add',
        'item_type'          => 'photo_album',
    ],
    [
        'name'               => 'photo.photo_album.edit',
        'phrase_title'       => 'photo::seo.photo_album_edit_title',
        'phrase_description' => 'photo::seo.photo_album_edit_description',
        'phrase_keywords'    => 'photo::seo.photo_album_edit_keywords',
        'phrase_heading'     => 'photo::seo.photo_album_edit_heading',
        'url'                => 'photo/album/edit/{id}',
        'item_type'          => 'photo_album',
    ],
    [
        'name'               => 'photo.photo_album.view_detail',
        'phrase_title'       => 'photo::seo.photo_album_view_detail_title',
        'phrase_description' => 'photo::seo.photo_album_view_detail_description',
        'phrase_keywords'    => 'photo::seo.photo_album_view_detail_keywords',
        'phrase_heading'     => 'photo::seo.photo_album_view_detail_heading',
        'url'                => 'photo/album/{id}',
        'item_type'          => 'photo_album',
    ],
    [
        'name'               => 'user.profile.photo',
        'phrase_title'       => 'photo::seo.user_profile_photo_title',
        'phrase_description' => 'photo::seo.user_profile_photo_desription',
        'phrase_keywords'    => 'photo::seo.user_profile_photo_keywords',
        'phrase_heading'     => 'photo::seo.user_profile_photo_heading',
        'url'                => 'user/{id}/photo',
        'item_type'          => 'user',
    ],
];
