<?php

namespace MetaFox\Form;

// stub: /phpstorm/form_fields.meta.stub

use Illuminate\Support\Facades\Facade;

/**
 * Class Builder.
 *
 * @method static \MetaFox\Photo\Support\Form\Field\AlbumField                album(?string $name=null)
 * @method static \MetaFox\Poll\Support\Form\Field\AttachPoll                 attachPoll(?string $name=null)
 * @method static \MetaFox\Form\Html\Attachment                               attachment(?string $name=null)
 * @method static \MetaFox\Form\Html\Autocomplete                             autocomplete(?string $name=null)
 * @method static \MetaFox\User\Form\Html\AvatarUploadField                   avatarUpload(?string $name=null)
 * @method static \MetaFox\Form\Html\Birthday                                 birthday(?string $name=null)
 * @method static \MetaFox\Form\Html\ButtonField                              button(?string $name=null)
 * @method static \MetaFox\Form\Html\CancelButton                             cancelButton(?string $name=null)
 * @method static \MetaFox\Form\Html\CategoryField                            category(?string $name=null)
 * @method static \MetaFox\Form\Html\CheckboxField                            checkbox(?string $name=null)
 * @method static \MetaFox\Form\Html\CheckboxGroupField                       checkboxGroup(?string $name=null)
 * @method static \MetaFox\Form\Html\ChipField                                chip(?string $name=null)
 * @method static \MetaFox\Form\Html\Choice                                   choice(?string $name=null)
 * @method static \MetaFox\Form\Html\ClearSearch                              clearSearch(?string $name=null)
 * @method static \MetaFox\Form\Html\ClearSearchForm                          clearSearchForm(?string $name=null)
 * @method static \MetaFox\Form\Html\ColorField                               color(?string $name=null)
 * @method static \MetaFox\Localize\Form\Html\CountryCityCode                 countryCity(?string $name=null)
 * @method static \MetaFox\Localize\Form\Html\SearchCountryCityCode           searchCountryCity(?string $name=null)
 * @method static \MetaFox\Form\Html\CountryState                             countryState(?string $name=null)
 * @method static \MetaFox\Localize\Form\Html\CurrencyPricingGroupField       currencyPricingGroup(?string $name=null)
 * @method static \MetaFox\Form\Html\CustomButtonField                        customButton(?string $name=null)
 * @method static \MetaFox\Form\Html\CustomGenders                            customGenders(?string $name=null)
 * @method static \MetaFox\Form\Html\Date                                     date(?string $name=null)
 * @method static \MetaFox\Form\Html\Datetime                                 datetime(?string $name=null)
 * @method static \MetaFox\Form\Html\DescriptionField                         description(?string $name=null)
 * @method static \MetaFox\Form\Html\DividerField                             divider(?string $name=null)
 * @method static \MetaFox\Form\Html\Dropdown                                 dropdown(?string $name=null)
 * @method static \MetaFox\Form\Html\Email                                    email(?string $name=null)
 * @method static \MetaFox\Form\Html\File                                     file(?string $name=null)
 * @method static \MetaFox\Form\Html\FilterCategoryField                      filterCategory(?string $name=null)
 * @method static \MetaFox\Form\Html\FriendPicker                             friendPicker(?string $name=null)
 * @method static \MetaFox\Form\Html\Gender                                   gender(?string $name=null)
 * @method static \MetaFox\Form\Html\Hidden                                   hidden(?string $name=null)
 * @method static \MetaFox\Captcha\Form\Html\HiddenImageCaptchaField          hiddenImageCaptcha(?string $name=null)
 * @method static \MetaFox\Form\Html\LinkField                                htmlLink(?string $name=null)
 * @method static \MetaFox\Captcha\Form\Html\ImageCaptchaField                imageCaptcha(?string $name=null)
 * @method static \MetaFox\Form\InlineEditSection                             inlineEditSection(?string $name=null)
 * @method static \MetaFox\Form\Html\Language                                 language(?string $name=null)
 * @method static \MetaFox\Form\Html\LinkButtonField                          linkButton(?string $name=null)
 * @method static \MetaFox\Form\Html\Location                                 location(?string $name=null)
 * @method static \MetaFox\Form\Html\MultipleLocation                         multipleLocation(?string $name=null)
 * @method static \MetaFox\Group\Support\Form\Html\MembershipQuestionField    membershipQuestion(?string $name=null)
 * @method static \MetaFox\Form\Html\NumberCode                               numberCode(?string $name=null)
 * @method static \MetaFox\Form\Html\Password                                 password(?string $name=null)
 * @method static \MetaFox\Form\Html\PhoneNumberField                         phoneNumber(?string $name=null)
 * @method static \MetaFox\Poll\Form\Html\PollAnswer                          pollAnswer(?string $name=null)
 * @method static \MetaFox\Poll\Form\Html\PollCloseTime                       pollCloseTime(?string $name=null)
 * @method static \MetaFox\Form\Html\PriceField                               price(?string $name=null)
 * @method static \MetaFox\Form\Html\Privacy                                  privacy(?string $name=null)
 * @method static \MetaFox\Form\Html\QrCode                                   qrCode(?string $name=null)
 * @method static \MetaFox\Quiz\Http\Resources\v1\Quiz\Field\QuizQuestion     quizQuestion(?string $name=null)
 * @method static \MetaFox\Form\Html\Radio                                    radio(?string $name=null)
 * @method static \MetaFox\Form\Html\RadioGroupField                          radioGroup(?string $name=null)
 * @method static \MetaFox\Form\Html\RawFileField                             rawFile(?string $name=null)
 * @method static \MetaFox\Captcha\Form\Html\RecaptchaV3Field                 recaptchaV3(?string $name=null)
 * @method static \MetaFox\Form\Html\RichTextEditor                           richTextEditor(?string $name=null)
 * @method static \MetaFox\Form\Html\SearchBoxField                           searchBox(?string $name=null)
 * @method static \MetaFox\Form\Html\IconButtonField                          iconButton(?string $name=null)
 * @method static \MetaFox\Form\Html\SearchSuggestionField                    searchSuggestion(?string $name=null)
 * @method static \MetaFox\Form\Section                                       section(?string $name=null)
 * @method static \MetaFox\Localize\Form\Html\SelectLocale                    selectLocale(?string $name=null)
 * @method static \MetaFox\Log\Support\SelectLogLevelField                    selectLogLevel(?string $name=null)
 * @method static \MetaFox\Mail\Support\SelectMailTransportField              selectMailTransport(?string $name=null)
 * @method static \MetaFox\Core\Form\SelectPackageField                       selectPackage(?string $name=null)
 * @method static \MetaFox\Core\Form\SelectPackageAliasField                  selectPackageAlias(?string $name=null)
 * @method static \MetaFox\Form\Html\SelectResolutionField                    selectResolution(?string $name=null)
 * @method static \MetaFox\Storage\Support\SelectStorageIdField               selectStorageId(?string $name=null)
 * @method static \MetaFox\Form\Html\SimpleCategoryField                      simpleCategory(?string $name=null)
 * @method static \MetaFox\Photo\Support\Form\Field\SimpleUploadPhotosField   simpleUploadPhotos(?string $name=null)
 * @method static \MetaFox\Form\Html\SinglePhotoField                         singlePhoto(?string $name=null)
 * @method static \MetaFox\Form\Html\SingleUpdateInputField                   singleUpdateInput(?string $name=null)
 * @method static \MetaFox\Form\Html\SingleVideoField                         singleVideo(?string $name=null)
 * @method static \MetaFox\Form\Html\SingleAudioField                         singleAudio(?string $name=null)
 * @method static \MetaFox\Form\Html\MultiAudioField                          multiAudio(?string $name=null)
 * @method static \MetaFox\Form\Html\Slug                                     slug(?string $name=null)
 * @method static \MetaFox\Form\Html\Submit                                   submit(?string $name=null)
 * @method static \MetaFox\Form\Html\SwitchField                              switch(?string $name=null)
 * @method static \MetaFox\Form\Html\TagsField                                tags(?string $name=null)
 * @method static \MetaFox\Form\Html\Text                                     text(?string $name=null)
 * @method static \MetaFox\Form\Html\CopyText                                 copyText(?string $name=null)
 * @method static \MetaFox\Form\Html\TextArea                                 textArea(?string $name=null)
 * @method static \MetaFox\Form\Html\Timezone                                 timezone(?string $name=null)
 * @method static \MetaFox\Form\Html\TitleField                               title(?string $name=null)
 * @method static \MetaFox\Form\Html\TypeCategoryField                        typeCategory(?string $name=null)
 * @method static \MetaFox\Form\Html\Typography                               typography(?string $name=null)
 * @method static \MetaFox\Form\Html\DynamicTypography                        dynamicTypography(?string $name=null)
 * @method static \MetaFox\Photo\Support\Form\Field\UploadMultiAlbumItemField uploadMultiAlbumItem(?string $name=null)
 * @method static \MetaFox\Form\Html\UploadMultiPhotoField                    uploadMultiMedia(?string $name=null)
 * @method static \MetaFox\Video\Http\Resources\v1\Video\Fields\VideoUrlField videoUrl(?string $name=null)
 * @method static \MetaFox\Form\Html\ViewMore                                 viewMore(?string $name=null)
 * @method static \MetaFox\Core\Form\YesNoChoice                              yesNoChoice(?string $name=null)
 * @method static \MetaFox\LiveStreaming\Support\Form\Html\MuxPlayer          muxPlayer(?string $name=null)
 * @method static \MetaFox\Form\Html\FacebookLoginButtonField                 facebookLoginButton(?string $name=null)
 * @method static \MetaFox\Form\Html\GoogleLoginButtonField                   googleLoginButton(?string $name=null)
 * @method static array                                                       getFields()
 * @method static array                                                       refresh()
 * @method static string                                                      getCreator(string $name)
 */
class Builder extends Facade
{
    protected static function getFacadeAccessor()
    {
        return 'HtmlFormBuilder';
    }
}
