<?php

/* this is auto generated file */
return [
    [
        'subInfo'  => 'event::phrase.browse_events_you_may_be_interested',
        'menu'     => 'core.dropdownMenu',
        'name'     => 'event',
        'label'    => 'event::phrase.events',
        'ordering' => 13,
        'icon'     => 'ico-calendar',
        'to'       => '/event',
    ],
    [
        'subInfo'  => 'event::phrase.browse_events_you_may_be_interested',
        'menu'     => 'core.primaryMenu',
        'name'     => 'event',
        'label'    => 'event::phrase.events',
        'ordering' => 13,
        'icon'     => 'ico-calendar',
        'to'       => '/event',
    ],
    [
        'tab'      => 'event',
        'showWhen' => [
            'and',
            ['truthy', 'acl.event.event.create'],
            ['truthy', 'item.profile_settings.event_share_events'],
            ['falsy', 'item.is_muted'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'event.event.headerItemActionOnGroupProfileMenu',
        'name'     => 'event',
        'label'    => 'event::phrase.add_new_event',
        'ordering' => 1,
        'to'       => '/event/add?owner_id=:id',
    ],
    [
        'tab'      => 'event',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.event.event.create'],
            ['truthy', 'item.profile_settings.event_share_events'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'event.event.headerItemActionOnPageProfileMenu',
        'name'     => 'event',
        'label'    => 'event::phrase.add_new_event',
        'ordering' => 1,
        'to'       => '/event/add?owner_id=:id',
    ],
    [
        'params' => [
            'interestedEvent' => [
                'removeEntity' => true,
            ],
        ],
        'showWhen' => [
            'and',
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'event.event.interestedMenu',
        'name'     => 'interested',
        'label'    => 'event::phrase.interested',
        'ordering' => 1,
        'value'    => 'interestedEvent',
        'icon'     => 'ico-calendar-star',
    ],
    [
        'color'  => 'primary',
        'params' => [
            'joinEvent' => [
                'removeEntity' => true,
            ],
        ],
        'showWhen' => [
            'and',
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'event.event.interestedMenu',
        'name'     => 'going',
        'label'    => 'event::phrase.going',
        'ordering' => 2,
        'value'    => 'joinEvent',
        'icon'     => 'ico-user3-check-o',
    ],
    [
        'params' => [
            'notInterestedEvent' => [
                'removeEntity' => true,
            ],
        ],
        'showWhen' => [
            'and',
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'event.event.interestedMenu',
        'name'     => 'not_interested',
        'label'    => 'event::phrase.not_interested',
        'ordering' => 3,
        'value'    => 'notInterestedEvent',
        'icon'     => 'ico-calendar-star-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'event::phrase.edit_event',
        'ordering' => 1,
        'value'    => 'editItem',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_approve'],
            ['truthy', 'item.is_pending'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'approve',
        'label'    => 'event::phrase.approve',
        'ordering' => 2,
        'value'    => 'approveItem',
        'icon'     => 'ico-check-circle-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'manage_guest',
        'label'    => 'event::phrase.manage_guest_list',
        'ordering' => 3,
        'value'    => 'event/viewAllGuest',
        'icon'     => 'ico-gear-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_mass_email'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'mass_email_guest',
        'label'    => 'event::phrase.mass_email_guest',
        'ordering' => 4,
        'value'    => 'event/massEmailEvent',
        'icon'     => 'ico-envelope-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['falsy', 'item.is_sponsored_feed'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'event::phrase.sponsor_in_feed',
        'ordering' => 5,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['truthy', 'item.is_sponsored_feed'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'event::phrase.unsponsor_in_feed',
        'ordering' => 6,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['falsy', 'item.is_sponsor'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'sponsor',
        'label'    => 'event::phrase.sponsor_this_item',
        'ordering' => 7,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['truthy', 'item.is_sponsor'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'event::phrase.unsponsor_this_item',
        'ordering' => 8,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 9,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'remove_feature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 10,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'delete',
        'label'    => 'event::phrase.delete',
        'ordering' => 14,
        'value'    => 'deleteItem',
        'icon'     => 'ico-trash',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_pending'],
            ['truthy', 'item.extra.can_invite'],
        ],
        'menu'     => 'event.event.itemInviteMenu',
        'name'     => 'invite_link',
        'label'    => 'event::phrase.generate_invite_link',
        'ordering' => 1,
        'value'    => 'event/generateInviteLink',
        'icon'     => 'ico-link',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_invite'],
        ],
        'menu'     => 'event.event.itemInviteMenu',
        'name'     => 'invites',
        'label'    => 'event::phrase.invite_people_to_come',
        'ordering' => 2,
        'value'    => 'event/invitePeopleToCome',
        'icon'     => 'ico-user-man-plus',
    ],
    [
        'menu'     => 'event.event.manageItemMenu',
        'name'     => 'manage_event',
        'label'    => 'event::phrase.manage_event',
        'ordering' => 1,
        'as'       => 'sidebarHeading',
    ],
    [
        'tab'      => 'general',
        'menu'     => 'event.event.manageItemMenu',
        'name'     => 'general',
        'label'    => 'event::phrase.event_detail',
        'ordering' => 2,
        'icon'     => 'ico-calendar-o',
        'to'       => '/event/manage/:id',
    ],
    [
        'tab'      => 'invite_guest',
        'menu'     => 'event.event.manageItemMenu',
        'name'     => 'invite_guest',
        'label'    => 'event::phrase.invite_guests',
        'ordering' => 3,
        'icon'     => 'ico-hashtag',
        'to'       => '/event/manage/:id/invite',
    ],
    [
        'tab'      => 'guest_list',
        'menu'     => 'event.event.manageItemMenu',
        'name'     => 'guest_list',
        'label'    => 'event::phrase.guest_list',
        'ordering' => 4,
        'icon'     => 'ico-user-man-o',
        'to'       => '/event/manage/:id/guests',
    ],
    [
        'tab'      => 'mass_email',
        'menu'     => 'event.event.manageItemMenu',
        'name'     => 'mass_email',
        'label'    => 'event::phrase.mass_email',
        'ordering' => 5,
        'icon'     => 'ico-user1-two-o',
        'to'       => '/event/manage/:id/mass-email',
    ],
    [
        'tab'      => 'landing',
        'menu'     => 'event.sidebarMenu',
        'name'     => 'landing',
        'label'    => 'event::phrase.home',
        'ordering' => 1,
        'icon'     => 'ico-calendar-o',
        'to'       => '/event',
    ],
    [
        'tab'      => 'all',
        'menu'     => 'event.sidebarMenu',
        'name'     => 'all',
        'label'    => 'event::phrase.all_events',
        'ordering' => 2,
        'icon'     => 'ico-hashtag',
        'to'       => '/event/all',
    ],
    [
        'tab'      => 'hosted',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'event.sidebarMenu',
        'name'     => 'hosted',
        'label'    => 'event::phrase.my_hosting_events',
        'ordering' => 3,
        'icon'     => 'ico-user-man-o',
        'to'       => '/event/hosted',
    ],
    [
        'tab'      => 'my_pending',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['neq', 'session.user.role.id', 1],
        ],
        'menu'     => 'event.sidebarMenu',
        'name'     => 'my_pending',
        'label'    => 'event::phrase.my_pending_events',
        'ordering' => 4,
        'icon'     => 'ico-user1-clock-o',
        'to'       => '/event/my-pending',
    ],
    [
        'tab'      => 'friend',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'event.sidebarMenu',
        'name'     => 'friend',
        'label'    => 'event::phrase.friends_events',
        'ordering' => 5,
        'icon'     => 'ico-user1-two-o',
        'to'       => '/event/friend',
    ],
    [
        'tab'      => 'past',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'event.sidebarMenu',
        'name'     => 'past',
        'label'    => 'event::phrase.past_events',
        'ordering' => 6,
        'icon'     => 'ico-calendar-check-o',
        'to'       => '/event/past',
    ],
    [
        'tab'      => 'invites',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'event.sidebarMenu',
        'name'     => 'invites',
        'label'    => 'event::phrase.event_invites',
        'ordering' => 7,
        'icon'     => 'ico-envelope-o',
        'to'       => '/event/invites',
    ],
    [
        'tab'      => 'pending',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.event.event.approve'],
        ],
        'menu'     => 'event.sidebarMenu',
        'name'     => 'pending',
        'label'    => 'event::phrase.pending_events',
        'ordering' => 8,
        'icon'     => 'ico-clock-o',
        'to'       => '/event/pending',
    ],
    [
        'tab'      => 'add',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.event.event.create'],
        ],
        'buttonProps' => [
            'fullWidth' => true,
            'color'     => 'primary',
            'variant'   => 'contained',
        ],
        'menu'     => 'event.sidebarMenu',
        'name'     => 'add',
        'label'    => 'event::phrase.create_new_event',
        'ordering' => 9,
        'as'       => 'sidebarButton',
        'icon'     => 'ico-plus',
        'to'       => '/event/add',
    ],
    [
        'tab'      => 'event',
        'showWhen' => [
            'or',
            ['eq', 'item.reg_method', '0'],
            [
                'or',
                ['truthy', 'acl.group.group.moderate'],
                ['truthy', 'item.is_member'],
            ],
        ],
        'menu'     => 'group.group.profileMenu',
        'name'     => 'event',
        'label'    => 'event::phrase.events',
        'ordering' => 10,
        'to'       => '/event',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.event.event.view'],
        ],
        'menu'     => 'group.searchWebCategoryMenu',
        'name'     => 'event',
        'label'    => 'event::phrase.event_global_search_label',
        'ordering' => 2,
    ],
    [
        'tab'      => 'event',
        'showWhen' => [
            'and',
            ['truthy', 'acl.event.event.view'],
            ['truthy', 'item.profile_settings.event_view_browse_events'],
        ],
        'menu'     => 'page.page.profileMenu',
        'name'     => 'event',
        'label'    => 'event::phrase.events',
        'ordering' => 10,
        'to'       => '/event',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.event.event.view'],
        ],
        'menu'     => 'search.webCategoryMenu',
        'name'     => 'event',
        'label'    => 'event::phrase.event_global_search_label',
        'ordering' => 4,
        'to'       => '/search/event',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.event.event.view'],
        ],
        'menu'     => 'search.webCategoryOrderingMenu',
        'name'     => 'event',
        'label'    => 'event::phrase.event_global_search_label',
        'ordering' => 5,
    ],
    [
        'tab'      => 'event',
        'showWhen' => [
            'and',
            ['truthy', 'item.profile_menu_settings.event_profile_menu'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'event',
        'label'    => 'event::phrase.events',
        'ordering' => 12,
        'to'       => '/event',
    ],
    [
        'tab'      => 'event',
        'showWhen' => [
            'and',
            ['truthy', 'acl.event.event.create'],
            ['truthy', 'item.is_owner'],
        ],
        'menu'     => 'event.event.headerItemActionOnUserProfileMenu',
        'name'     => 'event',
        'label'    => 'event::phrase.create_new_event',
        'ordering' => 1,
        'to'       => '/event/add?owner_id=:id',
    ],
];
