<?php

/* this is auto generated file */
return [
    [
        'name'         => 'admin.event.browse_category',
        'phrase_title' => 'core::phrase.categories',
        'url'          => 'admincp/event/category/browse',
    ],
    [
        'name'                 => 'admin.event.browse_child_category',
        'phrase_title'         => 'core::phrase.categories',
        'url'                  => 'admincp/event/category/{id}/category/browse',
        'custom_sharing_route' => 1,
    ],
    [
        'name'         => 'admin.event.create_category',
        'phrase_title' => 'core::phrase.add_category',
        'url'          => 'admincp/event/category/create',
    ],
    [
        'name'         => 'admin.event.edit_category',
        'phrase_title' => 'core::phrase.edit_category',
        'url'          => 'admincp/event/category/edit/{id}',
    ],
    [
        'name'         => 'admin.event.event_setting',
        'phrase_title' => 'core::phrase.settings',
        'url'          => 'admincp/event/setting',
    ],
    [
        'name'         => 'admin.event.permissions',
        'phrase_title' => 'core::phrase.permissions',
        'url'          => 'admincp/event/permission',
    ],
    [
        'name'               => 'event.browse_invites_event',
        'phrase_title'       => 'event::seo.browse_invites_event',
        'phrase_description' => 'event::seo.browse_invites_event_desription',
        'phrase_keywords'    => 'event::seo.browse_invites_event_keywords',
        'phrase_heading'     => 'event::seo.browse_invites_event_heading',
        'url'                => 'event/invites',
        'item_type'          => 'event',
    ],
    [
        'name'               => 'event.browse_my_pending_event',
        'phrase_title'       => 'event::seo.event_browse_my_pending_title',
        'phrase_description' => 'event::seo.event_browse_my_pending_description',
        'phrase_keywords'    => 'event::seo.event_browse_my_pending_keywords',
        'phrase_heading'     => 'event::seo.event_browse_my_pending_heading',
        'url'                => 'event/my-pending',
        'item_type'          => 'event',
    ],
    [
        'name'               => 'event.browse_pending_event',
        'phrase_title'       => 'event::seo.event_browse_pending_title',
        'phrase_description' => 'event::seo.event_browse_pending_description',
        'phrase_keywords'    => 'event::seo.event_browse_pending_keywords',
        'phrase_heading'     => 'event::seo.event_browse_pending_heading',
        'url'                => 'event/pending',
        'item_type'          => 'event',
    ],
    [
        'name'               => 'event.event',
        'phrase_title'       => 'core::seo.core_search_title',
        'phrase_description' => 'core::seo.core_search_description',
        'phrase_keywords'    => 'core::seo.core_search_keywords',
        'phrase_heading'     => 'core::seo.core_search_heading',
        'url'                => 'event/search',
        'item_type'          => 'event',
    ],
    [
        'name'               => 'event.event.all',
        'phrase_title'       => 'event::seo.event_browse_all_title',
        'phrase_description' => 'event::seo.event_desription',
        'phrase_keywords'    => 'event::seo.event_keywords',
        'phrase_heading'     => 'event::seo.event_heading',
        'url'                => 'event/all',
        'item_type'          => 'event',
    ],
    [
        'name'               => 'event.event.create',
        'phrase_title'       => 'event::seo.event_create_title',
        'phrase_description' => 'event::seo.event_create_description',
        'phrase_keywords'    => 'event::seo.event_create_keywords',
        'phrase_heading'     => 'event::seo.event_create_heading',
        'url'                => 'event/add',
        'item_type'          => 'event',
    ],
    [
        'name'               => 'event.event.edit',
        'phrase_title'       => 'event::seo.event_edit_title',
        'phrase_description' => 'event::seo.event_edit_description',
        'phrase_keywords'    => 'event::seo.event_edit_keywords',
        'phrase_heading'     => 'event::seo.event_edit_heading',
        'url'                => 'event/edit/{id}',
        'item_type'          => 'event',
    ],
    [
        'name'               => 'event.event.friend',
        'phrase_title'       => 'event::seo.event_browse_friend_title',
        'phrase_description' => 'event::seo.event_desription',
        'phrase_keywords'    => 'event::seo.event_keywords',
        'phrase_heading'     => 'event::seo.event_heading',
        'url'                => 'event/friend',
        'item_type'          => 'event',
    ],
    [
        'name'               => 'event.event.hosted',
        'phrase_title'       => 'event::seo.event_hosted_title',
        'phrase_description' => 'event::seo.event_hosted_description',
        'phrase_keywords'    => 'event::seo.event_hosted_keywords',
        'phrase_heading'     => 'event::seo.event_hosted_heading',
        'url'                => 'event/hosted',
        'item_type'          => 'event',
    ],
    [
        'name'               => 'event.event.landing',
        'phrase_title'       => 'event::seo.event_landing_title',
        'phrase_description' => 'event::seo.event_landing_description',
        'phrase_keywords'    => 'event::seo.event_landing_keywords',
        'phrase_heading'     => 'event::seo.event_landing_heading',
        'url'                => 'event',
        'item_type'          => 'event',
    ],
    [
        'name'               => 'event.event.past',
        'phrase_title'       => 'event::seo.event_past_title',
        'phrase_description' => 'event::seo.event_past_description',
        'phrase_keywords'    => 'event::seo.event_past_keywords',
        'phrase_heading'     => 'event::seo.event_past_heading',
        'url'                => 'event/past',
        'item_type'          => 'event',
    ],
    [
        'name'               => 'event.event.view_detail',
        'phrase_title'       => 'event::seo.event_view_detail_title',
        'phrase_description' => 'event::seo.event_view_detail_description',
        'phrase_keywords'    => 'event::seo.event_view_detail_keywords',
        'phrase_heading'     => 'event::seo.event_view_detail_heading',
        'url'                => 'event/{id}',
        'item_type'          => 'event',
    ],
    [
        'name'               => 'group.profile.event',
        'phrase_title'       => 'event::seo.group_profile_event_title',
        'phrase_description' => 'event::seo.group_profile_event_description',
        'phrase_keywords'    => 'event::seo.group_profile_event_keywords',
        'phrase_heading'     => 'event::seo.group_profile_event_heading',
        'url'                => 'group/{id}/event',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'page.profile.event',
        'phrase_title'       => 'event::seo.page_profile_event_title',
        'phrase_description' => 'event::seo.page_profile_event_description',
        'phrase_keywords'    => 'event::seo.page_profile_event_keywords',
        'phrase_heading'     => 'event::seo.page_profile_event_heading',
        'url'                => 'page/{id}/event',
        'item_type'          => 'page',
    ],
    [
        'name'               => 'user.profile.event',
        'phrase_title'       => 'event::seo.user_profile_event_title',
        'phrase_description' => 'event::seo.user_profile_event_desription',
        'phrase_keywords'    => 'event::seo.user_profile_event_keywords',
        'phrase_heading'     => 'event::seo.user_profile_event_heading',
        'url'                => 'user/{id}/event',
        'item_type'          => 'user',
    ],
];
