<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Announcement\\Http\\Resources\\v1\\Announcement\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'announcement',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Announcement\\Models\\Announcement',
        'type'       => 'entity',
        'name'       => 'announcement',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Announcements',
    ],
    [
        'driver'     => 'MetaFox\\Announcement\\Models\\Hidden',
        'type'       => 'entity',
        'name'       => 'announcement_hidden',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Announcement\\Models\\Style',
        'type'       => 'entity',
        'name'       => 'announcement_style',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Announcement\\Models\\AnnouncementView',
        'type'       => 'entity',
        'name'       => 'announcement_view',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Announcement\\Models\\Announcement',
        'type'       => 'entity-content',
        'name'       => 'announcement',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Announcements',
    ],
    [
        'driver'     => 'MetaFox\\Announcement\\Http\\Resources\\v1\\Announcement\\Admin\\SearchAnnouncementForm',
        'type'       => 'form',
        'name'       => 'announcement.search',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Announcement\\Http\\Resources\\v1\\Announcement\\Admin\\StoreAnnouncementForm',
        'type'       => 'form',
        'name'       => 'announcement.store',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Announcement\\Http\\Resources\\v1\\Announcement\\Admin\\UpdateAnnouncementForm',
        'type'       => 'form',
        'name'       => 'announcement.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Announcement\\Http\\Resources\\v1\\Announcement\\AnnouncementItemCollection',
        'type'       => 'json-collection',
        'name'       => 'announcement.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Announcement\\Http\\Resources\\v1\\AnnouncementView\\AnnouncementViewItemCollection',
        'type'       => 'json-collection',
        'name'       => 'announcement_view.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Announcement\\Http\\Resources\\v1\\Announcement\\Admin\\AnnouncementDetail',
        'type'       => 'json-resource',
        'name'       => 'announcement.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Announcement\\Http\\Resources\\v1\\Announcement\\AnnouncementItem',
        'type'       => 'json-resource',
        'name'       => 'announcement.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Announcement\\Http\\Resources\\v1\\AnnouncementView\\AnnouncementViewDetail',
        'type'       => 'json-resource',
        'name'       => 'announcement_view.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Announcement\\Http\\Resources\\v1\\AnnouncementView\\AnnouncementViewItem',
        'type'       => 'json-resource',
        'name'       => 'announcement_view.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Announcement\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'announcement',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Announcement\\Policies\\AnnouncementPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Announcement\\Models\\Announcement',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Announcement\\Http\\Resources\\v1\\Announcement\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'announcement',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Announcement\\Http\\Resources\\v1\\Announcement\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'announcement',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
];
