<?php

/* this is auto generated file */
return [
    [
        'name'         => 'admin.page.browse_category',
        'phrase_title' => 'core::phrase.categories',
        'url'          => 'admincp/page/category/browse',
    ],
    [
        'name'                 => 'admin.page.browse_child_category',
        'phrase_title'         => 'core::phrase.categories',
        'url'                  => 'admincp/page/category/{id}/category/browse',
        'custom_sharing_route' => 1,
    ],
    [
        'name'         => 'admin.page.browse_claim',
        'phrase_title' => 'page::phrase.manage_claims',
        'url'          => 'admincp/page/claim/browse',
    ],
    [
        'name'         => 'admin.page.create_category',
        'phrase_title' => 'core::phrase.add_category',
        'url'          => 'admincp/page/category/create',
    ],
    [
        'name'         => 'admin.page.edit_category',
        'phrase_title' => 'core::phrase.edit_category',
        'url'          => 'admincp/page/category/edit/{id}',
        'item_type'    => 'page_category',
    ],
    [
        'name'         => 'admin.page.page_setting',
        'phrase_title' => 'core::phrase.settings',
        'url'          => 'admincp/page/setting',
    ],
    [
        'name'         => 'admin.page.permissions',
        'phrase_title' => 'core::phrase.permissions',
        'url'          => 'admincp/page/permission',
    ],
    [
        'name'               => 'page.browse_all_page',
        'phrase_title'       => 'page::seo.page_browse_all_title',
        'phrase_description' => 'page::seo.page_browse_all_description',
        'phrase_keywords'    => 'page::seo.page_browse_all_keywords',
        'phrase_heading'     => 'page::seo.page_browse_all_heading',
        'url'                => 'page/all',
        'item_type'          => 'page',
    ],
    [
        'name'               => 'page.browse_friend_page',
        'phrase_title'       => 'page::seo.page_browse_friend_title',
        'phrase_description' => 'page::seo.page_browse_friend_description',
        'phrase_keywords'    => 'page::seo.page_browse_friend_keywords',
        'phrase_heading'     => 'page::seo.page_browse_friend_heading',
        'url'                => 'page/friend',
        'item_type'          => 'page',
    ],
    [
        'name'               => 'page.browse_invited_page',
        'phrase_title'       => 'page::seo.page_invites_title',
        'phrase_description' => 'page::seo.page_invites_description',
        'phrase_keywords'    => 'page::seo.page_invites_keywords',
        'phrase_heading'     => 'page::seo.page_invites_heading',
        'url'                => 'page/invited',
        'item_type'          => 'page',
    ],
    [
        'name'               => 'page.browse_liked_page',
        'phrase_title'       => 'page::seo.page_browse_liked_title',
        'phrase_description' => 'page::seo.page_browse_liked_description',
        'phrase_keywords'    => 'page::seo.page_browse_liked_keywords',
        'phrase_heading'     => 'page::seo.page_browse_liked_heading',
        'url'                => 'page/liked',
        'item_type'          => 'page',
    ],
    [
        'name'               => 'page.browse_my_pending_page',
        'phrase_title'       => 'page::seo.page_browse_my_pending_title',
        'phrase_description' => 'page::seo.page_browse_my_pending_description',
        'phrase_keywords'    => 'page::seo.page_browse_my_pending_keywords',
        'phrase_heading'     => 'page::seo.page_browse_my_pending_heading',
        'url'                => 'page/my-pending',
        'item_type'          => 'page',
    ],
    [
        'name'               => 'page.browse_pending_page',
        'phrase_title'       => 'page::seo.browse_pending_page_title',
        'phrase_description' => 'page::seo.browse_pending_page_description',
        'phrase_keywords'    => 'page::seo.browse_pending_page_keywords',
        'phrase_heading'     => 'page::seo.browse_pending_page_heading',
        'url'                => 'page/pending',
        'item_type'          => 'page',
    ],
    [
        'name'               => 'page.page',
        'phrase_title'       => 'core::seo.core_search_title',
        'phrase_description' => 'core::seo.core_search_description',
        'phrase_keywords'    => 'core::seo.core_search_keywords',
        'phrase_heading'     => 'core::seo.core_search_heading',
        'url'                => 'page/search',
        'item_type'          => 'page',
    ],
    [
        'name'               => 'page.page.about',
        'phrase_title'       => 'page::seo.page_about_title',
        'phrase_description' => 'page::seo.page_about_description',
        'phrase_keywords'    => 'page::seo.page_about_keywords',
        'phrase_heading'     => 'page::seo.page_about_my_heading',
        'url'                => 'page/settings/{id}/about',
        'item_type'          => 'page',
    ],
    [
        'name'               => 'page.page.chat',
        'phrase_title'       => 'page::seo.page_chat_title',
        'phrase_description' => 'page::seo.page_chat_description',
        'phrase_keywords'    => 'page::seo.page_chat_keywords',
        'phrase_heading'     => 'page::seo.page_chat_heading',
        'url'                => 'page/settings/{id}/chat',
        'item_type'          => 'page',
    ],
    [
        'name'               => 'page.page.create',
        'phrase_title'       => 'page::seo.page_create_title',
        'phrase_description' => 'page::seo.page_create_description',
        'phrase_keywords'    => 'page::seo.page_create_keywords',
        'phrase_heading'     => 'page::seo.page_create_heading',
        'url'                => 'page/add',
        'item_type'          => 'page',
    ],
    [
        'name'               => 'page.page.info',
        'phrase_title'       => 'page::seo.page_title',
        'phrase_description' => 'page::seo.page_description',
        'phrase_keywords'    => 'page::seo.page_keywords',
        'phrase_heading'     => 'page::seo.page_heading',
        'url'                => 'page/settings/{id}',
        'item_type'          => 'page',
    ],
    [
        'name'               => 'page.page.landing',
        'phrase_title'       => 'page::seo.page_landing_title',
        'phrase_description' => 'page::seo.page_landing_description',
        'phrase_keywords'    => 'page::seo.page_landing_keywords',
        'phrase_heading'     => 'page::seo.page_landing_heading',
        'url'                => 'page',
        'item_type'          => 'page',
    ],
    [
        'name'               => 'page.page.menu',
        'phrase_title'       => 'page::seo.page_menu_title',
        'phrase_description' => 'page::seo.page_menu_description',
        'phrase_keywords'    => 'page::seo.page_menu_keywords',
        'phrase_heading'     => 'page::seo.page_menu_heading',
        'url'                => 'page/settings/{id}/menu',
        'item_type'          => 'page',
    ],
    [
        'name'               => 'page.page.my',
        'phrase_title'       => 'page::seo.page_browse_my_title',
        'phrase_description' => 'page::seo.page_browse_my_description',
        'phrase_keywords'    => 'page::seo.page_browse_my_keywords',
        'phrase_heading'     => 'page::seo.page_browse_my_heading',
        'url'                => 'page/my',
        'item_type'          => 'page',
    ],
    [
        'name'               => 'page.page.permissions',
        'phrase_title'       => 'page::seo.page_permissions_title',
        'phrase_description' => 'page::seo.page_permissions_description',
        'phrase_keywords'    => 'page::seo.page_permissions_keywords',
        'phrase_heading'     => 'page::seo.page_permissions_heading',
        'url'                => 'page/settings/{id}/permissions',
        'item_type'          => 'page',
    ],
    [
        'name'               => 'page.profile.about',
        'phrase_title'       => 'page::seo.page_profile_about_title',
        'phrase_description' => 'page::seo.page_profile_about_description',
        'phrase_keywords'    => 'page::seo.page_profile_about_keywords',
        'phrase_heading'     => 'page::seo.page_profile_about_heading',
        'url'                => 'page/{id}/about',
        'item_type'          => 'page',
    ],
    [
        'name'               => 'page.profile.home',
        'phrase_title'       => 'page::seo.page_profile_home_title',
        'phrase_description' => 'page::seo.page_profile_home_description',
        'phrase_keywords'    => 'page::seo.page_profile_home_keywords',
        'phrase_heading'     => 'page::seo.page_profile_home_heading',
        'url'                => 'page/{id}/{tab?}',
        'item_type'          => 'page',
    ],
    [
        'name'               => 'page.profile.member',
        'phrase_title'       => 'page::seo.page_profile_member_title',
        'phrase_description' => 'page::seo.page_profile_member_description',
        'phrase_keywords'    => 'page::seo.page_profile_member_keywords',
        'phrase_heading'     => 'page::seo.page_profile_member_heading',
        'url'                => 'page/{id}/member',
        'item_type'          => 'page',
    ],
    [
        'name'               => 'page.profile.search',
        'phrase_title'       => 'page::seo.page_search_in_profile',
        'phrase_description' => 'page::seo.page_search_in_profile_description',
        'phrase_keywords'    => 'page::seo.page_search_in_profile_keywords',
        'phrase_heading'     => 'page::seo.page_search_in_profile_heading',
        'url'                => 'page/search/{id}',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'user.profile.page',
        'phrase_title'       => 'page::seo.user_profile_page_title',
        'phrase_description' => 'page::seo.user_profile_page_desription',
        'phrase_keywords'    => 'page::seo.user_profile_page_keywords',
        'phrase_heading'     => 'page::seo.user_profile_page_heading',
        'url'                => 'user/{id}/page',
        'item_type'          => 'user',
    ],
];
