<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Quiz\\Models\\Quiz',
        'type'       => 'entity',
        'name'       => 'quiz',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Quizzes',
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Models\\Answer',
        'type'       => 'entity',
        'name'       => 'quiz_answer',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Models\\PlayedResult',
        'type'       => 'entity',
        'name'       => 'quiz_played_result',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Models\\Question',
        'type'       => 'entity',
        'name'       => 'quiz_question',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Models\\Result',
        'type'       => 'entity',
        'name'       => 'quiz_result',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Models\\ResultDetail',
        'type'       => 'entity',
        'name'       => 'quiz_result_item',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Models\\Quiz',
        'type'       => 'entity-content',
        'name'       => 'quiz',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Quizzes',
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Http\\Resources\\v1\\Quiz\\EditQuizMobileForm',
        'type'       => 'form',
        'name'       => 'quiz.quiz.edit',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Http\\Resources\\v1\\Quiz\\CreateQuizMobileForm',
        'type'       => 'form',
        'name'       => 'quiz.quiz.store',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Http\\Resources\\v1\\Quiz\\SearchQuizMobileForm',
        'type'       => 'form',
        'name'       => 'quiz.search',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Http\\Resources\\v1\\Quiz\\SearchQuizForm',
        'type'       => 'form',
        'name'       => 'quiz.search',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Http\\Resources\\v1\\Quiz\\CreateQuizForm',
        'type'       => 'form',
        'name'       => 'quiz.store',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Http\\Resources\\v1\\Quiz\\EditQuizForm',
        'type'       => 'form',
        'name'       => 'quiz.update',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Http\\Resources\\v1\\Quiz\\Field\\QuizQuestion',
        'type'       => 'form-field',
        'name'       => 'quizQuestion',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Http\\Resources\\v1\\Quiz\\Admin\\SiteSettingForm',
        'type'       => 'form-settings',
        'name'       => 'quiz',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Http\\Resources\\v1\\Answer\\AnswerItemCollection',
        'type'       => 'json-collection',
        'name'       => 'quiz_answer.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Http\\Resources\\v1\\Quiz\\QuizEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'quiz.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Http\\Resources\\v1\\Quiz\\QuizItemCollection',
        'type'       => 'json-collection',
        'name'       => 'quiz.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Http\\Resources\\v1\\Question\\QuestionItemCollection',
        'type'       => 'json-collection',
        'name'       => 'quiz_question.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Http\\Resources\\v1\\Result\\ResultItemCollection',
        'type'       => 'json-collection',
        'name'       => 'quiz_result.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Http\\Resources\\v1\\ResultDetail\\ResultDetailItemCollection',
        'type'       => 'json-collection',
        'name'       => 'quiz_result_item.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Http\\Resources\\v1\\Answer\\AnswerItem',
        'type'       => 'json-resource',
        'name'       => 'quiz_answer.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Http\\Resources\\v1\\Quiz\\QuizDetail',
        'type'       => 'json-resource',
        'name'       => 'quiz.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Http\\Resources\\v1\\Quiz\\QuizEmbed',
        'type'       => 'json-resource',
        'name'       => 'quiz.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Http\\Resources\\v1\\Quiz\\QuizItem',
        'type'       => 'json-resource',
        'name'       => 'quiz.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Http\\Resources\\v1\\Question\\QuestionItem',
        'type'       => 'json-resource',
        'name'       => 'quiz_question.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Http\\Resources\\v1\\Result\\ResultDetail',
        'type'       => 'json-resource',
        'name'       => 'quiz_result.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Http\\Resources\\v1\\Result\\ResultItem',
        'type'       => 'json-resource',
        'name'       => 'quiz_result.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Http\\Resources\\v1\\ResultDetail\\ResultDetailItem',
        'type'       => 'json-resource',
        'name'       => 'quiz_result_item.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'quiz',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Policies\\QuizPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Quiz\\Models\\Quiz',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Http\\Resources\\v1\\Quiz\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'quiz',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Quiz\\Http\\Resources\\v1\\Quiz\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'quiz',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
];
