<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointPackage\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'activitypoint.package',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PackageTransaction\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'activitypoint.package_transaction',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointSetting\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'activitypoint.setting',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointStatistic\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'activitypoint.statistic',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointTransaction\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'activitypoint.transaction',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver' => 'MetaFox\\ActivityPoint\\Models\\PointPackage',
        'type'   => 'entity',
        'name'   => 'activitypoint_package',
    ],
    [
        'driver' => 'MetaFox\\ActivityPoint\\Models\\PackagePurchase',
        'type'   => 'entity',
        'name'   => 'activitypoint_package_purchase',
    ],
    [
        'driver' => 'MetaFox\\ActivityPoint\\Models\\PointSetting',
        'type'   => 'entity',
        'name'   => 'activitypoint_setting',
    ],
    [
        'driver' => 'MetaFox\\ActivityPoint\\Models\\PointStatistic',
        'type'   => 'entity',
        'name'   => 'activitypoint_statistic',
    ],
    [
        'driver' => 'MetaFox\\ActivityPoint\\Models\\PointTransaction',
        'type'   => 'entity',
        'name'   => 'activitypoint_transaction',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointStatistic\\Admin\\AdjustPointStatisticForm',
        'type'       => 'form',
        'name'       => 'activitypoint.adjust',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\Gateway\\Admin\\GatewayForm',
        'type'       => 'form',
        'name'       => 'activitypoint.gateway.form',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\ActivityPoint\\GiftActivityPointMobileForm',
        'type'       => 'form',
        'name'       => 'activitypoint.gift',
        'version'    => 'v1',
        'resolution' => 'mobile',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\ActivityPoint\\GiftActivityPointForm',
        'type'       => 'form',
        'name'       => 'activitypoint.gift',
        'version'    => 'v1',
        'resolution' => 'web',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointPackage\\PurchasePointPackageForm',
        'type'       => 'form',
        'name'       => 'activitypoint_package.purchase',
        'version'    => 'v1',
        'resolution' => 'web',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointPackage\\Admin\\SearchPointPackageForm',
        'type'       => 'form',
        'name'       => 'activitypoint_package.search',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointPackage\\Admin\\StorePointPackageForm',
        'type'       => 'form',
        'name'       => 'activitypoint_package.store',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointPackage\\Admin\\UpdatePointPackageForm',
        'type'       => 'form',
        'name'       => 'activitypoint_package.update',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointSetting\\Admin\\SearchPointSettingForm',
        'type'       => 'form',
        'name'       => 'activitypoint_setting.search',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointSetting\\Admin\\SearchPointSettingForm',
        'type'       => 'form',
        'name'       => 'activitypoint_setting.search.admin',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointSetting\\Admin\\UpdatePointSettingForm',
        'type'       => 'form',
        'name'       => 'activitypoint_setting.update',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointStatistic\\Admin\\AdjustPointStatisticForm',
        'type'       => 'form',
        'name'       => 'activitypoint_statistic.adjust',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointStatistic\\Admin\\MassAdjustPointStatisticForm',
        'type'       => 'form',
        'name'       => 'activitypoint_statistic.mass_adjust',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointStatistic\\Admin\\SearchPointStatisticForm',
        'type'       => 'form',
        'name'       => 'activitypoint_statistic.search.admin',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointTransaction\\SearchPointTransactionMobileForm',
        'type'       => 'form',
        'name'       => 'activitypoint_transaction.search',
        'version'    => 'v1',
        'resolution' => 'mobile',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointTransaction\\SearchPointTransactionForm',
        'type'       => 'form',
        'name'       => 'activitypoint_transaction.search',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_preload' => 1,
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointTransaction\\Admin\\SearchPointTransactionForm',
        'type'       => 'form',
        'name'       => 'activitypoint_transaction.search.admin',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PackageTransaction\\SearchPackageTransactionForm',
        'type'       => 'form',
        'name'       => 'package_transaction.search',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_preload' => 1,
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'       => 'form-settings',
        'name'       => 'activitypoint',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'core::phrase.settings',
        'url'        => '/admincp/activitypoint/setting',
    ],
    [
        'driver'  => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointPackage\\PointPackageItemCollection',
        'type'    => 'json-collection',
        'name'    => 'activitypoint_package.item',
        'version' => 'v1',
        'title'   => '',
    ],
    [
        'driver'  => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointSetting\\Admin\\PointSettingItemCollection',
        'type'    => 'json-collection',
        'name'    => 'activitypoint_setting.item',
        'version' => 'v1',
        'title'   => '',
    ],
    [
        'driver'  => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointStatistic\\Admin\\PointStatisticItemCollection',
        'type'    => 'json-collection',
        'name'    => 'activitypoint_statistic.item',
        'version' => 'v1',
        'title'   => '',
    ],
    [
        'driver'  => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointTransaction\\PointTransactionItemCollection',
        'type'    => 'json-collection',
        'name'    => 'activitypoint_transaction.item',
        'version' => 'v1',
        'title'   => '',
    ],
    [
        'driver'  => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointPackage\\PointPackageDetail',
        'type'    => 'json-resource',
        'name'    => 'activitypoint_package.detail',
        'version' => 'v1',
        'title'   => '',
    ],
    [
        'driver'  => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointPackage\\Admin\\PointPackageItem',
        'type'    => 'json-resource',
        'name'    => 'activitypoint_package.item',
        'version' => 'v1',
        'title'   => '',
    ],
    [
        'driver'  => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointSetting\\PointSettingByModule',
        'type'    => 'json-resource',
        'name'    => 'activitypoint_setting.by_module',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointSetting\\Admin\\PointSettingDetail',
        'type'    => 'json-resource',
        'name'    => 'activitypoint_setting.detail',
        'version' => 'v1',
        'title'   => '',
    ],
    [
        'driver'  => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointSetting\\PointSettingItem',
        'type'    => 'json-resource',
        'name'    => 'activitypoint_setting.item',
        'version' => 'v1',
        'title'   => '',
    ],
    [
        'driver'  => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointStatistic\\PointStatisticDetail',
        'type'    => 'json-resource',
        'name'    => 'activitypoint_statistic.detail',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointStatistic\\Admin\\PointStatisticItem',
        'type'    => 'json-resource',
        'name'    => 'activitypoint_statistic.item',
        'version' => 'v1',
        'title'   => '',
    ],
    [
        'driver'  => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointTransaction\\PointTransactionDetail',
        'type'    => 'json-resource',
        'name'    => 'activitypoint_transaction.detail',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointTransaction\\PointTransactionItem',
        'type'    => 'json-resource',
        'name'    => 'activitypoint_transaction.item',
        'version' => 'v1',
        'title'   => '',
    ],
    [
        'driver'  => 'MetaFox\\ActivityPoint\\Notifications\\AdjustPointsNotification',
        'type'    => 'notification',
        'name'    => 'adjust_points',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PackageSetting',
        'type'    => 'package-setting',
        'name'    => 'activitypoint',
        'version' => 'v1',
    ],
    [
        'driver' => 'MetaFox\\ActivityPoint\\Policies\\PointSettingPolicy',
        'type'   => 'policy-resource',
        'name'   => 'MetaFox\\ActivityPoint\\Models\\PointSetting',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\ActivityPoint\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'activitypoint',
        'version'    => 'v1',
        'resolution' => 'mobile',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointPackage\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'activitypoint_package',
        'version'    => 'v1',
        'resolution' => 'mobile',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointSetting\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'activitypoint_setting',
        'version'    => 'v1',
        'resolution' => 'mobile',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointTransaction\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'activitypoint_transaction',
        'version'    => 'v1',
        'resolution' => 'mobile',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\ActivityPoint\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'activitypoint',
        'version'    => 'v1',
        'resolution' => 'web',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointPackage\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'activitypoint_package',
        'version'    => 'v1',
        'resolution' => 'web',
        'title'      => '',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointPackage\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'activitypoint_package',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => '',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointSetting\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'activitypoint_setting',
        'version'    => 'v1',
        'resolution' => 'web',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PointTransaction\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'activitypoint_transaction',
        'version'    => 'v1',
        'resolution' => 'web',
    ],
    [
        'driver'     => 'MetaFox\\ActivityPoint\\Http\\Resources\\v1\\PackageTransaction\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'package_transaction',
        'version'    => 'v1',
        'resolution' => 'web',
    ],
];
