<?php

namespace MetaFox\Forum\Http\Resources\v1\Forum;

use MetaFox\Forum\Models\Forum as Model;
use MetaFox\Forum\Policies\ForumPolicy;

/**
 * Class GroupItem.
 * @property Model $resource
 * @SuppressWarnings(PHPMD.UnusedFormalParameter)
 */
class ForumEmbed extends ForumItem
{
    public function toArray($request): array
    {
        if (!policy_check(ForumPolicy::class, 'view', user(), $this->resource)) {
            return [];
        }

        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}
