<?php

/* this is auto generated file */
return [
    [
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'localization',
        'name'        => 'localization_settings',
        'label'       => 'core::phrase.settings',
        'ordering'    => 1,
        'to'          => '/admincp/localize/setting',
    ],
    [
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'localization',
        'name'        => 'countries',
        'label'       => 'core::phrase.countries',
        'ordering'    => 2,
        'to'          => '/admincp/localize/country/browse',
    ],
    [
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'localization',
        'name'        => 'currencies',
        'label'       => 'core::phrase.currencies',
        'ordering'    => 3,
        'to'          => '/admincp/localize/currency/browse',
    ],
    [
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'localization',
        'name'        => 'languages',
        'label'       => 'core::phrase.languages',
        'ordering'    => 4,
        'to'          => '/admincp/localize/language/browse',
    ],
    [
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'localization',
        'name'        => 'missing_phrases',
        'label'       => 'localize::phrase.missing_phrases',
        'ordering'    => 5,
        'to'          => '/admincp/localize/phrase/browse/missing',
    ],
    [
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'localization',
        'name'        => 'phrases',
        'label'       => 'localize::phrase.phrases',
        'ordering'    => 6,
        'to'          => '/admincp/localize/phrase/browse',
    ],
    [
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'localization',
        'name'        => 'time_zones',
        'label'       => 'core::phrase.time_zones',
        'ordering'    => 7,
        'to'          => '/admincp/localize/timezone/browse',
        'is_deleted'  => 1,
    ],
    [
        'menu'     => 'localize.admin',
        'name'     => 'settings',
        'label'    => 'core::phrase.settings',
        'ordering' => 1,
        'to'       => '/admincp/localize/setting',
    ],
    [
        'menu'     => 'localize.admin',
        'name'     => 'country',
        'label'    => 'localize::phrase.countries',
        'ordering' => 2,
        'to'       => '/admincp/localize/country/browse',
    ],
    [
        'menu'     => 'localize.admin',
        'name'     => 'currency',
        'label'    => 'localize::phrase.currencies',
        'ordering' => 3,
        'to'       => '/admincp/localize/currency/browse',
    ],
    [
        'menu'     => 'localize.admin',
        'name'     => 'add_currency',
        'label'    => 'localize::currency.add_new_currency',
        'ordering' => 4,
        'to'       => '/admincp/localize/currency/create',
    ],
    [
        'menu'     => 'localize.admin',
        'name'     => 'language',
        'label'    => 'localize::phrase.languages',
        'ordering' => 5,
        'to'       => '/admincp/localize/language/browse',
    ],
    [
        'menu'     => 'localize.admin',
        'name'     => 'new_language',
        'label'    => 'app::phrase.create_language_package',
        'ordering' => 6,
        'to'       => '/admincp/localize/language/create',
    ],
    [
        'menu'     => 'localize.admin',
        'name'     => 'phrases',
        'label'    => 'localize::phrase.phrases',
        'ordering' => 7,
        'to'       => '/admincp/localize/phrase/browse',
    ],
    [
        'menu'     => 'localize.admin',
        'name'     => 'missing',
        'label'    => 'localize::phrase.missing_phrases',
        'ordering' => 8,
        'to'       => '/admincp/localize/phrase/browse/missing',
    ],
    [
        'menu'       => 'localize.admin',
        'name'       => 'timezone',
        'label'      => 'core::phrase.time_zones',
        'ordering'   => 9,
        'to'         => '/admincp/localize/timezone/browse',
        'is_deleted' => 1,
    ],
    [
        'menu'       => 'localize.admin',
        'name'       => 'import_translation',
        'label'      => 'localize::phrase.import_phrases',
        'ordering'   => 10,
        'to'         => '/admincp/localize/phrase/form-import',
        'is_deleted' => 1,
        'is_active'  => 0,
    ],
];
