<?php

/* this is auto generated file */
return [
    [
        'tab'      => 'quiz',
        'showWhen' => [
            'or',
            ['eq', 'item.reg_method', '0'],
            ['truthy', 'item.is_member'],
        ],
        'menu'     => 'group.group.profileMenu',
        'name'     => 'quiz',
        'label'    => 'quiz::phrase.quizzes',
        'ordering' => 7,
        'to'       => '/quiz',
    ],
    [
        'tab'      => 'quiz',
        'menu'     => 'page.page.profileMenu',
        'name'     => 'quiz',
        'label'    => 'quiz::phrase.quizzes',
        'ordering' => 7,
        'to'       => '/quiz',
    ],
    [
        'menu'     => 'quiz.quiz.filter_menu',
        'name'     => 'all',
        'label'    => 'core::phrase.when.all',
        'ordering' => 1,
        'value'    => 'all',
    ],
    [
        'menu'     => 'quiz.quiz.filter_menu',
        'name'     => 'this_month',
        'label'    => 'core::phrase.when.this_month',
        'ordering' => 2,
        'value'    => 'this_month',
    ],
    [
        'menu'     => 'quiz.quiz.filter_menu',
        'name'     => 'this_week',
        'label'    => 'core::phrase.when.this_week',
        'ordering' => 3,
        'value'    => 'this_week',
    ],
    [
        'menu'     => 'quiz.quiz.filter_menu',
        'name'     => 'today',
        'label'    => 'core::phrase.when.today',
        'ordering' => 4,
        'value'    => 'today',
    ],
    [
        'tab'      => 'quiz',
        'showWhen' => [
            'and',
            ['truthy', 'acl.quiz.quiz.create'],
            ['truthy', 'item.profile_settings.quiz_share_quizzes'],
            ['falsy', 'item.is_muted'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'quiz.quiz.headerItemActionOnGroupProfileMenu',
        'name'     => 'quiz',
        'label'    => 'quiz::phrase.add_new_quiz',
        'ordering' => 1,
        'to'       => '/quiz/add?owner_id=:id',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'quiz::phrase.edit',
        'ordering' => 1,
        'value'    => 'editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['falsy', 'item.is_sponsored_feed'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'quiz::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'sponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['truthy', 'item.is_sponsored_feed'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'unsponsor_in_feed',
        'label'    => 'quiz::phrase.unsponsor_in_feed',
        'ordering' => 4,
        'value'    => 'unsponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['falsy', 'item.is_sponsor'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'sponsor',
        'label'    => 'quiz::phrase.sponsor_this_item',
        'ordering' => 5,
        'value'    => 'sponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['truthy', 'item.is_sponsor'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'unsponsor',
        'label'    => 'quiz::phrase.unsponsor_this_item',
        'ordering' => 6,
        'value'    => 'unsponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'unfeature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'approve',
        'label'    => 'quiz::phrase.approve',
        'ordering' => 11,
        'value'    => 'approveItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'style'     => 'danger',
        'menu'      => 'quiz.quiz.itemActionMenu',
        'name'      => 'delete',
        'label'     => 'quiz::phrase.delete',
        'ordering'  => 12,
        'value'     => 'deleteItem',
    ],
    [
        'menu'     => 'quiz.quiz.sort_menu',
        'name'     => 'latest',
        'label'    => 'core::phrase.sort.recent',
        'ordering' => 1,
        'value'    => 'latest',
    ],
    [
        'menu'     => 'quiz.quiz.sort_menu',
        'name'     => 'most_viewed',
        'label'    => 'core::phrase.sort.most_viewed',
        'ordering' => 2,
        'value'    => 'most_viewed',
    ],
    [
        'menu'     => 'quiz.quiz.sort_menu',
        'name'     => 'most_liked',
        'label'    => 'core::phrase.sort.most_liked',
        'ordering' => 3,
        'value'    => 'most_liked',
    ],
    [
        'menu'     => 'quiz.quiz.sort_menu',
        'name'     => 'most_discussed',
        'label'    => 'core::phrase.sort.most_discussed',
        'ordering' => 4,
        'value'    => 'most_discussed',
    ],
    [
        'tab'    => 'all',
        'params' => [
            'module_name'   => 'quiz',
            'resource_name' => 'quiz',
        ],
        'menu'     => 'quiz.sidebarMenu',
        'name'     => 'all_quiz',
        'label'    => 'quiz::phrase.all_quizzes',
        'ordering' => 1,
        'value'    => 'viewAll',
        'to'       => '/quiz/all',
    ],
    [
        'tab'      => 'my',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'quiz',
            'resource_name' => 'quiz',
        ],
        'menu'     => 'quiz.sidebarMenu',
        'name'     => 'my_quiz',
        'label'    => 'quiz::phrase.my_quizzes',
        'ordering' => 2,
        'value'    => 'viewMyQuizzes',
        'to'       => '/quiz/my',
    ],
    [
        'tab'      => 'my_pending',
        'showWhen' => [
            'and',
            ['neq', 'session.user.role.id', 1],
        ],
        'params' => [
            'module_name'   => 'quiz',
            'resource_name' => 'quiz',
        ],
        'menu'     => 'quiz.sidebarMenu',
        'name'     => 'my_pending',
        'label'    => 'quiz::phrase.my_pending_quizzes',
        'ordering' => 3,
        'value'    => 'viewMyPendingQuizzes',
        'to'       => '/quiz/pending',
    ],
    [
        'tab'      => 'friend',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'quiz',
            'resource_name' => 'quiz',
        ],
        'menu'     => 'quiz.sidebarMenu',
        'name'     => 'friend_quiz',
        'label'    => 'quiz::phrase.friends_quizzes',
        'ordering' => 4,
        'value'    => 'viewFriendQuizzes',
        'to'       => '/quiz/friend',
    ],
    [
        'tab'      => 'pending',
        'showWhen' => [
            'or',
            ['truthy', 'acl.quiz.quiz.approve'],
        ],
        'params' => [
            'module_name'   => 'quiz',
            'resource_name' => 'quiz',
        ],
        'menu'     => 'quiz.sidebarMenu',
        'name'     => 'pending',
        'label'    => 'quiz::phrase.pending_quizzes',
        'ordering' => 5,
        'value'    => 'viewPendingQuizzes',
        'to'       => '/quiz/pending',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.quiz.quiz.view'],
            ['falsy', 'is_hashtag'],
        ],
        'module_name'   => 'quiz',
        'resource_name' => 'quiz',
        'menu'          => 'search.mobileCategoryMenu',
        'name'          => 'quiz',
        'label'         => 'quiz::phrase.quiz_global_search_label',
        'ordering'      => 12,
        'value'         => 'searchGlobalQuiz',
    ],
    [
        'tab'      => 'quiz',
        'showWhen' => [
            'and',
            ['truthy', 'item.profile_menu_settings.quiz_profile_menu'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'quiz',
        'label'    => 'quiz::phrase.quizzes',
        'ordering' => 11,
        'to'       => '/quiz',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.quiz.quiz.view'],
        ],
        'module_name'   => 'quiz',
        'resource_name' => 'quiz',
        'menu'          => 'group.mobileCategoryMenu',
        'name'          => 'quiz',
        'label'         => 'quiz::phrase.quiz_global_search_label',
        'ordering'      => 12,
        'value'         => 'searchGlobalQuiz',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.quiz.quiz.view'],
        ],
        'module_name'   => 'quiz',
        'resource_name' => 'quiz',
        'menu'          => 'page.mobileCategoryMenu',
        'name'          => 'quiz',
        'label'         => 'quiz::phrase.quiz_global_search_label',
        'ordering'      => 12,
        'value'         => 'searchGlobalQuiz',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'quiz.quiz.detailActionMenu',
        'name'     => 'edit',
        'label'    => 'quiz::phrase.edit',
        'ordering' => 1,
        'value'    => 'editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['falsy', 'item.is_sponsored_feed'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'quiz.quiz.detailActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'quiz::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'sponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['truthy', 'item.is_sponsored_feed'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'quiz.quiz.detailActionMenu',
        'name'     => 'unsponsor_in_feed',
        'label'    => 'quiz::phrase.unsponsor_in_feed',
        'ordering' => 4,
        'value'    => 'unsponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['falsy', 'item.is_sponsor'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'quiz.quiz.detailActionMenu',
        'name'     => 'sponsor',
        'label'    => 'quiz::phrase.sponsor_this_item',
        'ordering' => 5,
        'value'    => 'sponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['truthy', 'item.is_sponsor'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'quiz.quiz.detailActionMenu',
        'name'     => 'unsponsor',
        'label'    => 'quiz::phrase.unsponsor_this_item',
        'ordering' => 6,
        'value'    => 'unsponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'quiz.quiz.detailActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'quiz.quiz.detailActionMenu',
        'name'     => 'unfeature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'quiz.quiz.detailActionMenu',
        'name'     => 'approve',
        'label'    => 'quiz::phrase.approve',
        'ordering' => 11,
        'value'    => 'approveItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'style'     => 'danger',
        'menu'      => 'quiz.quiz.detailActionMenu',
        'name'      => 'delete',
        'label'     => 'quiz::phrase.delete',
        'ordering'  => 12,
        'value'     => 'deleteItem',
    ],
    [
        'showWhen'  => [],
        'menu'      => 'core.bodyMenu',
        'name'      => 'quizzes',
        'label'     => 'quiz::phrase.quizzes',
        'ordering'  => 7,
        'value'     => '',
        'to'        => '/quiz',
        'as'        => 'item',
        'icon'      => 'check-square-o3',
        'iconColor' => '#0e5bb4',
    ],
];
