<?php

/* this is auto generated file */
return [
    [
        'subInfo'  => 'quiz::phrase.browse_quizzes_you_like_to_play',
        'menu'     => 'core.dropdownMenu',
        'name'     => 'quiz',
        'label'    => 'quiz::phrase.quizzes',
        'ordering' => 14,
        'icon'     => 'ico-check-square-o3',
        'to'       => '/quiz',
    ],
    [
        'subInfo'  => 'quiz::phrase.browse_quizzes_you_like_to_play',
        'menu'     => 'core.primaryMenu',
        'name'     => 'quiz',
        'label'    => 'quiz::phrase.quizzes',
        'ordering' => 14,
        'icon'     => 'ico-check-square-o3',
        'to'       => '/quiz',
    ],
    [
        'tab'      => 'quiz',
        'showWhen' => [
            'or',
            ['eq', 'item.reg_method', '0'],
            [
                'or',
                ['truthy', 'acl.group.group.moderate'],
                ['truthy', 'item.is_member'],
            ],
        ],
        'menu'     => 'group.group.profileMenu',
        'name'     => 'quiz',
        'label'    => 'quiz::phrase.quizzes',
        'ordering' => 7,
        'to'       => '/quiz',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.quiz.quiz.view'],
        ],
        'menu'     => 'group.searchWebCategoryMenu',
        'name'     => 'quiz',
        'label'    => 'quiz::phrase.quiz_global_search_label',
        'ordering' => 7,
    ],
    [
        'tab'      => 'quiz',
        'showWhen' => [
            'and',
            ['truthy', 'acl.quiz.quiz.view'],
            ['truthy', 'item.profile_settings.quiz_view_browse_quizzes'],
        ],
        'menu'     => 'page.page.profileMenu',
        'name'     => 'quiz',
        'label'    => 'quiz::phrase.quizzes',
        'ordering' => 7,
        'to'       => '/quiz',
    ],
    [
        'tab'      => 'quiz',
        'showWhen' => [
            'and',
            ['truthy', 'acl.quiz.quiz.create'],
            ['truthy', 'item.profile_settings.quiz_share_quizzes'],
            ['falsy', 'item.is_muted'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'quiz.quiz.headerItemActionOnGroupProfileMenu',
        'name'     => 'quiz',
        'label'    => 'quiz::phrase.add_new_quiz',
        'ordering' => 1,
        'to'       => '/quiz/add?owner_id=:id',
    ],
    [
        'tab'      => 'quiz',
        'showWhen' => [
            'and',
            ['truthy', 'acl.quiz.quiz.create'],
            ['truthy', 'item.profile_settings.quiz_share_quizzes'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'quiz.quiz.headerItemActionOnPageProfileMenu',
        'name'     => 'quiz',
        'label'    => 'quiz::phrase.add_new_quiz',
        'ordering' => 1,
        'to'       => '/quiz/add?owner_id=:id',
    ],
    [
        'tab'      => 'quiz',
        'showWhen' => [
            'and',
            ['truthy', 'acl.quiz.quiz.create'],
            ['truthy', 'item.is_owner'],
        ],
        'menu'     => 'quiz.quiz.headerItemActionOnUserProfileMenu',
        'name'     => 'quiz',
        'label'    => 'quiz::phrase.add_new_quiz',
        'ordering' => 1,
        'to'       => '/quiz/add?owner_id=:id',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'quiz::phrase.edit',
        'ordering' => 1,
        'value'    => 'editItem',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['falsy', 'item.is_sponsored_feed'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'quiz::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['truthy', 'item.is_sponsored_feed'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'unsponsor_in_feed',
        'label'    => 'quiz::phrase.unsponsor_in_feed',
        'ordering' => 4,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['falsy', 'item.is_sponsor'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'sponsor',
        'label'    => 'quiz::phrase.sponsor_this_item',
        'ordering' => 5,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['truthy', 'item.is_sponsor'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'unsponsor',
        'label'    => 'quiz::phrase.unsponsor_this_item',
        'ordering' => 6,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'unfeature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'approve',
        'label'    => 'quiz::phrase.approve',
        'ordering' => 11,
        'value'    => 'approveItem',
        'icon'     => 'ico-check-circle-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'menu'      => 'quiz.quiz.itemActionMenu',
        'name'      => 'delete',
        'label'     => 'quiz::phrase.delete',
        'ordering'  => 12,
        'value'     => 'deleteItem',
        'icon'      => 'ico-trash',
    ],
    [
        'tab'      => 'landing',
        'menu'     => 'quiz.sidebarMenu',
        'name'     => 'landing',
        'label'    => 'quiz::phrase.home',
        'ordering' => 1,
        'icon'     => 'ico-question-mark',
        'to'       => '/quiz',
    ],
    [
        'tab'      => 'all',
        'menu'     => 'quiz.sidebarMenu',
        'name'     => 'all_quiz',
        'label'    => 'quiz::phrase.all_quizzes',
        'ordering' => 2,
        'icon'     => 'ico-hashtag',
        'to'       => '/quiz/all',
    ],
    [
        'tab'      => 'my',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'quiz.sidebarMenu',
        'name'     => 'my_quiz',
        'label'    => 'quiz::phrase.my_quizzes',
        'ordering' => 3,
        'icon'     => 'ico-user-man-o',
        'to'       => '/quiz/my',
    ],
    [
        'tab'      => 'my_pending',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['neq', 'session.user.role.id', 1],
        ],
        'menu'     => 'quiz.sidebarMenu',
        'name'     => 'my_pending',
        'label'    => 'quiz::phrase.my_pending_quizzes',
        'ordering' => 4,
        'icon'     => 'ico-user1-clock-o',
        'to'       => '/quiz/my-pending',
    ],
    [
        'tab'      => 'friend',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'quiz.sidebarMenu',
        'name'     => 'friend_quiz',
        'label'    => 'quiz::phrase.friends_quizzes',
        'ordering' => 5,
        'icon'     => 'ico-user1-two-o',
        'to'       => '/quiz/friend',
    ],
    [
        'tab'      => 'pending',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.quiz.quiz.approve'],
        ],
        'menu'     => 'quiz.sidebarMenu',
        'name'     => 'pending',
        'label'    => 'quiz::phrase.pending_quizzes',
        'ordering' => 6,
        'icon'     => 'ico-check-circle-alt',
        'to'       => '/quiz/pending',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.quiz.quiz.create'],
        ],
        'buttonProps' => [
            'fullWidth' => true,
            'color'     => 'primary',
            'variant'   => 'contained',
        ],
        'menu'     => 'quiz.sidebarMenu',
        'name'     => 'add',
        'label'    => 'quiz::phrase.add_new_quiz',
        'ordering' => 7,
        'as'       => 'sidebarButton',
        'icon'     => 'ico-plus',
        'to'       => '/quiz/add',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.quiz.quiz.view'],
        ],
        'menu'     => 'search.webCategoryMenu',
        'name'     => 'quiz',
        'label'    => 'quiz::phrase.quiz_global_search_label',
        'ordering' => 12,
        'to'       => '/search/quiz',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.quiz.quiz.view'],
        ],
        'menu'     => 'search.webCategoryOrderingMenu',
        'name'     => 'quiz',
        'label'    => 'quiz::phrase.quiz_global_search_label',
        'ordering' => 10,
    ],
    [
        'tab'      => 'quiz',
        'showWhen' => [
            'and',
            ['truthy', 'item.profile_menu_settings.quiz_profile_menu'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'quiz',
        'label'    => 'quiz::phrase.quizzes',
        'ordering' => 11,
        'to'       => '/quiz',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.quiz.quiz.view'],
        ],
        'menu'     => 'search.webHashtagCategoryMenu',
        'name'     => 'quiz',
        'label'    => 'quiz::phrase.quiz_global_search_label',
        'ordering' => 5,
    ],
];
