<?php

/* this is auto generated file */
return [
    [
        'description' => 'Say something about this video...',
        'post_type'   => 'video',
        'icon_color'  => '#ffac00',
        'menu'        => 'event.event.feedComposerMenu',
        'name'        => 'compose_video',
        'label'       => 'video::phrase.video',
        'ordering'    => 5,
        'as'          => 'post.video',
        'value'       => 'video',
        'icon'        => 'video-player-o',
        'to'          => '3',
    ],
    [
        'description' => 'Say something about this video...',
        'post_type'   => 'video',
        'icon_color'  => '#ffac00',
        'menu'        => 'feed.feed.feedComposerMenu',
        'name'        => 'compose_video',
        'label'       => 'video::phrase.video',
        'ordering'    => 5,
        'as'          => 'post.video',
        'value'       => 'video',
        'icon'        => 'video-player-o',
        'to'          => '3',
        'showWhen'    => [
            'or',
            [
                'or',
                ['eq', 'attachmentType', 'photo'],
                ['eq', 'attachmentType', 'photo_set'],
            ],
            [
                'and',
                ['falsy', 'hasShareValue'],
                ['falsy', 'pstatusbg_enable'],
                ['falsy', 'hasPoll'],
                ['neq', 'attachmentType', 'link'],
            ],
        ],
    ],
    [
        'description' => 'Say something about this video...',
        'post_type'   => 'video',
        'icon_color'  => '#ffac00',
        'menu'        => 'group.group.feedComposerMenu',
        'name'        => 'compose_video',
        'label'       => 'video::phrase.video',
        'ordering'    => 5,
        'as'          => 'post.video',
        'value'       => 'video',
        'icon'        => 'video-player-o',
        'to'          => '3',
    ],
    [
        'description' => 'Say something about this video...',
        'post_type'   => 'video',
        'icon_color'  => '#ffac00',
        'menu'        => 'page.page.feedComposerMenu',
        'name'        => 'compose_video',
        'label'       => 'video::phrase.video',
        'ordering'    => 5,
        'as'          => 'post.video',
        'value'       => 'video',
        'icon'        => 'video-player-o',
        'to'          => '3',
        'showWhen'    => [
            'or',
            [
                'or',
                ['eq', 'attachmentType', 'photo'],
                ['eq', 'attachmentType', 'photo_set'],
            ],
            [
                'and',
                ['falsy', 'hasShareValue'],
                ['falsy', 'pstatusbg_enable'],
                ['falsy', 'hasPoll'],
                ['neq', 'attachmentType', 'link'],
            ],
        ],
    ],
    [
        'tab'      => 'video',
        'menu'     => 'page.page.profileMenu',
        'name'     => 'video',
        'label'    => 'video::phrase.videos',
        'ordering' => 5,
        'to'       => '/video',
    ],
    [
        'description' => 'Say something about this video...',
        'post_type'   => 'video',
        'icon_color'  => '#ffac00',
        'menu'        => 'user.user.feedComposerMenu',
        'name'        => 'compose_video',
        'label'       => 'video::phrase.video',
        'ordering'    => 5,
        'as'          => 'post.video',
        'value'       => 'video',
        'icon'        => 'video-player-o',
        'to'          => '3',
    ],
    [
        'tab'      => 'video',
        'showWhen' => [
            'and',
            ['truthy', 'item.profile_menu_settings.video_profile_menu'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'video',
        'label'    => 'video::phrase.videos',
        'ordering' => 5,
        'to'       => '/video',
    ],
    [
        'params' => [
            'module_name'   => 'video',
            'resource_name' => 'video',
        ],
        'menu'     => 'video.sidebarMenu',
        'name'     => 'all',
        'label'    => 'video::phrase.all_videos',
        'ordering' => 1,
        'value'    => 'viewAll',
    ],
    [
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'video',
            'resource_name' => 'video',
        ],
        'menu'     => 'video.sidebarMenu',
        'name'     => 'my',
        'label'    => 'video::phrase.my_videos',
        'ordering' => 2,
        'value'    => 'viewMyVideos',
    ],
    [
        'params' => [
            'module_name'   => 'video',
            'resource_name' => 'video',
        ],
        'showWhen' => [
            'and',
            ['neq', 'session.user.role.id', 1],
        ],
        'menu'     => 'video.sidebarMenu',
        'name'     => 'my_pending',
        'label'    => 'video::phrase.my_pending_videos',
        'ordering' => 3,
        'value'    => 'viewMyPendingVideos',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.video.video.approve'],
        ],
        'params' => [
            'module_name'   => 'video',
            'resource_name' => 'video',
        ],
        'menu'     => 'video.sidebarMenu',
        'name'     => 'pending',
        'label'    => 'video::phrase.pending_videos',
        'ordering' => 3,
        'value'    => 'viewPendingVideos',
    ],
    [
        'params' => [
            'module_name'   => 'video',
            'resource_name' => 'video',
        ],
        'menu'     => 'video.sidebarMenu',
        'name'     => 'friend',
        'label'    => 'video::phrase.friend_s_videos',
        'ordering' => 4,
        'value'    => 'viewFriendVideos',
    ],
    [
        'menu'     => 'video.video.filter_menu',
        'name'     => 'all',
        'label'    => 'core::phrase.when.all',
        'ordering' => 1,
        'value'    => 'all',
    ],
    [
        'menu'     => 'video.video.filter_menu',
        'name'     => 'this_month',
        'label'    => 'core::phrase.when.this_month',
        'ordering' => 2,
        'value'    => 'this_month',
    ],
    [
        'menu'     => 'video.video.filter_menu',
        'name'     => 'this_week',
        'label'    => 'core::phrase.when.this_week',
        'ordering' => 3,
        'value'    => 'this_week',
    ],
    [
        'menu'     => 'video.video.filter_menu',
        'name'     => 'today',
        'label'    => 'core::phrase.when.today',
        'ordering' => 4,
        'value'    => 'today',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'video.video.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'video::phrase.edit_video',
        'ordering' => 1,
        'value'    => 'editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'video.video.itemActionMenu',
        'name'     => 'approve',
        'label'    => 'video::phrase.approve',
        'ordering' => 1,
        'value'    => 'approveItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['falsy', 'item.is_processing'],
            ['falsy', 'item.is_sponsored_feed'],
        ],
        'menu'     => 'video.video.itemActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'video::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'sponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['truthy', 'item.is_sponsored_feed'],
        ],
        'menu'     => 'video.video.itemActionMenu',
        'name'     => 'unsponsor_in_feed',
        'label'    => 'video::phrase.unsponsor_in_feed',
        'ordering' => 4,
        'value'    => 'unsponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['falsy', 'item.is_processing'],
            ['falsy', 'item.is_sponsor'],
        ],
        'menu'     => 'video.video.itemActionMenu',
        'name'     => 'sponsor',
        'label'    => 'video::phrase.sponsor_this_item',
        'ordering' => 5,
        'value'    => 'sponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['truthy', 'item.is_sponsor'],
        ],
        'menu'     => 'video.video.itemActionMenu',
        'name'     => 'unsponsor',
        'label'    => 'video::phrase.unsponsor_this_item',
        'ordering' => 6,
        'value'    => 'unsponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['falsy', 'item.is_processing'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'className' => 'itemPrimary',
        'menu'      => 'video.video.itemActionMenu',
        'name'      => 'feature',
        'label'     => 'core::phrase.feature',
        'ordering'  => 7,
        'value'     => 'featureItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'className' => 'itemPrimary',
        'menu'      => 'video.video.itemActionMenu',
        'name'      => 'unfeature',
        'label'     => 'core::phrase.un_feature',
        'ordering'  => 8,
        'value'     => 'unfeatureItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'style'     => 'danger',
        'menu'      => 'video.video.itemActionMenu',
        'name'      => 'delete',
        'label'     => 'video::phrase.delete',
        'ordering'  => 11,
        'value'     => 'deleteItem',
    ],
    [
        'menu'     => 'video.video.sort_menu',
        'name'     => 'recent',
        'label'    => 'core::phrase.sort.recent',
        'ordering' => 1,
        'value'    => 'recent',
    ],
    [
        'menu'     => 'video.video.sort_menu',
        'name'     => 'most_viewed',
        'label'    => 'core::phrase.sort.most_viewed',
        'ordering' => 2,
        'value'    => 'most_viewed',
    ],
    [
        'menu'     => 'video.video.sort_menu',
        'name'     => 'most_liked',
        'label'    => 'core::phrase.sort.most_liked',
        'ordering' => 3,
        'value'    => 'most_liked',
    ],
    [
        'menu'     => 'video.video.sort_menu',
        'name'     => 'most_discussed',
        'label'    => 'core::phrase.sort.most_discussed',
        'ordering' => 4,
        'value'    => 'most_discussed',
    ],
    [
        'menu'     => 'video.video.sort_menu',
        'name'     => 'a_to_z',
        'label'    => 'core::phrase.sort.a_to_z',
        'ordering' => 5,
        'value'    => 'a_to_z',
    ],
    [
        'menu'     => 'video.video.sort_menu',
        'name'     => 'z_to_a',
        'label'    => 'core::phrase.sort.z_to_a',
        'ordering' => 6,
        'value'    => 'z_to_a',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.video.video.view'],
            ['falsy', 'is_hashtag'],
        ],
        'module_name'   => 'video',
        'resource_name' => 'video',
        'menu'          => 'search.mobileCategoryMenu',
        'name'          => 'video',
        'label'         => 'video::phrase.video_global_search_label',
        'ordering'      => 4,
        'value'         => 'searchGlobalVideo',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.video.video.view'],
        ],
        'module_name'   => 'video',
        'resource_name' => 'video',
        'menu'          => 'group.mobileCategoryMenu',
        'name'          => 'video',
        'label'         => 'video::phrase.video_global_search_label',
        'ordering'      => 4,
        'value'         => 'searchGlobalVideo',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.video.video.view'],
        ],
        'menu'     => 'search.mobileHashtagCategoryMenu',
        'name'     => 'video',
        'label'    => 'video::phrase.video_global_search_label',
        'ordering' => 5,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'video.video.detailActionMenu',
        'name'     => 'edit',
        'label'    => 'video::phrase.edit_video',
        'ordering' => 1,
        'value'    => 'editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'video.video.detailActionMenu',
        'name'     => 'approve',
        'label'    => 'video::phrase.approve',
        'ordering' => 1,
        'value'    => 'approveItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['falsy', 'item.is_processing'],
            ['falsy', 'item.is_sponsored_feed'],
        ],
        'menu'     => 'video.video.detailActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'video::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'sponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['truthy', 'item.is_sponsored_feed'],
        ],
        'menu'     => 'video.video.detailActionMenu',
        'name'     => 'unsponsor_in_feed',
        'label'    => 'video::phrase.unsponsor_in_feed',
        'ordering' => 4,
        'value'    => 'unsponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['falsy', 'item.is_processing'],
            ['falsy', 'item.is_sponsor'],
        ],
        'menu'     => 'video.video.detailActionMenu',
        'name'     => 'sponsor',
        'label'    => 'video::phrase.sponsor_this_item',
        'ordering' => 5,
        'value'    => 'sponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['truthy', 'item.is_sponsor'],
        ],
        'menu'     => 'video.video.detailActionMenu',
        'name'     => 'unsponsor',
        'label'    => 'video::phrase.unsponsor_this_item',
        'ordering' => 6,
        'value'    => 'unsponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['falsy', 'item.is_processing'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'className' => 'itemPrimary',
        'menu'      => 'video.video.detailActionMenu',
        'name'      => 'feature',
        'label'     => 'core::phrase.feature',
        'ordering'  => 7,
        'value'     => 'featureItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'className' => 'itemPrimary',
        'menu'      => 'video.video.detailActionMenu',
        'name'      => 'unfeature',
        'label'     => 'core::phrase.un_feature',
        'ordering'  => 8,
        'value'     => 'unfeatureItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'style'     => 'danger',
        'menu'      => 'video.video.detailActionMenu',
        'name'      => 'delete',
        'label'     => 'video::phrase.delete',
        'ordering'  => 11,
        'value'     => 'deleteItem',
    ],
    [
        'showWhen'  => [],
        'menu'      => 'core.bodyMenu',
        'name'      => 'video',
        'label'     => 'video::phrase.videos',
        'ordering'  => 4,
        'value'     => '',
        'to'        => '/video',
        'as'        => 'item',
        'icon'      => 'video-player-o',
        'iconColor' => '#ffac00',
    ],
];
