<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Session\\Http\\Resources\\v1\\Store\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'session.store',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Session\\Http\\Resources\\v1\\Admin\\UpdateApcSessionForm',
        'type'       => 'form-session',
        'name'       => 'apc',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_preload' => 1,
        'title'      => 'AWS Dynamodb',
    ],
    [
        'driver'     => 'MetaFox\\Session\\Http\\Resources\\v1\\Admin\\UpdateCookieArrayForm',
        'type'       => 'form-session',
        'name'       => 'array',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_preload' => 1,
        'title'      => 'Array',
    ],
    [
        'driver'     => 'MetaFox\\Session\\Http\\Resources\\v1\\Admin\\UpdateCookieSessionForm',
        'type'       => 'form-session',
        'name'       => 'cookie',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_preload' => 1,
        'title'      => 'Cookie',
    ],
    [
        'driver'     => 'MetaFox\\Session\\Http\\Resources\\v1\\Admin\\UpdateDatabaseSessionForm',
        'type'       => 'form-session',
        'name'       => 'database',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_preload' => 1,
        'title'      => 'Files',
    ],
    [
        'driver'     => 'MetaFox\\Session\\Http\\Resources\\v1\\Admin\\UpdateDynamoDbSessionForm',
        'type'       => 'form-session',
        'name'       => 'dynamodb',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_preload' => 1,
        'title'      => 'AWS Dynamodb',
    ],
    [
        'driver'     => 'MetaFox\\Session\\Http\\Resources\\v1\\Admin\\UpdateFileSessionForm',
        'type'       => 'form-session',
        'name'       => 'file',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_preload' => 1,
        'title'      => 'Files',
    ],
    [
        'driver'     => 'MetaFox\\Session\\Http\\Resources\\v1\\Admin\\UpdateMemcachedSessionForm',
        'type'       => 'form-session',
        'name'       => 'memcached',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_preload' => 1,
        'title'      => 'Memcached',
    ],
    [
        'driver'     => 'MetaFox\\Session\\Http\\Resources\\v1\\Admin\\UpdateRedisSessionForm',
        'type'       => 'form-session',
        'name'       => 'redis',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_preload' => 1,
        'title'      => 'Redis',
    ],
    [
        'driver'      => 'MetaFox\\Session\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'        => 'form-settings',
        'name'        => 'session',
        'version'     => 'v1',
        'resolution'  => 'admin',
        'is_preload'  => 1,
        'title'       => 'core::phrase.settings',
        'url'         => '/admincp/session/setting',
        'description' => 'Session Settings',
        'is_active'   => 0,
    ],
    [
        'driver'  => 'MetaFox\\Session\\Http\\Resources\\v1\\PackageSetting',
        'type'    => 'package-setting',
        'name'    => 'session',
        'version' => 'v1',
    ],
];
