<?php

/* this is auto generated file */
return [
    [
        'subInfo'  => 'user::phrase.browse_people_you_may_know',
        'menu'     => 'core.dropdownMenu',
        'name'     => 'members',
        'label'    => 'user::phrase.members',
        'ordering' => 3,
        'icon'     => 'ico-user1-three',
        'to'       => '/user',
    ],
    [
        'menu'     => 'core.headerSubMenu',
        'name'     => 'user',
        'ordering' => 6,
        'as'       => 'user',
        'icon'     => '',
    ],
    [
        'subInfo'  => 'user::phrase.browse_people_you_may_know',
        'menu'     => 'core.primaryMenu',
        'name'     => 'members',
        'label'    => 'user::phrase.members',
        'ordering' => 3,
        'icon'     => 'ico-user1-three',
        'to'       => '/user',
    ],
    [
        'tab'      => 'member',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_view_members'],
        ],
        'menu'     => 'group.group.profileMenu',
        'name'     => 'member',
        'label'    => 'user::phrase.members',
        'ordering' => 4,
        'to'       => '/member',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.user.user.view'],
        ],
        'menu'     => 'search.webCategoryMenu',
        'name'     => 'user',
        'label'    => 'user::phrase.user_global_search_label',
        'ordering' => 1,
        'to'       => '/search/user',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.user.user.view'],
        ],
        'menu'     => 'search.webCategoryOrderingMenu',
        'name'     => 'user',
        'label'    => 'user::phrase.user_global_search_label',
        'ordering' => 1,
    ],
    [
        'menu'     => 'user.actionMenuProfilePhoto',
        'name'     => 'add_photos',
        'ordering' => 1,
        'as'       => 'feed.ui.addPhotoButton',
    ],
    [
        'menu'     => 'user.headerRegisterMenu',
        'name'     => 'login',
        'label'    => 'user::phrase.sign_in',
        'ordering' => 1,
        'to'       => '/login',
    ],
    [
        'menu'     => 'user.headerRegisterMenu',
        'name'     => 'register',
        'label'    => 'user::phrase.don_t_have_an_account',
        'ordering' => 2,
        'to'       => '/register',
    ],
    [
        'menu'     => 'user.headerSignInMenu',
        'name'     => 'login',
        'label'    => 'user::phrase.already_had_an_account',
        'ordering' => 1,
        'to'       => '/login',
    ],
    [
        'menu'     => 'user.settingMenu',
        'name'     => 'account',
        'label'    => 'user::phrase.account_settings',
        'ordering' => 1,
        'as'       => 'sidebarHeading',
    ],
    [
        'tab'      => 'general',
        'menu'     => 'user.settingMenu',
        'name'     => 'landing',
        'label'    => 'user::phrase.profile_info',
        'ordering' => 2,
        'to'       => '/settings',
    ],
    [
        'tab'      => 'payment',
        'menu'     => 'user.settingMenu',
        'name'     => 'payment',
        'label'    => 'payment::phrase.payment_gateways',
        'ordering' => 3,
        'to'       => '/settings/payment',
    ],
    [
        'menu'     => 'user.settingMenu',
        'name'     => 'privacy_setting',
        'label'    => 'user::phrase.privacy_settings',
        'ordering' => 5,
        'as'       => 'sidebarHeading',
    ],
    [
        'tab'      => 'profile',
        'menu'     => 'user.settingMenu',
        'name'     => 'profile',
        'label'    => 'user::phrase.your_profile',
        'ordering' => 6,
        'to'       => '/settings/profile',
    ],
    [
        'tab'      => 'invisible',
        'menu'     => 'user.settingMenu',
        'name'     => 'invisible',
        'label'    => 'user::phrase.invisible_mode',
        'ordering' => 8,
        'to'       => '/settings/invisible',
    ],
    [
        'tab'      => 'items',
        'menu'     => 'user.settingMenu',
        'name'     => 'sharing',
        'label'    => 'user::phrase.sharing_items',
        'ordering' => 11,
        'to'       => '/settings/items',
    ],
    [
        'tab'      => 'blocked',
        'menu'     => 'user.settingMenu',
        'name'     => 'blocked',
        'label'    => 'user::phrase.blocked_users',
        'ordering' => 12,
        'to'       => '/settings/blocked',
    ],
    [
        'menu'     => 'user.settingMenu',
        'name'     => 'divider',
        'ordering' => 13,
        'as'       => 'divider',
    ],
    [
        'menu'     => 'user.settingMenu',
        'name'     => 'profile_menu_settings',
        'label'    => 'user::phrase.profile_menu_settings',
        'ordering' => 14,
        'as'       => 'sidebarHeading',
    ],
    [
        'tab'      => 'profile-menu',
        'menu'     => 'user.settingMenu',
        'name'     => 'profile_menu',
        'label'    => 'user::phrase.menu',
        'ordering' => 15,
        'to'       => '/settings/profile-menu',
    ],
    [
        'selectedWhen' => ['eq', 'item.sort_type', 1],
        'menu'         => 'user.shortcut.itemActionMenu',
        'name'         => 'auto',
        'label'        => 'user::phrase.sort_automatically',
        'ordering'     => 1,
        'value'        => 'user/shortcut/sortAutomatically',
        'icon'         => 'ico-star-o',
    ],
    [
        'selectedWhen' => ['eq', 'item.sort_type', 0],
        'menu'         => 'user.shortcut.itemActionMenu',
        'name'         => 'hide',
        'label'        => 'user::phrase.hide',
        'ordering'     => 3,
        'value'        => 'user/shortcut/hide',
        'icon'         => 'ico-eye-alt',
    ],
    [
        'selectedWhen' => ['eq', 'item.sort_type', 2],
        'menu'         => 'user.shortcut.itemActionMenu',
        'name'         => 'pin',
        'label'        => 'user::phrase.pin_to_top',
        'ordering'     => 2,
        'value'        => 'user/shortcut/pinToTop',
        'icon'         => 'ico-link',
    ],
    [
        'tab'      => 'landing',
        'menu'     => 'user.sidebarMenu',
        'name'     => 'landing',
        'label'    => 'user::phrase.all_members',
        'ordering' => 1,
        'icon'     => 'ico ico-user1-three',
        'to'       => '/user',
    ],
    [
        'tab'      => 'landing',
        'showWhen' => [
            'and',
            ['falsy', 'acl.user.user.isGuest'],
        ],
        'menu'      => 'user.sidebarMenu',
        'name'      => 'all',
        'label'     => 'user::phrase.all_members',
        'ordering'  => 2,
        'icon'      => 'ico ico-user1-three',
        'to'        => '/user/all',
        'is_delete' => 1,
        'is_active' => 0,
    ],
    [
        'tab'      => 'recommend',
        'showWhen' => [
            'and',
            ['falsy', 'acl.user.user.isGuest'],
        ],
        'menu'     => 'user.sidebarMenu',
        'name'     => 'recommend',
        'label'    => 'user::phrase.members_you_may_know',
        'ordering' => 2,
        'icon'     => 'ico-user2-three-o',
        'to'       => '/user/recommend',
    ],
    [
        'tab'      => 'recent',
        'menu'     => 'user.sidebarMenu',
        'name'     => 'recent',
        'label'    => 'user::phrase.recent_active',
        'ordering' => 3,
        'icon'     => 'ico-user2-clock-o',
        'to'       => '/user/recent',
    ],
    [
        'tab'      => 'featured',
        'menu'     => 'user.sidebarMenu',
        'name'     => 'featured',
        'label'    => 'user::phrase.featured_members',
        'ordering' => 4,
        'icon'     => 'ico-check-circle-alt',
        'to'       => '/user/featured',
    ],
    [
        'tab'      => 'photo',
        'menu'     => 'user.tabMenuProfilePhoto',
        'name'     => 'photo',
        'label'    => 'user::phrase.photos',
        'ordering' => 1,
        'to'       => 'photo',
    ],
    [
        'tab'      => 'album',
        'menu'     => 'user.tabMenuProfilePhoto',
        'name'     => 'album',
        'label'    => 'user::phrase.albums',
        'ordering' => 2,
        'to'       => 'album',
    ],
    [
        'showWhen' => [
            'and',
            [
                'includes',
                'item.friendship',
                [0, 7],
            ],
            ['truthy', 'item.extra.can_add_friend'],
        ],
        'menu'     => 'user.user.itemActionMenu',
        'name'     => 'add_friend',
        'label'    => 'user::phrase.add_friend',
        'ordering' => 1,
        'value'    => 'user/addFriend',
        'icon'     => 'ico-user3-plus-o',
    ],
    [
        'showWhen' => ['eq', 'item.friendship', 3],
        'menu'     => 'user.user.itemActionMenu',
        'name'     => 'cancel_request',
        'label'    => 'user::phrase.cancel_request',
        'ordering' => 2,
        'value'    => 'user/cancelRequest',
        'icon'     => 'ico-user2-del-o',
    ],
    [
        'showWhen' => ['eq', 'item.friendship', 1],
        'menu'     => 'user.user.itemActionMenu',
        'name'     => 'unfriend',
        'label'    => 'user::phrase.unfriend',
        'ordering' => 3,
        'value'    => 'user/unFriend',
        'icon'     => 'ico-user3-minus-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.friend.friend_list.update'],
            ['eq', 'item.friendship', 1],
        ],
        'menu'     => 'user.user.itemActionMenu',
        'name'     => 'edit_list',
        'label'    => 'user::phrase.move_to_friends_list',
        'ordering' => 4,
        'value'    => 'friend/assignFriendList',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['falsy', 'item.is_sponsored_feed'],
        ],
        'menu'     => 'user.user.itemActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'user::phrase.sponsor_in_feed',
        'ordering' => 6,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['truthy', 'item.is_sponsored_feed'],
        ],
        'menu'     => 'user.user.itemActionMenu',
        'name'     => 'delete_sponsor_in_feed',
        'label'    => 'user::phrase.unsponsor_in_feed',
        'ordering' => 7,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['falsy', 'item.is_sponsor'],
        ],
        'menu'     => 'user.user.itemActionMenu',
        'name'     => 'sponsor',
        'label'    => 'user::phrase.sponsor_this_item',
        'ordering' => 8,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['truthy', 'item.is_sponsor'],
        ],
        'menu'     => 'user.user.itemActionMenu',
        'name'     => 'delete_sponsor',
        'label'    => 'user::phrase.unsponsor_this_item',
        'ordering' => 9,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'     => 'user.user.itemActionMenu',
        'name'     => 'feature',
        'label'    => 'user::phrase.feature',
        'ordering' => 10,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'     => 'user.user.itemActionMenu',
        'name'     => 'delete_feature',
        'label'    => 'user::phrase.un_feature',
        'ordering' => 11,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['falsy', 'item.is_blocked'],
            ['neq', 'item.friendship', 5],
        ],
        'menu'     => 'user.user.itemActionMenu',
        'name'     => 'block',
        'label'    => 'user::phrase.block_this_user',
        'ordering' => 12,
        'value'    => 'blockItem',
        'icon'     => 'ico-ban',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['eq', 'item.friendship', 1],
        ],
        'menu'     => 'user.user.profileActionMenu',
        'name'     => 'un_friend',
        'label'    => 'user::phrase.un_friend',
        'ordering' => 1,
        'value'    => 'user/unFriend',
        'icon'     => 'ico-user3-minus-o',
    ],
    [
        'showWhen' => [
            'and',
            [
                'includes',
                'item.friendship',
                [0, 7],
            ],
            ['truthy', 'item.extra.can_add_friend'],
        ],
        'menu'     => 'user.user.profileActionMenu',
        'name'     => 'add_friend',
        'label'    => 'user::phrase.add_friend',
        'ordering' => 2,
        'value'    => 'user/addFriend',
        'icon'     => 'ico-user3-plus-o',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.friendship', 3],
        ],
        'menu'     => 'user.user.profileActionMenu',
        'name'     => 'cancel_request',
        'label'    => 'user::phrase.cancel_request',
        'ordering' => 3,
        'value'    => 'user/cancelRequest',
        'icon'     => 'ico-user2-del-o',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['eq', 'item.friendship', 2],
        ],
        'menu'     => 'user.user.profileActionMenu',
        'name'     => 'confirm_request',
        'label'    => 'core::phrase.confirm',
        'ordering' => 5,
        'value'    => 'user/acceptFriendRequest',
        'icon'     => 'ico-check',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['eq', 'item.friendship', 2],
        ],
        'menu'     => 'user.user.profileActionMenu',
        'name'     => 'delete_request',
        'label'    => 'user::phrase.delete',
        'ordering' => 6,
        'value'    => 'user/denyFriendRequest',
        'icon'     => 'ico-close',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'user.user.profileActionMenu',
        'name'     => 'edit_profile',
        'label'    => 'user::phrase.edit_profile',
        'ordering' => 7,
        'value'    => 'user/editProfile',
        'icon'     => 'ico-pencil',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_message'],
        ],
        'menu'     => 'user.user.profileActionMenu',
        'name'     => 'message',
        'label'    => 'user::phrase.message',
        'ordering' => 8,
        'value'    => 'chat/room/openChatRoom',
        'icon'     => 'ico-comment-o',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_poke'],
            ['neq', 'item.friendship', 5],
        ],
        'menu'      => 'user.user.profileActionMenu',
        'name'      => 'poke',
        'label'     => 'user::phrase.poke',
        'ordering'  => 8,
        'value'     => 'pokeItem',
        'icon'      => 'ico-smile-o',
        'is_active' => 0,
        'is_delete' => 1,
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_featured'],
        ],
        'menu'     => 'user.user.profileActionMenu',
        'name'     => 'feature',
        'label'    => 'user::phrase.featured_this_user',
        'ordering' => 10,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond-o',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_feature'],
            ['truthy', 'item.is_featured'],
        ],
        'menu'     => 'user.user.profileActionMenu',
        'name'     => 'unfeature',
        'label'    => 'user::phrase.un_featured_this_user',
        'ordering' => 10,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond-o',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['falsy', 'item.is_blocked'],
            ['neq', 'item.friendship', 5],
        ],
        'menu'     => 'user.user.profileActionMenu',
        'name'     => 'block',
        'label'    => 'user::phrase.block_this_user',
        'ordering' => 11,
        'value'    => 'blockItem',
        'icon'     => 'ico-ban',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.is_blocked'],
            ['neq', 'item.friendship', 5],
        ],
        'menu'     => 'user.user.profileActionMenu',
        'name'     => 'unblock',
        'label'    => 'user::phrase.un_block_this_user',
        'ordering' => 12,
        'value'    => 'unblockItem',
        'icon'     => 'ico-ban',
    ],
    [
        'active'   => true,
        'tab'      => 'home',
        'menu'     => 'user.user.profileMenu',
        'name'     => 'home',
        'label'    => 'user::phrase.overview',
        'ordering' => 1,
        'to'       => '/',
    ],
    [
        'tab'      => 'about',
        'showWhen' => [
            'and',
            ['truthy', 'item.profile_settings.profile_profile_info'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'about',
        'label'    => 'user::phrase.about',
        'ordering' => 2,
        'to'       => '/about',
    ],
    [
        'showWhen' => ['eq', 'item.friendship', 3],
        'menu'     => 'user.user.profilePopoverMenu',
        'name'     => 'cancel_request',
        'label'    => 'user::phrase.cancel_request',
        'ordering' => 1,
        'value'    => 'user/cancelRequest',
        'icon'     => 'ico-user2-del-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.friend.friend_list.update'],
            ['eq', 'item.friendship', 1],
        ],
        'menu'     => 'user.user.profilePopoverMenu',
        'name'     => 'edit_list',
        'label'    => 'user::phrase.move_to_friends_list',
        'ordering' => 2,
        'value'    => 'friend/assignFriendList',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => ['eq', 'item.friendship', 1],
        'menu'     => 'user.user.profilePopoverMenu',
        'name'     => 'delete',
        'label'    => 'user::phrase.unfriend',
        'ordering' => 3,
        'value'    => 'user/unFriend',
        'icon'     => 'ico ico-user3-minus-o',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['falsy', 'item.is_blocked'],
            ['neq', 'item.friendship', 5],
        ],
        'menu'     => 'user.user.profilePopoverMenu',
        'name'     => 'block',
        'label'    => 'user::phrase.block_this_user',
        'ordering' => 4,
        'value'    => 'blockItem',
        'icon'     => 'ico-ban',
    ],
];
