<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Category\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'marketplace.category',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Models\\Listing',
        'type'       => 'entity',
        'name'       => 'marketplace',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Marketplaces',
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Models\\Category',
        'type'       => 'entity',
        'name'       => 'marketplace_category',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Marketplace Categories',
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Models\\Invite',
        'type'       => 'entity',
        'name'       => 'marketplace_invite',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Models\\Invoice',
        'type'       => 'entity',
        'name'       => 'marketplace_invoice',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Models\\InvoiceTransaction',
        'type'       => 'entity',
        'name'       => 'marketplace_invoice_transaction',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Models\\Listing',
        'type'       => 'entity-content',
        'name'       => 'marketplace',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Marketplaces',
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Invoice\\PaymentInvoiceMobileForm',
        'type'       => 'form',
        'name'       => 'marketplace_invoice.payment',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Invoice\\PaymentInvoiceForm',
        'type'       => 'form',
        'name'       => 'marketplace_invoice.payment',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Category\\Admin\\DestroyCategoryForm',
        'type'       => 'form',
        'name'       => 'marketplace.marketplace_category.destroy',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Category\\Admin\\StoreCategoryForm',
        'type'       => 'form',
        'name'       => 'marketplace.marketplace_category.store',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Category\\Admin\\UpdateCategoryForm',
        'type'       => 'form',
        'name'       => 'marketplace.marketplace_category.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Image\\UploadImageForm',
        'type'       => 'form',
        'name'       => 'marketplace.marketplace_image.upload',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Listing\\PaymentListingMobileForm',
        'type'       => 'form',
        'name'       => 'marketplace.payment',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Listing\\PaymentListingForm',
        'type'       => 'form',
        'name'       => 'marketplace.payment',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Listing\\SearchListingForm',
        'type'       => 'form',
        'name'       => 'marketplace.search',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Listing\\SearchListingMobileForm',
        'type'       => 'form',
        'name'       => 'marketplace.search',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Listing\\SearchListingMapForm',
        'type'       => 'form',
        'name'       => 'marketplace.search_map',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Listing\\SearchSimpleForm',
        'type'       => 'form',
        'name'       => 'marketplace.search_simple',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Listing\\StoreListingMobileForm',
        'type'       => 'form',
        'name'       => 'marketplace.store',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Listing\\StoreListingForm',
        'type'       => 'form',
        'name'       => 'marketplace.store',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Listing\\UpdateListingForm',
        'type'       => 'form',
        'name'       => 'marketplace.update',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Listing\\UpdateListingMobileForm',
        'type'       => 'form',
        'name'       => 'marketplace.update',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'       => 'form-settings',
        'name'       => 'marketplace',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.settings',
        'url'        => '/admincp/marketplace/setting',
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Jobs\\DeleteCategoryJob',
        'type'       => 'job',
        'name'       => 'MetaFox\\Marketplace\\Jobs\\DeleteCategoryJob',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Category\\CategoryItemCollection',
        'type'       => 'json-collection',
        'name'       => 'marketplace_category.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Listing\\ListingEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'marketplace.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\InvoiceTransaction\\TransactionItemCollection',
        'type'       => 'json-collection',
        'name'       => 'marketplace_invoice_transaction.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Listing\\ListingItemCollection',
        'type'       => 'json-collection',
        'name'       => 'marketplace.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Category\\CategoryDetail',
        'type'       => 'json-resource',
        'name'       => 'marketplace_category.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Category\\CategoryItem',
        'type'       => 'json-resource',
        'name'       => 'marketplace_category.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Listing\\ListingDetail',
        'type'       => 'json-resource',
        'name'       => 'marketplace.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Listing\\ListingEmbed',
        'type'       => 'json-resource',
        'name'       => 'marketplace.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Image\\ImageItem',
        'type'       => 'json-resource',
        'name'       => 'marketplace_image.item',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\InvoiceTransaction\\TransactionItem',
        'type'       => 'json-resource',
        'name'       => 'marketplace_invoice_transaction.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Listing\\ListingItem',
        'type'       => 'json-resource',
        'name'       => 'marketplace.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'marketplace',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Policies\\CategoryPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Marketplace\\Models\\Category',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Policies\\InvoicePolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Marketplace\\Models\\Invoice',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Policies\\ListingPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Marketplace\\Models\\Listing',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Listing\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'marketplace',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Invoice\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'marketplace_invoice',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Listing\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'marketplace',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Marketplace\\Http\\Resources\\v1\\Invoice\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'marketplace_invoice',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
];
