<?php

/* this is auto generated file */
return [
    [
        'name'         => 'admin.marketplace.browse_category',
        'phrase_title' => 'core::phrase.categories',
        'url'          => 'admincp/marketplace/category/browse',
    ],
    [
        'name'                 => 'admin.marketplace.browse_child_category',
        'phrase_title'         => 'core::phrase.categories',
        'url'                  => 'admincp/marketplace/category/{id}/category/browse',
        'custom_sharing_route' => 1,
    ],
    [
        'name'         => 'admin.marketplace.create_category',
        'phrase_title' => 'core::phrase.add_category',
        'url'          => 'admincp/marketplace/category/create',
    ],
    [
        'name'         => 'admin.marketplace.marketplace_setting',
        'phrase_title' => 'core::phrase.settings',
        'url'          => 'admincp/marketplace/setting',
    ],
    [
        'name'         => 'admin.marketplace.permissions',
        'phrase_title' => 'core::phrase.permissions',
        'url'          => 'admincp/marketplace/permission',
    ],
    [
        'name'               => 'group.profile.marketplace',
        'phrase_title'       => 'marketplace::seo.group_profile_marketplace_title',
        'phrase_description' => 'marketplace::seo.group_profile_marketplace_description',
        'phrase_keywords'    => 'marketplace::seo.group_profile_marketplace_keywords',
        'phrase_heading'     => 'marketplace::seo.group_profile_marketplace_heading',
        'url'                => 'group/{id}/marketplace',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'marketplace.browse_all_marketplace',
        'phrase_title'       => 'marketplace::seo.marketplace_browse_all_title',
        'phrase_description' => 'marketplace::seo.marketplace_browse_all_description',
        'phrase_keywords'    => 'marketplace::seo.marketplace_browse_all_keywords',
        'phrase_heading'     => 'marketplace::seo.marketplace_browse_all_heading',
        'url'                => 'marketplace/all',
        'item_type'          => 'marketplace',
    ],
    [
        'name'               => 'marketplace.browse_expire_marketplace',
        'phrase_title'       => 'marketplace::seo.marketplace_browse_expire_marketplace_title',
        'phrase_description' => 'marketplace::seo.marketplace_browse_expire_marketplace_description',
        'phrase_keywords'    => 'marketplace::seo.marketplace_browse_expire_marketplace_keywords',
        'phrase_heading'     => 'marketplace::seo.marketplace_browse_expire_marketplace_heading',
        'url'                => 'marketplace/expire',
        'item_type'          => 'marketplace',
    ],
    [
        'name'               => 'marketplace.browse_friend_marketplace',
        'phrase_title'       => 'marketplace::seo.marketplace_browse_friend_title',
        'phrase_description' => 'marketplace::seo.marketplace_browse_friend_description',
        'phrase_keywords'    => 'marketplace::seo.marketplace_browse_friend_keywords',
        'phrase_heading'     => 'marketplace::seo.marketplace_browse_friend_heading',
        'url'                => 'marketplace/friend',
        'item_type'          => 'marketplace',
    ],
    [
        'name'               => 'marketplace.browse_history_marketplace',
        'phrase_title'       => 'marketplace::seo.marketplace_browse_history_title',
        'phrase_description' => 'marketplace::seo.marketplace_browse_history_description',
        'phrase_keywords'    => 'marketplace::seo.marketplace_browse_history_keywords',
        'phrase_heading'     => 'marketplace::seo.marketplace_browse_history_heading',
        'url'                => 'marketplace/history',
        'item_type'          => 'marketplace',
    ],
    [
        'name'               => 'marketplace.browse_invite_marketplace',
        'phrase_title'       => 'marketplace::seo.marketplace_browse_invite_marketplace_title',
        'phrase_description' => 'marketplace::seo.marketplace_browse_invite_marketplace_description',
        'phrase_keywords'    => 'marketplace::seo.marketplace_browse_invite_marketplace_keywords',
        'phrase_heading'     => 'marketplace::seo.marketplace_browse_invite_marketplace_heading',
        'url'                => 'marketplace/invite',
        'item_type'          => 'marketplace',
    ],
    [
        'name'               => 'marketplace.browse_invoice_marketplace_invoice',
        'phrase_title'       => 'marketplace::seo.marketplace_browse_invoice_marketplace_invoice_title',
        'phrase_description' => 'marketplace::seo.marketplace_browse_invoice_marketplace_invoice_description',
        'phrase_keywords'    => 'marketplace::seo.marketplace_browse_invoice_marketplace_invoice_keywords',
        'phrase_heading'     => 'marketplace::seo.marketplace_browse_invoice_marketplace_invoice_heading',
        'url'                => 'marketplace/invoice',
        'item_type'          => 'marketplace',
    ],
    [
        'name'               => 'marketplace.browse_my_pending_marketplace',
        'phrase_title'       => 'marketplace::seo.marketplace_browse_my_pending_title',
        'phrase_description' => 'marketplace::seo.marketplace_browse_my_pending_description',
        'phrase_keywords'    => 'marketplace::seo.marketplace_browse_my_pending_keywords',
        'phrase_heading'     => 'marketplace::seo.marketplace_browse_my_pending_heading',
        'url'                => 'marketplace/my-pending',
        'item_type'          => 'marketplace',
    ],
    [
        'name'               => 'marketplace.browse_pending_marketplace',
        'phrase_title'       => 'marketplace::seo.marketplace_browse_pending_marketplace_title',
        'phrase_description' => 'marketplace::seo.marketplace_browse_pending_marketplace_description',
        'phrase_keywords'    => 'marketplace::seo.marketplace_browse_pending_marketplace_keywords',
        'phrase_heading'     => 'marketplace::seo.marketplace_browse_pending_marketplace_heading',
        'url'                => 'marketplace/pending',
        'item_type'          => 'marketplace',
    ],
    [
        'name'               => 'marketplace.marketplace',
        'phrase_title'       => 'marketplace::seo.marketplace_marketplace_title',
        'phrase_description' => 'marketplace::seo.marketplace_marketplace_description',
        'phrase_keywords'    => 'marketplace::seo.marketplace_marketplace_keywords',
        'phrase_heading'     => 'marketplace::seo.marketplace_marketplace_heading',
        'url'                => 'marketplace/search',
        'item_type'          => 'marketplace',
    ],
    [
        'name'               => 'marketplace.marketplace.create',
        'phrase_title'       => 'marketplace::seo.marketplace_create_title',
        'phrase_description' => 'marketplace::seo.marketplace_create_description',
        'phrase_keywords'    => 'marketplace::seo.marketplace_create_keywords',
        'phrase_heading'     => 'marketplace::seo.marketplace_create_heading',
        'url'                => 'marketplace/add',
        'item_type'          => 'marketplace',
    ],
    [
        'name'               => 'marketplace.marketplace.edit',
        'phrase_title'       => 'marketplace::seo.marketplace_edit_title',
        'phrase_description' => 'marketplace::seo.marketplace_edit_description',
        'phrase_keywords'    => 'marketplace::seo.marketplace_edit_keywords',
        'phrase_heading'     => 'marketplace::seo.marketplace_edit_heading',
        'url'                => 'marketplace/edit/{id}',
        'item_type'          => 'marketplace',
    ],
    [
        'name'               => 'marketplace.marketplace.landing',
        'phrase_title'       => 'marketplace::seo.marketplace_landing_title',
        'phrase_description' => 'marketplace::seo.marketplace_landing_description',
        'phrase_keywords'    => 'marketplace::seo.marketplace_landing_keywords',
        'phrase_heading'     => 'marketplace::seo.marketplace_landing_heading',
        'url'                => 'marketplace',
        'item_type'          => 'marketplace',
    ],
    [
        'name'               => 'marketplace.marketplace.my',
        'phrase_title'       => 'marketplace::seo.marketplace_my_title',
        'phrase_description' => 'marketplace::seo.marketplace_my_description',
        'phrase_keywords'    => 'marketplace::seo.marketplace_my_keywords',
        'phrase_heading'     => 'marketplace::seo.marketplace_my_heading',
        'url'                => 'marketplace/my',
        'item_type'          => 'marketplace',
    ],
    [
        'name'               => 'marketplace.marketplace.view_detail',
        'phrase_title'       => 'marketplace::seo.marketplace_view_detail_title',
        'phrase_description' => 'marketplace::seo.marketplace_view_detail_description',
        'phrase_keywords'    => 'marketplace::seo.marketplace_view_detail_keywords',
        'phrase_heading'     => 'marketplace::seo.marketplace_view_detail_heading',
        'url'                => 'marketplace/{id}',
        'item_type'          => 'marketplace',
    ],
    [
        'name'               => 'marketplace.marketplace_invoice.view_detail',
        'phrase_title'       => 'marketplace::seo.marketplace_invoice_view_detail_title',
        'phrase_description' => 'marketplace::seo.marketplace_invoice_view_detail_description',
        'phrase_keywords'    => 'marketplace::seo.marketplace_invoice_view_detail_keywords',
        'phrase_heading'     => 'marketplace::seo.marketplace_invoice_view_detail_heading',
        'url'                => 'marketplace/invoice/{id}',
        'item_type'          => 'marketplace_invoice',
    ],
    [
        'name'               => 'page.profile.marketplace',
        'phrase_title'       => 'marketplace::seo.page_profile_marketplace_title',
        'phrase_description' => 'marketplace::seo.page_profile_marketplace_description',
        'phrase_keywords'    => 'marketplace::seo.page_profile_marketplace_keywords',
        'phrase_heading'     => 'marketplace::seo.page_profile_marketplace_heading',
        'url'                => 'page/{id}/marketplace',
        'item_type'          => 'page',
    ],
    [
        'name'               => 'user.profile.marketplace',
        'phrase_title'       => 'marketplace::seo.user_profile_marketplace_title',
        'phrase_description' => 'marketplace::seo.user_profile_marketplace_description',
        'phrase_keywords'    => 'marketplace::seo.user_profile_marketplace_keywords',
        'phrase_heading'     => 'marketplace::seo.user_profile_marketplace_heading',
        'url'                => 'user/{id}/marketplace',
        'item_type'          => 'user',
    ],
];
