<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Authorization\\Http\\Resources\\v1\\Device\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'authorization.device',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'Data Grid Settings',
    ],
    [
        'driver'     => 'MetaFox\\Authorization\\Http\\Resources\\v1\\Role\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'authorization.role',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver' => 'MetaFox\\Authorization\\Models\\Permission',
        'type'   => 'entity',
        'name'   => 'user_permission',
    ],
    [
        'driver' => 'MetaFox\\Authorization\\Models\\Role',
        'type'   => 'entity',
        'name'   => 'user_role',
    ],
    [
        'driver'     => 'MetaFox\\Authorization\\Http\\Resources\\v1\\Permission\\Admin\\SearchPermissionForm',
        'type'       => 'form',
        'name'       => 'user_permission.search',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Authorization\\Http\\Resources\\v1\\Permission\\Admin\\EditPermissionForm',
        'type'       => 'form',
        'name'       => 'user.edit_permission',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Authorization\\Http\\Resources\\v1\\Role\\Admin\\DeleteRoleForm',
        'type'       => 'form',
        'name'       => 'user.role.delete',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Authorization\\Http\\Resources\\v1\\Role\\Admin\\CreateRoleForm',
        'type'       => 'form',
        'name'       => 'user.user_role.store',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Authorization\\Http\\Resources\\v1\\Role\\Admin\\EditRoleForm',
        'type'       => 'form',
        'name'       => 'user.user_role.update',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'  => 'MetaFox\\Authorization\\Http\\Resources\\v1\\Permission\\PermissionItemCollection',
        'type'    => 'json-collection',
        'name'    => 'user_permission.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Authorization\\Http\\Resources\\v1\\Role\\Admin\\RoleItemCollection',
        'type'    => 'json-collection',
        'name'    => 'user_role.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Authorization\\Http\\Resources\\v1\\Permission\\PermissionDetail',
        'type'    => 'json-resource',
        'name'    => 'user_permission.detail',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Authorization\\Http\\Resources\\v1\\Permission\\PermissionItem',
        'type'    => 'json-resource',
        'name'    => 'user_permission.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Authorization\\Http\\Resources\\v1\\Role\\Admin\\RoleDetail',
        'type'    => 'json-resource',
        'name'    => 'user_role.detail',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Authorization\\Http\\Resources\\v1\\Role\\Admin\\RoleItem',
        'type'    => 'json-resource',
        'name'    => 'user_role.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Authorization\\Http\\Resources\\v1\\PackageSetting',
        'type'    => 'package-setting',
        'name'    => 'authorization',
        'version' => 'v1',
    ],
    [
        'driver' => 'MetaFox\\Authorization\\Policies\\PermissionPolicy',
        'type'   => 'policy-resource',
        'name'   => 'MetaFox\\Authorization\\Models\\Permission',
    ],
    [
        'driver' => 'MetaFox\\Authorization\\Policies\\RolePolicy',
        'type'   => 'policy-resource',
        'name'   => 'MetaFox\\Authorization\\Models\\Role',
    ],
    [
        'driver'     => 'MetaFox\\Authorization\\Http\\Resources\\v1\\Device\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'user_device',
        'version'    => 'v1',
        'resolution' => 'mobile',
    ],
    [
        'driver'     => 'MetaFox\\Authorization\\Http\\Resources\\v1\\Device\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'user_device',
        'version'    => 'v1',
        'resolution' => 'web',
    ],
    [
        'driver'     => 'MetaFox\\Authorization\\Http\\Resources\\v1\\Permission\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'user_permission',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_preload' => 1,
    ],
];
