<?php

/* this is auto generated file */
return [
    [
        'subInfo'  => 'page::phrase.browse_pages_you_may_like',
        'menu'     => 'core.dropdownMenu',
        'name'     => 'pages',
        'label'    => 'page::phrase.pages',
        'ordering' => 7,
        'icon'     => 'ico-flag-waving',
        'to'       => '/page',
    ],
    [
        'subInfo'  => 'page::phrase.browse_pages_you_may_like',
        'menu'     => 'core.primaryMenu',
        'name'     => 'pages',
        'label'    => 'page::phrase.pages',
        'ordering' => 7,
        'icon'     => 'ico-flag-waving',
        'to'       => '/page',
    ],
    [
        'menu'     => 'page.actionMenuProfileMarketplace',
        'name'     => 'add_marketplace',
        'ordering' => 1,
        'as'       => 'marketplace.ui.addMarketplaceButton',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'page.actionMenuProfilePhoto',
        'name'     => 'add_photos',
        'ordering' => 1,
        'as'       => 'feed.ui.addPhotoButton',
    ],
    [
        'menu'     => 'page.actionMenuProfilePoll',
        'name'     => 'add_poll',
        'ordering' => 1,
        'as'       => 'poll.ui.addPollButton',
    ],
    [
        'menu'     => 'page.actionMenuProfileQuiz',
        'name'     => 'add_m_quizzes',
        'ordering' => 1,
        'as'       => 'quiz.ui.addQuizButton',
    ],
    [
        'tab'      => 'page',
        'showWhen' => [
            'and',
            ['truthy', 'acl.page.page.create'],
            ['truthy', 'item.is_owner'],
        ],
        'menu'     => 'page.page.headerItemActionOnUserProfileMenu',
        'name'     => 'page',
        'label'    => 'page::phrase.add_new_page',
        'ordering' => 1,
        'to'       => '/page/add?owner_id=:id',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'page.page.itemActionMenu',
        'name'     => 'manage',
        'label'    => 'page::phrase.manage',
        'ordering' => 1,
        'value'    => 'pages/manage',
        'icon'     => 'ico-gear-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'       => 'page.page.itemActionMenu',
        'name'       => 'edit',
        'label'      => 'page::phrase.edit',
        'ordering'   => 1,
        'value'      => 'editItem',
        'icon'       => 'ico-pencilline-o',
        'is_active'  => 0,
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.membership', 3],
        ],
        'menu'      => 'page.page.itemActionMenu',
        'name'      => 'decline',
        'label'     => 'page::phrase.decline',
        'ordering'  => 2,
        'value'     => 'page/declineInvite',
        'icon'      => 'ico-close',
        'is_active' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'      => 'page.page.itemActionMenu',
        'name'      => 'invite',
        'label'     => 'page::phrase.invite_friends',
        'ordering'  => 3,
        'value'     => 'page/inviteFriends',
        'icon'      => 'ico-envelope-o',
        'is_active' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['falsy', 'item.is_sponsored_feed'],
        ],
        'menu'     => 'page.page.itemActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'page::phrase.sponsor_in_feed',
        'ordering' => 4,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['truthy', 'item.is_sponsored_feed'],
        ],
        'menu'     => 'page.page.itemActionMenu',
        'name'     => 'unsponsor_in_feed',
        'label'    => 'page::phrase.unsponsor_in_feed',
        'ordering' => 5,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['falsy', 'item.is_sponsor'],
        ],
        'menu'     => 'page.page.itemActionMenu',
        'name'     => 'sponsor',
        'label'    => 'page::phrase.sponsor_this_item',
        'ordering' => 6,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
            ['truthy', 'item.is_sponsor'],
        ],
        'menu'     => 'page.page.itemActionMenu',
        'name'     => 'unsponsor',
        'label'    => 'page::phrase.unsponsor_this_item',
        'ordering' => 7,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'     => 'page.page.itemActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 8,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'     => 'page.page.itemActionMenu',
        'name'     => 'unfeature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 9,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'menu'      => 'page.page.itemActionMenu',
        'name'      => 'delete',
        'label'     => 'page::phrase.delete',
        'ordering'  => 11,
        'value'     => 'deleteItem',
        'icon'      => 'ico-trash',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['falsy', 'item.is_liked'],
            ['truthy', 'item.extra.can_like'],
        ],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'like',
        'label'    => 'page::phrase.like',
        'ordering' => 1,
        'value'    => 'page/like',
        'icon'     => 'ico-thumbup-o',
    ],
    [
        'color'    => 'default',
        'showWhen' => [
            'and',
            ['truthy', 'item.is_liked'],
            [
                'or',
                ['truthy', 'item.extra.can_unlike'],
                ['truthy', 'item.is_owner'],
            ],
        ],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'liked',
        'label'    => 'page::phrase.liked',
        'ordering' => 1,
        'value'    => 'page/unlike',
        'icon'     => 'ico-thumbup-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_message'],
        ],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'message',
        'label'    => 'page::phrase.message',
        'ordering' => 3,
        'value'    => 'comingSoon',
        'icon'     => 'ico-comment-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_claim'],
        ],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'claim',
        'label'    => 'page::phrase.claim_page',
        'ordering' => 4,
        'value'    => 'page/claim',
        'icon'     => 'ico-compose-alt',
    ],
    [
        'showWhen' => ['truthy', 'item.extra.can_edit'],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'manage',
        'label'    => 'page::phrase.manage',
        'ordering' => 5,
        'value'    => 'pages/manage',
        'icon'     => 'ico-gear-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'invite',
        'label'    => 'page::phrase.invite_friends',
        'ordering' => 6,
        'value'    => 'page/inviteFriends',
        'icon'     => 'ico-envelope-o',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond-o',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'unfeature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'approve',
        'label'    => 'group::phrase.approve',
        'ordering' => 9,
        'value'    => 'approveItem',
        'icon'     => 'ico-check-circle-o',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_moderate'],
            ['falsy', 'item.is_sponsor'],
            [
                'or',
                ['truthy', 'item.extra.can_sponsor'],
                ['truthy', 'item.extra.can_purchase_sponsor'],
            ],
        ],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'sponsor',
        'label'    => 'page::phrase.sponsor',
        'ordering' => 10,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_moderate'],
            ['truthy', 'item.is_sponsor'],
            [
                'or',
                ['truthy', 'item.extra.can_sponsor'],
                ['truthy', 'item.extra.can_purchase_sponsor'],
            ],
        ],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'unsponsor',
        'label'    => 'page::phrase.un_sponsor',
        'ordering' => 11,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            [
                'or',
                ['truthy', 'item.is_owner'],
                ['truthy', 'item.extra.can_moderate'],
            ],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'reassign_owner',
        'label'    => 'page::phrase.reassign_owner',
        'ordering' => 12,
        'value'    => 'page/reassignOwnerDialog',
        'icon'     => 'ico-user2-next-o',
    ],
    [
        'showWhen' => [
            'or',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'menu'      => 'page.page.profileActionMenu',
        'name'      => 'delete',
        'label'     => 'page::phrase.delete',
        'ordering'  => 14,
        'value'     => 'deleteItem',
        'icon'      => 'ico-trash',
    ],
    [
        'active'   => true,
        'tab'      => 'home',
        'menu'     => 'page.page.profileMenu',
        'name'     => 'home',
        'label'    => 'page::phrase.overview',
        'ordering' => 1,
        'to'       => '/',
    ],
    [
        'tab'      => 'about',
        'menu'     => 'page.page.profileMenu',
        'name'     => 'about',
        'label'    => 'page::phrase.about',
        'ordering' => 2,
        'to'       => '/about',
    ],
    [
        'showWhen' => [],
        'tab'      => 'member',
        'menu'     => 'page.page.profileMenu',
        'name'     => 'members',
        'label'    => 'page::phrase.members',
        'ordering' => 3,
        'to'       => '/member',
    ],
    [
        'menu'     => 'page.page.profilePopoverMenu',
        'name'     => 'message',
        'label'    => 'page::phrase.message',
        'ordering' => 1,
        'value'    => 'comingSoon',
        'icon'     => 'ico-comment-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'      => 'page.page.profilePopoverMenu',
        'name'      => 'invite',
        'label'     => 'page::phrase.invite_friends',
        'ordering'  => 2,
        'value'     => 'page/inviteFriends',
        'icon'      => 'ico-envelope-o',
        'is_active' => 1,
    ],
    [
        'menu'     => 'page.pageSettingsMenu',
        'name'     => 'page_settings',
        'label'    => 'page::phrase.page_settings',
        'ordering' => 1,
        'as'       => 'sidebarHeading',
    ],
    [
        'tab'      => 'info',
        'menu'     => 'page.pageSettingsMenu',
        'name'     => 'page_info',
        'label'    => 'page::phrase.page_info',
        'ordering' => 2,
        'to'       => '/page/settings/:id/info',
    ],
    [
        'tab'      => 'about',
        'menu'     => 'page.pageSettingsMenu',
        'name'     => 'about_page',
        'label'    => 'page::phrase.about_page',
        'ordering' => 3,
        'to'       => '/page/settings/:id/about',
    ],
    [
        'menu'     => 'page.pageSettingsMenu',
        'name'     => 'page_settings_divider',
        'ordering' => 4,
        'as'       => 'sidebarDivider',
    ],
    [
        'menu'     => 'page.pageSettingsMenu',
        'name'     => 'privacy_settings',
        'label'    => 'page::phrase.privacy_settings',
        'ordering' => 5,
        'as'       => 'sidebarHeading',
    ],
    [
        'tab'      => 'permissions',
        'menu'     => 'page.pageSettingsMenu',
        'name'     => 'permissions',
        'label'    => 'core::phrase.permissions',
        'ordering' => 6,
        'to'       => '/page/settings/:id/permissions',
    ],
    [
        'menu'     => 'page.pageSettingsMenu',
        'name'     => 'privacy_divider',
        'ordering' => 7,
        'as'       => 'sidebarDivider',
    ],
    [
        'menu'     => 'page.pageSettingsMenu',
        'name'     => 'page_menu_settings',
        'label'    => 'page::phrase.page_menu_settings',
        'ordering' => 8,
        'as'       => 'sidebarHeading',
    ],
    [
        'tab'      => 'landing',
        'menu'     => 'page.pageSettingsMenu',
        'name'     => 'menu',
        'label'    => 'page::phrase.menu',
        'ordering' => 9,
        'to'       => '/page/settings/:id/menu',
    ],
    [
        'menu'     => 'page.pageSettingsMenu',
        'name'     => 'page_menu_divider',
        'ordering' => 10,
        'as'       => 'sidebarDivider',
    ],
    [
        'menu'     => 'page.pageSettingsMenu',
        'name'     => 'page_messages',
        'label'    => 'page::phrase.page_messages',
        'ordering' => 11,
        'as'       => 'sidebarHeading',
    ],
    [
        'tab'      => 'inbox',
        'menu'     => 'page.pageSettingsMenu',
        'name'     => 'inbox',
        'label'    => 'page::phrase.inbox',
        'ordering' => 12,
        'to'       => '/page/settings/:id/chat',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 1],
            ['truthy', 'item.extra.can_remove_as_admin'],
        ],
        'menu'     => 'page.page_member.itemActionMenu',
        'name'     => 'remove_as_admin',
        'label'    => 'page::phrase.remove_as_admin',
        'ordering' => 3,
        'value'    => 'page/removeAsAdmin',
        'icon'     => 'ico-user2-down-o',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 0],
            ['truthy', 'item.extra.can_set_as_admin'],
            ['falsy', 'item.extra.can_cancel_admin_invite'],
        ],
        'menu'     => 'page.page_member.itemActionMenu',
        'name'     => 'set_as_admin',
        'label'    => 'page::phrase.set_as_admin',
        'ordering' => 4,
        'value'    => 'page/setAsAdmin',
        'icon'     => 'ico-businessman',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 0],
            ['truthy', 'item.extra.can_set_as_admin'],
            ['truthy', 'item.extra.can_cancel_admin_invite'],
        ],
        'menu'     => 'page.page_member.itemActionMenu',
        'name'     => 'remove_admin_invite',
        'label'    => 'page::phrase.remove_admin_invite',
        'ordering' => 5,
        'value'    => 'closeMenu, page/removeAdminInvite',
        'icon'     => 'ico-close-circle-o',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 1],
            ['truthy', 'item.extra.can_reassign_owner'],
        ],
        'menu'     => 'page.page_member.itemActionMenu',
        'name'     => 'reassign_owner',
        'label'    => 'page::phrase.reassign_owner',
        'ordering' => 6,
        'value'    => 'page/reassignOwner',
        'icon'     => 'ico-businessman',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_block'],
        ],
        'menu'     => 'page.page_member.itemActionMenu',
        'name'     => 'block_from_page',
        'label'    => 'page::phrase.block_from_page',
        'ordering' => 7,
        'value'    => 'page/blockFromPage',
        'icon'     => 'ico-ban',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.is_blocked'],
            ['neq', 'item.friendship', 5],
        ],
        'menu'     => 'page.page_member.itemActionMenu',
        'name'     => 'unblock',
        'label'    => 'page::phrase.un_block_this_user',
        'ordering' => 8,
        'value'    => 'unblockItem',
        'icon'     => 'ico-ban',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 0],
            ['truthy', 'item.extra.can_remove_member'],
        ],
        'menu'     => 'page.page_member.itemActionMenu',
        'name'     => 'remove_member',
        'label'    => 'page::phrase.remove_member',
        'ordering' => 9,
        'value'    => 'page/removeMember',
        'icon'     => 'ico-user1-del-o',
    ],
    [
        'tab'      => 'landing',
        'menu'     => 'page.sidebarMenu',
        'name'     => 'landing',
        'label'    => 'page::phrase.home',
        'ordering' => 1,
        'icon'     => 'ico-flag-waving-o',
        'to'       => '/page',
    ],
    [
        'tab'      => 'all',
        'menu'     => 'page.sidebarMenu',
        'name'     => 'all',
        'label'    => 'page::phrase.all_pages',
        'ordering' => 2,
        'icon'     => 'ico-hashtag',
        'to'       => '/page/all',
    ],
    [
        'tab'      => 'my',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'page.sidebarMenu',
        'name'     => 'my',
        'label'    => 'page::phrase.my_pages',
        'ordering' => 3,
        'icon'     => 'ico-user-man-o',
        'to'       => '/page/my',
    ],
    [
        'tab'      => 'my_pending',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['neq', 'session.user.role.id', 1],
        ],
        'menu'     => 'page.sidebarMenu',
        'name'     => 'my_pending',
        'label'    => 'page::phrase.my_pending_pages',
        'ordering' => 4,
        'icon'     => 'ico-user1-clock-o',
        'to'       => '/page/my-pending',
    ],
    [
        'tab'      => 'friend',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'page.sidebarMenu',
        'name'     => 'friend',
        'label'    => 'page::phrase.friends_pages',
        'ordering' => 5,
        'icon'     => 'ico-user1-two-o',
        'to'       => '/page/friend',
    ],
    [
        'tab'      => 'liked',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'page.sidebarMenu',
        'name'     => 'like',
        'label'    => 'page::phrase.liked_pages',
        'ordering' => 6,
        'icon'     => 'ico-thumbup-o',
        'to'       => '/page/liked',
    ],
    [
        'tab'      => 'invited',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'page.sidebarMenu',
        'name'     => 'invited',
        'label'    => 'page::phrase.page_invites',
        'ordering' => 7,
        'icon'     => 'ico-envelope-o',
        'to'       => '/pages/invited',
    ],
    [
        'tab'      => 'pending',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.page.page.approve'],
        ],
        'menu'     => 'page.sidebarMenu',
        'name'     => 'pending',
        'label'    => 'page::phrase.pending_pages',
        'ordering' => 8,
        'icon'     => 'ico-clock-o',
        'to'       => '/page/pending',
    ],
    [
        'tab'      => 'add',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.page.page.create'],
        ],
        'buttonProps' => [
            'fullWidth' => true,
            'color'     => 'primary',
            'variant'   => 'contained',
        ],
        'menu'     => 'page.sidebarMenu',
        'name'     => 'add',
        'label'    => 'page::phrase.create_new_page',
        'ordering' => 9,
        'as'       => 'sidebarButton',
        'icon'     => 'ico-plus',
        'to'       => '/page/add',
    ],
    [
        'tab'      => 'video',
        'menu'     => 'page.sidebarSearchInPageMenu',
        'name'     => 'manage-hidden',
        'label'    => 'page::phrase.videos',
        'ordering' => 3,
    ],
    [
        'tab'      => 'photo',
        'menu'     => 'page.tabMenuProfilePhoto',
        'name'     => 'photo',
        'label'    => 'page::phrase.photos',
        'ordering' => 1,
        'to'       => 'photo',
    ],
    [
        'tab'      => 'album',
        'menu'     => 'page.tabMenuProfilePhoto',
        'name'     => 'album',
        'label'    => 'page::phrase.albums',
        'ordering' => 2,
        'to'       => 'album',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.page.page.view'],
        ],
        'menu'     => 'search.webCategoryMenu',
        'name'     => 'page',
        'label'    => 'page::phrase.page_global_search_label',
        'ordering' => 8,
        'to'       => '/search/page',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.page.page.view'],
        ],
        'menu'     => 'search.webCategoryOrderingMenu',
        'name'     => 'page',
        'label'    => 'page::phrase.page_global_search_label',
        'ordering' => 7,
    ],
    [
        'tab'      => 'page',
        'showWhen' => [
            'and',
            ['truthy', 'item.profile_menu_settings.page_profile_menu'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'pages',
        'label'    => 'page::phrase.pages',
        'ordering' => 7,
        'to'       => '/page',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_share'],
        ],
        'menu'     => 'feed.itemShareActionsMenu',
        'name'     => 'share_on_page',
        'label'    => 'activity::phrase.share_on_page',
        'ordering' => 4,
        'value'    => 'page/shareOnPageProfile',
        'icon'     => 'ico-flag-waving',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_pending', 0],
            ['truthy', 'item.extra.can_pin_item'],
            ['falsy', 'item.extra.can_review_feed'],
            ['truthy', 'profile_id'],
            ['eq', 'profile_type', 'page'],
            ['noneOf', 'item.pins', '$.profile_id'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'pinItemOnPage',
        'label'    => 'page::phrase.pin_post_on_page',
        'ordering' => 2,
        'value'    => 'pinItem',
        'icon'     => 'ico-thumb-tack',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_pending', 0],
            ['truthy', 'item.extra.can_pin_item'],
            ['truthy', 'profile_id'],
            ['eq', 'profile_type', 'page'],
            ['oneOf', 'item.pins', '$.profile_id'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'unpinItemOnPage',
        'label'    => 'activity::phrase.unpin_post',
        'ordering' => 3,
        'value'    => 'unpinItem',
        'icon'     => 'ico-thumb-tack-o',
    ],
];
