<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Form\\InlineEditSection',
        'type'       => 'form',
        'name'       => 'inlineEditSection',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\Attachment',
        'type'       => 'form-field',
        'name'       => 'attachment',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\Attachment',
        'type'       => 'form-field',
        'name'       => 'attachment',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\Autocomplete',
        'type'       => 'form-field',
        'name'       => 'autocomplete',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\Autocomplete',
        'type'       => 'form-field',
        'name'       => 'autocomplete',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\BirthdayField',
        'type'       => 'form-field',
        'name'       => 'birthday',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\Birthday',
        'type'       => 'form-field',
        'name'       => 'birthday',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\ButtonField',
        'type'       => 'form-field',
        'name'       => 'button',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\Button',
        'type'       => 'form-field',
        'name'       => 'button',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\CancelButton',
        'type'       => 'form-field',
        'name'       => 'cancelButton',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\CategoryField',
        'type'       => 'form-field',
        'name'       => 'category',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\CategoryField',
        'type'       => 'form-field',
        'name'       => 'category',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\CheckboxField',
        'type'       => 'form-field',
        'name'       => 'checkbox',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\CheckboxField',
        'type'       => 'form-field',
        'name'       => 'checkbox',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\CheckboxGroupField',
        'type'       => 'form-field',
        'name'       => 'checkboxGroup',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\CheckboxGroupField',
        'type'       => 'form-field',
        'name'       => 'checkboxGroup',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\ChipField',
        'type'       => 'form-field',
        'name'       => 'chip',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\ChipField',
        'type'       => 'form-field',
        'name'       => 'chip',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\Choice',
        'type'       => 'form-field',
        'name'       => 'choice',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\ChoiceField',
        'type'       => 'form-field',
        'name'       => 'choice',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\ClearSearch',
        'type'       => 'form-field',
        'name'       => 'clearSearch',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\ClearSearch',
        'type'       => 'form-field',
        'name'       => 'clearSearch',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\ClearSearchForm',
        'type'       => 'form-field',
        'name'       => 'clearSearchForm',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\Clickable',
        'type'       => 'form-field',
        'name'       => 'clickable',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\ColorField',
        'type'       => 'form-field',
        'name'       => 'color',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\CountryState',
        'type'       => 'form-field',
        'name'       => 'countryState',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\CountryState',
        'type'       => 'form-field',
        'name'       => 'countryState',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\CustomButtonField',
        'type'       => 'form-field',
        'name'       => 'customButton',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\CustomGenders',
        'type'       => 'form-field',
        'name'       => 'customGenders',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\CustomGendersField',
        'type'       => 'form-field',
        'name'       => 'customGenders',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\DateField',
        'type'       => 'form-field',
        'name'       => 'date',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\Date',
        'type'       => 'form-field',
        'name'       => 'date',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\DateTimeField',
        'type'       => 'form-field',
        'name'       => 'dateTime',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\Datetime',
        'type'       => 'form-field',
        'name'       => 'datetime',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\DescriptionField',
        'type'       => 'form-field',
        'name'       => 'description',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\DividerField',
        'type'       => 'form-field',
        'name'       => 'divider',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\Dropdown',
        'type'       => 'form-field',
        'name'       => 'dropdown',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\Email',
        'type'       => 'form-field',
        'name'       => 'email',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\EmailField',
        'type'       => 'form-field',
        'name'       => 'email',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\FieldPickerField',
        'type'       => 'form-field',
        'name'       => 'fieldPicker',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\FileField',
        'type'       => 'form-field',
        'name'       => 'file',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\File',
        'type'       => 'form-field',
        'name'       => 'file',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\FilterCategoryField',
        'type'       => 'form-field',
        'name'       => 'filterCategory',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\FriendPickerField',
        'type'       => 'form-field',
        'name'       => 'friendPicker',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\FriendPicker',
        'type'       => 'form-field',
        'name'       => 'friendPicker',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\Gender',
        'type'       => 'form-field',
        'name'       => 'gender',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\HiddenField',
        'type'       => 'form-field',
        'name'       => 'hidden',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\Hidden',
        'type'       => 'form-field',
        'name'       => 'hidden',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\LinkField',
        'type'       => 'form-field',
        'name'       => 'htmlLink',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\InformationField',
        'type'       => 'form-field',
        'name'       => 'information',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\InlineEditSection',
        'type'       => 'form-field',
        'name'       => 'inlineEditSection',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\InputField',
        'type'       => 'form-field',
        'name'       => 'input',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\IntegerField',
        'type'       => 'form-field',
        'name'       => 'integer',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\Language',
        'type'       => 'form-field',
        'name'       => 'language',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\LinkButtonField',
        'type'       => 'form-field',
        'name'       => 'linkButton',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\LinkButtonField',
        'type'       => 'form-field',
        'name'       => 'linkButton',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\Location',
        'type'       => 'form-field',
        'name'       => 'location',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\MultipleLocation',
        'type'       => 'form-field',
        'name'       => 'multipleLocation',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\LocationField',
        'type'       => 'form-field',
        'name'       => 'location',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\AppleLoginButtonField',
        'type'       => 'form-field',
        'name'       => 'appleLoginButton',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\FacebookLoginButtonField',
        'type'       => 'form-field',
        'name'       => 'facebookLoginButton',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\GoogleLoginButtonField',
        'type'       => 'form-field',
        'name'       => 'googleLoginButton',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\FacebookLoginButtonField',
        'type'       => 'form-field',
        'name'       => 'facebookLoginButton',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\GoogleLoginButtonField',
        'type'       => 'form-field',
        'name'       => 'googleLoginButton',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\MembershipField',
        'type'       => 'form-field',
        'name'       => 'membership',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\MentionInputField',
        'type'       => 'form-field',
        'name'       => 'mentionInput',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\MultiFileField',
        'type'       => 'form-field',
        'name'       => 'multiFile',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\NumberField',
        'type'       => 'form-field',
        'name'       => 'number',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\NumberCode',
        'type'       => 'form-field',
        'name'       => 'numberCode',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\NumberCode',
        'type'       => 'form-field',
        'name'       => 'numberCode',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\Password',
        'type'       => 'form-field',
        'name'       => 'password',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\PasswordField',
        'type'       => 'form-field',
        'name'       => 'password',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\PhoneNumberField',
        'type'       => 'form-field',
        'name'       => 'phoneNumber',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\PhoneNumberField',
        'type'       => 'form-field',
        'name'       => 'phoneNumber',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\PointPackageField',
        'type'       => 'form-field',
        'name'       => 'pointPackage',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\PriceField',
        'type'       => 'form-field',
        'name'       => 'price',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\PriceField',
        'type'       => 'form-field',
        'name'       => 'price',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\PrivacyField',
        'type'       => 'form-field',
        'name'       => 'privacy',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\Privacy',
        'type'       => 'form-field',
        'name'       => 'privacy',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\QrCode',
        'type'       => 'form-field',
        'name'       => 'qrCode',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\QuizQuestionField',
        'type'       => 'form-field',
        'name'       => 'quizQuestion',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\RadioField',
        'type'       => 'form-field',
        'name'       => 'radio',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\Radio',
        'type'       => 'form-field',
        'name'       => 'radio',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\RadioGroupField',
        'type'       => 'form-field',
        'name'       => 'radioGroup',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\RadioGroupField',
        'type'       => 'form-field',
        'name'       => 'radioGroup',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\RadioLabelGroupField',
        'type'       => 'form-field',
        'name'       => 'radioLabelGroup',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\RangeSliderField',
        'type'       => 'form-field',
        'name'       => 'rangeSlider',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\RawFileField',
        'type'       => 'form-field',
        'name'       => 'rawFile',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\RegisterButtonField',
        'type'       => 'form-field',
        'name'       => 'registerButton',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\RelationshipPickerField',
        'type'       => 'form-field',
        'name'       => 'relationshipPicker',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\RichTextEditor',
        'type'       => 'form-field',
        'name'       => 'richTextEditor',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\RichTextEditor',
        'type'       => 'form-field',
        'name'       => 'richTextEditor',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\Row',
        'type'       => 'form-field',
        'name'       => 'row',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\SearchBoxField',
        'type'       => 'form-field',
        'name'       => 'searchBox',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\IconButtonField',
        'type'       => 'form-field',
        'name'       => 'iconButton',
        'resolution' => 'web',
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\SearchSuggestionField',
        'type'       => 'form-field',
        'name'       => 'searchSuggestion',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Section',
        'type'       => 'form-field',
        'name'       => 'section',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Section',
        'type'       => 'form-field',
        'name'       => 'section',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\SelectResolutionField',
        'type'       => 'form-field',
        'name'       => 'selectResolution',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\SimpleCategoryField',
        'type'       => 'form-field',
        'name'       => 'simpleCategory',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\SimpleFriendPickerField',
        'type'       => 'form-field',
        'name'       => 'simpleFriendPicker',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\SinglePhotoField',
        'type'       => 'form-field',
        'name'       => 'singlePhoto',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\SinglePhotoField',
        'type'       => 'form-field',
        'name'       => 'singlePhoto',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\SingleUpdateInputField',
        'type'       => 'form-field',
        'name'       => 'singleUpdateInput',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\SingleVideoField',
        'type'       => 'form-field',
        'name'       => 'singleVideo',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\SingleAudioField',
        'type'       => 'form-field',
        'name'       => 'singleAudio',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\MultiAudioField',
        'type'       => 'form-field',
        'name'       => 'multiAudio',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\SingleAudioField',
        'type'       => 'form-field',
        'name'       => 'singleAudio',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\SliderField',
        'type'       => 'form-field',
        'name'       => 'slider',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\Slug',
        'type'       => 'form-field',
        'name'       => 'slug',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\SpamQuestionField',
        'type'       => 'form-field',
        'name'       => 'spamQuestion',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\SubFormField',
        'type'       => 'form-field',
        'name'       => 'subForm',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\Submit',
        'type'       => 'form-field',
        'name'       => 'submit',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\SubmitButton',
        'type'       => 'form-field',
        'name'       => 'submit',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\SubmitButton',
        'type'       => 'form-field',
        'name'       => 'submitButton',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\SwitchField',
        'type'       => 'form-field',
        'name'       => 'switch',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\SwitchField',
        'type'       => 'form-field',
        'name'       => 'switch',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\TabListField',
        'type'       => 'form-field',
        'name'       => 'tabList',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\TagsField',
        'type'       => 'form-field',
        'name'       => 'tags',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\TagsField',
        'type'       => 'form-field',
        'name'       => 'tags',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\Text',
        'type'       => 'form-field',
        'name'       => 'text',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\TextField',
        'type'       => 'form-field',
        'name'       => 'text',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\ComposerInput',
        'type'       => 'form-field',
        'name'       => 'composerInput',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\CopyText',
        'type'       => 'form-field',
        'name'       => 'copyText',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\TextAreaField',
        'type'       => 'form-field',
        'name'       => 'textArea',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\TextArea',
        'type'       => 'form-field',
        'name'       => 'textArea',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\TimePickerField',
        'type'       => 'form-field',
        'name'       => 'timePicker',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\Timezone',
        'type'       => 'form-field',
        'name'       => 'timezone',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\TitleField',
        'type'       => 'form-field',
        'name'       => 'title',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\TypeCategoryField',
        'type'       => 'form-field',
        'name'       => 'typeCategory',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\TypeCategoryField',
        'type'       => 'form-field',
        'name'       => 'typeCategory',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\Typography',
        'type'       => 'form-field',
        'name'       => 'typography',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\DynamicTypography',
        'type'       => 'form-field',
        'name'       => 'dynamicTypography',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\Typography',
        'type'       => 'form-field',
        'name'       => 'typography',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\UploadMultiPhotoField',
        'type'       => 'form-field',
        'name'       => 'uploadMultiMedia',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\UrlField',
        'type'       => 'form-field',
        'name'       => 'url',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Mobile\\VideoUploadField',
        'type'       => 'form-field',
        'name'       => 'videoUpload',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Html\\ViewMore',
        'type'       => 'form-field',
        'name'       => 'viewMore',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Form\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'form',
        'is_active'  => true,
        'is_preload' => false,
    ],
];
