<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Sticker\\Http\\Resources\\v1\\StickerSet\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'sticker.sticker_set',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver' => 'MetaFox\\Sticker\\Models\\Sticker',
        'type'   => 'entity',
        'name'   => 'sticker',
    ],
    [
        'driver' => 'MetaFox\\Sticker\\Models\\StickerRecent',
        'type'   => 'entity',
        'name'   => 'sticker_recent',
    ],
    [
        'driver' => 'MetaFox\\Sticker\\Models\\StickerSet',
        'type'   => 'entity',
        'name'   => 'sticker_set',
    ],
    [
        'driver' => 'MetaFox\\Sticker\\Models\\StickerUserValue',
        'type'   => 'entity',
        'name'   => 'sticker_user_value',
    ],
    [
        'driver'     => 'MetaFox\\Sticker\\Http\\Resources\\v1\\StickerSet\\Admin\\SearchStickerSetForm',
        'type'       => 'form',
        'name'       => 'sticker.sticker_set.search',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Sticker\\Http\\Resources\\v1\\StickerSet\\Admin\\StoreStickerSetForm',
        'type'       => 'form',
        'name'       => 'sticker.sticker_set.store',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Sticker\\Http\\Resources\\v1\\StickerSet\\Admin\\UpdateStickerSetForm',
        'type'       => 'form',
        'name'       => 'sticker.sticker_set.update',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Sticker\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'       => 'form-settings',
        'name'       => 'sticker',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'core::phrase.settings',
        'url'        => '/admincp/sticker/setting',
    ],
    [
        'driver'  => 'MetaFox\\Sticker\\Http\\Resources\\v1\\StickerSet\\StickerSetEmbedCollection',
        'type'    => 'json-collection',
        'name'    => 'sticker_set.embed',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Sticker\\Http\\Resources\\v1\\StickerSet\\StickerSetItemCollection',
        'type'    => 'json-collection',
        'name'    => 'sticker_set.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Sticker\\Http\\Resources\\v1\\Sticker\\StickerEmbedCollection',
        'type'    => 'json-collection',
        'name'    => 'sticker.embed',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Sticker\\Http\\Resources\\v1\\Sticker\\StickerItemCollection',
        'type'    => 'json-collection',
        'name'    => 'sticker.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Sticker\\Http\\Resources\\v1\\StickerSet\\StickerSetDetail',
        'type'    => 'json-resource',
        'name'    => 'sticker_set.detail',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Sticker\\Http\\Resources\\v1\\StickerSet\\StickerSetEmbed',
        'type'    => 'json-resource',
        'name'    => 'sticker_set.embed',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Sticker\\Http\\Resources\\v1\\StickerSet\\StickerSetItem',
        'type'    => 'json-resource',
        'name'    => 'sticker_set.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Sticker\\Http\\Resources\\v1\\Sticker\\StickerDetail',
        'type'    => 'json-resource',
        'name'    => 'sticker.detail',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Sticker\\Http\\Resources\\v1\\Sticker\\StickerEmbed',
        'type'    => 'json-resource',
        'name'    => 'sticker.embed',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Sticker\\Http\\Resources\\v1\\Sticker\\StickerItem',
        'type'    => 'json-resource',
        'name'    => 'sticker.item',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Sticker\\Http\\Resources\\v1\\MobileSetting',
        'type'    => 'package-mobile',
        'name'    => 'sticker',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Sticker\\Http\\Resources\\v1\\PackageSetting',
        'type'    => 'package-setting',
        'name'    => 'sticker',
        'version' => 'v1',
    ],
    [
        'driver'  => 'MetaFox\\Sticker\\Http\\Resources\\v1\\WebSetting',
        'type'    => 'package-web',
        'name'    => 'sticker',
        'version' => 'v1',
    ],
    [
        'driver' => 'MetaFox\\Sticker\\Policies\\StickerSetPolicy',
        'type'   => 'policy-resource',
        'name'   => 'MetaFox\\Sticker\\Models\\StickerSet',
    ],
    [
        'driver'     => 'MetaFox\\Sticker\\Http\\Resources\\v1\\StickerSet\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'sticker_set',
        'version'    => 'v1',
        'resolution' => 'mobile',
    ],
    [
        'driver'     => 'MetaFox\\Sticker\\Http\\Resources\\v1\\Sticker\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'sticker',
        'version'    => 'v1',
        'resolution' => 'web',
    ],
    [
        'driver'     => 'MetaFox\\Sticker\\Http\\Resources\\v1\\StickerSet\\MobileSetting',
        'type'       => 'resource-web',
        'name'       => 'sticker_set',
        'version'    => 'v1',
        'resolution' => 'mobile',
    ],
    [
        'driver'     => 'MetaFox\\Sticker\\Http\\Resources\\v1\\StickerSet\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'sticker_set',
        'version'    => 'v1',
        'resolution' => 'web',
    ],
];
