<?php

/* this is auto generated file */
return [
    [
        'menu'     => 'core.adminSidebarMenu',
        'name'     => 'dashboard',
        'label'    => 'core::phrase.dashboard',
        'ordering' => 1,
        'icon'     => 'ico-bar-chart-2',
        'to'       => '/admincp',
    ],
    [
        'menu'     => 'core.adminSidebarMenu',
        'name'     => 'apps',
        'label'    => 'core::phrase.apps',
        'ordering' => 2,
        'as'       => 'subMenu',
        'icon'     => 'ico-box',
    ],
    [
        'menu'     => 'core.adminSidebarMenu',
        'name'     => 'app-settings',
        'label'    => 'core::phrase.app_settings',
        'ordering' => 3,
        'as'       => 'subMenu',
        'icon'     => 'ico-controlboard-h',
    ],
    [
        'menu'     => 'core.adminSidebarMenu',
        'name'     => 'settings',
        'label'    => 'core::phrase.settings',
        'ordering' => 4,
        'as'       => 'subMenu',
        'icon'     => 'ico-gear',
        'to'       => '/admincp/core/setting',
    ],
    [
        'menu'     => 'core.adminSidebarMenu',
        'name'     => 'members',
        'label'    => 'core::phrase.members',
        'ordering' => 5,
        'as'       => 'subMenu',
        'icon'     => 'ico-user-circle-o',
        'to'       => '/admincp',
    ],
    [
        'menu'     => 'core.adminSidebarMenu',
        'name'     => 'localization',
        'label'    => 'core::phrase.localization',
        'ordering' => 6,
        'as'       => 'subMenu',
        'icon'     => 'ico-globe',
        'to'       => '/admincp',
    ],
    [
        'menu'     => 'core.adminSidebarMenu',
        'name'     => 'appearance',
        'label'    => 'core::phrase.appearance',
        'ordering' => 7,
        'as'       => 'subMenu',
        'icon'     => 'ico-paint-brush',
        'to'       => '/admincp',
    ],
    [
        'menu'     => 'core.adminSidebarMenu',
        'name'     => 'maintenance',
        'label'    => 'core::phrase.maintenance',
        'ordering' => 8,
        'as'       => 'subMenu',
        'icon'     => 'ico-power',
        'to'       => '/admincp',
    ],
    [
        'menu'     => 'core.adminSidebarMenu',
        'name'     => 'toggleEditor',
        'label'    => 'core::phrase.toggle_editor',
        'ordering' => 9,
        'value'    => '@layout/toggleEditor',
        'icon'     => 'ico-color-palette',
    ],
    [
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'settings',
        'name'        => 'generalSettings',
        'label'       => 'core::phrase.site_settings',
        'ordering'    => 1,
        'to'          => '/admincp/core/setting',
    ],
    [
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'settings',
        'name'        => 'licenseKey',
        'label'       => 'core::phrase.license_key',
        'ordering'    => 3,
        'to'          => '/admincp/core/setting/license-key',
    ],
    [
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'settings',
        'name'        => 'toggleSite',
        'label'       => 'core::phrase.toggle_site',
        'ordering'    => 4,
        'to'          => '/admincp/core/setting/site-mode',
    ],
    [
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'settings',
        'name'        => 'attachment',
        'label'       => 'core::phrase.attachments',
        'ordering'    => 6,
        'to'          => '/admincp/core/setting/attachment',
    ],
    [
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'members',
        'name'        => 'browse',
        'label'       => 'core::phrase.browse',
        'ordering'    => 1,
        'to'          => '/admincp/user/user/browse',
    ],
    [
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'maintenance',
        'name'        => 'overview',
        'label'       => 'core::phrase.system_overview',
        'ordering'    => 1,
        'to'          => '/admincp/core/overview/system',
    ],
    [
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'maintenance',
        'name'        => 'phpinfo',
        'label'       => 'core::phrase.phpinfo',
        'ordering'    => 2,
        'to'          => '/admincp/core/overview/phpinfo',
    ],
    [
        'showWhen'    => ['eq', 'setting.app.env', 'local'],
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'maintenance',
        'name'        => 'routes',
        'label'       => 'core::phrase.routes',
        'ordering'    => 10,
        'to'          => '/admincp/core/maintain/browse/route',
    ],
    [
        'showWhen'    => ['eq', 'setting.app.env', 'local'],
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'maintenance',
        'name'        => 'events',
        'label'       => 'core::phrase.events',
        'ordering'    => 11,
        'to'          => '/admincp/core/maintain/browse/event',
    ],
    [
        'showWhen'    => ['eq', 'setting.app.env', 'local'],
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'maintenance',
        'name'        => 'drivers',
        'label'       => 'core::phrase.drivers',
        'ordering'    => 11,
        'to'          => '/admincp/core/maintain/browse/driver',
    ],
    [
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'appearance',
        'name'        => 'block',
        'label'       => 'core::phrase.blocks',
        'ordering'    => 0,
        'to'          => '/admincp',
        'is_active'   => 0,
    ],
    [
        'menu'     => 'core.bundle_task.admin',
        'name'     => 'bundle',
        'label'    => 'core::phrase.rebuild_site',
        'ordering' => 1,
        'icon'     => 'ico-bar-chart-2',
        'to'       => '/admincp/layout/build/create',
    ],
];
