<?php

return [
    'menuHeader' => [
        [
            'id'        => 1,
            'label'     => '',
            'icon'      => '',
            'iconColor' => '',
            'as'        => 'section',
            'path'      => '/',
        ],
        [
            'id'        => 2,
            'label'     => 'System Settings',
            'icon'      => 'gear-o',
            'iconColor' => '#686868',
            'as'        => 'header',
            'to'        => '/settings',
        ],
    ],
    'menuBody' => [
        [
            'id'        => 3,
            'label'     => 'FAVOURITES',
            'icon'      => '',
            'iconColor' => '',
            'as'        => 'section',
            'to'        => '/',
        ],
        [
            'id'        => 4,
            'label'     => 'Music',
            'icon'      => 'music-album',
            'iconColor' => '#ff4986',
            'as'        => 'item',
            'to'        => '/music-song',
        ],
        [
            'id'        => 4,
            'label'     => 'Activity Points',
            'icon'      => 'star-circle-o',
            'iconColor' => '#2681d5',
            'as'        => 'item',
            'to'        => '/activitypoint',
        ],
        [
            'id'        => 4,
            'label'     => 'Friends',
            'icon'      => 'user1-two',
            'iconColor' => '#2681d5',
            'as'        => 'item',
            'to'        => '/friend',
        ],
        [
            'id'        => 5,
            'label'     => 'Videos',
            'icon'      => 'videocam',
            'iconColor' => '#ff564a',
            'as'        => 'item',
            'to'        => '/video',
        ],
        [
            'id'        => 6,
            'label'     => 'Pages',
            'icon'      => 'flag-waving',
            'iconColor' => '#ff891f',
            'as'        => 'item',
            'to'        => '/page',
        ],
        [
            'id'        => 7,
            'label'     => 'Marketplace',
            'icon'      => 'shopbasket',
            'iconColor' => '#a1560f',
            'as'        => 'item',
            'to'        => '/marketplace',
        ],
        [
            'id'        => 8,
            'label'     => 'Quizzes',
            'icon'      => 'check-square-o3',
            'iconColor' => '#0e5bb4',
            'as'        => 'item',
            'to'        => '/quiz',
        ],
        [
            'id'        => 9,
            'label'     => 'Forums',
            'icon'      => 'comment-square',
            'iconColor' => '#ffba27',
            'as'        => 'item',
            'to'        => '/forum',
        ],
        [
            'id'        => 10,
            'label'     => 'Blogs',
            'icon'      => 'newspaper-alt',
            'iconColor' => '#0097fc',
            'as'        => 'item',
            'to'        => '/blog',
        ],
        [
            'id'        => 11,
            'label'     => 'Members',
            'icon'      => 'user1-three',
            'iconColor' => '#1d6f96',
            'as'        => 'item',
            'to'        => '/user',
        ],
        [
            'id'        => 12,
            'label'     => 'Photos',
            'icon'      => 'photos-alt',
            'iconColor' => '#00b7f4',
            'as'        => 'item',
            'to'        => '/photo',
        ],
        [
            'id'        => 13,
            'label'     => 'Events',
            'icon'      => 'calendar',
            'iconColor' => '#ff5319',
            'as'        => 'item',
            'to'        => '/event',
        ],
        [
            'id'        => 14,
            'label'     => 'Groups',
            'icon'      => 'user3-three',
            'iconColor' => '#b132fb',
            'as'        => 'item',
            'to'        => '/group',
        ],
        [
            'id'        => 15,
            'label'     => 'Polls',
            'icon'      => 'barchart',
            'iconColor' => '#00d475',
            'as'        => 'item',
            'to'        => "\poll",
        ],
        [
            'id'        => 17,
            'label'     => 'Membership',
            'icon'      => 'address-book',
            'iconColor' => '#ff4986',
            'as'        => 'item',
            'to'        => '/subscription',
            'showWhen'  => [
                'and',
                ['truthy', 'setting.subscription.enable_subscription_packages'],
            ],
        ],
        [
            'id'        => 24,
            'label'     => 'Saved Items',
            'icon'      => 'bookmark-o',
            'iconColor' => '#ff564a',
            'as'        => 'item',
            'to'        => '/saved',
        ],
    ],
    'moreItem'   => false,
    'moreBody'   => [],
    'menuHelper' => [
        [
            'id'        => 19,
            'label'     => 'TERMS & PRIVACY',
            'icon'      => '',
            'iconColor' => '',
            'as'        => 'section',
            'to'        => '/',
        ],
        [
            'id'        => 20,
            'label'     => 'Terms & Policies',
            'icon'      => 'address-book',
            'iconColor' => '#686868',
            'as'        => 'helper',
            'to'        => 'term-of-use',
        ],
        [
            'id'        => 21,
            'label'     => 'Privacy Shortcuts',
            'icon'      => 'lock',
            'iconColor' => '#686868',
            'as'        => 'helper',
            'to'        => 'policy',
        ],
    ],
    'menuFooter' => [
        [
            'id'        => 17,
            'label'     => '',
            'icon'      => '',
            'iconColor' => '',
            'as'        => 'section',
            'to'        => '/',
        ],
        [
            'id'        => 18,
            'label'     => 'Sign Out',
            'icon'      => 'signout',
            'iconColor' => '#686868',
            'as'        => 'footer',
            'value'     => '@auth/logout',
        ],
    ],
];
