<?php

/* this is auto generated file */
return [
    // App Bar Header Menu
    [
        'showWhen' => [],
        'menu'     => 'core.headerMenu',
        'name'     => 'top_section',
        'label'    => '',
        'ordering' => 1,
        'value'    => '',
        'as'       => 'section',
        'icon'     => '',
    ],
    [
        'showWhen'  => [],
        'menu'      => 'core.headerMenu',
        'name'      => 'system_settings',
        'label'     => 'core::phrase.system_settings_menu_label',
        'ordering'  => 2,
        'value'     => '',
        'to'        => '/settings',
        'as'        => 'header',
        'icon'      => 'gear-o',
        'iconColor' => '#686868',
    ],
    // App Bar Body Menu
    [
        'showWhen' => [],
        'menu'     => 'core.bodyMenu',
        'name'     => 'top_section',
        'label'    => 'core::phrase.favorites_uppercase_label',
        'ordering' => 1,
        'value'    => '',
        'as'       => 'section',
        'icon'     => '',
    ],
    // App Bar Helper Menu
    [
        'showWhen'  => [],
        'menu'      => 'core.helperMenu',
        'name'      => 'top_section',
        'label'     => 'core::phrase.terms_privacy_uppercase_label',
        'ordering'  => 1,
        'value'     => '',
        'to'        => '/',
        'as'        => 'section',
        'icon'      => '',
        'iconColor' => '',
    ],
    [
        'showWhen'  => [],
        'menu'      => 'core.helperMenu',
        'name'      => 'terms_and_policy',
        'label'     => 'core::phrase.terms_policies_menu_label',
        'ordering'  => 2,
        'value'     => '',
        'to'        => 'term-of-use',
        'as'        => 'helper',
        'icon'      => 'address-book',
        'iconColor' => '#686868',
    ],
    [
        'showWhen'  => [],
        'menu'      => 'core.helperMenu',
        'name'      => 'privacy_shortcuts',
        'label'     => 'core::phrase.privacy_shortcuts_menu_label',
        'ordering'  => 3,
        'value'     => '',
        'to'        => 'policy',
        'as'        => 'helper',
        'icon'      => 'lock',
        'iconColor' => '#686868',
    ],
    // App Bar Footer Menu
    [
        'showWhen'  => [],
        'menu'      => 'core.footerMenu',
        'name'      => 'top_section',
        'label'     => '',
        'ordering'  => 1,
        'value'     => '',
        'to'        => '/',
        'as'        => 'section',
        'icon'      => '',
        'iconColor' => '',
    ],
    [
        'showWhen'  => [],
        'menu'      => 'core.footerMenu',
        'name'      => 'sign_out',
        'label'     => 'core::phrase.logout',
        'ordering'  => 2,
        'value'     => '@auth/logout',
        'to'        => '',
        'as'        => 'footer',
        'icon'      => 'signout',
        'iconColor' => '#686868',
    ],
];
