<?php

/* this is auto generated file */
return [
    [
        'menu'      => 'core.accountMenu',
        'name'      => 'switch_account',
        'label'     => 'core::phrase.switch_account',
        'ordering'  => 1,
        'icon'      => 'ico-unlock-o',
        'to'        => '/switch-account',
        'is_active' => 0,
    ],
    [
        'menu'     => 'core.accountMenu',
        'name'     => 'account_settings',
        'label'    => 'core::phrase.account_settings',
        'ordering' => 2,
        'icon'     => 'ico-gear',
        'to'       => '/settings',
    ],
    [
        'menu'     => 'core.accountMenu',
        'name'     => 'manage_hidden',
        'label'    => 'core::phrase.manage_hidden',
        'ordering' => 5,
        'value'    => 'manageHidden',
        'icon'     => 'ico-eye-alt-blocked',
    ],
    [
        'menu'      => 'core.accountMenu',
        'name'      => 'themes',
        'label'     => 'core::phrase.themes',
        'ordering'  => 7,
        'value'     => 'chooseTheme',
        'icon'      => 'ico-color-palette',
        'is_active' => 0,
    ],
    [
        'menu'     => 'core.accountMenu',
        'name'     => 'dark_mode',
        'label'    => 'core::phrase.dark_mode',
        'ordering' => 8,
        'as'       => 'darkMode',
        'value'    => 'toggleDarkMode',
        'icon'     => 'ico-contrast',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.core.admincp.has_admin_access'],
        ],
        'menu'     => 'core.accountMenu',
        'name'     => 'toggle-control',
        'label'    => 'core::phrase.editor_mode',
        'ordering' => 9,
        'value'    => '@layout/toggleEditor',
        'icon'     => 'ico-color-palette',
    ],
    [
        'target'   => 'blank',
        'showWhen' => [
            'and',
            ['truthy', 'session.user.extra.has_admin_access'],
        ],
        'menu'     => 'core.accountMenu',
        'name'     => 'admincp',
        'label'    => 'core::phrase.admincp',
        'ordering' => 11,
        'icon'     => 'ico-businessman',
        'to'       => '/admincp',
    ],
    [
        'menu'     => 'core.accountMenu',
        'name'     => 'logout',
        'label'    => 'core::phrase.logout',
        'ordering' => 12,
        'icon'     => 'ico-signout',
        'to'       => '/logout',
    ],
    [
        'behavior'  => 'more',
        'placement' => 'bottom',
        'content'   => [
            'component' => 'appbar.menu.more',
        ],
        'menu'     => 'core.headerSubMenu',
        'name'     => 'more_menu',
        'label'    => 'core::phrase.more',
        'ordering' => 1,
        'as'       => 'popover',
        'icon'     => 'ico-dottedmore-o',
        'to'       => '',
    ],
    [
        'menu'     => 'core.headerSubMenu',
        'name'     => 'menu_divider',
        'ordering' => 5,
        'as'       => 'divider',
    ],
    [
        'placement' => 'bottom-end',
        'content'   => [
            'component' => 'user.ui.accountMenuPopper',
        ],
        'menu'     => 'core.headerSubMenu',
        'name'     => 'more',
        'ordering' => 7,
        'as'       => 'popover',
        'icon'     => 'ico-caret-down',
    ],
    [
        'menu'     => 'core.leftFooterMenu',
        'name'     => 'privacy',
        'label'    => 'core::phrase.privacy',
        'ordering' => 1,
        'to'       => '/policy',
    ],
    [
        'menu'     => 'core.leftFooterMenu',
        'name'     => 'terms',
        'label'    => 'core::phrase.terms',
        'ordering' => 2,
        'to'       => '/term-of-use',
    ],
    [
        'menu'     => 'core.primaryMenu',
        'name'     => 'home',
        'label'    => 'core::phrase.home',
        'ordering' => 1,
        'icon'     => 'ico-home-alt',
        'to'       => '/',
    ],
    [
        'menu'     => 'core.rightFooterMenu',
        'name'     => 'copyright',
        'label'    => 'core::phrase.site_copyright',
        'ordering' => 1,
    ],
    [
        'menu'     => 'core.shortcutMenu',
        'name'     => '1',
        'label'    => 'core::phrase.it_group_new_jersey',
        'ordering' => 1,
        'to'       => '/pages/304',
    ],
    [
        'menu'     => 'core.shortcutMenu',
        'name'     => '2',
        'label'    => 'core::phrase.it_group_new_jersey',
        'ordering' => 2,
        'to'       => '/pages/304',
    ],
    [
        'menu'     => 'core.shortcutMenu',
        'name'     => '3',
        'label'    => 'core::phrase.it_group_new_jersey',
        'ordering' => 3,
        'to'       => '/pages/304',
    ],
    [
        'menu'     => 'core.shortcutMenu',
        'name'     => '4',
        'label'    => 'core::phrase.it_group_new_jersey',
        'ordering' => 4,
        'to'       => '/pages/304',
    ],
];
