<?php

/* this is auto generated file */
return [
    [
        'name'               => 'music.music_song.landing',
        'phrase_title'       => 'music::seo.music_song_landing_title',
        'phrase_description' => 'music::seo.music_song_landing_description',
        'phrase_keywords'    => 'music::seo.music_song_landing_keywords',
        'phrase_heading'     => 'music::seo.music_song_landing_heading',
        'url'                => 'music',
        'item_type'          => 'music_song',
    ],
    [
        'name'               => 'music.browse_all_music_song',
        'phrase_title'       => 'music::seo.music_song_browse_all_title',
        'phrase_description' => 'music::seo.music_song_browse_all_description',
        'phrase_keywords'    => 'music::seo.music_song_browse_all_keywords',
        'phrase_heading'     => 'music::seo.music_song_browse_all_heading',
        'url'                => 'music/song',
        'item_type'          => 'music_song',
    ],
    [
        'name'               => 'music.browse_all_music_album',
        'phrase_title'       => 'music::seo.music_album_browse_all_title',
        'phrase_description' => 'music::seo.music_album_browse_all_description',
        'phrase_keywords'    => 'music::seo.music_album_browse_all_keywords',
        'phrase_heading'     => 'music::seo.music_album_browse_all_heading',
        'url'                => 'music/albums',
        'item_type'          => 'music_album',
    ],
    [
        'name'               => 'music.browse_all_music_playlist',
        'phrase_title'       => 'music::seo.music_playlist_browse_all_title',
        'phrase_description' => 'music::seo.music_playlist_browse_all_description',
        'phrase_keywords'    => 'music::seo.music_playlist_browse_all_keywords',
        'phrase_heading'     => 'music::seo.music_playlist_browse_all_heading',
        'url'                => 'music/playlists',
        'item_type'          => 'music_playlist',
    ],
    [
        'name'               => 'music.browse_friend_music_song',
        'phrase_title'       => 'music::seo.music_song_browse_friend_title',
        'phrase_description' => 'music::seo.music_song_browse_friend_description',
        'phrase_keywords'    => 'music::seo.music_song_browse_friend_keywords',
        'phrase_heading'     => 'music::seo.music_song_browse_friend_heading',
        'url'                => 'music/friend',
        'item_type'          => 'music_song',
    ],
    [
        'name'               => 'music.browse_pending_music_song',
        'phrase_title'       => 'music::seo.music_song_browse_pending_title',
        'phrase_description' => 'music::seo.music_song_browse_pending_description',
        'phrase_keywords'    => 'music::seo.music_song_browse_pending_keywords',
        'phrase_heading'     => 'music::seo.music_song_browse_pending_heading',
        'url'                => 'music/pending',
        'item_type'          => 'music_song',
    ],
    [
        'name'               => 'music.music_song.create',
        'phrase_title'       => 'music::seo.music_song_create_title',
        'phrase_description' => 'music::seo.music_song_create_description',
        'phrase_keywords'    => 'music::seo.music_song_create_keywords',
        'phrase_heading'     => 'music::seo.music_song_create_heading',
        'url'                => 'music/add',
        'item_type'          => 'music_song',
    ],
    [
        'name'               => 'music.music_playlist.create',
        'phrase_title'       => 'music::seo.music_playlist_create_title',
        'phrase_description' => 'music::seo.music_playlist_create_description',
        'phrase_keywords'    => 'music::seo.music_playlist_create_keywords',
        'phrase_heading'     => 'music::seo.music_playlist_create_heading',
        'url'                => 'music/playlist/add',
        'item_type'          => 'music_playlist',
    ],
    [
        'name'               => 'music.music_song.edit',
        'phrase_title'       => 'music::seo.music_song_edit_title',
        'phrase_description' => 'music::seo.music_song_edit_description',
        'phrase_keywords'    => 'music::seo.music_song_edit_keywords',
        'phrase_heading'     => 'music::seo.music_song_edit_heading',
        'url'                => 'music/song/edit/{id}',
        'item_type'          => 'music_song',
    ],
    [
        'name'               => 'music.music_album.edit',
        'phrase_title'       => 'music::seo.music_album_edit_title',
        'phrase_description' => 'music::seo.music_album_edit_description',
        'phrase_keywords'    => 'music::seo.music_album_edit_keywords',
        'phrase_heading'     => 'music::seo.music_album_edit_heading',
        'url'                => 'music/album/edit/{id}',
        'item_type'          => 'music_album',
    ],
    [
        'name'               => 'music.music_song.view_detail',
        'phrase_title'       => 'music::seo.music_song_view_detail_title',
        'phrase_description' => 'music::seo.music_song_view_detail_description',
        'phrase_keywords'    => 'music::seo.music_song_view_detail_keywords',
        'phrase_heading'     => 'music::seo.music_song_view_detail_heading',
        'url'                => 'music/song/{id}',
        'item_type'          => 'music_song',
    ],
    [
        'name'               => 'music.music_album.view_detail',
        'phrase_title'       => 'music::seo.music_album_view_detail_title',
        'phrase_description' => 'music::seo.music_album_view_detail_description',
        'phrase_keywords'    => 'music::seo.music_album_view_detail_keywords',
        'phrase_heading'     => 'music::seo.music_album_view_detail_heading',
        'url'                => 'music/album/{id}',
        'item_type'          => 'music_album',
    ],
    [
        'name'               => 'music.my',
        'phrase_title'       => 'music::seo.music_my_title',
        'phrase_description' => 'music::seo.music_my_description',
        'phrase_keywords'    => 'music::seo.music_my_keywords',
        'phrase_heading'     => 'music::seo.music_my_heading',
        'url'                => 'music/my',
    ],
    [
        'name'               => 'admin.music.setting',
        'phrase_title'       => 'music::seo.admin_setting_title',
        'phrase_description' => 'music::seo.admin_setting_description',
        'phrase_keywords'    => 'music::seo.admin_setting_keywords',
        'phrase_heading'     => 'music::seo.admin_setting_heading',
        'url'                => 'admincp/music/setting',
    ],
    [
        'name'               => 'admin.music.permission',
        'phrase_title'       => 'music::seo.admin_permission_title',
        'phrase_description' => 'music::seo.admin_permission_description',
        'phrase_keywords'    => 'music::seo.admin_permission_keywords',
        'phrase_heading'     => 'music::seo.admin_permission_heading',
        'url'                => 'admincp/music/permission',
    ],
    [
        'name'               => 'admin.music.browse_genre',
        'phrase_title'       => 'music::seo.admin_browse_genre_title',
        'phrase_description' => 'music::seo.admin_browse_genre_description',
        'phrase_keywords'    => 'music::seo.admin_browse_genre_keywords',
        'phrase_heading'     => 'music::seo.admin_browse_genre_heading',
        'url'                => 'admincp/music/genre/browse',
    ],
    [
        'name'               => 'admin.music.create_genre',
        'phrase_title'       => 'music::seo.admin_create_genre_title',
        'phrase_description' => 'music::seo.admin_create_genre_description',
        'phrase_keywords'    => 'music::seo.admin_create_genre_keywords',
        'phrase_heading'     => 'music::seo.admin_create_genre_heading',
        'url'                => 'admincp/music/genre/create',
    ],
    [
        'name'               => 'music.music.my_library',
        'phrase_title'       => 'music::seo.music_my_library_title',
        'phrase_description' => 'music::seo.music_my_library_description',
        'phrase_keywords'    => 'music::seo.music_my_library_keywords',
        'phrase_heading'     => 'music::seo.music_my_library_heading',
        'url'                => 'music/my-library',
    ],
    [
        'name'               => 'music.music_playlist.edit',
        'phrase_title'       => 'music::seo.music_edit_playlist_title',
        'phrase_description' => 'music::seo.music_edit_playlist_description',
        'phrase_keywords'    => 'music::seo.music_edit_playlist_keywords',
        'phrase_heading'     => 'music::seo.music_edit_playlist_heading',
        'url'                => 'music/playlist/edit/{id}',
        'item_type'          => 'music_playlist',
    ],
    [
        'name'               => 'music.music_playlist.view_detail',
        'phrase_title'       => 'music::seo.music_playlist_view_detail_title',
        'phrase_description' => 'music::seo.music_playlist_view_detail_description',
        'phrase_keywords'    => 'music::seo.music_playlist_view_detail_keywords',
        'phrase_heading'     => 'music::seo.music_playlist_view_detail_heading',
        'url'                => 'music/playlist/{id}',
        'item_type'          => 'music_playlist',
    ],
    [
        'name'               => 'music.search',
        'phrase_title'       => 'music::seo.music_search_title',
        'phrase_description' => 'music::seo.music_search_description',
        'phrase_keywords'    => 'music::seo.music_search_keywords',
        'phrase_heading'     => 'music::seo.music_search_heading',
        'url'                => 'music/search',
    ],
    [
        'name'               => 'user.profile.music',
        'phrase_title'       => 'music::seo.user_profile_music_title',
        'phrase_description' => 'music::seo.user_profile_music_desription',
        'phrase_keywords'    => 'music::seo.user_profile_music_keywords',
        'phrase_heading'     => 'music::seo.user_profile_music_heading',
        'url'                => 'user/{id}/music',
        'item_type'          => 'user',
    ],
    [
        'name'               => 'group.profile.music',
        'phrase_title'       => 'music::seo.group_profile_music_title',
        'phrase_description' => 'music::seo.group_profile_music_description',
        'phrase_keywords'    => 'music::seo.group_profile_music_keywords',
        'phrase_heading'     => 'music::seo.group_profile_music_heading',
        'url'                => 'group/{id}/music',
        'item_type'          => 'group',
    ],
    [
        'name'               => 'page.profile.music',
        'phrase_title'       => 'music::seo.page_profile_music_title',
        'phrase_description' => 'music::seo.page_profile_music_description',
        'phrase_keywords'    => 'music::seo.page_profile_music_keywords',
        'phrase_heading'     => 'music::seo.page_profile_music_heading',
        'url'                => 'page/{id}/music',
        'item_type'          => 'page',
    ],
];
